### PR TITLE
[Overlay] Enforce focus after backdrop mouse down

### LINKED ISSUE #1324: [Dialogs] Escape key doesn't close the dialog when focus out side of dialog
### Bug report

- __Package version(s)__: v1.21.0
- __Browser and OS versions__:  Chrome 57.0.2987.133 (64-bit), ubuntu 16.04 LTS

#### Steps to reproduce

http://blueprintjs.com/docs/#core/components/dialog

1. Disable `Click outside to close`.
2. Click `Show dialog`.
3. Click out side of the dialog.
4. Press ESC.

#### Actual behavior

Dialog doesn't closed.

#### Expected behavior

Dialog should be closed.

### PR DESCRIPTION
**Pull request by llorca**
#### Checklist

- [ ] Include tests

### CODE REVIEW

File: packages/core/src/components/overlay/overlay.tsx [hunk 1]
```diff
@@ -309,10 +309,15 @@ export class Overlay extends React.Component<IOverlayProps, IOverlayState> {
...
 
     private handleBackdropMouseDown = (e: React.MouseEvent<HTMLDivElement>) => {
-        if (this.props.canOutsideClickClose) {
-            safeInvoke(this.props.onClose, e);
+        const { backdropProps, canOutsideClickClose, enforceFocus, onClose } = this.props;
+        if (canOutsideClickClose) {
+            safeInvoke(onClose, e);
+        }
+        if (enforceFocus) {
+            // make sure document.activeElement is updated before bringing the focus back
```
Comment (adidahiya) [inline packages/core/src/components/overlay/overlay.tsx]: not sure I understand this comment -- what's the "before" part about? isn't it updating document.activeElement _by_ bringing the focus back?

File: packages/core/src/components/overlay/overlay.tsx [hunk 2]
```diff
@@ -309,10 +309,15 @@ export class Overlay extends React.Component<IOverlayProps, IOverlayState> {
...
+            requestAnimationFrame(() => this.bringFocusInsideOverlay());
```
Comment (adidahiya) [inline packages/core/src/components/overlay/overlay.tsx]: why do we need requestAnimationFrame?

File: packages/core/src/components/overlay/overlay.tsx (hunk 1 above)
Comment (llorca) [inline packages/core/src/components/overlay/overlay.tsx]: Kind of the same problem than in `Select` and `MultiSelect`: https://github.com/palantir/blueprint/pull/1275/files#diff-61619f2144645e953195b1eadae9ceadR199

In both this case and the one from the URL above, `document.activeElement` isn't the expected value after clicking away. From what I understand, rAF allows to wait for the next frame at which point `activeElement` is the correct value.

Comment (llorca) [inline packages/core/src/components/overlay/overlay.tsx]: https://stackoverflow.com/questions/11592966/get-the-newly-focussed-element-if-any-from-the-onblur-event

File: packages/core/src/components/overlay/overlay.tsx (hunk 2 above)
Comment (llorca) [inline packages/core/src/components/overlay/overlay.tsx]: https://stackoverflow.com/questions/11592966/get-the-newly-focussed-element-if-any-from-the-onblur-event

File: packages/core/src/components/overlay/overlay.tsx (hunk 1 above)
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: `rAF` is decidedly _not_ "the next frame," but the last possible moment of the same frame: __before the next repaint__. it lets us execute some logic after DOM updates but before repainting (to avoid flicker).

File: packages/core/src/components/overlay/overlay.tsx [hunk 3]
```diff
@@ -309,10 +309,15 @@ export class Overlay extends React.Component<IOverlayProps, IOverlayState> {
     }
 
     private handleBackdropMouseDown = (e: React.MouseEvent<HTMLDivElement>) => {
-        if (this.props.canOutsideClickClose) {
-            safeInvoke(this.props.onClose, e);
+        const { backdropProps, canOutsideClickClose, enforceFocus, onClose } = this.props;
+        if (canOutsideClickClose) {
+            safeInvoke(onClose, e);
+        }
+        if (enforceFocus) {
```
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: would be super great to add a unit test for this case. we have others for `enforceFocus`, should be a matter of copy-and-edit.

Comment (llorca) [inline packages/core/src/components/overlay/overlay.tsx]: Failing so far. What I have:
```tsx
it("returns focus to overlay after clicking the backdrop if enforceFocus=true", () => {
    wrapper = mount(
        <Overlay enforceFocus={true} canOutsideClickClose={false} inline={true} isOpen={true}>
            {createOverlayContents()}
        </Overlay>,
    );
    wrapper.find(BACKDROP_SELECTOR).simulate("mousedown");
    assert.equal(document.body.querySelector(BACKDROP_SELECTOR), document.activeElement);
});
```
I can't figure out what the last line should be. As of now, it gives me this:
```
expected null to equal <body class="">
```
which I don't understand because the `BACKDROP_SELECTOR` element exists, also why is `document.activeElement` equals to `body` after mousing down on the backdrop?

**Comment by llorca** [comment]
Made that test work 👍  Ready for review again.

File: packages/core/src/components/overlay/overlay.tsx (hunk 2 above)
Comment (adidahiya) [inline packages/core/src/components/overlay/overlay.tsx]: that link demonstrates `setTimeout`, which potentially makes more sense here (as noted in the other comment thread, `rAF` is not the next frame

File: packages/core/src/components/overlay/overlay.tsx (hunk 3 above)
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: ✅ test fixed

File: packages/core/src/components/overlay/overlay.tsx (hunk 2 above)
Comment (llorca) [inline packages/core/src/components/overlay/overlay.tsx]: We're already using `rAF` everywhere else we need the updated `document.activeElement` after triggering an event. Happy to change across the board to maintain consistency, I'll let you and @giladgray decide which is best and I'll open a separate PR if necessary

Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: we've enjoyed success using `rAF` for focus things, more than with `setTimeout` because it executes later _in the same frame_. i support this.
