### PR TITLE
[core] fix(MenuDivider): handle escape key to close popover

### LINKED ISSUE #6054: MenuDivider does not handle escape key to close popover
#### Environment

- __Package version(s)__: core v4.17.8, popover2 v1.13.12

#### Code Sandbox

https://codesandbox.io/p/sandbox/recursing-wave-ldgezp

#### Steps to reproduce

1. Render a Menu with MenuItem2 and MenuDivider items inside a popover
2. Make the MenuItem2 components inactive (`disabled={true}` or `shouldDismissPopover={true}`)
3. Open the popover
4. Click on a MenuItem2, then press the escape key
5. Open the popover
6. Click on a MenuDivider, then press the escape key

#### Actual behavior

Popover closed after step 4
Popover stayed open after step 6

#### Expected behavior

Popover should close after step 4, and also after step 6

#### Possible solution

Seems related to https://github.com/palantir/blueprint/issues/5947, where the suggestion of adding a `tabIndex={0}` to an element which should be focusable (and therefore handle the "escape key to close overlay" behavior) seems to work. Should be an easy fix to `MenuDivider.tsx`, probably just need to add `tabIndex={0}` here: https://github.com/palantir/blueprint/blob/6d86a19b9e858c4cde66a253b1172dcf896872d8/packages/core/src/components/menu/menuDivider.tsx#L54

### PR DESCRIPTION
**Pull request by mshende**
#### Changes proposed in this pull request:

Previously MenuDivider did not handle escape key to close popover. This should fix that.

### CODE REVIEW

File: packages/core/src/components/menu/menuDivider.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ export class MenuDivider extends React.Component<MenuDividerProps> {
         } else {
             // section header with title
             return (
-                <li className={classNames(Classes.MENU_HEADER, className)} role="separator">
+                <li className={classNames(Classes.MENU_HEADER, className)} role="separator" tabIndex={0}>
```
Comment (adidahiya) [inline packages/core/src/components/menu/menuDivider.tsx]:
```suggestion
                <li className={classNames(Classes.MENU_HEADER, className)} role="separator" tabIndex={-1}>
```

see discussion in https://github.com/palantir/blueprint/issues/6054#issuecomment-1513424391

**Review by adidahiya — CHANGES_REQUESTED** [review]

**Review by adidahiya — APPROVED** [review]

**Comment by adidahiya** [comment]
<h3>Update packages/core/src/components/menu/menuDivider.tsx</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/b03b13fe-b59e-4b62-9e17-d04cc7e0f963/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/b03b13fe-b59e-4b62-9e17-d04cc7e0f963/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/b03b13fe-b59e-4b62-9e17-d04cc7e0f963/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/b03b13fe-b59e-4b62-9e17-d04cc7e0f963/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>
