### PR TITLE
[EditableText] only sets defaultValue on initial render

### LINKED ISSUE #987: EditableText should not reset value in componentWillReceiveProps when uncontrolled
### Bug report

- __Package version(s)__: 1.11.1
- __Browser and OS versions__: Chrome 57.0.2987.133 (64-bit) on OSX 10.11.6 (though I'm pretty confident this doesn't matter)

#### Steps to reproduce

1. Add an editable text with an uncontrolled value, but some other prop controlled by state. (e.g. `<EditableText placeholder={this.state.placeholder} />`)
1. Type some text into the EditableText
1. Change the state (e.g. `e.g. this.setState({ placeholder: "new-placeholder" })`)

#### Actual behavior

The value in the EditableText should remain the same

#### Expected behavior

The value in the EditableText is cleared

#### Hypothesis for the underlying issue

EditableText resets its state value in `componentWillReceiveProps`, which seems very wrong when the component's value is uncontrolled.

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- turns out uncontrolled usage _never worked in a big way_
- so i refactored the example such that Title is uncontrolled. now we have an example to test differences between the two modes.

#### Reviewers should focus on:

- note that `maxLength` affects the two inputs differently because there's some logic that trims the controlled state. try setting max length to something less than the length of both fields.

cc @dskiff

### CODE REVIEW

File: packages/core/examples/editableTextExample.tsx [hunk 1]
```diff
@@ -78,15 +61,20 @@ export class EditableTextExample extends BaseExample<IEditableTextExampleState>
...
                 <IntentSelect intent={this.state.intent} key="intent" onChange={this.handleIntentChange} />,
-                <label className={Classes.LABEL} key="maxlength">
-                    Max length
-                    <input
-                        className={Classes.INPUT}
+                <div className={Classes.FORM_GROUP} key="maxlength">
+                    <label className={Classes.LABEL} htmlFor={INPUT_ID}>Max length</label>
+                    <NumericInput
+                        id={INPUT_ID}
+                        className={Classes.FORM_CONTENT}
```
Comment (cmslewis) [inline packages/core/examples/editableTextExample.tsx]: Can you apply `pt-fill` to the numeric input to ensure it has the same width as the intent dropdown? Right now, it's deferring to the default input width, which is too wide.

image

File: packages/core/examples/editableTextExample.tsx [hunk 2]
```diff
@@ -78,15 +61,20 @@ export class EditableTextExample extends BaseExample<IEditableTextExampleState>
...
+                        onValueChange={this.handleMaxLengthChange}
                         placeholder="Unlimited"
-                        onChange={this.handleMaxLengthChange}
-                        value={this.state.maxLength !== undefined ? this.state.maxLength.toString() : ""}
+                        value={this.state.maxLength || ""}
                     />
-                </label>,
+                </div>,
+            ],
+            [
```
Comment (cmslewis) [inline packages/core/examples/editableTextExample.tsx]: I'd love to add a custom style for this example column to make it triple-wide. Looks a little goofy right now:

image

This is what it could look like:

image

File: packages/core/examples/editableTextExample.tsx [hunk 3]
```diff
@@ -99,11 +87,18 @@ export class EditableTextExample extends BaseExample<IEditableTextExampleState>
                     key="swap"
                     onChange={this.toggleSwap}
                 />,
+                <small key="note">Title field is uncontrolled; report is controlled.</small>,
```
Comment (cmslewis) [inline packages/core/examples/editableTextExample.tsx]: nit: @llorca, is this the best typographic/implementation choice here?

Comment (llorca) [inline packages/core/examples/editableTextExample.tsx]: I believe we actually moved that note within the editable text placeholder for clarity. I know it might not be the prettiest, but it'll get better soon once we redesign the example frames

Comment (cmslewis) [inline packages/core/examples/editableTextExample.tsx]: Sure thing.

File: packages/core/examples/editableTextExample.tsx (hunk 2 above)
Comment (giladgray) [inline packages/core/examples/editableTextExample.tsx]: oh dang i meant to remove the small text! cuz we added "(controlled)" to the placeholder

File: packages/core/examples/editableTextExample.tsx (hunk 3 above)
Comment (giladgray) [inline packages/core/examples/editableTextExample.tsx]: yep forgot to remove

**Comment by thasner** [comment]
There's a class of usage where the user only cares about confirmed changes.
Still "controlled" for `value`, just not controlled for `staged_value`.
This PR  broke that usage :/
Is that not a common usage pattern?

for anyone who wants to continue `value`-controlled usage, and not be forced to track `staged_value` in your component's state, you can just "reset" the component by giving it a `key` equal to `defaultValue`, e.g.:
```
<EditableText
    defaultValue={title}
    key={title}
    onConfirm={this.handleTitleChange}
/>
```

**Comment by TheDolo** [comment]
I agree with Thasner, thank you for the "key" fix :)

**Comment by llorca** [comment]
@giladgray whatcha think? Something we can fix/improve?

**Comment by thasner** [comment]
another option is to create a wrapper component:
```
import * as React from "react";

import { EditableText, IEditableTextProps } from "@blueprintjs/core";

interface IProps extends IEditableTextProps {
    defaultValue?: "do not declare this, controlled mode";
    onConfirm: IEditableTextProps["onConfirm"];
    value: string;
}

interface IState {
    stagedValue: string;
}

export class ConfirmableText extends React.PureComponent<IProps, IState> {
    public state: IState = { stagedValue: this.props.value };

    public render() {
        return (
            <EditableText
                {...this.props}
                onChange={(stagedValue) => this.setState({ stagedValue })}
                value={this.state.stagedValue}
            />
        );
    }

    public componentWillReceiveProps(nextProps: IProps) {
        if (nextProps.value !== this.props.value) {
            this.setState({ stagedValue: nextProps.value });
        }
    }
}
```

**Comment by adidahiya** [comment]
please open a new issue for this discussion?

**Comment by thasner** [comment]
cool, https://github.com/palantir/blueprint/issues/1176
