### PR TITLE
[DateTime] Add `isUserChange` support for DateInput

### LINKED ISSUE #2418: DateInput - Navigating to a different month automatically selects a new date
### Bug report

`@blueprintjs/datetime` 1.25.4
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
OSX 10.13.4 (17E199)

#### Steps to reproduce

- Select an initial date with the date picker
- Open the date picker again, navigate to a different month, but don't pick anything
- Close the date picker

#### Actual behavior

- Initial date is picked
- When opening the date picker, changing the month, not doing anything and closing, the date that was previously selected has changed

#### Expected behavior

- Initial date is picked
- When opening the date picker, changing the month, not doing anything, and closing, the date that was selected initially should stay

#### Comments

I don't know if this is behavior that you intend on keeping, but this sounds like something that could be controlled via a prop, and if that prop exists, I'm not seeing it in the [documentation](http://blueprintjs.com/docs/v1/#datetime/dateinput). It doesn't make sense to me to change the date that was selected using the month navigator by default.

### PR DESCRIPTION
**Pull request by qcz**
#### Checklist
- [X] [Enable CircleCI for your fork](https://circleci.com/add-projects)
- [X] Include tests
- [X] Update documentation

#### Changes proposed in this pull request:
* Add `isUserChange` support for DateInput to be able to distinguish month/year changes from real date selections.
* Change the name of the second parameter of the onChange handler in `IDatePickerProps` to `isUserChange`, so all supported components use the same argument name.

### CODE REVIEW

File: packages/datetime/src/dateInput.tsx [hunk 1]
```diff
@@ -73,9 +73,10 @@ export interface IDateInputProps extends IDatePickerBaseProps, IDateFormatProps,
 
     /**
      * Called when the user selects a new valid date through the `DatePicker` or by typing
-     * in the input.
+     * in the input. The second argument is true if and only if the user clicked on a date in the
+     * calendar; it will be false if the date was changed by choosing a new month or year.
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: @qcz i just edited these docs a bit. question: is the arg true if the user types in a new date in the input?

**Comment by qcz** [comment]
<h3>update prop docs</h3>

Preview: <strong><a href='https://54-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://54-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://54-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/datetime/src/dateInput.tsx (hunk 1 above)
Comment (giladgray) [reply packages/datetime/src/dateInput.tsx]: +1 to `isUserChange`, please do that!

**Comment by qcz** [comment]
<h3>hasUserManuallySelectedDate → isUserChange</h3>

Preview: <strong><a href='https://61-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://61-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://61-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by qcz** [comment]
<h3>Fix lint error</h3>

Preview: <strong><a href='https://68-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://68-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://68-127462892-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/datetime/src/dateInput.tsx (hunk 1 above)
Comment (qcz) [reply packages/datetime/src/dateInput.tsx]: @giladgray: done!

**Comment by qcz** [comment]
@giladgray: Thanks! Looking forward to it!
