### PR TITLE
[DateRangeInput] Fix various bugs

### LINKED ISSUE #971: DateRangeInput with controlled usage doesn't set end date focus
### Bug report

- __Package version(s)__: 1.13.0
- __Browser and OS versions__: Chrome

#### Steps to reproduce

1. Use a `DateRangeInput` component from datetime package in a controlled manner (set `value` and `onChange` props and omit `defaultValue` prop).
2. Click start date input field.
3. Select a value from the DateRangePicker.

#### Actual behavior

Start date input field is populated with selected value; however the focus is still on the start date input field instead of end date input field. If you now select another date, it will overwrite the previously selected start date. 

#### Expected behavior

Expect start date value to be selected but focus set on the end date input field with the next selection in the DateRangePicker to set the value for the end date field. (This is how the DateRangeInput component behaves when in uncontrolled manner).

### LINKED ISSUE #1040: DateRangeInput's behavior is very different between the controlled and uncontrolled uses
The UX for DateRangeInput works as expected when used in an uncontrolled fashion. Focus between the fields switches as one expects and it is possible for a user to select a range using only the calendars.
However, when used in a controlled fashion, focus does not change and it is only possible to select a date range if a user manually changes the focus of the text fields. Definitely poor UX.

I propose that the uncontrolled behavior remains the same, and that the controlled behavior is changed to behave more like it. `onChange` should only be called when a user closes the date range popup and state should be managed internally while it is open.

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests
- [x] Update documentation (updated example to add "Use controlled mode" prop)

#### Changes proposed in this pull request:

- Controlled mode now has the same UX as uncontrolled mode.
    - In particular, clicking a start date in controlled mode moves the focus to the end-date field and vice versa.
- If you hover over a date and then use the keyboard to edit it, the keyboard-edited date will be displayed (before, we were simply displaying the hovered date, which didn't show the effects of your keystrokes.)
    - In general, any time the value changes, we now clear the `{start,end}HoverString` value in state, showing the `{start,end}InputString` instead.
- After typing an invalid date into a field, hovering over a valid date will hide the error state for the duration of the hover. The error state will return if you mouse out of the calendar without clicking a date.
- Throw a descriptive error if `value === null` (`undefined` triggers uncontrolled mode and `[null, null]` empties the fields in a controlled fashion, but a strictly `null` value doesn't have clear semantics).
- Added unit tests verifying these changes.

#### Reviewers should focus on:

- Make sure everything looks and feels good in both uncontrolled and controlled modes!
- I've included a "Use controlled mode" prop to help you test the dev preview. Should I nix that toggle before merging this PR?

### CODE REVIEW

File: packages/datetime/examples/dateRangeInputExample.tsx [hunk 1]
```diff
@@ -40,8 +44,26 @@ export class DateRangeInputExample extends BaseExample<IDateRangeInputExampleSta
...
-        return <DateRangeInput {...this.state} />;
+        const { value, useControlledMode, ...uncontrolledModeProps } = this.state;
+        return (
+            <div>
+                <DateRangeInput
+                    {...uncontrolledModeProps}
+                    onChange={this.handleChange}
+                    value={useControlledMode ? value : undefined}
+                />
+            </div>
```
Comment (giladgray) [inline packages/datetime/examples/dateRangeInputExample.tsx]: why the wrapper element? shouldn't be necessary

File: packages/datetime/src/dateRangeInput.tsx [hunk 2]
```diff
@@ -329,6 +332,12 @@ export class DateRangeInput extends AbstractComponent<IDateRangeInputProps, IDat
         this.setState(nextState);
     }
 
+    protected validateProps(props: IDateRangeInputProps & { children?: React.ReactNode }) {
```
Comment (giladgray) [inline packages/datetime/src/dateRangeInput.tsx]: safe to remove `children`, esp considering that this component doesn't really support `children` 😄

File: packages/datetime/src/dateRangeInput.tsx [hunk 3]
```diff
@@ -616,30 +627,38 @@ export class DateRangeInput extends AbstractComponent<IDateRangeInputProps, IDat
...
-            // this case will be relevant when we start showing the hovered
-            // range in the input fields. goal is to show an empty field for
-            // clarity until the mouse moves over a different date.
+            // this case will be relevant when we start showing the hovered range in the input
+            // fields. goal is to show an empty field for clarity until the mouse moves over a
+            // different date.
+            const baseState = { ...nextState, [keys.inputString]: "" };
             if (isValueControlled) {
-                nextState = { ...nextState, [keys.inputString]: "" };
+                nextState = baseState;
```
Comment (giladgray) [inline packages/datetime/src/dateRangeInput.tsx]: `baseState` seems only used here (not used in spread below) so please inline it.

File: packages/datetime/src/dateRangeInput.tsx [hunk 4]
```diff
@@ -616,30 +627,38 @@ export class DateRangeInput extends AbstractComponent<IDateRangeInputProps, IDat
...
             Utils.safeInvoke(this.props.onChange, this.getDateRangeForCallback(moment(null), boundary));
         } else if (this.isMomentValidAndInRange(maybeNextValue)) {
-            // note that error cases that depend on both fields (e.g.
-            // overlapping dates) should fall through into this block so that
-            // the UI can update immediately, possibly with an error message on
-            // the other field.
+            // note that error cases that depend on both fields (e.g. overlapping dates) should fall
+            // through into this block so that the UI can update immediately, possibly with an error
+            // message on the other field.
+            //
```
Comment (giladgray) [inline packages/datetime/src/dateRangeInput.tsx]: please no whitespace in comments like this. line length should be enough indicator of new thought.

File: packages/datetime/test/dateRangeInputTests.tsx [hunk 5]
```diff
@@ -2045,6 +2058,31 @@ describe("<DateRangeInput>", () => {
...
+            const onChange = (nextValue: DateRange) => controlledRoot.setProps({ value: nextValue });
+            const { root, getDayElement } = wrap(<DateRangeInput onChange={onChange} value={[null, null]} />);
+            controlledRoot = root;
+
+            getStartInput(controlledRoot).simulate("focus");
+            getDayElement(1).simulate("click"); // triggers a controlled value change
+            assertEndInputFocused(controlledRoot);
+        });
+
+        it(`Typing in a field while hovering over a date shows the typed date, not the hovered date`, () => {
```
Comment (giladgray) [inline packages/datetime/test/dateRangeInputTests.tsx]: unnecessary backtick quote?

File: packages/datetime/test/dateRangeInputTests.tsx [hunk 6]
```diff
@@ -2045,6 +2058,31 @@ describe("<DateRangeInput>", () => {
...
+            let controlledRoot: WrappedComponentRoot;
+
+            const onChange = (nextValue: DateRange) => controlledRoot.setProps({ value: nextValue });
```
Comment (giladgray) [inline packages/datetime/test/dateRangeInputTests.tsx]: _clever_

File: packages/datetime/examples/dateRangeInputExample.tsx (hunk 1 above)
Comment (cmslewis) [inline packages/datetime/examples/dateRangeInputExample.tsx]: Originally added this `<div>` because I had a label below the `DateRangeInput` for debugging. Can remove this now.

Comment (cmslewis) [inline packages/datetime/examples/dateRangeInputExample.tsx]: It's vestigial from debugging. See explanation below.

Done.

File: packages/datetime/src/dateRangeInput.tsx (hunk 2 above)
Comment (cmslewis) [inline packages/datetime/src/dateRangeInput.tsx]: Done

File: packages/datetime/src/dateRangeInput.tsx (hunk 4 above)
Comment (cmslewis) [inline packages/datetime/src/dateRangeInput.tsx]: Done

File: packages/datetime/test/dateRangeInputTests.tsx (hunk 5 above)
Comment (cmslewis) [inline packages/datetime/test/dateRangeInputTests.tsx]: Done

File: packages/datetime/src/dateRangeInput.tsx (hunk 3 above)
Comment (cmslewis) [inline packages/datetime/src/dateRangeInput.tsx]: Oops, this is a mistake actually.

Comment (cmslewis) [inline packages/datetime/src/dateRangeInput.tsx]: Fixed the test that was mistakenly passing, and fixed this.

Done.

File: packages/datetime/test/dateRangeInputTests.tsx [hunk 7]
```diff
@@ -1967,28 +1967,30 @@ describe("<DateRangeInput>", () => {
...
 
+            getStartInput(root).simulate("focus");
             getDayElement(START_DAY).simulate("click");
             assertInputTextsEqual(root, "", "");
             expect(onChange.called).to.be.true;
             expect(onChange.calledWith([null, null])).to.be.true;
         });
 
-        it(`Clearing only the start input (e.g.) invokes onChange with [null, <endDate>]`, () => {
+        it("Clearing only the start input (e.g.) invokes onChange with [null, <endDate>]", () => {
```
Comment (giladgray) [inline packages/datetime/test/dateRangeInputTests.tsx]: "(e.g.)" throws me off here. not an example, that's actually what you're testing.

Comment (cmslewis) [inline packages/datetime/test/dateRangeInputTests.tsx]: Ah, yeah, the "e.g." applies to the start input. Could also test the end input, but I use the start input alone as the representative.
