### PR TITLE
[core] feat(InputGroup): add leftElement prop

### LINKED ISSUE #4039: custom leftIcon in InputGroup is renderer outside of element
#### Environment

- __Package version(s)__: 3.24.0
- __Browser and OS versions__: Firefox 75 / macOS 10.14

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/mutable-wave-nuvm8

#### Steps to reproduce

1. Create an InputGroup element
2. Use a custom React element as leftIcon attribute

#### Actual behavior

The leftIcon element is rendered outside of the InputGroup

#### Expected behavior

The leftIcon element should be displayed inside the InputGroup. When using a Blueprintjs icon as a leftIcon element, the icon is correctly displayed inside the InputGroup.

### PR DESCRIPTION
**Pull request by justinbhopper**
#### Checklist

- [x] Update documentation

#### Changes proposed in this pull request:

Related discussion: https://github.com/palantir/blueprint/issues/4039#issuecomment-612308331

This PR adds a new `leftElement` to the `InputGroup`, which should allow users a better option for injecting left-aligned content than the current `leftIcon` prop.  The current `leftIcon` prop allows content, but is not styled in a good enough way to align things correctly.

#### Reviewers should focus on:

This PR uses the same approach as `rightElement` currently does for calculating necessary padding.  

It also adds the styling for the icon (color, margins, etc) that is currently being applied to leftIcon.  I chose to do this because I feel it may be common to add `<Icon>` in `leftElement`, for example when a custom icon is specified.

I modified the example in the docs to have one usage.  I felt it was good to illustrate how it can be used, but of course feel free to ask me to revert it.

**Another note** - this PR actually fixes another bug with `InputGroup` when `small={true}`.  The padding-right calculations for `rightElement` was causing the `InputGroup` to always have a right-padding of 10px by default, but the `small` variant was supposed to have 8px.  My changes in this PR ensures that calculated padding is now only applied when custom content is provided.

### CODE REVIEW

File: packages/core/src/components/forms/inputGroup.tsx [hunk 1]
```diff
@@ -133,11 +143,24 @@ export class InputGroup extends AbstractPureComponent2<IInputGroupProps & HTMLIn
...
+        if (prevProps.leftElement !== leftElement || prevProps.rightElement !== rightElement) {
             this.updateInputWidth();
         }
     }
 
+    private maybeRenderLeftElement() {
+        const { leftElement, leftIcon } = this.props;
+        if (leftElement == null) {
+            return <Icon icon={leftIcon} />;
+        }
```
Comment (adidahiya) [inline packages/core/src/components/forms/inputGroup.tsx:156]: I think we should return `undefined` if there is no leftElement. more concretely:

```
if (leftElement != null) {
  ...
} else if (leftIcon != null) {
  ...
}
```

this also matches our naming convention where "maybeX" render methods always have `| undefined` in their computed return type.

in addition, I think you should use prop validation to ensure `leftElement` and `leftIcon` are mutually exclusive. we do this with `AbstractPureComponent2#validateProps`. you will need to implement `validateProps` in this component. also make a note of this in the props JSDoc comments

File: packages/core/src/common/classes.ts [hunk 2]
```diff
@@ -143,6 +143,7 @@ export const HTML_TABLE_STRIPED = `${HTML_TABLE}-striped`;
 export const INPUT = `${NS}-input`;
 export const INPUT_GHOST = `${INPUT}-ghost`;
 export const INPUT_GROUP = `${INPUT}-group`;
+export const INPUT_LEFT = `${INPUT}-left`;
```
Comment (adidahiya) [inline packages/core/src/common/classes.ts:146]: I'd prefer to be a little more verbose and call this `${INPUT}-left-container`

File: packages/core/src/components/forms/inputGroup.tsx (hunk 1 above)
Comment (justinbhopper) [reply packages/core/src/components/forms/inputGroup.tsx:174]: Done, thank you for the input
