### PR TITLE
Fix Table row reordering example

### LINKED ISSUE #7128: Reordering rows in Table doesn't work
https://blueprintjs.com/docs/#table/features

https://github.com/user-attachments/assets/60c640ae-bc4c-4b9c-a327-8824c5f1816a

#### Environment

- __Package version(s)__: 
- __Operating System__: 
- __Browser name and version__: 

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/p/sandbox/blueprint-v5-x-sandbox-react-16-wy0ojy)): 

#### Steps to reproduce

1. 
1. 
1.

### PR DESCRIPTION
**Pull request by liubrandon**
#### Checklist

-   [x] Includes tests
  - None needed, before and after video included
-   [X] Update documentation

#### Changes proposed in this pull request:

Table2 row reordering didn't work because the cells weren't rerendering after the React state updated.

#### Reviewers should focus on:

Column reordering worked without `cellRendererDependencies` because the children depended on columns directly. Maybe there's a smarter way so that Table2 knows when rows have been reordered, but in the meantime, update the docs to help consumers avoid this footgun.

#### Screenshot

After:

https://github.com/user-attachments/assets/79a87138-2188-40d6-927e-741f96ae4ded

Multirow reordering works too:

https://github.com/user-attachments/assets/316bf62e-1fc6-4fc8-a991-517c52e727b8

### CODE REVIEW

File: packages/docs-app/src/examples/table-examples/tableReorderableExample.tsx [hunk 1]
```diff
@@ -74,6 +74,7 @@ export class TableReorderableExample extends React.PureComponent<ExampleProps, T
         return (
             <Example options={options} showOptionsBelowExample={true} {...this.props}>
                 <Table2
+                    cellRendererDependencies={[this.state]}
```
Comment (liubrandon) [inline packages/docs-app/src/examples/table-examples/tableReorderableExample.tsx:77]: this could have also just been `cellRendererDependencies={this.state.data}`

File: packages/table/src/docs/table-features.md [hunk 2]
```diff
@@ -65,7 +65,8 @@ regular expression (`[a-zA-Z]`). If the content is invalid, a `Intent.DANGER` st
 @## Reordering
 
 The table supports drag-reordering of columns and rows via the `enableColumnReordering` and `enableRowReordering`
-props, respectively.
+
```
Comment (ggdouglas) [inline packages/table/src/docs/table-features.md:68]: **nit:** Can we omit the extra newline here?

**Review by ggdouglas — APPROVED** [review]
Thanks for updating!

File: packages/table/src/docs/table-features.md (hunk 2 above)
Comment (liubrandon) [reply packages/table/src/docs/table-features.md:68]: Sorry it got merged before I pushed it up!

Comment (liubrandon) [reply packages/table/src/docs/table-features.md:68]: https://github.com/palantir/blueprint/pull/7412

**Comment by jason-shoe** [comment]
fire change
