### PR TITLE
use HTMLAttributes instead of HTMLProps

### LINKED ISSUE #2181: Card missing onDragStart, onMouseEnter, and onMouseLeave event handlers
### Bug report

- __Package version(s)__: `^1.35.4`
- __Browser and OS versions__: `Chrome 64.0.3282.167`, `Windows 10`

#### Steps to reproduce

1. Create an element
```html
<Card onDragStart={this.handleDrag} onMouseEnter={this.handleMouseEnter} onMouseLeave={this.handleMouseLeave}>
```

#### Actual behavior

Respective events are called when dragged, mouse entered, or mouse left.

#### Expected behavior

Nothing happens.

### PR DESCRIPTION
**Pull request by giladgray**
part of #2266. fixes #2181.

ensure `HTMLAttributes` appears last in extends list (otherwise it breaks the interface tables)

### CODE REVIEW

File: packages/core/src/components/button/abstractButton.tsx [hunk 1]
```diff
@@ -56,7 +56,10 @@ export interface IButtonState {
     isActive: boolean;
 }
 
-export abstract class AbstractButton<T> extends React.Component<React.HTMLProps<T> & IButtonProps, IButtonState> {
+export abstract class AbstractButton<H extends React.HTMLAttributes<any>> extends React.PureComponent<
```
Comment (llorca) [inline packages/core/src/components/button/abstractButton.tsx]: 🤯

Comment (giladgray) [reply packages/core/src/components/button/abstractButton.tsx]: emoji didn't come though, it's just a square. what's the sentiment here?

Comment (llorca) [reply packages/core/src/components/button/abstractButton.tsx]: image

Comment (giladgray) [reply packages/core/src/components/button/abstractButton.tsx]: oh yes very nice

File: packages/core/src/components/navbar/navbarDivider.tsx [hunk 2]
```diff
@@ -10,8 +10,7 @@ import * as Classes from "../../common/classes";
 import { IProps } from "../../common/props";
 
 // allow the empty interface so we can label it clearly in the docs
-// tslint:disable-next-line:no-empty-interface
-export interface INavbarDividerProps extends React.HTMLProps<HTMLDivElement>, IProps {
+export interface INavbarDividerProps extends IProps, React.HTMLAttributes<HTMLDivElement> {
```
Comment (giladgray) [inline packages/core/src/components/navbar/navbarDivider.tsx]: pro tip: `div` and `span` don't have special attrs so they both use `HTMLAttributes<T>` but other elements like `label` or `input` have their own `LabelHTMLAttributes<T>` interfaces

File: packages/core/src/components/forms/inputGroup.tsx [hunk 3]
```diff
@@ -48,7 +48,7 @@ export interface IInputGroupState {
     rightElementWidth?: number;
 }
 
-export class InputGroup extends React.PureComponent<HTMLInputProps & IInputGroupProps, IInputGroupState> {
+export class InputGroup extends React.PureComponent<IInputGroupProps & HTMLInputProps, IInputGroupState> {
```
Comment (themadcreator) [inline packages/core/src/components/forms/inputGroup.tsx]: extend interface instead of `&` the types (as per convention elsewhere)
