### PR TITLE
Fixes MultiSelect placeholder and adds tests

### LINKED ISSUE #1398: [Labs] Can't override input placeholder on MultiSelect
### Bug report

- __Package version(s)__: 1.24.0
- __Browser and OS versions__: Electron 1.6.11

#### Steps to reproduce

1. Try to override the input placeholder on a `MultiSelect` as follows (culled almost directly from the docs):
    ```JSX
    <ElosMultiSelect
        items={this.props.items}
        itemListPredicate={this.filterItems}
        itemRenderer={this.renderMenuItem}
        noResults={
            <MenuItem
                disabled={true}
                text={"Nothing easy"}
            />
        }
        onItemSelect={this.onItemSelect}
        selectedItems={this.state.selectedItems}
        tagInputProps={{
            'tagProps': {
                'className': tagClasses,
                'intent': Intent.PRIMARY,
            },
            'className': tagInputClasses,
            'inputProps': {
                'placeholder': this.props.placeholder,
            },
            'onRemove': this.handleTagRemove,
        }}
        tagRenderer={renderTag}
    />
    ```
2. Try to select (either via the Enter button or a click) any item from the multiselect.

#### Actual behavior

```
Uncaught TypeError: Cannot read property 'focus' of undefined
    at MultiSelect._this.handleItemSelect (http://localhost:6789/build/bundle.js:100148:24)
    at Object.safeInvoke (http://localhost:6789/build/bundle.js:5936:21)
    at QueryList._this.handleKeyUp (http://localhost:6789/build/bundle.js:99985:30)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:6789/build/bundle.js:33638:16)
    at executeDispatch (http://localhost:6789/build/bundle.js:33423:21)
    at Object.executeDispatchesInOrder (http://localhost:6789/build/bundle.js:33446:5)
    at executeDispatchesAndRelease (http://localhost:6789/build/bundle.js:29279:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:6789/build/bundle.js:29290:10)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:6789/build/bundle.js:40678:9)
```

#### Expected behavior

I don't think this should cause an error; apologies if this is me being an idiot, but as far as I can tell the order of property spreading shouldn't overwrite the necessary `ref` callback, especially since I'm not providing anything other than `placeholder` in `inputProps`.

Removing the section:
```
'inputProps': {
    'placeholder': this.props.placeholder,
},
```

from `tagInputProps` makes everything work.

I read the section on controlled usage and didn't see anything that would prevent me from overriding placeholder...any thoughts on this?

### PR DESCRIPTION
**Pull request by sushain97**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)
- [x] Include tests
~~- [ ] Update documentation~~ N/A

#### Changes proposed in this pull request:

None

#### Reviewers should focus on:

The tests could probably be improved

#### Screenshot

None

### CODE REVIEW

File: packages/labs/test/multiSelectTests.tsx [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+import { Classes, MenuItem } from "@blueprintjs/core";
+import { assert } from "chai";
+import * as classNames from "classnames";
+import { mount } from "enzyme";
+import * as React from "react";
+
+import { Film, TOP_100_FILMS } from "../examples/data";
+import { IMultiSelectProps, ISelectItemRendererProps, MultiSelect } from "../src/index";
+
+describe("<MultiSelect>", () => {
```
Comment (giladgray) [inline packages/labs/test/multiSelectTests.tsx]: please also write a test for the bug you are fixing--that `placeholder` works as expected.

Comment (sushain97) [inline packages/labs/test/multiSelectTests.tsx]: Well, `placeholder` itself works as expected even without this fix! It's only when you both have a placeholder and the `onItemSelect` callback fires that this problem arises. I wrote a test for just checking that the `placeholder` propagates first but it wasn't really doing much :) I can add it back if you think it helps in terms of test completeness.

Comment (giladgray) [inline packages/labs/test/multiSelectTests.tsx]: make a test for the exact bug report: it's mostly about `inputProps.placeholder`

Comment (sushain97) [inline packages/labs/test/multiSelectTests.tsx]: The bug report is specifically about selecting an option when something is in `inputProps`. The bad behavior doesn't occur until the actual click occurs. I added an earlier test I removed that checks that `placeholder` is properly propagated but it would have passed before this fix as well.
