### PR TITLE
[DateInput] Selected value stays selected when canClearSelection=false with timePrecision enabled

### LINKED ISSUE #1737: Bug: DateInput with timePrecision ignores canClearSelection
Code:

```jsx
<DateInput
  value={new Date()}
  onChange={d => console.log(d)}
  timePrecision={TimePickerPrecision.MINUTE}
  canClearSelection={false}
/>
<DateInput
  value={new Date()}
  onChange={d => console.log(d)}
  canClearSelection={false}
/>
```

On first input, that has `timePrecision`, when picking the same day on the calendar, it fires `onChange` with an unexpected `null` value.

The second input, when picking the same date, it fires `onChange` with the same date, as expected.

Example: 
https://codesandbox.io/s/k516yqoxyv

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

BEFORE:
1. Make a `DateInput` with `canClearSelection=false` and `timePrecision` enabled.
1. Select a date.
1. Click the selected date again.
1. `onChange` is erroneously emitted with `null`, suggesting that the date has just been deselected, which shouldn't be possible.

AFTER:
`DateInput` no longer emits `onChange` with `null` when clicking selected date with `canClearSelection=false` with `timePrecision` enabled.

#### Reviewers should focus on:

Nothing in particular. Easy fix.

#### Screenshot

Here's a working example with the following props:

```tsx
<DateInput
    canClearSelection={false}
    value={new Date(2017, Months.NOVEMBER, 6)}
    onChange={console.log}
    timePrecision={TimePickerPrecision.SECOND}
/>
```

### CODE REVIEW

File: packages/datetime/src/dateInput.tsx [hunk 1]
```diff
@@ -298,9 +299,9 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
         const prevMomentDate = this.state.value;
         const momentDate = fromDateToMoment(date);
 
-        // this change handler was triggered by a change in month, day, or (if enabled) time. for UX
-        // purposes, we want to close the popover only if the user explicitly clicked a day within
-        // the current month.
+        // this change handler was triggered by a change in month, day, or (if
+        // enabled) time. for UX purposes, we want to close the popover only if
+        // the user explicitly clicked a day within the current month.
```
Comment (cmslewis) [inline packages/datetime/src/dateInput.tsx]: Wrapped to 80 chars. @adidahiya is there a `tslint` rule or `prettier` rule that can enforce a different max-line-length for comments? Wrapping them at 120 chars makes them kind of hard to read.
