### PR TITLE
[datetime]fix (dateRangeInput): DateRangeInput should not close on selection when time inputs receive key presses

### LINKED ISSUE #3655: DateRangeInput should not close on selection when time inputs receive key presses
after following up on #3644 / #3185, I realized that this is not desirable:

related: #1988

### PR DESCRIPTION
**Pull request by vedadeepta**
#### Checklist

- [x] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:
Selected date in the state and the changed date are checked using the `areSameTime` date-util to 
determine if the user has changed any `<TimePicker />` values. If timepicker values are updated then the popover is kept open.

#### Screenshot
bp3-gif-of the-bug-fixed-showing-that-date-input-is-not-closed-when-timepicker-value-changes

### CODE REVIEW

**Comment by adidahiya** [comment]
[docs preview](https://circleci.com/gh/palantir/blueprint/26419/artifacts/0//home/circleci/project/packages/docs-app/dist/index.html)

File: packages/datetime/src/dateRangeInput.tsx [hunk 1]
```diff
@@ -735,6 +736,38 @@ export class DateRangeInput extends AbstractPureComponent<IDateRangeInputProps,
...
+        if (this.props.closeOnSelection) {
+            // trivial case when TimePicker is not shown
+            if (this.props.timePrecision == null) {
+                return false;
+            }
+
+            let currentStartDate: Date = new Date(new Date().setHours(0, 0, 0, 0));
+            let currentEndDate: Date = new Date(new Date().setHours(0, 0, 0, 0));
+
+            if (this.isControlled()) {
```
Comment (adidahiya) [inline packages/datetime/src/dateRangeInput.tsx]: I think we could DRY this up a little with a helper function... it's repeated on L786. we could have something like

```
private getSelectedRange(fallbackRange: [Date, Date]) {
    if (this.isControlled()) {
        ...
    } else {
        ...
    }
}
```

and the "fallback" would be what you have on L746-747

Comment (vedadeepta) [reply packages/datetime/src/dateRangeInput.tsx]: Modified existing `getSelectedRange` to accept a optional `fallbackRange` param. I'm not sure if you wanted this or to create a new function with `fallbackRange` param which returned the `DateRange` .

**Comment by vedadeepta** [comment]
[docs preview after refactor](https://circleci.com/gh/palantir/blueprint/26429/artifacts/0//home/circleci/project/packages/docs-app/dist/index.html)
