### PR TITLE
[DateRangeInput] Speed up the DRI tests

### LINKED ISSUE #1423: Speed up the `DateRangeInput` tests
### Bug report

- __Package version(s)__: v1.24.0

#### Steps to reproduce

1. Run `gulp-datetime` locally.

#### Actual behavior

`DateRangeInput` tests take foreverrrr.

#### Expected behavior

`DateRangeInput` tests are fast.

### PR DESCRIPTION
**Pull request by cmslewis**
#### Changes proposed in this pull request:

Use a single component instance for all DRI hover tests. This ultimately shaves `20 seconds` off the time for the DRI tests, a nearly `30%` reduction.

_Before:_
`1 min 9.075 secs`

_After_:
`49.435 secs`

#### Reviewers should focus on:

Is the new, public `DRI.reset()` method okay to have?

### CODE REVIEW

File: packages/datetime/test/dateRangeInputTests.tsx [hunk 1]
```diff
@@ -789,6 +793,10 @@ describe("<DateRangeInput>", () => {
                 changeInputText(endInput, "");
             });
 
+            afterEach(() => {
+                rootInstance.reset();
```
Comment (giladgray) [inline packages/datetime/test/dateRangeInputTests.tsx]: i wonder if this can be done with enzyme `wrapper.setProps(DRI.defaultProps)` and relying on `componentWillReceiveProps` instead of introducing a test-only instance method?

**Comment by cmslewis** [comment]
@giladgray The trouble is that we also have to reset default *state*.

On Aug 8, 2017, at 5:05 PM, Gilad Gray <notifications@github.com<mailto:notifications@github.com>> wrote:


@giladgray commented on this pull request.

________________________________

In packages/datetime/test/dateRangeInputTests.tsx[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_blueprint_pull_1424-23discussion-5Fr132063143&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=-xHM_msPNZ5Ueek6I-8Uf3C2NKIdRgHQEGOCuANP978&m=JwcvOEIQq7Rf-5HJ0i8mK-eD4rOZhPtZ3mWxoRCVdsM&s=Ju0vAtH_fHRyCiv5U1lvLHxJca782LlyIwo_qm_S-_c&e=>:

> @@ -789,6 +793,10 @@ describe("<DateRangeInput>", () => {
                 changeInputText(endInput, "");
             });

+            afterEach(() => {
+                rootInstance.reset();


i wonder if this can be done with enzyme wrapper.setProps(DRI.defaultProps) and relying on componentWillReceiveProps instead of introducing a test-only instance method?

File: packages/datetime/test/dateRangeInputTests.tsx (hunk 1 above)
Comment (cmslewis) [inline packages/datetime/test/dateRangeInputTests.tsx]: @giladgray The trouble is that we also have to reset default *state*.

Comment (giladgray) [inline packages/datetime/test/dateRangeInputTests.tsx]: fair enough
