### PR TITLE
[datetime2] fix(DateInput2): display updated timezone immediately

### LINKED ISSUE #5714: DateInput2 timezone does not update until popover is opened again
#### Environment

- __Package version(s)__: @blueprintjs/datetime2 v0.8.2
- __Operating System__: macOS
- __Browser name and version__: Chrome

#### Code Sandbox

Observable in the [DateInput2 docs](https://blueprintjs.com/docs/#datetime2/date-input2)

#### Steps to reproduce

1. Select a date
1. Change the timezone

#### Actual behavior

New timezone does not display until the input is clicked or focussed again to reopen the popover:

#### Expected behavior

New timezone should display immediately after selecting it from the dropdown.

#### Possible solution

Check `renderTarget` usage to make sure the InputGroup is getting re-rendered after timezone selection.

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Fix `renderTarget` dependency list so that the timezone displayed inside DateInput2 is updated immediately after changing it via the TimezoneSelect.

The fact that we have to do this is a sign that React hooks are kind of lame. 

#### Reviewers should focus on:

No regressions

### CODE REVIEW

File: packages/datetime2/test/components/dateInput2Tests.tsx [hunk 1]
```diff
@@ -479,7 +479,7 @@ describe("<DateInput2>", () => {
             assert.doesNotThrow(() => mount(<DateInput2 {...DEFAULT_PROPS_CONTROLLED} value={null} />));
         });
 
-        describe("when changing timezone", () => {
+        describe.only("when changing timezone", () => {
```
Comment (adidahiya) [inline packages/datetime2/test/components/dateInput2Tests.tsx]:
```suggestion
        describe("when changing timezone", () => {
```
