### PR TITLE
Fix preview comments for forks

### LINKED ISSUE #372: Enable blueprint-bot comments for forks
Also would be neat if contributors didn't have to manually trigger CI. With all the great external contributions we're getting, it's starting to create quite a bit of friction in the review process.

Two instances of CI enabled where blueprint-bot didn't post a comment: https://github.com/palantir/blueprint/pull/371 https://github.com/palantir/blueprint/pull/349

According to @adidahiya, it has to do with this line in the Circle config: https://github.com/palantir/blueprint/blob/497a03eab4420e48db0865407995895aa25726fa/circle.yml#L31

### PR DESCRIPTION
**Pull request by invliD**
**Fixes #372**

@giladgray Could you check if preview comments still work when PRing from a branch of this repo instead of a fork?

### CODE REVIEW

**Comment by invliD** [comment]
<h3>Fix preview comments for forks</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/invliD/blueprint/11/artifacts/0//home/ubuntu/blueprint/packages/docs/dist/index.html' target='_blank'>docs</a></strong>
Coverage: <a href='https://circleci.com/api/v1/project/invliD/blueprint/11/artifacts/0//home/ubuntu/blueprint/packages/core//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>core</a> | <a href='https://circleci.com/api/v1/project/invliD/blueprint/11/artifacts/0//home/ubuntu/blueprintpackages/datetime//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>datetime</a>

File: scripts/artifactVariables.sh [hunk 1]
```diff
@@ -17,9 +17,12 @@ COMMIT_MESSAGE=${COMMIT_MESSAGE//\"/\\\"}
 function submitPreviewComment {
     COMMENT_JSON="{\"body\": \"$1\"}"
 
-    if PR_NUMBER=$(basename $CI_PULL_REQUEST); then
+    if [ -n "$PR_NUMBER" ] ; then
+        UPSTREAM_USERNAME=$(echo $CI_PULL_REQUEST | awk -F/ '{print $4;}')
+        UPSTREAM_REPONAME=$(echo $CI_PULL_REQUEST | awk -F/ '{print $5;}')
+        UPSTREAM_API_BASE_URL="https://$GH_AUTH_TOKEN:$GH_API_URL/repos/$UPSTREAM_USERNAME/$UPSTREAM_REPONAME"
```
Comment (giladgray) [inline scripts/artifactVariables.sh]: seems like all of this can be computed at the top of the file with the other variables.

then it can also be used in the `else` block on line 29 for consistency.

**Comment by invliD** [comment]
<h3>Address comment</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/invliD/blueprint/13/artifacts/0//home/ubuntu/blueprint/packages/docs/dist/index.html' target='_blank'>docs</a></strong>
Coverage: <a href='https://circleci.com/api/v1/project/invliD/blueprint/13/artifacts/0//home/ubuntu/blueprint/packages/core//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>core</a> | <a href='https://circleci.com/api/v1/project/invliD/blueprint/13/artifacts/0//home/ubuntu/blueprintpackages/datetime//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>datetime</a>

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -140,3 +140,24 @@ your feature works as intended.
 After this point, you may be asked to make modification to your code to adhere
 to coherent code style or to fix bugs you may have not noticed. Once you get
 approvals from 1 or 2 repository owners, we will merge your code! :confetti_ball: :tada:
+
+
+### Using a fork
+
+If you're developing on a fork of Blueprint, navigate to
+[CircleCI](https://circleci.com/), log in using your GitHub account and enable
```
Comment (cmslewis) [inline CONTRIBUTING.md]: nit: I'm sure our docs aren't consistent about this, but I'd like to see an [Oxford comma](https://www.grammarly.com/blog/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/) here:

```
...your GitHub account, and enable...
```

File: CONTRIBUTING.md [hunk 3]
```diff
@@ -140,3 +140,24 @@ your feature works as intended.
...
+builds for your fork of Blueprint.
+
+#### Enable preview comments
+
+Optionally you can also enable preview comments. To do that, navigate to the
```
Comment (cmslewis) [inline CONTRIBUTING.md]: nit: add a comma after "Optionally":

```
Optionally, you...
```

File: CONTRIBUTING.md [hunk 4]
```diff
@@ -140,3 +140,24 @@ your feature works as intended.
...
+[token settings](https://github.com/settings/tokens) on GitHub and create a
```
Comment (cmslewis) [inline CONTRIBUTING.md]: nit: add comma after `GitHub`:

```
...on GitHub, and create...
```

File: CONTRIBUTING.md [hunk 5]
```diff
@@ -140,3 +140,24 @@ your feature works as intended.
...
+user token with the `public_repo` scope.
+
+Navigate to CircleCI repo settings:
+`https://circleci.com/gh/<your GitHub user name>/blueprint/edit#env-vars` and
```
Comment (cmslewis) [inline CONTRIBUTING.md]: nit: somewhat of an awkward case, but I'd still add comma after the URL:

```
`https://circleci.com/gh/<your GitHub user name>/blueprint/edit#env-vars`, and
```

**Comment by invliD** [comment]
@adidahiya was too quick, sorry. :(

**Comment by cmslewis** [comment]
@invliD - not a problem! The code improvement was definitely worth the merge regardless, and we can always tweak nitty stuff after the fact. Thanks again.
