### PR TITLE
[Slider] Use percentage values in slider styles

### LINKED ISSUE #2338: Slider and RangeSlider do not properly redraw on container resize
### Bug report

- 2.x
- Any OS and browser

#### Steps to reproduce

1. Add a Slider or RangeSlider in a fluid container (one that resizes when you resize the window)
2. Resize the window
1. The slider does not visually update(internally it does, as it makes a small jump to the proportional new value)

#### Actual behavior

The slider does not properly visually update its heads locations when resizing the parent container

#### Expected behavior

The slider should visually update its dimension proportionally to its width

I have attached a GIF with this behavior

slider-on-resize

You can see that the correct redrawing happens(the jump) at the first mouse click attempt on head or track.

It should behave like this:
slider-on-resize-proper

For my slider cases, I mitigate it using this code, that I call in the windows resize, after changing state

```js
  fixSliders() {
    if (this.timelineRangeSliderRef.current) {
      const slider = this.timelineRangeSliderRef.current.trackElement.parentNode;
      const track = slider.querySelector('.pt-slider-track');
      const progress = slider.querySelector('.pt-slider-progress');
      const handles = Array.prototype.slice.call(slider.querySelectorAll('.pt-slider-handle'));
      if (!slider || !track) {
        return;
      }
      try {
        const [left, right] = handles;
        const scale = track.offsetWidth;
        const handle = left.offsetWidth;
        const leftPercentage = this.state.playbackTimeline.range[0] * (100 / TIMELINE_SCALE_MAX);
        const leftProportionalPosition = ((leftPercentage * scale) / 100) - handle;
        const rightPercentage = this.state.playbackTimeline.range[1] * (100 / TIMELINE_SCALE_MAX);
        const rightProportionalPosition = ((rightPercentage * scale) / 100) - handle;
        const progressProportionalWidth = rightProportionalPosition - leftProportionalPosition;
        const progressProportionalPosition = leftProportionalPosition + handle;
        // set new sizes and locations
        left.style.left = `${leftProportionalPosition}px`;
        right.style.left = `${rightProportionalPosition}px`;
        progress.style.width = `${progressProportionalWidth}px`;
        progress.style.left = `${progressProportionalPosition}px`;
      } catch (error) {
        console.error(error);
      }
    }
    if (this.timelinePlayheadSliderRef.current) {
      const slider = this.timelinePlayheadSliderRef.current.trackElement.parentNode;
      const track = slider.querySelector('.pt-slider-track');
      const progress = slider.querySelector('.pt-slider-progress');
      const left = slider.querySelector('.pt-slider-handle');
      if (!slider || !track || !left) {
        return;
      }
      try {
        const scale = track.offsetWidth;
        const handle = left.offsetWidth;
        const handleMiddle = handle / 2;
        const percentage = this.state.playbackTimeline.playhead * (100 / TIMELINE_SCALE_MAX);
        const proportionalPosition = ((percentage * scale) / 100) - handleMiddle;
        const progressProportionalWidth = proportionalPosition + handleMiddle;
        left.style.left = `${proportionalPosition}px`;
        progress.style.width = `${progressProportionalWidth}px`;
      } catch (error) {
        console.error(error);
      }
    }
  }
```

Called
```js
      this.windowResizeListener = () => {
        const verticalOffset = HEADER_HEIGHT + FOOTER_HEIGHT + HEADER_HEIGHT;
        this.setState({
          ...this.state,
          container: {
            width: window.innerWidth,
            height: window.innerHeight - verticalOffset,
          },
        }, () => {
          this.fixSliders();
        });
      };
      window.addEventListener('resize', this.windowResizeListener);
      this.windowResizeListener();
```

I have created this CodeSandbox demo that you can access here https://codesandbox.io/s/3v2qr0j5mm

### PR DESCRIPTION
**Pull request by reiv**
#### Changes proposed in this pull request:

This PR changes the slider styles to use percentages instead of absolute pixel values. This should allow the slider to be freely resized without requiring a forced re-render.

#### Screenshot

This recording shows the slider being resized (`width` is being set in the inspector).

### CODE REVIEW

**Comment by llorca** [comment]
uh oh, that's great stuff. seems to be working well!

I'm seeing a little regression with the 3rd docs example: the slider handle is gone
image

**Comment by reiv** [comment]
<h3>Update test</h3>

Preview: <strong><a href='https://334-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://334-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://334-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by reiv** [comment]
<h3>Remove stray comments</h3>

Preview: <strong><a href='https://339-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://339-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://339-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by reiv** [comment]
<h3>Restore PEMDAS</h3>

Preview: <strong><a href='https://345-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://345-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://345-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by giladgray** [comment]
@reiv dude yes this is brilliant! do we even need `tickSize` (pixels) anymore?

**Comment by reiv** [comment]
@giladgray Had to leave that in because there was some stuff in the slider handler code (`clientToValue`) that depended on it:

https://github.com/palantir/blueprint/blob/66bf86735f668a7c0450166de54c652ab4a8ef19/packages/core/src/components/slider/handle.tsx#L93-L94

Perhaps that can be rewritten too, but I don't fully understand it yet.

**Comment by reiv** [comment]
<h3>Don't set useOppositeDimension flag to get handle offset</h3>

Preview: <strong><a href='https://375-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://375-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://375-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by reiv** [comment]
<h3>Restore previous logic with added comment</h3>

Preview: <strong><a href='https://405-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://405-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://405-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/core/src/components/slider/handle.tsx [hunk 1]
```diff
@@ -50,12 +51,18 @@ export class Handle extends AbstractPureComponent<IHandleProps, IHandleState> {
...
+        // The handle midpoint of RangeSlider is actually shifted by a margin to
+        // be on the edge of the visible handle element. Because the midpoint
+        // calculation does not take this margin into account, we instead
+        // measure the long side (which is equal to the short side plus the
+        // margin).
         const { handleMidpoint } = this.getHandleMidpointAndOffset(this.handleElement, true);
-        const offset = Math.round((value - min) * tickSize - handleMidpoint);
-        const style: React.CSSProperties = vertical ? { bottom: offset } : { left: offset };
+        const offsetRatio = (value - min) * tickSizeRatio;
+        const offsetCalc = `calc(${offsetRatio * 100}% - ${handleMidpoint}px)`;
```
Comment (giladgray) [inline packages/core/src/components/slider/handle.tsx]: 👌

File: packages/core/src/components/slider/slider.tsx [hunk 2]
```diff
@@ -49,20 +49,23 @@ export class Slider extends CoreSlider<ISliderProps> {
     private handle: Handle;
 
     protected renderFill() {
-        const { tickSize } = this.state;
+        const { tickSizeRatio } = this.state;
         const initialValue = clamp(this.props.initialValue, this.props.min, this.props.max);
 
-        let offset = Math.round((initialValue - this.props.min) * tickSize);
-        let size = Math.round((this.props.value - initialValue) * tickSize);
```
Comment (giladgray) [inline packages/core/src/components/slider/slider.tsx]: it's cool that we don't need to `round` anymore, but i think we want to ensure a maximum number of decimal places via `number.toFixed(2)` to reduce sub-pixel rendering.

Comment (reiv) [reply packages/core/src/components/slider/slider.tsx]: Do you mean rounding the value of `offsetRatio`? I don't think that would accomplish much because the actual computed value in pixels doesn't have any restrictions on the number of decimal places. Here's an example of a round percentage yielding sub-pixel precision (shows inline styles and computed value from inspector):

slider-subpixel

Unfortunately CSS `calc` provides no facilities for rounding the result. :cry:

Comment (giladgray) [reply packages/core/src/components/slider/slider.tsx]: no i mean `${(offset * 100).toFixed(2)}%`

Comment (giladgray) [reply packages/core/src/components/slider/slider.tsx]: sub-pixel renders are going to happen here for sure, but there's a limit to precision on the screen. it's definitely possible that my suggestion isn't really helpful?

Comment (reiv) [reply packages/core/src/components/slider/slider.tsx]: Well, at the very least we'll get inline styles that are easy on the eyes if anyone happens to be snooping around with inspect element. I'll make it happen :+1:

**Comment by reiv** [comment]
<h3>Fix test</h3>

Preview: <strong><a href='https://417-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://417-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://417-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/core/src/components/slider/slider.tsx [hunk 3]
```diff
@@ -60,8 +60,8 @@ export class Slider extends CoreSlider<ISliderProps> {
             size = Math.abs(size);
         }
 
-        const offsetPercentage = `${offset * 100}%`;
-        const sizePercentage = `${size * 100}%`;
+        const offsetPercentage = `${(offset * 100).toFixed(2)}%`;
+        const sizePercentage = `${(size * 100).toFixed(2)}%`;
```
[the remark this answers is not in the document]
Comment (giladgray) [reply packages/core/src/components/slider/slider.tsx]: it could go in `coreSlider.tsx`

[the remark this answers is not in the document]
Comment (reiv) [reply packages/core/src/components/slider/slider.tsx]: Ok sure.

**Comment by reiv** [comment]
<h3>Add formatPercentage helper function</h3>

Preview: <strong><a href='https://447-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://447-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://447-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by reiv** [comment]
<h3>Renames</h3>

Preview: <strong><a href='https://448-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://448-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://448-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>
