### PR TITLE
[core] fix: toasters closing immediately on hover if `timeout` is set to 0

### LINKED ISSUE #6742: Toaster with timeout zero is dismissed early
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^5.10.0",
- __Operating System__: Mac OS 14
- __Browser name and version__: Chrome 122

#### Code Sandbox

[Code sandbox](https://codesandbox.io/p/sandbox/bp-dialog-forked-36md2v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltd9jymi00063b6hg4k9oz5s%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltd9jymi00023b6hdq2msqe9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltd9jymi00033b6h3nmeutqj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltd9jymi00053b6hbrgkudlf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltd9jymi00023b6hdq2msqe9%2522%253A%257B%2522id%2522%253A%2522cltd9jymi00023b6hdq2msqe9%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltd9jymi00053b6hbrgkudlf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltd9jymi00043b6h7pycrpwt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltd9jymi00053b6hbrgkudlf%2522%252C%2522activeTabId%2522%253A%2522cltd9jymi00043b6h7pycrpwt%2522%257D%252C%2522cltd9jymi00033b6h3nmeutqj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltd9jymi00033b6h3nmeutqj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

#### Steps to reproduce

See the linked code sandbox
1. Open a Toast with timeout of `0`. Note that focusing the toast will dismiss it (without clicking the 'x')
1. Note that with an explicit timeout (e.g. `100_000`) this is not the case; Toast remains open after focusing.
1. `timeout: Infinity` is poorly behaved; Toast immediately closes

#### Actual behavior

See above and also screen recording from sandbox:

https://github.com/palantir/blueprint/assets/20345725/40bc7800-1b37-4cf9-bd1a-405425e835df

#### Expected behavior

Toast with `timeout: 0` should not dismiss early. `timeout: Infinity` should also behave the same as `timeout: 0`

### PR DESCRIPTION
**Pull request by gluxon**
Fixes https://github.com/palantir/blueprint/issues/6742, which was a regression from https://github.com/palantir/blueprint/pull/6656 / `@blueprintjs/core@5.9.0`.

## Context

The [docs](https://github.com/palantir/blueprint/assets/906558/7d20f9cd-4066-4e75-b5e0-1a36a15e8f12) specify that a `timeout` prop of `0` will cause toasts to persist until a user manually dismisses it.

> Milliseconds to wait before automatically dismissing toast. Providing a value less than or equal to 0 will disable the timeout (this is discouraged).

Screenshot 2024-05-02 at 11 29 05 PM

## Problem

In a semi-recent refactor of the `<OverlayToaster>` component, a `timeout` value of `0` caused the toaster to instead be immediately dismissed. Note how hovering in and out of a progress toast causes it to disappear.

https://github.com/palantir/blueprint/assets/906558/7d20f9cd-4066-4e75-b5e0-1a36a15e8f12

## Explanation

The new `<Toast2>` implementation does properly check if the `timeout` prop is `0` or negative on initial mount.

https://github.com/palantir/blueprint/blob/488658d901b2704673450c9c7d9fb923660e3c6e/packages/core/src/components/toast/toast2.tsx#L54-L57

However, it's incorrect on the pause/resume timeout logic that happens when users mouse over a toaster. This logic always starts a timeout on mouse out, even if the timeout is `0`. The original `<Toast>` implementation didn't do this.

https://github.com/palantir/blueprint/blob/488658d901b2704673450c9c7d9fb923660e3c6e/packages/core/src/components/toast/toast2.tsx#L87-L88

## Changes

Copying the logic from the original implementation, which doesn't schedule a timeout at all if it's `0`.

https://github.com/palantir/blueprint/blob/9dfba77ec5094c7752e5b73eb49a7e72dced9dcb/packages/core/src/components/toast/toast.tsx#L117-LL122

https://github.com/palantir/blueprint/assets/906558/3f40ffb9-609c-40a7-a50f-8cb86b937356

### CODE REVIEW

File: packages/core/src/components/toast/toast2.tsx [hunk 1]
```diff
@@ -43,12 +43,15 @@ export const Toast2 = React.forwardRef<HTMLDivElement, ToastProps>((props, ref)
...
+    // Per docs: "Providing a value less than or equal to 0 will disable the timeout (this is discouraged)."
+    const isTimeoutEnabled = timeout != null && timeout > 0;
+
     // timeout is triggered & cancelled by updating `isTimeoutStarted` state
     useTimeout(
         () => {
             triggerDismiss(true);
         },
-        isTimeoutStarted && timeout !== undefined ? timeout : null,
+        isTimeoutStarted && isTimeoutEnabled ? timeout : null,
```
Comment (gluxon) [inline packages/core/src/components/toast/toast2.tsx:54]: This fix looks simple. The hard part was making sure it was the right fix, which I ended up convincing myself is the case.

**Review by pgoldberg — APPROVED** [review]

**Review by invliD — APPROVED** [review]
