### PR TITLE
[core] fix(ContextMenuPopover): clean up document handlers on close

### LINKED ISSUE #6684: ContextMenuPopover blocks body scrolling after closing
#### Environment

- __Package version(s)__: unreleased v5.9.x
- __Operating System__: macOS
- __Browser name and version__: Firefox

#### Steps to reproduce

Visit docs preview from latest Overlay2 related PR https://github.com/palantir/blueprint/pull/6681

#### Actual behavior

cannot scroll document body after closing the context menu

Screen Recording 2024-01-30 at 8 51 00 AM

#### Expected behavior

should be able to resume normal scroll interactions with document after this context menu is closed

#### Possible solution

fix Overlay2 document "mousedown" handler cleanup logic

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

- fix(`ContextMenuPopover`): clean up document handlers on close to allow normal scroll interactions to resume
  - _this was an unreleased regression, so the "fix" will not be included in release notes_
- feat(`ContextMenuPopover`): support configuration of DOM mounting / unmounting methods in imperative `showContextMenu` / `hideContextMenu` APIs
  - _similar to recent changes made to `OverlayToaster` (#6239)_
- docs: minor improvements to overlay-based component docs (consistent formatting)

#### Reviewers should focus on:

Fixes the linked bug

#### Screenshot

Screen Recording 2024-01-30 at 8 55 29 AM

### CODE REVIEW

File: packages/core/src/common/utils/mountOptions.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import type * as React from "react";
+
+/** Identical to `import("react-dom").Container`, copied here to avoid an unncessary type dependency. */
+type Container = Element | Document | DocumentFragment;
+
+/**
+ * Generic options interface for Blueprint APIs which imperatively mount a React component to the
+ * DOM using `"react-dom"`: `OverlayToaster.create`, `showContextMenu`, etc.
+ *
+ * The `domRenderer` currently defaults to React 16's `ReactDOM.create()`; a future version of Blueprint
```
Comment (adidahiya) [inline packages/core/src/common/utils/mountOptions.ts]:
```suggestion
 * The `domRenderer` currently defaults to React 16's `ReactDOM.render()`; a future version of Blueprint
```

File: packages/docs-app/src/examples/core-examples/drawerExample.tsx [hunk 2]
```diff
@@ -183,7 +186,7 @@ export class DrawerExample extends React.PureComponent<ExampleProps<BlueprintExa
 }
 
 const SIZES: Array<string | OptionProps> = [
-    { label: "Default", value: undefined },
+    { label: "Default", value: "default" },
```
Comment (adidahiya) [inline packages/docs-app/src/examples/core-examples/drawerExample.tsx:189]: note that this fixes a minor React warning about a missing "key" on HTMLSelect children in this example

**Comment by adidahiya** [comment]
<h3>Update packages/core/src/common/utils/mountOptions.ts</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/b6cabc9a-e023-453f-9cba-c45989f71f3c/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/b6cabc9a-e023-453f-9cba-c45989f71f3c/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/b6cabc9a-e023-453f-9cba-c45989f71f3c/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/b6cabc9a-e023-453f-9cba-c45989f71f3c/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>
