### PR TITLE
[core] fix(Icon): accept standard HTML attributes

### LINKED ISSUE #4500: Icon component cannot accept ARIA `role` prop
#### Environment

- __Package version(s)__: 3.38
- __Operating System__: RHEL7 (not relevant)
- __Browser name and version__: Firefox 78 (not relevant)

#### Code Sandbox

N/A

#### Steps to reproduce

1. Try to render `<Icon icon="cross" role="image" />`

#### Actual behavior

TypeScript fails to compile because the `Icon` component does not accept a `role` prop.

#### Expected behavior

The `Icon` component would pass through `role` to the underlying `<svg>` or `<span>`

#### Possible solution

`Icon` is currently defined as using `React.DOMAttributes<HTMLElement>>`:

https://github.com/palantir/blueprint/blob/26351ca79595ebaf633c57b1beadc37a9f2d62b6/packages/core/src/components/icon/icon.tsx#L90

Per the React TS types, `role` is part of the `HTMLAttributes` interface, which extends `DOMAttributes`:

```ts
    interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
        // React-specific Attributes
        defaultChecked?: boolean;
        defaultValue?: string | number | ReadonlyArray<string>;
        suppressContentEditableWarning?: boolean;
        suppressHydrationWarning?: boolean;

        // Standard HTML Attributes
        accessKey?: string;
        // omit

        // WAI-ARIA
        role?: string;

        // omit
    }
```

Perhaps it should be switched over to use `HTMLAttributes` instead?

### PR DESCRIPTION
**Pull request by ChristianIvicevic**
#### Checklist

- [X] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

This PR adds standard default HTML attributes to the core Icon component. The motivation was the inability to set a role for icons and with the proposed solution in the linked issue this is now possible.

#### Reviewers should focus on:

Unfortunately the `IIconProps` type already declares a `title` property which collides with the definition in `HTMLAttributes` due to deviating types. In order to prevent issue in the `HTMLSelect` component I decided to omit the latter. This fix is open for dicussion.

### CODE REVIEW

File: packages/core/src/components/icon/icon.tsx [hunk 1]
```diff
@@ -87,7 +87,9 @@ export interface IIconProps extends IIntentProps, IProps {
 }
 
 @polyfill
-export class Icon extends AbstractPureComponent2<IIconProps & React.DOMAttributes<HTMLElement>> {
+export class Icon extends AbstractPureComponent2<
+    IIconProps & Omit<React.HTMLAttributes<HTMLElement>, "title"> & React.DOMAttributes<HTMLElement>
```
Comment (adidahiya) [inline packages/core/src/components/icon/icon.tsx]: we don't need `React.DOMAttributes` anymore, since `React.HTMLAttributes` extends it.

**Review by adidahiya — CHANGES_REQUESTED** [review]

File: packages/core/src/components/icon/icon.tsx (hunk 1 above)
Comment (ChristianIvicevic) [reply packages/core/src/components/icon/icon.tsx]: Ah this is my bad, didn't see it in the first place.

**Review by adidahiya — APPROVED** [review]
