### PR TITLE
Fix hostname for GA

### LINKED ISSUE #91: enable Google Analytics
update condition here: https://github.com/palantir/blueprint/blob/master/docs/docs/index.html#L19
and add GA to landing page.

### PR DESCRIPTION
**Pull request by cyu06**
Fixes #91.

### CODE REVIEW

File: packages/docs/src/components/styleguide.tsx [hunk 1]
```diff
@@ -174,7 +174,7 @@ export class Styleguide extends React.Component<IStyleguideProps, IStyleguideSta
         this.props.onUpdate(this.state.activePageId);
         // whoa handling future history...
         window.addEventListener("hashchange", () => {
-            if (location.hostname.indexOf("github.io") !== -1) {
+            if (location.hostname.indexOf("blueprint") !== -1) {
```
Comment (giladgray) [inline packages/docs/src/components/styleguide.tsx]: why is this check different from all other checks?

Comment (cyu06) [inline packages/docs/src/components/styleguide.tsx]: Because we use this component internally with a different hostname.

Comment (giladgray) [inline packages/docs/src/components/styleguide.tsx]: nice
