### PR TITLE
[Labs] Add initialContent prop for selection components

### LINKED ISSUE #1473: [Labs] Omnibox doesn't render items if query is empty string
### Bug report

- __Package version(s)__: ^0.5.0
- __Browser and OS versions__: MacOS Chrome 60.0.3112.90

#### Steps to reproduce

1. Open Omnibox (without entering a query)

#### Actual behavior

My itemListPredicate function returns a list of recent searches if the query length is 0. Currently, the Omnibox doesn't render this list if the query length is 0. 

#### Expected behavior

The Omnibox should render an itemList regardless of the query length. I was able to resolve the issue by changing the three occurences of `this.state.query.length > 0` to `this.state.query.length >= 0` in omnibox.tsx.

### PR DESCRIPTION
**Pull request by llorca**
#### Checklist

- [ ] Include tests
- [x] Update documentation

#### Changes proposed in this pull request:

Add `initialContent` prop to `Omnibox`, `Select` and `MultiSelect`. This allows consumers to render custom content when the query is empty.

#### Reviewers should focus on:

- Code is getting repetitive, will need help to figure out how to refactor it nicely.
- ~~Is there a better name for this prop?~~

### CODE REVIEW

File: packages/labs/src/components/omnibox/omnibox.tsx [hunk 1]
```diff
@@ -31,14 +31,19 @@ import * as Classes from "../../common/classes";
...
+
+    /**
      * Custom renderer for an item in the dropdown list. Receives a boolean indicating whether
      * this item is active (selected by keyboard arrows) and an `onClick` event handler that
      * should be attached to the returned element.
      */
     itemRenderer: (itemProps: ISelectItemRendererProps<T>) => JSX.Element;
 
     /** React child to render when filtering items returns zero results. */
-    noResults?: string | JSX.Element;
```
Comment (giladgray) [inline packages/labs/src/components/omnibox/omnibox.tsx]: why remove this? lets just use `React.ReactChild` in both places (this and new `initialRenderer`).

File: packages/labs/src/components/omnibox/omnibox.tsx [hunk 2]
```diff
@@ -31,14 +31,19 @@ import * as Classes from "../../common/classes";
 
 export interface IOmniboxProps<T> extends IListItemsProps<T> {
     /**
+     * React child to render when query is empty.
+     */
+    initialRenderer?: JSX.Element;
```
Comment (giladgray) [inline packages/labs/src/components/omnibox/omnibox.tsx]: ❌ this is not a _renderer_, it's an already rendered element. either name or type must change.

note how it's `noResults: JSX.Element` and `itemRenderer: (props) => JSX.Element`

File: packages/labs/src/components/omnibox/omnibox.tsx [hunk 3]
```diff
@@ -179,20 +184,34 @@ export class Omnibox<T> extends React.Component<IOmniboxProps<T>, IOmniboxState<
...
+                    {menuChildren}
                 </Menu>
             );
         }
+
         return undefined;
     }
 
+    private isQueryEmpty = () => {
+        return !(this.state.query.length > 0);
```
Comment (giladgray) [inline packages/labs/src/components/omnibox/omnibox.tsx]: `private isQueryEmpty = () => this.state.query.length === 0` (one line)

**Comment by giladgray** [comment]
would be super great to add a unit test to `Select`

File: packages/labs/src/components/omnibox/omnibox.tsx (hunk 2 above)
Comment (llorca) [inline packages/labs/src/components/omnibox/omnibox.tsx]: Yeah I called that out in the description. Please provide a naming suggestion

File: packages/labs/src/components/omnibox/omnibox.tsx (hunk 1 above)
Comment (llorca) [inline packages/labs/src/components/omnibox/omnibox.tsx]: `string` didn't make sense so I normalized. Will update to `React.ReactChild`

File: packages/labs/src/components/omnibox/omnibox.tsx (hunk 2 above)
Comment (giladgray) [inline packages/labs/src/components/omnibox/omnibox.tsx]: `initialContent`? `emptyContent`?

File: packages/labs/src/components/omnibox/omnibox.tsx (hunk 1 above)
Comment (giladgray) [inline packages/labs/src/components/omnibox/omnibox.tsx]: `noResults="No results"` what's wrong with that?

Comment (llorca) [inline packages/labs/src/components/omnibox/omnibox.tsx]: We force render everything into a `Menu`, so from a design standpoint, a raw string within a menu is 🚫

File: packages/labs/examples/multiSelectExample.tsx [hunk 4]
```diff
@@ -19,7 +19,7 @@ const INTENTS = [Intent.NONE, Intent.PRIMARY, Intent.SUCCESS, Intent.DANGER, Int
 
 export interface IMultiSelectExampleState {
     films?: Film[];
-    initialRenderer?: boolean;
+    initialContent?: boolean;
```
Comment (giladgray) [inline packages/labs/examples/multiSelectExample.tsx]: i'd call this `hasInitialContent` to distinguish from the actual prop since this one's a boolean

File: packages/labs/src/components/omnibox/omnibox.tsx [hunk 5]
```diff
@@ -33,7 +33,7 @@ export interface IOmniboxProps<T> extends IListItemsProps<T> {
     /**
      * React child to render when query is empty.
      */
-    initialRenderer?: JSX.Element;
+    initialContent?: JSX.Element;
```
Comment (giladgray) [inline packages/labs/src/components/omnibox/omnibox.tsx]: `React.ReactChild` here too

File: packages/labs/src/components/select/multiSelect.tsx [hunk 6]
```diff
@@ -35,7 +35,7 @@ export interface IMultiSelectProps<T> extends IListItemsProps<T> {
     /**
      * React child to render when query is empty.
      */
-    initialRenderer?: JSX.Element;
+    initialContent?: JSX.Element;
```
Comment (giladgray) [inline packages/labs/src/components/select/multiSelect.tsx]: React.ReactChild

File: packages/labs/src/components/select/select.tsx [hunk 7]
```diff
@@ -36,7 +36,7 @@ export interface ISelectProps<T> extends IListItemsProps<T> {
     /**
      * React child to render when query is empty.
      */
-    initialRenderer?: JSX.Element;
+    initialContent?: JSX.Element;
```
Comment (giladgray) [inline packages/labs/src/components/select/select.tsx]: React.ReactChild

**Comment by llorca** [comment]
@giladgray ready for re-review when you get a chance 👍

File: packages/labs/examples/multiSelectExample.tsx [hunk 8]
```diff
@@ -80,6 +88,12 @@ export class MultiSelectExample extends BaseExample<IMultiSelectExampleState> {
                     checked={this.state.resetOnSelect}
                     onChange={this.handleResetChange}
                 />,
+                <Switch
+                    key="hasInitialContent"
+                    label="Show initial renderer"
```
Comment (giladgray) [inline packages/labs/examples/multiSelectExample.tsx]: old prop name... "Use initial content" ?

File: packages/labs/examples/selectExample.tsx [hunk 9]
```diff
@@ -96,6 +105,12 @@ export class SelectExample extends BaseExample<ISelectExampleState> {
                     checked={this.state.disabled}
                     onChange={this.handleDisabledChange}
                 />,
+                <Switch
+                    key="hasInitialContent"
+                    label="Show initial renderer"
```
Comment (giladgray) [inline packages/labs/examples/selectExample.tsx]: again with prop name

File: packages/labs/src/components/omnibox/omnibox.tsx [hunk 10]
```diff
@@ -179,20 +184,32 @@ export class Omnibox<T> extends React.Component<IOmniboxProps<T>, IOmniboxState<
...
+        const { initialContent } = this.props;
+        let menuChildren: any;
+
+        if (!this.isQueryEmpty()) {
+            menuChildren = this.renderItems(listProps);
+        } else if (initialContent != null) {
+            menuChildren = initialContent;
+        }
+
+        if (menuChildren != null) {
```
Comment (cmslewis) [inline packages/labs/src/components/omnibox/omnibox.tsx]: nit: i tend to do:

```tsx
return menuChildren == null
    ? undefined
    : (
        <Menu ulRef={listProps.itemsParentRef}>
            {this.renderItems(listProps)}
            {menuChildren}
        </Menu>
    );
```

or maybe even:

```tsx
return menuChildren == null ? undefined : (
    <Menu ulRef={listProps.itemsParentRef}>
        {this.renderItems(listProps)}
        {menuChildren}
    </Menu>
);
```

File: packages/labs/src/components/omnibox/omnibox.tsx [hunk 11]
```diff
@@ -179,20 +184,32 @@ export class Omnibox<T> extends React.Component<IOmniboxProps<T>, IOmniboxState<
...
-                    {this.renderItems(listProps)}
+                    {menuChildren}
                 </Menu>
             );
         }
+
         return undefined;
     }
 
+    private isQueryEmpty = () => this.state.query.length === 0;
```
Comment (cmslewis) [inline packages/labs/src/components/omnibox/omnibox.tsx]: I prefer explicit `return` if you're returning something. and explicit returns inline are kinda weird (TSLint may even complain about that), so here's how I would write this:

```tsx
private isQueryEmpty = () => {
    return this.state.query.length === 0;
}
```

File: packages/labs/src/components/select/multiSelect.tsx [hunk 12]
```diff
@@ -175,10 +184,12 @@ export class MultiSelect<T> extends React.Component<IMultiSelectProps<T>, IMulti
         }));
     }
 
+    private isQueryEmpty = () => this.state.query.length === 0;
```
Comment (cmslewis) [inline packages/labs/src/components/select/multiSelect.tsx]: nit: same

File: packages/labs/src/components/select/select.tsx [hunk 13]
```diff
@@ -210,11 +219,13 @@ export class Select<T> extends React.Component<ISelectProps<T>, ISelectState<T>>
     }
 
     private maybeRenderInputClearButton() {
-        return this.state.query.length > 0
+        return !this.isQueryEmpty()
             ? <Button className={CoreClasses.MINIMAL} iconName="cross" onClick={this.resetQuery} />
             : undefined;
     }
 
+    private isQueryEmpty = () => this.state.query.length === 0;
```
Comment (cmslewis) [inline packages/labs/src/components/select/select.tsx]: nit: same

File: packages/labs/src/components/omnibox/omnibox.tsx (hunk 10 above)
Comment (llorca) [reply packages/labs/src/components/omnibox/omnibox.tsx]: Happy to address those nits but they seem to be conflicting with some previous feedback. @giladgray?

File: packages/labs/src/components/omnibox/omnibox.tsx (hunk 11 above)
Comment (adidahiya) [reply packages/labs/src/components/omnibox/omnibox.tsx]: generally 👎 ; I think the terse style is nice

File: packages/labs/src/components/omnibox/omnibox.tsx (hunk 10 above)
Comment (adidahiya) [reply packages/labs/src/components/omnibox/omnibox.tsx]: let's just switch to prettier and throw away all these debates

**Comment by cmslewis** [comment]
@llorca I think you've addressed all of @giladgray's feedback, so I'd say you're good to merge if that's the case.
