### PR TITLE
[Table] Select the target cell on right-click

### LINKED ISSUE #1187: Table selection/context menu bugginess
### Bug report

- __Package version(s)__: Latest
- __Browser and OS versions__: Mac Sierra

#### Steps to reproduce

There are actually 2 things happening here, the first, and more important one for me, is that it doesn't seem like the Table component handles context menu clicks in the usual way: 
asdfasdfasd

As you can see (on the docs page itself), when I right click above in your example table, the selected region doesn't change. I believe this is because the table `onSelection` prop does not get fired for right-clicks. I am running into this same issue with my own Table as well but am not sure quite how to solve it. Any help would be appreciated.

The second, smaller issue , is that for some reason opening the context menu causes the whole page to shift slightly. You can see this in the video as well if you look closely. I also find this to be the case when implementing my own blueprint tables. Does anyone know why this is happening?

Thanks very much!

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

- 🐛 __Fixed__ `Table` now selects the target cell on right-click if the cell is not already contained in a selection.

### CODE REVIEW

File: packages/table/src/tableBody.tsx [hunk 1]
```diff
@@ -215,8 +215,24 @@ export class TableBody extends React.Component<ITableBodyProps, {}> {
             return undefined;
         }
 
-        const target = this.locateClick(e.nativeEvent as MouseEvent);
-        return renderBodyContextMenu(new MenuContext(target, selectedRegions, grid.numRows, grid.numCols));
+        const targetRegion = this.locateClick(e.nativeEvent as MouseEvent);
+        const { numRows, numCols } = grid;
+
+        const menuContext = new MenuContext(targetRegion, selectedRegions, numRows, numCols);
```
Comment (gscshoyru) [inline packages/table/src/tableBody.tsx]: Should we not be fixing the selectedRegions first here? Before we render the menu?

Comment (cmslewis) [reply packages/table/src/tableBody.tsx]: Sure, fixed

**Comment by llorca** [comment]
Doesn't seem to work on my end.

Right click behavior:
rightclick

Ctrl click behavior:
ctrlclick

Expected behavior:
- Right/ctrl click on a cell/column/row selects said cell/column/row. It shouldn't append to any current selection but create a new one instead

**Comment by cmslewis** [comment]
@llorca Try with the new build once it finishes. The upcoming version works fine and passes tests locally FWIW.

**Comment by llorca** [comment]
Yup, right-click behavior now works!

Note that ctrl-click behavior is still broken, still behaving as the GIF above.

**Comment by cmslewis** [comment]
@llorca @gscshoyru I'm going to fix the cmd+click thing once #1524 merges. I have an issue tracking the follow-up already.
