### PR TITLE
brilliant docs anchors!

### LINKED ISSUE #167: [Docs] Difficult to select text above heading
#### Actual behavior:

In the docs, you cannot select text just above the heading or click links because the element is oversized and has had massive padding applied which is layering above the text just above it.

In the below screenshot
screen shot 2016-11-15 at 3 09 47 pm

We see that the padding for the heading overlaps the text making it difficult to select.

#### Expected behavior:

The headers should only be taking as much space as they are supposed to and all text and links across the documentation should be selectable and clickable respectively

### LINKED ISSUE #172: Links in toasts with intent are not accessible
### Bug Report

- __Package version(s)__: v1.0.1

#### Describe the issue:

screen shot 2016-11-15 at 11 13 55 am

#### Actual behavior:

The links are `$blue3`.

#### Expected behavior:

The links are white but underlined.

### PR DESCRIPTION
**Pull request by giladgray**
#### PR checklist

- [x] Addresses an existing issue: fixes #167 

#### What changes did you make?

- revert anchor padding trick for section positioning (see 06d41ab)
- invisible `<a name="" />` with negative margin solves all our anchor woes!
- can even use only margins on the headings! adjust margins a bit to account for collapsing and descenders.
- adjust some params for the scroll spy algorithm to account for new styles.

this one little change cleans up every hack in these headings!
(discovered by inspecting styles of React docs site)

### CODE REVIEW

File: packages/docs/src/index.tsx [hunk 1]
```diff
@@ -57,3 +57,9 @@ ReactDOM.render(
 // tslint:enable:jsx-no-lambda
 
 FocusStyleManager.onlyShowFocusOnTabs();
+
+// scroll down a bit when loading on a hash anchor so it appears below the fixed navbar.
+// i think this is necessary because the negative margin trick doesn't work on page load
+// with react (might work via SSR where HTML is already there).
+// (80px = navbar height + content padding)
+if (location.hash) { scrollBy(0, -80); }
```
Comment (adidahiya) [inline packages/docs/src/index.tsx]: no implicit null-to-boolean conversion please. also make this multiline

**Comment by llorca** [comment]
Still a few inconsistencies, check out the screenshots:

When loading `/`:
image

When clicking on "Overview":
image

When loading `/#overview`:
image

**Comment by giladgray** [comment]
resolving those inconsistencies via #176, will update this PR when it merges
