### PR TITLE
[Button] Utils.isEmptyReactNode solves icon regression

### LINKED ISSUE #2769: Migrating to 3.0: Icon Buttons have extra padding on right side
#### Environment

- __Package version(s)__: `@blueprintjs/core 3.2.0`
- __Browser and OS versions__: Max OS X Sierra, Chrome 68.0.3440.84

#### Steps to reproduce

Buttons with an icon but no text have extra right padding in Blueprint 3.X (and maybe in 2.X too, since that's when the SVG icon refactor occurred?).

#### Actual behavior

From the [Button docs](http://blueprintjs.com/docs/#core/components/button):

screen shot 2018-08-07 at 9 21 37 am
screen shot 2018-08-07 at 9 22 09 am

#### Expected behavior

image

image

#### Possible solution

Given that:
- We'd need to detect when `.bp3-button-text` is `:empty` in order to remove the `margin-right` from the _preceding_ `svg` element, and
- CSS selectors don't let you peek ahead like that,

It follows that:
- A pure CSS solution here would presumably require us to either (1) add a new `bp3-button-empty` CSS class to the root button element, or (2) move the `margin-right` on the `svg` to a `margin-left` on `bp3-button-text`, then do this:

    ```scss
    .bp3-icon + .bp3-button-text {
        margin: 7px; // or whatever SCSS variable math yields this value
    }
   
    .bp3-button-text:empty {
        margin-left: 0;
    }
    ```

I propose (2).

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- `Utils.isEmptyReactNode` to ensure correct detection of empty nodes.
- this fixes a regression in #2727 where `children` is easily non-null

### CODE REVIEW

File: packages/core/src/common/utils.ts [hunk 1]
```diff
@@ -24,6 +24,23 @@ export function isFunction(value: any): value is Function {
     return typeof value === "function";
 }
 
+/**
+ * Returns true if `node` is null/undefined, false, empty string, or an array
+ * composed of those. If `node` is an array, only one level of the array is
+ * checked, for performance reasons.
+ */
+export function isEmptyReactNode(node?: React.ReactNode, skipArray = false): boolean {
```
Comment (cmslewis) [inline packages/core/src/common/utils.ts]: `isEmptyReactNode`/`isReactNodeEmpty`? Would normally lean toward the second. The former implies to me that the function is also going to verify that the parameter _is_ a `ReactNode` in the first place.

File: packages/core/test/common/utilsTests.tsx [hunk 2]
```diff
@@ -16,6 +16,19 @@ describe("Utils", () => {
         assert.isFalse(Utils.isFunction(undefined));
     });
 
+    it("isEmptyReactNode", () => {
+        // empty nodes
+        assert.isTrue(Utils.isEmptyReactNode(undefined), "undefined");
+        assert.isTrue(Utils.isEmptyReactNode(null), "null");
+        assert.isTrue(Utils.isEmptyReactNode(""), '""');
+        assert.isTrue(Utils.isEmptyReactNode([]), "[]");
```
Comment (cmslewis) [inline packages/core/test/common/utilsTests.tsx]: I'd use `[undefined, null, false, ""]` to make the case thorough.
