### PR TITLE
[select] fix: mark items arrays as readonly where appropriate

### LINKED ISSUE #4976: Select's types don't accept readonly item arrays
#### Environment

- __Package version(s)__:
  - @blueprintjs/core: 3.48.0
  - @blueprintjs/select: 3.17.0
- __Operating System__: macOS 11.6
- __Browser name and version__: Firefox 92

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)):
https://codesandbox.io/s/blueprint-sandbox-forked-8sm3h?file=/src/index.tsx

#### Steps to reproduce

1.  open above link

#### Actual behavior

The code does not compile

#### Expected behavior

Select should be able to receive readonly array since it does not mutate the passed array.

#### Possible solution

Annotate the props with `readonly`

### PR DESCRIPTION
**Pull request by maclockard**
#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Added readonly annotations to select array props

#### Reviewers should focus on:

The types

### CODE REVIEW

File: packages/select/src/common/predicate.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@
  * A custom predicate for returning an entirely new `items` array based on the provided query.
  * See usage sites in `IListItemsProps`.
  */
-export type ItemListPredicate<T> = (query: string, items: T[]) => T[];
+export type ItemListPredicate<T> = (query: string, items: readonly T[]) => T[];
```
Comment (maclockard) [inline packages/select/src/common/predicate.ts]: Changing the types of callback arguments may cause compile breaks for consumers, but should be easily fixed, since if they were mutating this argument here, it was probably causing problems

File: packages/docs-theme/src/components/navigator.tsx [hunk 2]
```diff
@@ -85,7 +85,7 @@ export class Navigator extends React.PureComponent<INavigatorProps> {
     }
 
     private filterMatches: ItemListPredicate<INavigationSection> = (query, items) =>
-        filter(items, query, {
+        filter([...items], query, {
```
Comment (maclockard) [inline packages/docs-theme/src/components/navigator.tsx]: could also cast as a writable array instead. Problem here is the upstream types for `filter` from `fuzzaldrin-plus` don't use `readonly` for this argument

File: packages/select/src/common/listItemsProps.ts [hunk 3]
```diff
@@ -155,7 +155,7 @@ export interface IListItemsProps<T> extends Props {
     /**
      * Callback invoked when multiple items are selected at once via pasting.
      */
-    onItemsPaste?: (items: T[]) => void;
+    onItemsPaste?: (items: readonly T[]) => void;
```
Comment (maclockard) [inline packages/select/src/common/listItemsProps.ts]: this one is optional since `items` here appears to be a new array when this callback is invoked.

File: packages/docs-app/src/examples/select-examples/multiSelectExample.tsx [hunk 4]
```diff
@@ -209,7 +209,7 @@ export class MultiSelectExample extends React.PureComponent<IExampleProps, IMult
         this.selectFilms([film]);
     }
 
-    private selectFilms(filmsToSelect: IFilm[]) {
+    private selectFilms(filmsToSelect: readonly IFilm[]) {
```
Comment (adidahiya) [inline packages/docs-app/src/examples/select-examples/multiSelectExample.tsx]: this seems like a breaking change for consumers, no? looks like you were getting TS compilation errors until you changed this.

Comment (maclockard) [reply packages/docs-app/src/examples/select-examples/multiSelectExample.tsx]: Yeah, that was what I was talking about here: https://github.com/palantir/blueprint/pull/5171#discussion_r828450664 

It is a compile time break, but if people were actually modifying the array I would imagine the select wouldn't be working.

However, it's easy enough to make a mutable copy of the item list and pass that to the callback instead if you'd prefer to avoid the compile time break

Comment (adidahiya) [reply packages/docs-app/src/examples/select-examples/multiSelectExample.tsx]: yeah, i'd prefer that to avoid upgrade surprises right now. I don't want to force consumers to add the `readonly ` even if it's easy to do so. we can make the compile break in v5.0 (v4 is already closed for breaking changes)

**Review by adidahiya — APPROVED** [review]

**Comment by adidahiya** [comment]
I have to revert this, it's causing downstream compilation errors:

```
[error] TypeScript error packages/[redacted]/filterable-select.tsx:25:9 - error TS2345: Argument of type 'readonly T[]' is not assignable to parameter of type 'T[]'.
  The type 'readonly T[]' is 'readonly' and cannot be assigned to the mutable type 'T[]'.

25         items,
           ~~~~~
```

**Comment by maclockard** [comment]
@adidahiya curious if that's actually coming from using a `Select`/`QueryList`/etc component or if its coming from downstream consumer reusing `IListItemsProps`/`ISelectProps`/etc for their own components?

I suspect it's probably the second looking at the file name. If that's the case, seems easy enough to only apply the change for types blueprint components use, and leave the exported types alone?

**Comment by adidahiya** [comment]
It is the latter, "downstream consumer reusing `ISelectProps` for their own components". I'm open to an alternative fix if you want to send a PR. I'll test it downstream before merging.

**Comment by maclockard** [comment]
hmmm, now that I think about it, my potential solution to that problem kinda falls under 'no one wins' territory since folks trying to get the actual prop types will have trouble.

I think it makes sense to do this as a breaking change as a part of v5. That way we could also fix the callback types as well. What does queuing a change for v5 look like?

**Comment by adidahiya** [comment]
> What does queuing a change for v5 look like?

I'm not ready for this yet, but i'll have a process for this ready in the next few weeks. Stay tuned
