### PR TITLE
Tabs2: new API for Tabs component

### LINKED ISSUE #261: Tabs component improvements
I have a few suggestions on the <Tabs> component, mainly in regards to the layout to make slightly more customizable. In my case, I would like to add an element to be right aligned in level of the tabs within that component. 

In my use case i have several tabs with forms and settings where you can configure the application, with a single button for saving all changes once you are happy. This button I would like to have within the tabs but aligned to the right of them instead of having it as now shown at the bottom of the page.

This new component part could be a general element, so that you could also add other components than a button, for example a progress indicator or spinner perhaps.

Perhaps something like this;
```js
<Tabs>
    <TabList>
        <Tab>First tab</Tab>
        <Tab>Second tab</Tab>
        <TabElement align={Position.RIGHT}><Button iconName="refresh" text="Save Settings" onClick={this.saveConfiguration}/></TabElement >
        <TabElement align={Position.RIGHT}><Spinner intent={1} value={this.props.progressSaving}/></TabElement >
    </TabList>
    <TabPanel>
        First panel
    </TabPanel>
    <TabPanel>
        Second panel
    </TabPanel>
</Tabs>
```

It could even be a new component, a `<Toolbar>` or similar where you can componse the left side to have tabs and the right side to have an input, button or other component. 

This would mean that you would decouple the need to have equal `<Tab>` and `<TabPanel>` as you would probably only want to have the `<TabList>` within it and display the content somewhere else.

### LINKED ISSUE #384: SSR tabs are not reused on client
### Bug report

- __Package version(s)__: `1.4.0`
- __Browser and OS versions__: `Chrome 54.0.2840.98`, `OSX 10.11.6`

#### Steps to reproduce
I don't have clean repo to provide with example, but sample usage example for tabs with SSR enabled project will be enough to reproduce the problem.

#### Actual behavior

I am getting this warning when rendering `Sample Usage` [example](http://blueprintjs.com/docs/#components.tabs.js).
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) trols="pt-tab-panel-0" aria-disabled="fa
 (server) trols="pt-tab-panel-20" aria-disabled="f
```
Every time I reload page, server rendered tabs get ID that is increasing. 
I think the problem is in the way IDs are generated [here](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/tabs/tabs.tsx#L373). Module scoped variable is used to count tabs which gets initialized on 1st import and keeps increasing on each server render.

#### Expected behavior

Expected behavior would be that tabs are rendered in isolation and markup is reused on client.

### PR DESCRIPTION
**Pull request by giladgray**
#### Fixes #261, Fixes #384
Related, perhaps future fixes: #197, #363, #509, #583 

#### Changes proposed in this pull request:

A brand-new React API for the `Tabs` component, which we're calling `Tabs2` so this can be shipped now in a non-breaking way. The CSS API is unchanged. `Tabs2` will replace the old `Tabs` components in 2.0.0.

- Only two components (`Tabs` and `Tab`) are needed, rather than the previous four.
- Selection is managed by ID, rather than by index. This is more reliable and deterministic and
    does not require translating between numbers and tab names. It does, however, require that
    every `Tab` have a locally unique `id` prop.
- Arbitrary elements are supported in the tab list, and order is respected. Yes, you can even
    insert things _between_ `Tab`s.
- Greatly simplified logic: everything is in `tabs.tsx` and nary a `cloneElement`!

#### Reviewers should focus on:

- the API itself: `ITabs2Props`, `ITab2Props`.
- the CSS API is actually unchanged.

### CODE REVIEW

**Comment by giladgray** [comment]
I have a big question: 

### should the children of `Tab` be the panel (current behavior) or the title (and add `panel` prop a la `Popover`)?

current usage looks like this:

```jsx
<Tabs2 id="types">
    <Tab2 id="fruits" title="Fruits">
        <h1>A list of fruits</h1>
    </Tab2>
    <Tab2 id="grains" title="Grains">
        <h1>A list of grains</h1>
    </Tab2>
    <input type="text" placeholder="Search..." />
</Tabs2>
```

usage could look like this:

```jsx
<Tabs2 id="types">
    <Tab2 id="fruits" panel={fruitPanel}>
        Fruits
        <Tag>{totalFruits}</Tag>
    </Tab2>
    <Tab2 id="grains" title="Grains" panel={grainPanel} />
    <input type="text" placeholder="Search..." />
</Tabs2>
```

**Comment by adidahiya** [comment]
unfortunately markdown does not work inside callouts in the docs:

image

File: packages/core/src/components/tabs2/tabs.tsx [hunk 1]
```diff
@@ -0,0 +1,285 @@
...
+        if (this.tabElement == null) {
+            return [] as Elements;
+        }
+        return this.tabElement.queryAll(TAB_SELECTOR + subselector);
+    }
+
+    private getTabClickHandler(newTabId: TabId) {
+        return () => {
+            const isControlled = this.props.selectedTabId !== undefined;
+            const { selectedTabId } = isControlled ? this.props : this.state;
```
Comment (ericanderson) [inline packages/core/src/components/tabs2/tabs.tsx]: Above you specify that state is the conical authority for `selectedTabId` and set on every prop change. Therefor, you should just be able to pull this off `this.state` no?

File: packages/core/src/components/tabs2/tabs.tsx [hunk 2]
```diff
@@ -0,0 +1,285 @@
...
+        const { indicatorWrapperStyle, selectedTabId } = this.state;
+
+        const tabTitles = React.Children.map(this.props.children, (child) => {
+            if (isTab(child)) {
+                const { id } = child.props;
+                return (
+                    <TabTitle
+                        {...child.props}
+                        parentId={this.props.id}
+                        onClick={this.getTabClickHandler(id)}
```
Comment (ericanderson) [inline packages/core/src/components/tabs2/tabs.tsx]: This creates a new function every render cycle, hurting performance.

Suggestion: on `TabTitle` change `onClick` to pass the id.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 3]
```diff
@@ -0,0 +1,285 @@
...
+    /** Queries root HTML element for all `.pt-tab`s with optional filter selector */
+    private getTabElements(subselector = "") {
+        if (this.tabElement == null) {
+            return [] as Elements;
+        }
+        return this.tabElement.queryAll(TAB_SELECTOR + subselector);
+    }
+
+    private getTabClickHandler(newTabId: TabId) {
+        return () => {
```
Comment (ericanderson) [inline packages/core/src/components/tabs2/tabs.tsx]: Nit: Rename to `handleTabClick` and drop the wrapped function and just process. See above comment.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 4]
```diff
@@ -0,0 +1,285 @@
...
+
+    private handleKeyPress = (e: React.KeyboardEvent<HTMLDivElement>) => {
+        const targetTabElement = (e.target as HTMLElement).closest(TAB_SELECTOR) as HTMLElement;
+        if (targetTabElement != null && isEventKeyCode(e, Keys.SPACE, Keys.ENTER)) {
+            e.preventDefault();
+            targetTabElement.click();
+        }
+    }
+
+    private handleTabRef = (tabElement: HTMLDivElement) => { this.tabElement = tabElement; };
```
Comment (ericanderson) [inline packages/core/src/components/tabs2/tabs.tsx]: Nit: `tabElement` can be `undefined` while in the process of unmounting.

**Comment by ericanderson** [comment]
Regarding the big question, I have no strong preference but would lean towards having `panel`.

I would also want `panel` to be optional. I might want to use tabs in a complex enough scenario in which having the `<Tabs2/>` component managing the rendering actually hinders me. For example, if I want a shared left panel below the tabs, but want the tabs to control a right panel below the tabs. This would be challenging (impossible?).

File: packages/core/src/components/tabs2/tab.tsx [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+    id: TabId;
+
+    /**
+     * Content of tab title element,
+     * rendered in a list above the active panel
+     */
+    title: string | JSX.Element;
+}
+
+@PureRender
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tab.tsx]: unfortunately it's what we have to do in Blueprint until 2.0 because we support `"react": "^15.0.1 || ^0.14"`

File: packages/core/src/components/tabs2/tabs.tsx (hunk 2 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: that would require making `TabTitle` a full component so it can have an instance method... thoughts on that refactor?

File: packages/core/src/components/tabs2/tabs.tsx (hunk 1 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: hmmm i'll play with that. you just may be correct 🌮

File: packages/core/src/components/tabs2/tabs.tsx (hunk 4 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: yep that's ok and expected. i check for existence before using `this.tabElement` elsewhere.

**Comment by giladgray** [comment]
oh yea of course `panel` would be optional! i forgot but that's actually the primary motivation for a `panel` prop: you could easily drop the prop and render your panel elsewhere in your app, as you suggested above.

**Comment by cmslewis** [comment]
Regarding the big question, I absolutely vote for the `panel` prop (though should we call it `content`, as `Popover` does?). Then we can put arbitrary content into the tab title (`Tag`, `Icon`, text, etc.) as you demonstrated.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 6]
```diff
@@ -0,0 +1,285 @@
...
+//     </Tab>
+//     <input type="text" placeholder="Search..." />
+// </Tabs>
+
+// TODO
+// vertical key bindings? up/dn
+
+type TabElement = React.ReactElement<ITab2Props & { children: React.ReactNode }>;
+
+const TAB_SELECTOR = `.${Classes.TAB}`;
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: Codebase pattern question: should component-specific constants go in the component as static fields (accessible via `Tabs2.TAB_SELECTOR`, e.g.), or should they live outside as you've done here? If anything, the latter leads to shorter line lengths, but I admittedly haven't heard a clear answer to this general question yet.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 7]
```diff
@@ -0,0 +1,285 @@
...
+     * Whether the selected tab indicator should animate its movement.
+     * @default true
+     */
+    animate?: boolean;
+
+    /**
+     * Initial selected tab `id`. Note that this prop refers only to `<Tab>` children;
+     * other types of elements are ignored.
+     * @default first tab
+     */
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: FWIW based on the language here I didn't _immediately_ grok how this prop would play into the usage (feels obvious now, but I was initially reading this as some kind of identifier that was tossed to whichever element was currently selected, rather than the ID of the tab I should render as initially selected). Might be worthwhile to massage the messaging here just a little.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 8]
```diff
@@ -0,0 +1,285 @@
...
+    constructor(props?: ITabs2Props, context?: any) {
+        super(props, context);
+        let selectedTabId = props.selectedTabId;
+        if (selectedTabId === undefined) {
+            // select first tab in absence of user input
+            selectedTabId = props.defaultSelectedTabId === undefined
+                ? this.getTabChildren()[0].props.id
+                : props.defaultSelectedTabId;
+            // NOTE: providing an unknown ID will hide the selection
+        }
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: nit: For this kind of controlled/default value juggling, I've started to use a private function called `getInitialX`—in this case, `getInitialSelectedId`—to avoid having a mutable variable and to reduce complexity in the constructor.

```
private getInitialSelectedId = () => {
  const controlledSelectedTabId = props.selectedTabId;
  const { defaultSelectedTabId } = props;

  if (controlledSelectedTabId !== undefined) {
    return controlledSelectedTabId;
  } else if (defaultSelectedTabId !== undefined) {
    return defaultSelectedTabId;
  } else {
    return this.getTabChildren()[0].props.id;
  }
}
```

ubernit: I'd also prefer a `this.getTabChild(index: number)` function instead of `this.getTabChildren()[index: number]`, even though it would only be needed here.

File: packages/core/src/components/tabs2/tabs.tsx (hunk 2 above)
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: I'm curious to see the performance difference. If it's noticeable or otherwise egregious, might as well?

File: packages/core/src/components/tabs2/tabs.tsx [hunk 9]
```diff
@@ -0,0 +1,285 @@
...
+                    <TabTitle
+                        {...child.props}
+                        parentId={this.props.id}
+                        onClick={this.getTabClickHandler(id)}
+                        selected={id === selectedTabId}
+                    />
+                );
+            } else {
+                // TabTitle renders an <li> so let's do the same here
+                return <li>{child}</li>;
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: Big +1. As a Blueprint user in the past, I was bitten a couple times by unidentifiable wrappers like this. e.g. What if I want to style a particular tab title as a whole entity? In this implementation, there's no ID/class/selector that will let me style one particular outermost `li` wrapper. Maybe we could at least include a CSS class like `pt-tab-title-{myTabId}`?

File: packages/core/src/components/tabs2/tabs.tsx [hunk 10]
```diff
@@ -0,0 +1,285 @@
...
+        return (
+            <div className={classes}>
+                <div
+                    className={Classes.TAB_LIST}
+                    onKeyDown={this.handleKeyDown}
+                    onKeyPress={this.handleKeyPress}
+                    ref={this.handleTabRef}
+                    role="tablist"
+                >
+                    {this.props.animate ? tabIndicator : undefined}
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: If `animate={false}`, do we still show a blue underline beneath the selected tab?

File: packages/core/src/components/tabs2/tabs.tsx [hunk 11]
```diff
@@ -0,0 +1,285 @@
...
+        }
+        return this.tabElement.queryAll(TAB_SELECTOR + subselector);
+    }
+
+    private getTabClickHandler(newTabId: TabId) {
+        return () => {
+            const isControlled = this.props.selectedTabId !== undefined;
+            const { selectedTabId } = isControlled ? this.props : this.state;
+            if (newTabId !== selectedTabId) {
+                safeInvoke(this.props.onChange, newTabId, selectedTabId);
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: nit: We're pretty inconsistent syntactically with `Utils.safeInvoke` vs `safeInvoke`. Would prefer to align on one pattern (in particular, I prefer the former, because it's nice to see the namespace).

File: packages/core/src/components/tabs2/tabs.tsx [hunk 12]
```diff
@@ -0,0 +1,285 @@
...
+        if (focusedElement == null) { return; }
+
+        // must rely on DOM state because we have no way of mapping `focusedElement` to a JSX.Element
+        const enabledTabElements = this.getTabElements()
+            .filter((el) => el.getAttribute("aria-disabled") === "false");
+        const focusedIndex = enabledTabElements.indexOf(focusedElement);
+
+        if (focusedIndex >= 0 && isEventKeyCode(e, Keys.ARROW_LEFT, Keys.ARROW_RIGHT)) {
+            // UP keycode is between LEFT and RIGHT so this produces 1 | -1
+            const direction = e.which - Keys.ARROW_UP;
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: Hmm this is a little too clever for my taste. Would prefer expressing the `-1` and `+1` explicitly, then nixing the comment.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 13]
```diff
@@ -0,0 +1,285 @@
...
+            const { length } = enabledTabElements;
+            // auto-wrapping at 0 and `length`
+            const nextFocusedIndex = (focusedIndex + direction + length) % length;
+            (enabledTabElements[nextFocusedIndex] as HTMLElement).focus();
+        }
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: But all told this is super cool behavior. 👍

File: packages/core/test/tabs/tabs2Tests.tsx [hunk 14]
```diff
@@ -0,0 +1,274 @@
...
+        tabList.simulate("keypress", { target: tabElements[2], which: Keys.SPACE });
+
+        assert.equal(changeSpy.callCount, 2);
+        assert.deepEqual(changeSpy.args, [
+            [TAB_IDS[1], TAB_IDS[0]],
+            [TAB_IDS[2], TAB_IDS[1]],
+        ]);
+    });
+
+    it("animate=false removes moving indicator element", () => {
```
Comment (cmslewis) [inline packages/core/test/tabs/tabs2Tests.tsx]: Yeah I feel like we should keep the blue underline on the selected tab, even if it doesn't animate. Was there a design discussion in the past about this point?

File: packages/core/examples/tabs2Example.tsx [hunk 15]
```diff
@@ -0,0 +1,96 @@
+/*
+ * Copyright 2015 Palantir Technologies, Inc. All rights reserved.
```
Comment (giladgray) [inline packages/core/examples/tabs2Example.tsx]: yeah yeah working on it

File: packages/core/examples/tabs2Example.tsx [hunk 16]
```diff
@@ -0,0 +1,96 @@
...
+                    label="Render active tab panel only"
+                    key="active"
+                    onChange={this.toggleActiveOnly}
+                />,
+            ],
+        ];
+    }
+
+    private getTitle(title: string) {
+        return title + (this.state.activeTabId === title.toLowerCase() ? " (active)" : "");
```
Comment (giladgray) [inline packages/core/examples/tabs2Example.tsx]: no we certainly don't. i added that to test something we had a unit test for in the old API, and it just worked out of the box. i'd like to refactor the example a bunch so need to review it thoroughly (too late 😄 )

File: packages/core/src/components/tabs2/_tabs2.scss [hunk 17]
```diff
@@ -0,0 +1,64 @@
...
+
+<div class="pt-callout pt-intent-danger pt-icon-error">
+  <h5>Original `Tabs` API is deprecated since v1.10.0</h5>
+  The original `Tabs` API has been deprecated in v1.10.0 favor of the simpler and more flexible
+  `Tabs2` API described below. Documentation for the deprecated components can be found
+  [further below](#components.tabs.deprecated). The deprecated components will be removed in v2.0.
+</div>
+
+<div class="pt-callout pt-intent-primary pt-icon-info-sign">
+  <h5>Advantages of new API</h5>
```
Comment (giladgray) [inline packages/core/src/components/tabs2/_tabs2.scss]: next time leave the comment on the suspect code. i fixed this locally but this comment may not disappear as i haven't touched _this_ `h5` line.

File: packages/core/src/components/tabs2/tab.tsx [hunk 18]
```diff
@@ -0,0 +1,56 @@
...
+    disabled?: boolean;
+
+    /**
+     * Unique identifier used to control which tab is selected.
+     */
+    id: TabId;
+
+    /**
+     * Content of tab title element,
+     * rendered in a list above the active panel
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tab.tsx]: copy-pasta but yes i agree

File: packages/core/src/components/tabs2/tab.tsx [hunk 19]
```diff
@@ -0,0 +1,56 @@
...
+        id: undefined,
+        title: "Untitled",
+    };
+
+    public displayName = "Blueprint.Tab2";
+
+    public render() {
+        const { className, children } = this.props;
+        return (
+            <div className={classNames(Classes.TAB_PANEL, className)} role="tablist">
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tab.tsx]: this `render` function isn't actually used in the component but i had to do something. see `Tabs#renderTabPanel`.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 20]
```diff
@@ -0,0 +1,285 @@
...
+//         <h1>first panel</h1>
+//     </Tab>
+//     <Tab id="b" title="Beta">
+//         <h1>second panel</h1>
+//     </Tab>
+//     <input type="text" placeholder="Search..." />
+// </Tabs>
+
+// TODO
+// vertical key bindings? up/dn
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: wow you really tore this apart didn't you.

this was my feature list during development to make sure i hit everything the old `Tabs` did. if you read commit-by-commit you can watch it change 😄 . this final remaining issue is a "new" feature that i wanted some input on. after discussing with antoine, i'm gonna do it.

File: packages/core/src/components/tabs2/tabs.tsx [hunk 21]
```diff
@@ -0,0 +1,285 @@
...
+ * Copyright 2015 Palantir Technologies, Inc. All rights reserved.
+ * Licensed under the BSD-3 License as modified (the “License”); you may obtain a copy
+ * of the license at https://github.com/palantir/blueprint/blob/master/LICENSE
+ * and https://github.com/palantir/blueprint/blob/master/PATENTS
+ */
+
+import * as classNames from "classnames";
+import * as PureRender from "pure-render-decorator";
+import * as React from "react";
+// import { findDOMNode } from "react-dom";
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: already have :)

File: packages/core/src/components/tabs2/tabs.tsx (hunk 6 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: i guess it depends if you expect it to be useful outside the component. for instance, see `static Tab` [below](https://github.com/palantir/blueprint/pull/722/files#diff-ce03cc94ae3b7ac25aa6ea2639bf0448R93) which is only useful outside the component.

this CSS selector should not be necessary outside as querying the DOM is rarely necessary in React.

File: packages/core/src/components/tabs2/tabs.tsx (hunk 7 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: in this component, `selectedTabId` === `value` for other form components. i think the `X`, `defaultX` pattern is well understood?

File: packages/core/src/components/tabs2/tabs.tsx (hunk 6 above)
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: I prefer simple `const` for private things like this.

It gets a little more interesting when exporting static values or methods. Using `static` leads to shorter import statements on the consumer side, but longer references when you use the value. Not sure there's a general solution since it depends on how many such modules you're exporting from a module or attaching to a class.

File: packages/core/src/components/tabs2/tabs.tsx (hunk 8 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: i did the `getInitialSelectedId`, but don't see a need for `getTabChild` as it's used exactly once and the array format is used several times.

File: packages/core/src/components/tabs2/tabs.tsx (hunk 2 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: it won't be noticeable cuz this guy doesn't re-render much, but it's always an important consideration for React components (and the subject of several tslint-react rules).

File: packages/core/src/components/tabs2/tabs.tsx (hunk 9 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: sure thing. it seems we're using `li`s for the tabs but wrapping them in a `div` (not a `ul`) so might as well make them all `div`s too.

File: packages/core/src/components/tabs2/tabs.tsx (hunk 10 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: yes, via CSS only. try deleting the tab indicator element from the DOM!

File: packages/core/src/components/tabs2/tabs.tsx (hunk 11 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: i don't see this as an issue

i prefer deconstructed imports basically always unless you're going to use a big chunk of the imported library. in this case (and in many other cases throughout the codebase), i'm only using one util function so the deconstruction is ideal.

File: packages/core/src/components/tabs2/tabs.tsx (hunk 12 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: considering refactor this to `Hotkeys` when i add up/down

File: packages/core/test/tabs/tabs2Tests.tsx (hunk 14 above)
Comment (giladgray) [inline packages/core/test/tabs/tabs2Tests.tsx]: try it bro! delete the tab indicator from the DOM. it works via CSS only.

File: packages/core/src/components/tabs2/_tabs2.scss (hunk 17 above)
Comment (cmslewis) [inline packages/core/src/components/tabs2/_tabs2.scss]: 👍

File: packages/core/src/components/tabs2/tabs.tsx (hunk 7 above)
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: Sure, fair.

File: packages/core/src/components/tabs2/_tabs2.scss [hunk 22]
```diff
@@ -0,0 +1,64 @@
+// Copyright 2017 Palantir Technologies, Inc. All rights reserved.
+// Licensed under the BSD-3 License as modified (the “License”); you may obtain a copy
+// of the license at https://github.com/palantir/blueprint/blob/master/LICENSE
+// and https://github.com/palantir/blueprint/blob/master/PATENTS
+
+/*
+JavaScript API
+
+<div class="pt-callout pt-intent-danger pt-icon-error">
+  <h5>Original `Tabs` API is deprecated since v1.10.0</h5>
```
Comment (llorca) [inline packages/core/src/components/tabs2/_tabs2.scss]: Gotta change that 1.11.0 amirite

File: packages/core/src/components/tabs2/tabs.tsx (hunk 8 above)
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs.tsx]: Sounds good.

File: packages/core/test/tabs/tabs2Tests.tsx (hunk 14 above)
Comment (cmslewis) [inline packages/core/test/tabs/tabs2Tests.tsx]: 👍

**Comment by cmslewis** [comment]
@giladgray let me know when you want me to do another CR pass here.

File: packages/core/src/components/tabs2/_tabs2.scss (hunk 17 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/_tabs2.scss]: fixed, but this comment won't go away :)

File: packages/core/src/components/tabs2/tabs.tsx (hunk 7 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: i tried to clear up the language by adding not about "uncontrolled usage" here. helpful?

**Comment by themadcreator** [comment]
I think I like @cmslewis's suggestion of `content` instead of `panel`. But, what if I define `title` and `content` as well as children in the JSX? Are the `<Tab>`s children its content or its label?

Also to @ericanderson's comment, how would you create a set of tabs that drive a container not directly below/next to the tabs? Like what if i want the nice tab list to set the content of a panel on another side of the page or something? That's probably be a job for the `onChange` prop, but then maybe that callback should get the full `ITabProps` to have access to the content.

**Comment by giladgray** [comment]
I prefer `panel` as it generates a `role="tabpanel"` (ARIA). It's also a term folks are used to from the previous Tabs API: `TabList`, `TabPanel`, etc.

Creating a set of tabs to drive a separate container is as easy as omitting the `panel` prop on all `Tab`s and using controlled mode to store and act upon the selected tab ID.

**Comment by giladgray** [comment]
ok @cmslewis and @ericanderson, I have addressed all of your comments. please re-review at your earliest convenience.

File: packages/core/examples/tabs2Example.tsx [hunk 23]
```diff
@@ -0,0 +1,134 @@
...
+                            selectedTabId={this.state.navbarTabId}
+                        >
+                            <Tab2 id="Home" title="Home" />
+                            <Tab2 id="Files" title="Files" />
+                            <Tab2 id="Builds" title="Builds" />
+                        </Tabs2>
+                    </div>
+                </div>
+                <h1 style={{ marginTop: 30, marginBottom: 30 }}>{this.state.navbarTabId}</h1>
+                {/* uncontrolled mode & each Tab has a panel: */}
```
Comment (cmslewis) [inline packages/core/examples/tabs2Example.tsx]: Huh, TIL how to put comments in JSX.

File: packages/core/src/components/tabs2/tabTitle.tsx [hunk 24]
```diff
@@ -0,0 +1,61 @@
...
+    /** Whether the tab is currently selected. */
+    selected: boolean;
+}
+
+@PureRender
+export class TabTitle extends React.Component<ITabTitleProps, {}> {
+    public static displayName = "Blueprint.TabTitle";
+
+    public render() {
+        const { disabled, id, parentId, selected} = this.props;
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabTitle.tsx]: nit: `selected}` => `selected }`

**Comment by adidahiya** [comment]
checking this out now

**Comment by adidahiya** [comment]
weird that the example code doesn't match the actual example

image

File: packages/core/src/components/tabs2/tabs.tsx [hunk 25]
```diff
@@ -0,0 +1,293 @@
...
+@PureRender
+export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
+    /** Insert a `Tabs2.Expander` between any two children to right-align all subsequent children. */
+    public static Expander = Expander;
+
+    public static Tab = Tab2;
+
+    public static defaultProps: ITabs2Props = {
+        animate: true,
+        id: "",
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: I realized recently that we can start using partial types for default props and retain type safety for consumers. Sometimes we only want to supply defaults for a few props but not make those fields we omit optional in the props interface. I believe this should work for us:

```ts
public static defaultProps: Partial<ITabs2Props> = {
    animate: true,
    renderActiveTabPanelOnly: false,
    vertical: false,
};
```

File: packages/core/src/components/tabs2/tabs.tsx [hunk 26]
```diff
@@ -0,0 +1,293 @@
...
+        renderActiveTabPanelOnly: false,
+        vertical: false,
+    };
+
+    public displayName = "Blueprint.Tabs2";
+
+    private tablistElement: HTMLDivElement;
+
+    constructor(props?: ITabs2Props, context?: any) {
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: context should be omitted if there are no contextTypes. I was wrong about this in the past, which is why the codebase has these args in other places. https://github.com/palantir/tslint-react/issues/54

File: packages/core/src/components/tabs2/tabs.tsx [hunk 27]
```diff
@@ -0,0 +1,293 @@
...
+
+    public render() {
+        const { indicatorWrapperStyle, selectedTabId } = this.state;
+
+        const tabTitles = React.Children.map(this.props.children, (child) => {
+            return isTab(child) ? this.renderTabTitle(child) : child;
+        });
+
+        const tabPanels = this.getTabChildren()
+            .filter(this.props.renderActiveTabPanelOnly ? (tab) => tab.props.id === selectedTabId : () => true)
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: minor: destructure from props at the top of this function

```ts
const { children, className, renderActiveTabPanelOnly, vertical } = this.props;
```

File: packages/core/src/components/tabs2/tabs.tsx [hunk 28]
```diff
@@ -0,0 +1,293 @@
...
+            .map(this.renderTabPanel);
+
+        const tabIndicator = (
+            <div className="pt-tab-indicator-wrapper" style={indicatorWrapperStyle}>
+                <div className="pt-tab-indicator" />
+            </div>
+        );
+
+        const classes = classNames(Classes.TABS, { "pt-vertical": this.props.vertical }, this.props.className);
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: nit: `Classes.VERTICAL`?

File: packages/core/src/components/tabs2/tabs.tsx [hunk 29]
```diff
@@ -0,0 +1,293 @@
...
+        const tabTitles = React.Children.map(this.props.children, (child) => {
+            return isTab(child) ? this.renderTabTitle(child) : child;
+        });
+
+        const tabPanels = this.getTabChildren()
+            .filter(this.props.renderActiveTabPanelOnly ? (tab) => tab.props.id === selectedTabId : () => true)
+            .map(this.renderTabPanel);
+
+        const tabIndicator = (
+            <div className="pt-tab-indicator-wrapper" style={indicatorWrapperStyle}>
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: do we have this in `Classes`?

File: packages/core/src/components/tabs2/tabs.tsx [hunk 30]
```diff
@@ -0,0 +1,293 @@
...
+    }
+
+    public componentWillReceiveProps({ selectedTabId }: ITabs2Props) {
+        if (selectedTabId !== undefined) {
+            // keep state in sync with controlled prop, so state is canonical source of truth
+            this.setState({ selectedTabId });
+        }
+    }
+
+    public componentDidUpdate(_: ITabs2Props, prevState: ITabs2State) {
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: nit: stylistically I still prefer naming this first arg `_prevProps`

File: packages/core/src/components/tabs2/tabs.tsx [hunk 31]
```diff
@@ -0,0 +1,293 @@
...
+        const { selectedTabId } = this.state;
+        if (newTabId !== selectedTabId) {
+            safeInvoke(this.props.onChange, newTabId, selectedTabId);
+            if (this.props.selectedTabId === undefined) {
+                this.setState({ selectedTabId: newTabId });
+            }
+        }
+    }
+
+    private handleTabRef = (tabElement: HTMLDivElement) => { this.tablistElement = tabElement; };
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: minor: prefer placing this next to the ref

```ts
private tablistElement: ...;
private refHandlers = {
    tablist: (element: HTMLDivElement) => this.tablistElement = element,
};
```

File: packages/core/src/components/tabs2/tabs.tsx [hunk 32]
```diff
@@ -0,0 +1,293 @@
...
+            indicatorWrapperStyle = {
+                height: clientHeight,
+                transform: `translateX(${Math.floor(offsetLeft)}px) translateY(${Math.floor(offsetTop)}px)`,
+                width: clientWidth,
+            };
+        }
+        this.setState({ indicatorWrapperStyle });
+    }
+
+    private renderTabPanel = (tab: TabElement) => {
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: this can be `static`

File: packages/core/src/components/tabs2/tabs.tsx [hunk 33]
```diff
@@ -0,0 +1,293 @@
...
+                id={generateTabPanelId(this.props.id, id)}
+                key={id}
+                role="tabpanel"
+            >
+                {panel}
+            </div>
+        );
+    }
+
+    private renderTabTitle = (tab: TabElement) => {
```
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: this can be `static` or a standalone fn

File: packages/core/src/components/tabs2/tabs.tsx (hunk 29 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: nope

File: packages/core/src/components/tabs2/tabs.tsx (hunk 30 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: oh yes me too

File: packages/core/src/components/tabs2/tabs.tsx (hunk 33 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: not so! `this` is used on almost every line.

File: packages/core/src/components/tabs2/tabs.tsx (hunk 32 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs.tsx]: it uses `this` multiple times

File: packages/core/src/components/tabs2/tabs.tsx (hunk 33 above)
Comment (adidahiya) [inline packages/core/src/components/tabs2/tabs.tsx]: oops my bad... I guess I'm so used to seeing `this.props` destructured in the other codebases I work in. carry on

File: packages/docs/src/styles/_examples.scss [hunk 34]
```diff
@@ -193,8 +193,12 @@ $options-margin: $pt-grid-size * 3;
 }
 
 .docs-tabs2-example {
-  .pt-navbar .pt-tab {
-    line-height: $pt-grid-size * 5;
+  .pt-navbar {
+    position: static;
+
+    .pt-tab {
+      line-height: $pt-grid-size * 5;
```
Comment (giladgray) [inline packages/docs/src/styles/_examples.scss]: `$pt-navbar-height`

File: packages/docs/src/styles/_examples.scss [hunk 35]
```diff
@@ -193,8 +193,12 @@ $options-margin: $pt-grid-size * 3;
 }
 
 .docs-tabs2-example {
-  .pt-navbar .pt-tab {
-    line-height: $pt-grid-size * 5;
+  .pt-navbar {
+    position: static;
```
Comment (giladgray) [inline packages/docs/src/styles/_examples.scss]: move this more generally in docs examples styles to hit http://blueprintjs.com/docs/#components.navbar too

**Comment by brsanthu** [comment]
Not sure if this is the right place to ask this. Any thoughts on why we cannot specify the tab panel content like this?

`<Tab2 id='rx' title='React'>Hello World</Tab2>`
