### PR TITLE
[datetime2] feat: DatePicker3 using react-day-picker v8

### LINKED ISSUE #5652: Localising @blueprintjs/datetime2 components in React 18
#### Environment

- __Package version(s)__: 4.10.2"
- __Browser and OS versions__: Brave 1.144.50, macOS 12.6.0

#### Question

I'm trying to localise my `DateRangeInput2` control to the german language. Based on the [linked documentation](https://blueprintjs.com/docs/#datetime/datepicker.localization) to the old `datetime` package one needs to import `LocalUtils` from `react-day-picker` and apply it to the `localUtils` property together with a language code in `locale` to the component:

```tsx
import {LocalUtils} from "react-day-picker";

// [...]

<DateRangeInput2
                localeUtils={LocalUtils}
                locale="de"
                onChange={([start, end]) => {}}
                formatDate={formatDate}
                parseDate={parseDate} />

// [...]
```

Since I'm in a typescript project, just applying that gives me:

```
Compiled with problems:X

ERROR in ./src/main.tsx 13:0-46

Module not found: Error: Can't resolve 'react-day-picker' in '.../src'


ERROR in src/main.tsx:22:26

TS2307: Cannot find module 'react-day-picker' or its corresponding type declarations.
  > 22 | import {LocalUtils} from "react-day-picker";
```

Suppressing it with `// @ts-ignore` gives me:

```
Compiled with problems:X

ERROR in ./src/main.tsx 14:0-46

Module not found: Error: Can't resolve 'react-day-picker' in '.../src'
```

After installing it `react-day-picker`, it claims there's no class called `LocalUtils`:

```
Compiled with problems:X

ERROR in ./src/CourseSelection.tsx 519:21-31

export 'LocalUtils' (imported as 'LocalUtils') was not found in 'react-day-picker'
```

So I checked with the `@blueprintjs/datetime2`s `package.json` and tried to install the required version of `react-day-picker`: `7.4.9`.

Upon installation npm returned me the dependency resolving error:

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"~0.13.x || ~0.14.x || ^15.0.0 || ^16.0.0 || ^17.0.0" from react-day-picker@7.4.9
npm ERR! node_modules/react-day-picker
npm ERR!   react-day-picker@"7.4.9" from the root project
```

For info, I'm using `react@^18.2.0`, therefore it's not compatible with older versions of `react-day-picker`.

I could not find till which version `LocalUtils` was available in `react-day-picker`.

I know it's more off a typescript question than BlueprintJS specific, but could anyone get localisation for `datetime2` working in React 18? Thanks!

### LINKED ISSUE #5699: Issue updating to React 18 caused by @blueprintjs/datetime dependency
#### Environment

- __Package version(s)__: 
    "@blueprintjs/core": "4.11.5",
    "@blueprintjs/datetime": "4.4.5"
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.8.1-rc",
     "@types/react": "18.0.23",
    "@types/react-dom": "18.0.7",
    
- __Operating System__: MacOS M1
- __Browser name and version__: Chrome Version 106.0.5249.119 

#### Actual behavior
After updating a some what large project from React 16 to React 18 my project fails to build.
The error is in a node module inside of Blueprintjs/datetime
The Error I am seeing...
```
node_modules/@blueprintjs/datetime/node_modules/react-day-picker/types/Props.d.ts(47,13): error TS2694: Namespace 'React' has no exported member 'SFC'.
node_modules/@blueprintjs/datetime/node_modules/react-day-picker/types/Props.d.ts(72,13): error TS2694: Namespace 'React' has no exported member 'SFC'.
node_modules/@blueprintjs/datetime/node_modules/react-day-picker/types/Props.d.ts(145,13): error TS2694: Namespace 'React' has no exported member 'SFC'.
```

### PR DESCRIPTION
**Pull request by adidahiya**
### Checklist

- [x] Includes tests
- [x] Update documentation

### Screenshot

image

### Changes proposed in this pull request:

Add react-day-picker (a.k.a. "RDP") v8.x as a dependency of `@blueprintjs/datetime2` and create new "v3" variant of DatePicker which uses this new version of the day picker library.

<details>
<summary>Details on upgrade complications</summary>

When I first looked at the [v8 upgrade guide](https://react-day-picker.js.org/guides/upgrading), I thought we might be able to mitigate the breaking changes and handle them all within Blueprint code. It would be nice if we could support _both_ v7 and v8 at the same time. Reviewing the breaking changes suggests that this might be possible, as they fall into a few manageable categories:

* :ballot_box_with_check: breaking changes that require no mitigation, or a simple rename within Blueprint code
  * `todayButton` removed
  * `canChangeMonth` → `disableNavigation`
  * `selectedDays` → `selected`
  * DayPickerInput removed
* ✅ breaking name changes that can (in theory) be mitigated / managed by Blueprint and not exposed to consumers (although this would generate code cruft)
    * `initialMonth` → `defaultMonth`
    * `disabledDays` → `disabled`
    * `showWeekNumbers` → `showWeekNumber`
    * `daysOfWeek` → `dayOfWeek`
    * `firstDayOfWeek` → `weekStartsOn`
* ❓not sure about these changes
    * v8 use the locale setting to calculate the week days and numbers. The previous versions were using [ISO week dates](https://en.wikipedia.org/wiki/ISO_week_date). To toggle the ISO week dates, use the `ISOWeek` prop.

However, after attempting the upgrade and compiling with the new `react-day-picker` types, it became clear that it was going to be difficult to implement `DatePicker` and `DateRangePicker` in a way that worked with both v7 and v8. Some of those changes include:

- how caption and navbar elements are rendered
- how modifier styles (both built-in and custom) are applied

So, instead of making the `@blueprintjs/datetime` components compatible with react-day-picker v8, I've decided to create "v2" variants in `@blueprintjs/datetime2`.

</details>

### Questions for reviewers

Edit: we decided to go with Option 1, using the "v3" name.

It's unclear what to name this new variant of DatePicker. If we call it DatePicker2, there's a bit of a naming collision since there are already some "v2" components in `@blueprintjs/datetime2` which are aliases for the newly-promoted `@blueprintjs/datetime` v5 components. Here's a list of component names in the current state of the API & the future desired "end" state of the public datetime components API:

| Current state | End state |
| - | - |
| @blueprintjs/datetime2 v1.x (all components using rdp v7) | @blueprintjs/datetime2 v2.x (all components using rdp v8) |
| - | DatePicker2 |
| DateInput2 (alias for DateInput) | DateInput2 |
| - | DateRangePicker2 |
| DateRangeInput2 (alias for DateRangeInput) | DateRangeInput2 |

There are a few potential paths to get our API to the desired end state. IMO option 2 feels a little more clean but I'm open to feedback here:

### Option 1

<details>
<summary>Introduce "v3" components in the current major version</summary>

@blueprintjs/datetime2 v1.x
- using rdp v8
  - DatePicker3
  - DateInput3
  - DateRangePicker3
  - DateRangeInput3
- using rdp v7
  - DateInput2 (alias for `{ DateInput } from "@blueprintjs/datetime"`)
  - DateRangeInput2 (alias for `{ DateRangeInput } from "@blueprintjs/datetime"`)

We'd then likely have to keep around the "v3" names in datetime2 v2.x (just like we did for ["v2" names in v1.0](https://github.com/palantir/blueprint/blob/6707f73ce395b0f88113424104e9bfb5fe9c68fb/packages/datetime2/src/index.ts#L25)):

@blueprintjs/datetime2 v2.x (all using rdp v8)
- DatePicker3 (alias for DatePicker2)
- DatePicker2
- DateInput3 (alias for DateInput2)
- DateInput2
- DateRangePicker3 (alias for DateRangePicker2)
- DateRangePicker2
- DateRangeInput3 (alias for DateRangeInput2)
- DateRangeInput2

Users would be able to migrate to the "v3" components in datetime2 v1.x to deal with breaking changes before bumping to v2.0.

</details>

### Option 2

<details>
<summary>Update "v2" components to optionally use the rdp v8 implementation</summary>

Instead of simply aliasing `{ DateInput } from "@blueprintjs/datetime"`, `DateInput2` could be implemented as a component which has the option to use react-day-picker v8.x under the hood:

```tsx
import { DateInput as DateInputRDP7, DateInputProps as DateInputRDP7Props } from "@blueprintjs/datetime";

import { DateInputRDP8, DateInputRDP8Props } from "./dateInputRDP8"

export type DateInput2Props = DateInputRDP7Props | DateInputRDP8Props;

function isDateInputRDP8Props(props: DateInput2Props): props is DateInputRDP8Props {
    return (props as DateInputRDP8Props).useReactDayPicker8 === true;
}

export function DateInput2(props: DateInput2Props) {
    if (isDateInputRDP8Props(props)) {
        // next-generation DateInput2 using react-day-picker v8
        return <DateInputRDP8 {...props} />;
    } else {
        // alias for { DateInput } from "@blueprintjs/datetime"
        return <DateInputRDP7 {...props} />;
    }
}
```

where the new component has this flag:

```tsx
export interface DateInputRDP8Props {
    useReactDayPicker8: true;
    // .. other props
}
```

This would mean that users could update their code for React 18 compatibility with the following changes:

```diff
- import { DateInput, DatePicker } from "@blueprintjs/datetime";
+ import { DateInput2, DatePicker2 } from "@blueprintjs/datetime2";

- <DateInput />
+ <DateInput2 useReactDayPicker8={true} />

- <DatePicker />
+ <DatePicker2 /> // no prop flag required
```

or, if their code still has "v2" references after the Popover2 migration:

```diff
- import { DatePicker } from "@blueprintjs/datetime";
- import { DateInput2 } from "@blueprintjs/datetime2";
+ import { DateInput2, DatePicker2 } from "@blueprintjs/datetime2";

- <DateInput2 />
+ <DateInput2 useReactDayPicker8={true} />

- <DatePicker />
+ <DatePicker2 />
```

</details>

### Reviewers should focus on:

- No regressions compared to DatePicker
- Sufficient testing of localization APIs
- Naming conventions
- Updated documentation for DatePicker2

---

<details>
<summary>Expand to see outdated notes when this work was being done on the v4.x branch</summary>

... naming semantics get a little weird, since we still want to leave `DateInput2` and `DateRangeInput2` easy to upgrade as only popover-related API changes rather than adding on another layer of breaking changes... bear with me (rdp = react-day-picker):

- In Blueprint v4.x:
    - DatePicker uses rdp v7
	- DateRangePicker uses rdp v7
	- DatePicker2 uses rdp v8
	- DateRangePicker2 uses rdp v8
	- DateInput2 uses rdp v7 (via DatePicker); popper.js v2
	- DateRangeInput2 uses rdp v7 (via DateRangePicker); popper.js v2
- In Blueprint v5.x:
    - DatePicker uses rdp v7
    - DateRangePicker uses rdp v7
    - DatePicker2 uses rdp v8
    - DateRangePicker2 uses rdp v8
    - DateInput2 uses rdp v8 (via DatePicker2); popper.js v2
    - DateRangeInput2 uses rdp v8 (via DatePicker2); popper.js v2

</details>

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>ADd colors variables import</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/ed8b3c53-73b5-413a-a691-f8f94f0e28c0/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/ed8b3c53-73b5-413a-a691-f8f94f0e28c0/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/ed8b3c53-73b5-413a-a691-f8f94f0e28c0/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/ed8b3c53-73b5-413a-a691-f8f94f0e28c0/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/datetime2/src/classes.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ */
+
+import { Classes as DatetimeClasses } from "@blueprintjs/datetime";
+
+const RDP_DAY = "rdp-day";
+const DATEPICKER_NAV_BUTTON = `${DatetimeClasses.DATEPICKER}-nav-button`;
+
+export const Classes = {
+    ...DatetimeClasses,
+    DATEPICKER_DAY: RDP_DAY,
```
Comment (adidahiya) [inline packages/datetime2/src/classes.ts]: we probably need to rename these to use "DATEPICKER2" since users might be referencing these class names expecting them to work with DatePicker "v1"

File: packages/datetime2/src/components/date-picker2/_date-picker2.scss [hunk 2]
```diff
@@ -0,0 +1,234 @@
+// Copyright 2023 Palantir Technologies, Inc. All rights reserved.
+// Licensed under the Apache License, Version 2.0.
+
+@import "@blueprintjs/colors/lib/scss/colors";
+@import "@blueprintjs/core/src/components/popover/common";
+@import "@blueprintjs/datetime/src/common";
+
+$cell-size: $pt-grid-size * 3 !default;
```
Comment (adidahiya) [inline packages/datetime2/src/components/date-picker2/_date-picker2.scss]: this variable is unused. the dimension is now specified in react-day-picker-overrides as a CSS custom property

File: packages/datetime2/src/components/date-picker2/_date-picker2.scss [hunk 3]
```diff
@@ -0,0 +1,234 @@
...
+$header-height: $pt-grid-size * 4 !default;
+$header-margin: ($header-height - $pt-input-height) * 0.5 !default;
```
Comment (adidahiya) [inline packages/datetime2/src/components/date-picker2/_date-picker2.scss]: these are unused. seem to be unused in DatePicker v1 as well...

File: packages/datetime2/src/components/date-picker2/datePicker2Props.ts [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+    DatePickerProps,
+    "dayPickerProps" | "defaultValue" | "locale" | "localeUtils" | "modifiers" | "onChange" | "value"
+>;
+
+export interface DatePicker2Props extends DatePickerSharedProps, Props {
+    /**
+     * Props to pass to react-day-picker's single day picker. See API documentation
+     * [here](https://react-day-picker.js.org/api/interfaces/DayPickerSingleProps).
+     *
+     * TODO(@adidahiya): improve this documentation for overriding dayPickerProps
```
Comment (adidahiya) [inline packages/datetime2/src/components/date-picker2/datePicker2Props.ts]: don't leave TODO in code

File: packages/datetime2/test/common/dayPickerTestUtils.ts [hunk 5]
```diff
@@ -0,0 +1,32 @@
+/*
+ * Copyright 2016 Palantir Technologies, Inc. All rights reserved.
```
Comment (adidahiya) [inline packages/datetime2/test/common/dayPickerTestUtils.ts]:
```suggestion
 * Copyright 2023 Palantir Technologies, Inc. All rights reserved.
```

File: packages/docs-app/src/examples/datetime2-examples/datePicker2LocalizedExample.tsx [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+import * as React from "react";
+
+import { Example, ExampleProps } from "@blueprintjs/docs-theme";
+import { DatePicker2 } from "@blueprintjs/datetime2";
+
+export class DatePicker2LocalizedExample extends React.PureComponent<ExampleProps> {
+    public render() {
+        return (
+            <Example options={false} {...this.props}>
+                <DatePicker2 localeCode="fr" />
```
Comment (adidahiya) [inline packages/docs-app/src/examples/datetime2-examples/datePicker2LocalizedExample.tsx]: consider adding a locale switcher dropdown for some commonly used locales

**Review by adidahiya — COMMENTED** [review]
I still need to figure out how to override these day of the week abbreviations to not be uppercase. it might be tough with localization support:

image

@CPerinet do you think it's ok to leave them as uppercase (this is a change from the existing DayPicker component)?

**Comment by adidahiya** [comment]
<h3>fix formatting and lint</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/6ba84732-2b95-42ef-8d6d-3d2985b35a74/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/6ba84732-2b95-42ef-8d6d-3d2985b35a74/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/6ba84732-2b95-42ef-8d6d-3d2985b35a74/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/6ba84732-2b95-42ef-8d6d-3d2985b35a74/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
> I still need to figure out how to override these day of the week abbreviations to not be uppercase. it might be tough with localization support:

I figured it out using react-day-picker [formatters](https://react-day-picker.js.org/api/types/Formatters) 👍🏽

**Comment by adidahiya** [comment]
<h3>fix lint, add comment</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/6df1c203-f694-4eb3-956a-9539ebd9b08c/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/6df1c203-f694-4eb3-956a-9539ebd9b08c/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/6df1c203-f694-4eb3-956a-9539ebd9b08c/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/6df1c203-f694-4eb3-956a-9539ebd9b08c/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>fix datetime tests</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/8f3772b6-7a68-420c-95ef-c8566397f915/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/8f3772b6-7a68-420c-95ef-c8566397f915/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/8f3772b6-7a68-420c-95ef-c8566397f915/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/8f3772b6-7a68-420c-95ef-c8566397f915/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by PetrusAsikainen** [comment]
> `DateInput2` could be implemented as a component which has the option to use react-day-picker v8.x under the hood

My two cents: I see `DatePicker3` as a cleaner implementation. Such numbering is currently being used in BlueprintJS, users will be already used to it.

Introducing a `useReactDayPicker8` prop is more verbose, makes the component tree deeper and typings more complex, and I don't think something like that is used in the API now.

And just like the `DatePicker3` alias, the transitional prop would have to be kept in the typings in datetime 2.x to make TypeScript happy - and trying to remove it, deprecate it, or require it to be set to `true` in the future would probably get ugly.

---

By the way: what's the intended way for a user to install `datetime2` with rdp v7? At least with the current `peerDependencies` that wouldn't seem to go through without overriding something.

**Comment by adidahiya** [comment]
> By the way: what's the intended way for a user to install `datetime2` with rdp v7? At least with the current `peerDependencies` that wouldn't seem to go through without overriding something.

@PetrusAsikainen @blueprintjs/datetime2/package.json allows rdp v7 _or_ v8 as a peer dependency on this PR branch, so you will be able to install v7 once this change merges: https://github.com/palantir/blueprint/blob/4eaa19045a3046d019ea243c30b58977242dd6b9/packages/datetime2/package.json#L44

---

re feedback on Option 1 vs 2: heard. I don't have strong conviction on either approach at the moment, so I'm cool with going with Option 1 and using the "DatePicker3" name. You're right that it adheres better to existing naming conventions in Blueprint (and @ericjeney seems to agree). Thanks for the feedback 👍🏽

**Comment by PetrusAsikainen** [comment]
> @PetrusAsikainen @blueprintjs/datetime2/package.json allows rdp v7 _or_ v8 as a peer dependency on this PR branch, so you will be able to install v7 once this change merges:

Ah, seems I was reading the diff on a very wide screen and missed the collapsed `}, "devDependencies": {` :D

image

**Comment by PetrusAsikainen** [comment]
With this setup, users will be only able to install and use one version of `react-day-picker` at a time with a `datetime2` dependency. Consequences:

- Blueprint 5 users wanting to upgrade their date pickers to rdp v8, gradually or at once, will need to install `datetime2` with rdp v8, and `datetime` with rdp v7.
    - Gradual upgraders will also need to "promote" all `datetime2` imports to `datetime`, since they'll lose the `datetime2` with rdp v7.
- Blueprint 4 `datetime2` users can only upgrade everything at once to rdp v8, since they'll lose the `datetime2` with rdp v7.
- Blueprint 5 `datetime2` users wanting to stay at v7 must either "promote" to `datetime`, or make sure rdp stays at v7.
- Blueprint 4 `datetime2` users wanting to stay at v7 must make sure rdp stays at v7.

Furthermore, a npm update might bump rdp to v8 automatically, so even the dependencies change might be breaking for existing `datetime2` 1.x consumers.

I'm not sure what your backwards compatibility requirements are, but this might be best implemented in a new major version of `datetime2` that only supports rdp v8. That would make it very clear what version of `datetime2` maps to which react-day-picker.

A new major version would also make it clearer what gradual upgraders need to do ("promote" all existing usages to keep them at v7). For Blueprint 4 users, I don't think a gradual upgrade is reasonable unless you want to introduce something like `datetime3` just for them.

---

If you decide to go with supporting both v7 and v8 in 1.x, it would make sense to include some kind of guard that verifies the dependency is at the correct version. This might either rely on a `DateInput2`/`DateInput3` or `useReactDayPicker8` type manual flag, or check the props for the breaking changes and allow either version if no breaking changes are hit.

**Comment by adidahiya** [comment]
<h3>Use v3 name</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/4eba793d-c07c-467d-bc3f-180bf5b7da03/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/4eba793d-c07c-467d-bc3f-180bf5b7da03/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/4eba793d-c07c-467d-bc3f-180bf5b7da03/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/4eba793d-c07c-467d-bc3f-180bf5b7da03/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>revert to 'locale' prop name</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/7a9dea91-7fe1-4150-b777-56a5aaa5398d/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/7a9dea91-7fe1-4150-b777-56a5aaa5398d/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/7a9dea91-7fe1-4150-b777-56a5aaa5398d/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/7a9dea91-7fe1-4150-b777-56a5aaa5398d/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
### Blueprint v4 upgrade path

Blueprint 4 users need to upgrade to Blueprint 5 first to get any of this new react-day-picker v8 compatibility. That's already enforced with datetime2's dependency on core. I'm not going to explicitly describe an upgrade path from datetime2 v0.x `DatePicker` -> datetime2 v1.1 `DatePicker3`. They should migrate to datetime2 v1.x first without using rdp v8 via [this migration guide](https://github.com/palantir/blueprint/wiki/datetime2-component-migration).

### react-day-picker version

re: problem of only having one version of react-day-picker via a transitive dependency on @blueprintjs/datetime2. This would be a problem if users were forced to only install one version. But I don't think this is the case. datetime2 currently depends on datetime which pulls in react-day-picker v7, and that's not changing in this PR. This means an import like this will work:

```ts
import { DateInput2, DateInput3 } from "@blueprintjs/datetime2";
```

where:
- `DateInput2` references `{ DateInput } from "@blueprintjs/datetime"` > `{ DayPickerProps } from "react-day-picker"` (rdp v7)
- `DateInput3` references `{ DayPickerSingleProps } from "react-day-picker"` (rdp v8)

We ~could even~ should actually update datetime2/package.json to _require_ rdp v8. That way users wouldn't need to add an explicit `react-day-picker` dependency to get the new functionality, they would just get both versions installed automatically (this may look surprising in dependency lockfiles but the new version would only be pulled in and affect bundle size after migrating to the "v3" components).

**Comment by adidahiya** [comment]
<h3>minor docs fixes</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/ae585ab4-158c-459b-bb78-14fcfb2b21ef/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/ae585ab4-158c-459b-bb78-14fcfb2b21ef/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/ae585ab4-158c-459b-bb78-14fcfb2b21ef/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/ae585ab4-158c-459b-bb78-14fcfb2b21ef/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
I'm going to go ahead with this approach. I will try to cut a pre-release version of datetime2 which I can use to demonstrate multiple copies of react-day-picker working together in a code sandbox.

**Comment by adidahiya** [comment]
btw I updated the documentation to mention multiple rdp copies:

image
