### PR TITLE
fix a bunch of little bugs

### LINKED ISSUE #1861: [InputGroup] Add default paddingRight to input without rightElement
Hello team!
Just noticed a small issue with text input groups. As I understand, CSS component `TextInput` should display same as default `InputGroup` JS component.
However, `TextInput` has `padding-right: 12px`, but `InputGroup` (withou rightElement) has `padding-right: 0` (inline style rule). 

CSS:
screenshot at dec 04 17-48-07

JS:
screenshot at dec 04 17-49-03

I guess `InputGroup` also should have padding-right.
The problem reason is [here](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/inputGroup.tsx#L117)

### LINKED ISSUE #2347: Inconsistency in validateProps documentation
[`AbstractComponent`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/abstractComponent.ts#L68) and [`AbstractPureComponent`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/abstractPureComponent.ts#L68) both contain a comment regarding `validateProps` that is no longer true: "In contrast to propTypes, these runtime checks are _always_ run, not just in development mode."

As of #977, `validateProps` is only run in development. Was this an intentional change?

### LINKED ISSUE #2365: Large Tag Input "X" Buttons incorrect Size
In 2.0.0, the Tag Input's tags have too-small "X" buttons when in "large" mode.

To reproduce:

1. Go to: http://blueprintjs.com/docs/v2/#core/components/tag-input
2. Activate the "Large" toggle
3. The tags get bigger, but the "x" buttons say the same size.

### LINKED ISSUE #2370: Checkbox component does not work in controlled mode
### Bug report

blueprintjs/core: 2.1.1,
Browser: Google Chrome | 65.0.3325.181 (Official Build) (64-bit)
OS: macOS Sierra 10.12.6 (16G1314)

#### Steps to reproduce

1. Use `Checkbox` component
2. Add `checked` and `onChange` property
3. Click on component

#### Actual behavior

Checkbox change indicator but `onChange` does not invoke

#### Expected behavior

Checkbox should invoke `onChange` when click on component happend

#### Example code
```
import React, {Component} from 'react';
import {Checkbox} from '@blueprintjs/core';

class Test extends Component {
    constructor(props) {
        super(props);
        this.state = {
            isChecked: false
        };
    }

    handleEnabledChange() {
        this.setState({isChecked: !this.state.isChecked});
    }

    render() {
        return (
            <Checkbox
                checked={this.state.isChecked}
                label={this.state.isChecked ? 'Checked' : 'Unchecked'}
                onChange={this.handleEnabledChange}
            />
        );
    }
}

export default Test;
```
#### Note
I am not sure but probably this [change](https://github.com/palantir/blueprint/pull/2323/commits/6c8a29f65053310ee5bc399c7459d4f4dc379c78#diff-c3a6a2b0fe2f0ed4fefa920240aeb9f4R177) is cause this issue

### PR DESCRIPTION
**Pull request by giladgray**
Fixes #2365 (large tag X)
~~Fixes #2370 (checkbox onChange)~~ already fixed
Fixes #2347 (validateProps docs)
Fixes #1861 (InputGroup right padding)

docs nav now ensures that active menu item is visible after page change.

### CODE REVIEW

File: packages/core/src/compatibility/browser.ts [hunk 1]
```diff
@@ -6,9 +6,9 @@
 
 const userAgent = typeof navigator !== "undefined" ? navigator.userAgent : "";
 const browser = {
-    isEdge: !!userAgent.match(/Edge/),
-    isInternetExplorer: !!userAgent.match(/Trident/) || !!userAgent.match(/rv:11/),
-    isWebkit: !!userAgent.match(/AppleWebKit/),
+    isEdge: /Edge/.test(userAgent),
+    isInternetExplorer: /Trident|rv:11/.test(userAgent),
+    isWebkit: /AppleWebKit/.test(userAgent),
```
Comment (themadcreator) [inline packages/core/src/compatibility/browser.ts]: 💯
