### PR TITLE
React 16 and Enzyme 3 migration

### LINKED ISSUE #144: Use React.PureComponent instead of pure-render-decorator
docs: https://facebook.github.io/react/docs/react-api.html#react.purecomponent

- it is just as usable as the decorator; you can override `shouldComponentUpdate` to opt out of pure rendering
- this reduces complexity by removing 2 dependencies (decorator + its typings)
- ~~this will require rewriting the tslint rule which enforces pure components~~ this seems to have gotten lost somewhere in the last few months...
- :fire: requires a react dependency of >= 15.3.0

### LINKED ISSUE #866: React 16 support
Preemptively creating an umbrella issue for this task, like https://github.com/ant-design/ant-design/issues/5377.

Related React issues / deprecations:

- https://github.com/facebook/react/issues/8854
- https://github.com/facebook/react/issues/9207

We should try to support both v15 and v16 in a single Blueprint version (maintaining multiple compatible releases will be cumbersome).

Sub-tasks:

- [ ] migrate to [react-transition-group](https://github.com/reactjs/react-transition-group)
- [x] remove usage of proptypes (https://github.com/palantir/blueprint/issues/991)
- [ ] use `unstable_createPortal ` instead of `unstable_renderSubtreeIntoContainer` (#1509)

### LINKED ISSUE #1051: Replace deprecated dependency react-addons-css-transition-group
### Bug report

- __Package version(s)__: 1.16.0
- __Browser and OS versions__: Chrome 57 on OSX (but it doesn't matter)

#### Steps to reproduce

1. Install Blueprint using YARN

#### Actual behavior

Requires the deprecated `react-addons-css-transition-group` package as a peer dependency.

#### Expected behavior

Allows (preferably, recommends) the [react-transition-group](https://github.com/reactjs/react-transition-group) fork, as recommended by the README for [react-addons-css-transition-group](https://www.npmjs.com/package/react-addons-css-transition-group).

### LINKED ISSUE #1680: Fix flaky tests
These tests often flaked and caused builds to fail. They're `it.skip`'d for now, but we should find a way to make them more reliable and reenable them:
- [ ] `Toaster > with autoFocus set to true > focuses on newly created toast`
- [x] `<Overlay> > Focus management > brings focus to overlay if autoFocus=true`

### LINKED ISSUE #1860: Update Portal to use React 16 Portals for simpler unit testing with Enzyme.
Enzyme has been updated to support React 16 Portals.

React 16 Portals: https://reactjs.org/docs/portals.html
Relevant Enzyme issue: https://github.com/airbnb/enzyme/issues/1150
Relevant Enzyme pull request: https://github.com/airbnb/enzyme/pull/1345

If Blueprint.Portal was updated to make use of ReactDOM.createPortal, then components involving Blueprint.Portals would be much easier to unit test via Enzyme, because Enzyme's wrapper methods (find, etc.) are now able to work across portal boundaries.

It may even simplify the implementation of Blueprint.Portal.

### PR DESCRIPTION
**Pull request by adidahiya**
Fixes #1051 
Fixes #144 
Fixes #866 (for real)
Fixes #1860 
Fixes #1680 

### Changes in this PR

- Upgrade `react` and `react-dom` to v16
  - Load `es6-shim` in all tests to ensure compatibility
  - Fix prop validation tests that broke due to React failing faster on thrown JS Errors
- Replace `react-addons-css-transition-group` with `react-transition-group`
- Replace `pure-render-decorator` usage with `extends React.PureComponent`
  - Split `AbstractComponent` into impure `AbstractComponent` and pure `AbstractPureComponent` classes
- Upgrade `enzyme` to v3 and install `enzyme-adapter-react-16`
  - Fix various tests that broke due to Enzyme API changes
- `<Portal>`: Replace `ReactDOM._unstableRenderSubtreeToContainer` with `ReactDOM.createPortal`

### CODE REVIEW

File: packages/core/src/components/overlay/overlayTransition.tsx [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/*
+ * Copyright 2017 Palantir Technologies, Inc. All rights reserved.
+ * Licensed under the terms of the LICENSE file distributed with this project.
+ */
+
+import * as React from "react";
+import { CSSTransition } from "react-transition-group";
+import { IOverlayProps } from "./overlay";
+
+export function OverlayTransition<
```
Comment (adidahiya) [inline packages/core/src/components/overlay/overlayTransition.tsx]: this is no longer used; will remove

File: packages/core/src/components/overlay/overlay.tsx [hunk 2]
```diff
@@ -158,27 +156,26 @@ export class Overlay extends React.Component<IOverlayProps, IOverlayState> {
...
 
         const transitionGroup = (
-            <CSSTransitionGroup
-                transitionAppear={true}
-                transitionAppearTimeout={transitionDuration}
-                transitionEnterTimeout={transitionDuration}
-                transitionLeaveTimeout={transitionDuration}
-                transitionName={transitionName}
-            >
+            <TransitionGroup appear={true}>
```
Comment (adidahiya) [inline packages/core/src/components/overlay/overlay.tsx]: see https://github.com/reactjs/react-transition-group/blob/master/Migration.md

File: packages/core/src/components/button/buttonGroup.tsx [hunk 3]
```diff
@@ -38,8 +37,7 @@ export interface IButtonGroupProps extends IProps, React.HTMLProps<HTMLDivElemen
 
 // this component is simple enough that tests would be purely tautological.
 /* istanbul ignore next */
-@PureRender
-export class ButtonGroup extends React.Component<IButtonGroupProps, {}> {
+export class ButtonGroup extends React.PureComponent<IButtonGroupProps, {}> {
```
Comment (giladgray) [inline packages/core/src/components/button/buttonGroup.tsx]: we should be able to drop these empty `{}` state types, as the React types now provide a default: `interface Component<P = {}, S = {}>`.

though it's fine to not do this now, or ever.

File: packages/core/src/components/icon/icon.tsx [hunk 4]
```diff
@@ -31,8 +30,7 @@ export interface IIconProps extends IIntentProps, IProps {
     iconSize?: 16 | 20 | "inherit";
 }
 
-@PureRender
-export class Icon extends React.Component<IIconProps & React.HTMLAttributes<HTMLSpanElement>, never> {
+export class Icon extends React.PureComponent<IIconProps & React.HTMLAttributes<HTMLSpanElement>, never> {
```
Comment (giladgray) [inline packages/core/src/components/icon/icon.tsx]: remove `never`, or make it `{}` like all the others

File: packages/core/src/components/overlay/overlay.tsx [hunk 5]
```diff
@@ -264,15 +261,25 @@ export class Overlay extends React.Component<IOverlayProps, IOverlayState> {
...
+
         if (hasBackdrop && isOpen) {
             return (
-                <div
-                    {...backdropProps}
-                    className={classNames(Classes.OVERLAY_BACKDROP, backdropClassName, backdropProps.className)}
-                    onMouseDown={this.handleBackdropMouseDown}
-                    tabIndex={this.props.canOutsideClickClose ? 0 : null}
-                />
+                <CSSTransition classNames={transitionName} timeout={transitionDuration}>
```
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: _`classNames`_ 😱 
should we do this??

File: packages/core/src/components/portal/portal.tsx [hunk 6]
```diff
@@ -52,37 +52,25 @@ export class Portal extends React.Component<IPortalProps, {}> {
...
-    public componentDidMount() {
-        const targetElement = document.createElement("div");
-        targetElement.classList.add(Classes.PORTAL);
-
-        if (this.context.blueprintPortalClassName != null) {
-            targetElement.classList.add(this.context.blueprintPortalClassName);
+    constructor(props: IPortalProps, context: IPortalContext) {
+        super(props, context);
+        this.targetElement = document.createElement("div");
+        this.targetElement.classList.add(Classes.PORTAL);
```
Comment (giladgray) [inline packages/core/src/components/portal/portal.tsx]: why move to constructor instead of didMount?

File: packages/core/src/components/overlay/overlay.tsx (hunk 5 above)
Comment (adidahiya) [reply packages/core/src/components/overlay/overlay.tsx]: that's their API. are you asking if we should do this for our own props? I don't think there's anything wrong with the current names, so would prefer to keep them

File: packages/core/src/components/portal/portal.tsx (hunk 6 above)
Comment (adidahiya) [reply packages/core/src/components/portal/portal.tsx]: it happens sooner this way. also this is how the API example was set up

Comment (adidahiya) [reply packages/core/src/components/portal/portal.tsx]: oh also I need it to be there by the time `render()` is called, which is not true of `componentDidMount`

File: packages/core/karma.conf.js [hunk 7]
```diff
@@ -20,6 +21,19 @@ module.exports = function (config) {
             "src/components/tag-input/*",
             "src/components/tooltip2/*",
         ],
+        coverageOverrides: {
```
Comment (adidahiya) [inline packages/core/karma.conf.js]: oops, bad copy-paste

**Comment by adidahiya** [comment]
Some regressions I noticed (which can be addressed in follow-up PRs):

- <kbd>ESC</kbd> key to close Dialogs doesn't work until you hit <kbd>TAB</kbd> to move focus into the Dialog element
- When opening a `<Select>`, the input field is not focussed immediately (likely related to the above issue)

**Comment by adidahiya** [comment]
Filed https://github.com/palantir/blueprint/issues/1901 to address those later ^

File: packages/core/karma.conf.js [hunk 8]
```diff
@@ -10,7 +10,12 @@ module.exports = function (config) {
     const baseConfig = createKarmaConfig({
         dirname: __dirname,
         coverageExcludes: [
+            // not worth full coverage
             "src/accessibility/*",
+            "src/common/abstractComponent*",
+            // deprecated components
+            "src/components/popover/*",
```
Comment (themadcreator) [inline packages/core/karma.conf.js]: are these actually deprecated if they're being replaced by labs components?

File: packages/core/src/components/portal/portal.tsx [hunk 9]
```diff
@@ -52,37 +52,30 @@ export class Portal extends React.Component<IPortalProps, {}> {
...
+        return ReactDOM.createPortal(
             <div {...removeNonHTMLProps(this.props)} ref={this.props.containerRef}>
                 {this.props.children}
             </div>,
             this.targetElement,
-            () => safeInvoke(this.props.onChildrenMount),
         );
     }
 
+    public componentDidMount() {
```
Comment (themadcreator) [inline packages/core/src/components/portal/portal.tsx]: it looks like `componentDidMount` is maintained, but `componentDidUpdate` was removed which used an unstable method. IS this functionality still captured?

File: packages/labs/test/index.ts [hunk 10]
```diff
@@ -2,4 +2,11 @@
  * Copyright 2017 Palantir Technologies, Inc. All rights reserved.
  */
 
+import "es6-shim";
```
Comment (themadcreator) [inline packages/labs/test/index.ts]: wasn't this supposed to be removed?

File: packages/table/src/table.tsx [hunk 11]
```diff
@@ -492,7 +492,7 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
     // time. it serves as a signal that we can switch to batch rendering.
     private didCompletelyMount = false;
 
-    public constructor(props: ITableProps, context?: any) {
+    public constructor(props: ITableProps & { children: React.ReactNode }, context?: any) {
```
Comment (themadcreator) [inline packages/table/src/table.tsx]: `ITableProps` already has a definition for `children`, shouldn't these match?

File: packages/table/src/table.tsx [hunk 12]
```diff
@@ -664,7 +664,8 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         );
     }
 
-    public componentWillReceiveProps(nextProps: ITableProps) {
+    public componentWillReceiveProps(nextProps: ITableProps & { children: React.ReactNode }) {
```
Comment (themadcreator) [inline packages/table/src/table.tsx]: ^ same

File: packages/core/src/components/portal/portal.tsx [hunk 13]
```diff
@@ -52,37 +52,30 @@ export class Portal extends React.Component<IPortalProps, {}> {
...
+        document.body.appendChild(this.targetElement);
+        safeInvoke(this.props.onChildrenMount);
+    }
+
     public componentWillUnmount() {
-        ReactDOM.unmountComponentAtNode(this.targetElement);
```
Comment (cmslewis) [inline packages/core/src/components/portal/portal.tsx]: Why don't we need this anymore?

File: packages/labs/test/index.ts (hunk 10 above)
Comment (themadcreator) [reply packages/labs/test/index.ts]: (though it's just test code code, so... yolo)

File: packages/core/src/components/tabs2/tab2.tsx [hunk 14]
```diff
@@ -39,8 +38,7 @@ export interface ITab2Props extends IProps {
     title?: string | JSX.Element;
 }
 
-@PureRender
-export class Tab2 extends React.Component<ITab2Props, {}> {
+export class Tab2 extends React.PureComponent<ITab2Props, {}> {
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tab2.tsx]: @giladgray FYI: this edit. (You moved these files in #1900.)

File: packages/core/test/collapsible-list/collapsibleListTests.tsx [hunk 15]
```diff
@@ -22,7 +22,7 @@ import {
 describe("<CollapsibleList>", () => {
     it("adds className to itself", () => {
         const list = renderCollapsibleList(3, { className: "winner" });
-        assert.lengthOf(list.find(".winner"), 1);
+        assert.isNotEmpty(list.find(".winner"));
```
Comment (cmslewis) [inline packages/core/test/collapsible-list/collapsibleListTests.tsx]: Hmm, this check isn't equivalent. Was this suffering from Enzyme 3's `.hostNodes()` issue (https://github.com/airbnb/enzyme/issues/1174)? Seems like the fix for too many elements here is:

```tsx
assert.lengthOf(list.find(".winner").hostNodes(), 1);
```

File: packages/core/test/text/textTests.tsx [hunk 16]
```diff
@@ -15,7 +15,7 @@ describe("<Text>", () => {
         const textContent = "textContent";
         const className = "bp-test-class";
         const wrapper = mount(<Text className={className}>{textContent}</Text>);
-        const element = wrapper.find(`.${className}`);
+        const element = wrapper.find(`div.${className}`);
```
Comment (cmslewis) [inline packages/core/test/text/textTests.tsx]:
```tsx
wrapper.find(`.${className}`).hostNodes()
```

is clearer

File: packages/core/test/toast/toasterTests.ts [hunk 17]
```diff
@@ -130,10 +128,11 @@ describe("Toaster", () => {
 
         it("focuses on newly created toast", done => {
             toaster.show({ message: "focus on me" });
+            // small explicity timeout reduces flakiness of these tests
```
Comment (cmslewis) [inline packages/core/test/toast/toasterTests.ts]: `explicit`~ly~

File: packages/core/test/tree/treeTests.tsx [hunk 18]
```diff
@@ -131,44 +131,43 @@ describe("<Tree>", () => {
         contents[2].iconName = "pt-icon-document";
 
         const tree = renderTree({ contents });
-        const iconSelector = `.${Classes.TREE_NODE_ICON}.pt-icon-document`;
-        assert.lengthOf(tree.find(`.c0 > .${Classes.TREE_NODE_CONTENT} .${Classes.TREE_NODE_ICON}`), 0);
-        assert.lengthOf(tree.find(`.c1 > .${Classes.TREE_NODE_CONTENT} ${iconSelector}`), 1);
-        assert.lengthOf(tree.find(`.c2 > .${Classes.TREE_NODE_CONTENT} ${iconSelector}`), 1);
+        const iconSelector = `span.${Classes.TREE_NODE_ICON}.pt-icon-document`;
+        assert.lengthOf(tree.find(`.c0 > .${Classes.TREE_NODE_CONTENT} span.${Classes.TREE_NODE_ICON}`), 0, "c0");
```
Comment (cmslewis) [inline packages/core/test/tree/treeTests.tsx]: Ah, the tag names make more sense with more complex selectors like this.

File: packages/labs/test/index.ts (hunk 10 above)
Comment (adidahiya) [reply packages/labs/test/index.ts]: no, you _explicitly_ need to bring it in to support React 16. We're definitely not _removing_ es6-shim from the page runtime; we are pushing the responsibility down to consumers of the library (e.g. the test environment, table-dev-app, docs-app, our other apps, etc.)

File: packages/datetime/package.json [hunk 19]
```diff
@@ -24,6 +24,7 @@
     "test": "npm-run-all -s compile:cjs test:pre -p test:karma test:iso",
     "test:pre": "tsc -p ./test",
     "test:karma": "karma start",
+    "test:karma:debug": "karma start --browsers=Chrome --single-run=false --reporters=mocha --debug",
```
Comment (cmslewis) [inline packages/datetime/package.json]: Can we get rid of `--browsers=Chrome` for this task? I've been changing the browser to "PhantomJS" locally/manually for the past few months whenever I need to write tests. It's much more useful to dev against the environment that Circle is actually going to use. 

Would be cool to have a `test:karma:debug:chrome` task as a supplement though.

File: packages/core/karma.conf.js (hunk 8 above)
Comment (adidahiya) [reply packages/core/karma.conf.js]: we'll need to remember to remove this line when @cmslewis's Popover2 -> Popover change goes.

File: packages/table/src/table.tsx (hunk 11 above)
Comment (adidahiya) [reply packages/table/src/table.tsx]: yeah good catch. will fix

File: packages/labs/package.json [hunk 20]
```diff
@@ -24,6 +24,7 @@
     "test": "npm-run-all -s test:pre -p test:karma",
     "test:pre": "tsc -p ./test",
     "test:karma": "karma start",
+    "test:karma:debug": "karma start --browsers=Chrome --single-run=false --reporters=mocha --debug",
```
Comment (cmslewis) [inline packages/labs/package.json]: Same

File: packages/select/package.json [hunk 21]
```diff
@@ -24,26 +24,28 @@
     "test": "npm-run-all -s compile:cjs test:pre -p test:karma test:iso",
     "test:pre": "tsc -p ./test",
     "test:karma": "karma start",
+    "test:karma:debug": "karma start --browsers=Chrome --single-run=false --reporters=mocha --debug",
```
Comment (cmslewis) [inline packages/select/package.json]: Same

File: packages/core/src/components/portal/portal.tsx (hunk 9 above)
Comment (adidahiya) [reply packages/core/src/components/portal/portal.tsx]: yeah so now that we're actually returning something from `render` instead of `null` all the time, the React tree works as expected. there's a unit test for the context-preserving functionality (`it("respects blueprintPortalClassName on context"`)

File: packages/select/test/suggestTests.tsx [hunk 22]
```diff
@@ -73,7 +73,7 @@ describe("Suggest", () => {
 
         it("scrolls active item into view when popover opens", () => {
             const wrapper = suggest();
-            const queryList = (wrapper.getNode() as any).queryList; // private ref
+            const queryList = ((wrapper.instance() as Suggest<Film>) as any).queryList; // private ref
```
Comment (cmslewis) [inline packages/select/test/suggestTests.tsx]: what does double-casting do for us?

File: packages/table/package.json [hunk 23]
```diff
@@ -24,27 +24,29 @@
     "test": "npm-run-all -s compile:cjs test:pre -p test:karma test:iso",
     "test:pre": "tsc -p ./test",
     "test:karma": "karma start",
+    "test:karma:debug": "karma start --browsers=Chrome --single-run=false --reporters=mocha --debug",
```
Comment (cmslewis) [inline packages/table/package.json]: Same

File: packages/table/src/table.tsx (hunk 11 above)
Comment (cmslewis) [inline packages/table/src/table.tsx]: Worth making a new props interface in `core/.../props.ts`? This is used in a few places.

e.g.
```tsx
export interface IChildrenProps {
    children: React.ReactNode;
}
```

File: packages/labs/test/index.ts (hunk 10 above)
Comment (themadcreator) [reply packages/labs/test/index.ts]: oh i see

File: packages/core/src/components/portal/portal.tsx (hunk 13 above)
Comment (adidahiya) [reply packages/core/src/components/portal/portal.tsx]: React cleans up itself when you actually return things in `render`

File: packages/datetime/package.json (hunk 19 above)
Comment (adidahiya) [reply packages/datetime/package.json]: can be a follow up

File: packages/select/test/suggestTests.tsx (hunk 22 above)
Comment (adidahiya) [reply packages/select/test/suggestTests.tsx]: just helps clarify intent to developers

File: packages/table/src/table.tsx (hunk 11 above)
Comment (adidahiya) [reply packages/table/src/table.tsx]: no, I removed it

File: packages/core/test/collapsible-list/collapsibleListTests.tsx (hunk 15 above)
Comment (adidahiya) [reply packages/core/test/collapsible-list/collapsibleListTests.tsx]: Yeah but is that really a more meaningful / useful test? IMO this is another tautology and I would rather have a auto-generated test suite for spreading props / classNames rather than including one of these test cases at the start of every component test suite

Comment (adidahiya) [reply packages/core/test/collapsible-list/collapsibleListTests.tsx]: ok I can switch to `hostNodes`

File: packages/datetime/package.json (hunk 19 above)
Comment (adidahiya) [reply packages/datetime/package.json]: actually I prefer your approach, will remove `--browsers` and require devs to supply that override manually

File: packages/core/test/collapsible-list/collapsibleListTests.tsx (hunk 15 above)
Comment (adidahiya) [reply packages/core/test/collapsible-list/collapsibleListTests.tsx]: would you mind documenting this here? https://palantir.quip.com/QISEA7SVbqfk

**Comment by hysoftwareeng** [comment]
Is this going to be in the next release (after 1.35.0). I currently still see a unmet peer dependency when installing core 1.35.0 
capture

**Comment by giladgray** [comment]
@hysoftwareeng this will be in our upcoming 2.0 release, but the [installation instructions](http://blueprintjs.com/docs/#blueprint.npm-installation) do not change: react is still a `peerDependency` so you must explicitly install it yourself in your application.

screen shot 2017-12-15 at 11 08 53 am

**Comment by Skovy** [comment]
When will a release be cut for 2.0? It's not possible to upgrade to React 16 if blueprintjs is a dependency. Thanks!

**Comment by rmendelovits** [comment]
I have the following error when trying to upgrade to React 16: 

npm WARN pure-render-decorator@1.2.1 requires a peer of react@^15.0.0 || ^0.14.0
 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4
.2 but none is installed. You must install peer dependencies yourself.

But where does pure-render-decorator/react-addons-css-transition-group come from?

the pure-render-decorator is a requirement for these two packages.
- @blueprintjs/core
- @blueprintjs/table

and I get this warning when I try to move to react-transition-group
npm WARN @blueprintjs/core@1.35.1 requires a peer of react-addons-css-transition
-group@^15.0.1 || ^0.14 but none is installed. You must install peer dependencie
s yourself.

**Comment by adidahiya** [comment]
Those warnings can be safely ignored. See https://github.com/palantir/blueprint/issues/866#issuecomment-348617976.

Anyway, I just released the first beta of blueprint 2.0.0, you can try it out for react 16 support. Release notes coming soon.

**Comment by rmendelovits** [comment]
Thanks

**Comment by Skovy** [comment]
@adidahiya not sure I follow. `react-addons-css-transition-group` requires `react@^15.4.2`, and we have `react@16.2.0`. Does that mean  `react-addons-css-transition-group` would then require us to have two versions of React in the bundle?

When I upgrade to React `16.2.0` and run `yarn check`, I'm recieve these errors:

```
error "react-addons-css-transition-group#react@^15.4.2" doesn't satisfy found match of "react@16.2.0"
error "@blueprintjs/core#pure-render-decorator#react@^15.0.0 \|\| ^0.14.0" doesn't satisfy found match of "react@16.2.0"
error "@blueprintjs/datetime#react-day-picker#react@~0.13.x \|\| ~0.14.x \|\| ^15.0.0" doesn't satisfy found match of "react@16.2.0"
```

**Comment by adidahiya** [comment]
@Skovy Since these are peer dependencies, no, you don't need to end up with two versions of React in your bundle. Warnings aside, does this cause a problem at runtime in your application when you try to use React 16.2.0?

Also, I suggest upgrading react-day-picker to a version that allows React 16 as a peer dependency: https://github.com/gpbl/react-day-picker/blob/3156e3de1664caa15cf12cfd0fdd96350874e8c5/package.json#L55

**Comment by Skovy** [comment]
@adidahiya got it, thanks for the insight and I appreciate the help! 👍

**Comment by Skovy** [comment]
@adidahiya I opened a PR to upgrade `react-day-picker`, but ran into linting problems. Would appreciate any insights on https://github.com/palantir/blueprint/pull/2055.
