### PR TITLE
[Table] Pass custom className to Table, Column, ColumnHeaderCell elements

### LINKED ISSUE #641: Table doesn't pass through classes provided to its classNames prop
Check out https://github.com/palantir/blueprint/blob/master/packages/table/src/table.tsx#L378. It would be nice if you passed through whatever classes are provided via className

### LINKED ISSUE #690: Table `Column` component doesn't respect className prop
### Bug report

- __Package version(s)__: Blueprint table 1.6.0
- __Browser and OS versions__: Chrome 56 OSX 10.11.6

#### Steps to reproduce

1. Make a blueprint table with`Column` components that have a `className` prop set.

#### Actual behavior

Column headers don't get the class specified added in the rendered HTML.

#### Expected behavior

Column headers have the class specified added in the rendered HTML.

(Pretty sure this is a regression, this previously worked for us.)

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

- Pass through custom `className` for `Table`, `Column`, and `ColumnHeaderCell`
- Add unit tests for each

#### Reviewers should focus on:

- Does this scheme make sense?

### CODE REVIEW

File: packages/table/test/columnTests.tsx [hunk 1]
```diff
@@ -84,4 +84,15 @@ describe("Column", () => {
...
     });
+
+    it("passes custom class name to renderer", () => {
+        const CLASS_NAME = "my-custom-class-name";
+        const table = harness.mount(
+            <Table numRows={5}>
+                <Column className={CLASS_NAME} />
+            </Table>,
+        );
+        const columnNode = table.find(`.${Classes.TABLE_HEADER}`, 0).element;
```
Comment (giladgray) [inline packages/table/test/columnTests.tsx]: oh snap is that an index arg to `find()`?? had no idea! i actually might prefer `.find().first()` for _this_ case, as it's harder to miss.

File: packages/table/test/columnTests.tsx [hunk 2]
```diff
@@ -84,4 +84,15 @@ describe("Column", () => {
...
+        expect(columnNode.classList.contains(CLASS_NAME)).to.be.true;
```
Comment (giladgray) [inline packages/table/test/columnTests.tsx]: i do believe enzyme has [`hasClass`](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/hasClass.md)

File: packages/table/src/table.tsx [hunk 3]
```diff
@@ -372,7 +372,11 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         const { isRowHeaderShown } = this.props;
         this.validateGrid();
         return (
-            <div className={Classes.TABLE_CONTAINER} ref={this.setRootTableRef} onScroll={this.handleRootScroll}>
+            <div
+                className={classNames(Classes.TABLE_CONTAINER, this.props.className)}
```
Comment (giladgray) [inline packages/table/src/table.tsx]: not to be a stickler but both of these render functions deconstruct `this.props` a few lines up. you could add `className` there?

Comment (cmslewis) [inline packages/table/src/table.tsx]: I prefer to avoid deconstructing unless:

1. ...a variable is used in more than one place in that scope.
1. ...(less importantly) deconstructing helps keep later lines below our linter's `max-line-length`.

That said, consistency is also nice. I'll deconstruct in `columnHeaderCell.tsx`, since that one seems more egregious.

File: packages/table/test/columnTests.tsx (hunk 2 above)
Comment (cmslewis) [inline packages/table/test/columnTests.tsx]: True, but that function has been wholly unreliable for me for some reason. I'll give it a try though.

File: packages/table/test/columnTests.tsx (hunk 1 above)
Comment (cmslewis) [inline packages/table/test/columnTests.tsx]: This is a custom `ElementHarness` class, not an Enzyme wrapper.
