### PR TITLE
[Icon] unknown string icon name renders blank icon

### LINKED ISSUE #2925: Icon should render a blank icon instead of empty element when an unknown icon string is passed
#### Environment

- __Package version(s)__: 3.2.0
- __Browser and OS versions__: N/A

#### Steps to reproduce
`<Icon className={className} color={color} icon="foobarbaz" />`

#### Actual behavior

Renders `null` (no DOM element)

#### Expected behavior

???

#### Possible solution

Renders `<Icon className={className} color={color} icon="blank" />`

--- 

We're reading these strings from config, so if they're defined incorrect it'd be nicer to have a blank-but-well-sized icon rather than a missing DOM element which messes with document flow.

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- unknown icon name renders markup but no path elements, resulting in blank icon.

### CODE REVIEW

File: packages/core/src/components/icon/icon.tsx [hunk 1]
```diff
@@ -71,29 +74,27 @@ export class Icon extends React.PureComponent<IIconProps & React.DOMAttributes<H
...
-            return icon;
-        }
-
         // choose which pixel grid is most appropriate for given icon size
         const pixelGridSize = iconSize >= Icon.SIZE_LARGE ? Icon.SIZE_LARGE : Icon.SIZE_STANDARD;
+        // render path elements, or nothing if icon name is unknown.
         const paths = this.renderSvgPaths(pixelGridSize, icon);
-        if (paths == null) {
-            return null;
-        }
```
Comment (themadcreator) [inline packages/core/src/components/icon/icon.tsx]: so now it will always have an empty `<svg>` instead of nothing?

File: packages/core/src/components/icon/icon.tsx [hunk 2]
```diff
@@ -25,23 +25,26 @@ export interface IIconProps extends IIntentProps, IProps {
...
-     * - If given an `IconName` (a string literal union of all icon names),
-     *   that icon will be rendered as an `<svg>` with `<path>` tags.
-     * - If given a `JSX.Element`, that element will be rendered and _all other props on this component are ignored._
-     *   This type is supported to simplify usage of this component in other Blueprint components.
-     *   As a consumer, you should never use `<Icon icon={<element />}` directly; simply render `<element />` instead.
+     * - If `null` or `undefined` or `false`, this component will render
+     *   nothing.
+     * - If given an `IconName` (a string literal union of all icon names), that
+     *   icon will be rendered as an `<svg>` with `<path>` tags. Unknown strings
+     *   will render a blank icon.
```
Comment (themadcreator) [inline packages/core/src/components/icon/icon.tsx]: is a "blank icon" different than an empty `<svg>`? if so, how? if not, how is it an "icon" at all?

the wording makes it sound like there is some sort of stand in icon for a "blank" situation, kind of like the broken `` graphic.

File: packages/core/src/components/icon/icon.tsx (hunk 1 above)
Comment (giladgray) [reply packages/core/src/components/icon/icon.tsx]: if you say `<Icon icon="blah" />` then yes. `<Icon icon={null} />` renders `null`.

File: packages/core/src/components/icon/icon.tsx (hunk 2 above)
Comment (giladgray) [reply packages/core/src/components/icon/icon.tsx]: image
😂
