### PR TITLE
[RadioGroup] [HtmlSelect] options support className and disabled

### LINKED ISSUE #2782: Migrating to 3.0: <RadioGroup> no longer passes custom classNames to <Radio> options
#### Environment

- __Package version(s)__: `@blueprintjs/core` 3.2.0

#### Steps to reproduce

1. Create a `<RadioGroup>` with `options` having custom `className`s.

#### Actual behavior

Custom `className`s are not passed down to the `<Radio>` elements.

#### Expected behavior

Custom `className`s _are_ passed down to the `<Radio>` elements. This used to work in 1.X, so this is a _regression_. 😲 

#### Possible solution

Pretty straightforward. Just need to pass in the `className` for each option right [here](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/radioGroup.tsx#L98).

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

- 🐛 Fix regression: `<RadioGroup>` passes custom `className` to its options
- 🐛 Fix regression: `<HtmlSelect>` passes custom `className` to its options

#### Reviewers should focus on:

Nothing in particular. Should be simple.

#### Screenshot

N/A

### CODE REVIEW

File: packages/core/src/components/html-select/htmlSelect.tsx [hunk 1]
```diff
@@ -60,8 +60,9 @@ export class HTMLSelect extends React.PureComponent<IHTMLSelectProps> {
         );
 
         const optionChildren = options.map(option => {
-            const { value, label }: IOptionProps = typeof option === "object" ? option : { value: option };
-            return <option key={value} value={value} children={label || value} />;
+            const { className: optionClassName, value, label }: IOptionProps =
```
Comment (cmslewis) [inline packages/core/src/components/html-select/htmlSelect.tsx]: Had to mix up the variable name to avoid shadowing the `className` variable on [L59](https://github.com/palantir/blueprint/pull/2783/files#diff-a8ae96697a4c86c0af1cafd4a6894e7cR59).

File: packages/core/test/controls/radioGroupTests.tsx [hunk 2]
```diff
@@ -100,6 +100,17 @@ describe("<RadioGroup>", () => {
         assert.lengthOf(group.find(Radio), 2);
     });
 
+    it("passes custom classNames to options", () => {
+        const OPTIONS = [{ className: "apple", value: "a" }, { className: "banana", value: "b" }];
+        const group = mount(<RadioGroup onChange={emptyHandler} options={OPTIONS} selectedValue="a" />);
+        assert.strictEqual(findRadio(group, { value: "a" }).prop("className"), "apple");
+        assert.strictEqual(findRadio(group, { value: "b" }).prop("className"), "banana");
```
Comment (giladgray) [inline packages/core/test/controls/radioGroupTests.tsx]: enzyme provides `wrapper.hasClass(name): boolean`, but this is ok as error messages will be different.

File: packages/core/test/html-select/htmlSelectTests.tsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+import * as React from "react";
+
+import { HTMLSelect, IOptionProps } from "../../src/index";
+
+describe("<HtmlSelect>", () => {
+    const emptyHandler = () => {
+        return;
+    };
+
+    it("renders options without CSS classes by default", () => {
```
Comment (giladgray) [inline packages/core/test/html-select/htmlSelectTests.tsx]: i hate to say it, but... 🤷‍♂️ since you're adding a test suite here then might as well test that all the options props come out as expected, not just `className`.  keep it simple, short and sweet.

File: packages/core/test/controls/radioGroupTests.tsx (hunk 2 above)
Comment (giladgray) [reply packages/core/test/controls/radioGroupTests.tsx]: but do move this near the other `options` tests

**Comment by giladgray** [comment]
@cmslewis i've discovered that `HTMLSelect` also doesn't support `disabled` right now, so we should def test all the props.
