### PR TITLE
[Popover2] Make sure targetElement exists before trying to call its function

### LINKED ISSUE #1856: Bug: Labs: Popover2: updateDarkParent() throws when rendered with react-test-renderer
### Bug report

- __Package version(s)__:  0.13.0
- __Browser and OS versions__: 
"react-test-renderer": "^16.1.1"
windows 10 / macos 10.13.1

#### Steps to reproduce

1. Render Popover2 component like this
```jsx
import React from 'react';
import renderer from 'react-test-renderer';
import { Popover2 } from '@blueprintjs/labs';

it('renders with react-test-renderer', () => {
    const component = renderer.create(
      <Popover2 content={<span>My content</span>}>
        <span>Hi there</span>
      </Popover2>,
    );
    expect(component).toMatchSnapshot();
  });
```

#### Cause
[updateDarkParent](https://github.com/palantir/blueprint/blob/master/packages/labs/src/components/popover/popover2.tsx#L386) assumes there will be a target element, which is not the case if we're not working from within an actual dom. A simple fix would be to assert that `targetElement` exists before trying to call `closest` on it

#### Actual behavior

```
 FAIL  renders with react-test-renderer (5.731s)

    TypeError: Cannot read property 'closest' of null

      at Popover2.Object.<anonymous>.Popover2.updateDarkParent (node_modules/@blueprintjs/labs/dist/components/popover/popover2.js:205:51)
      at Popover2.Object.<anonymous>.Popover2.componentDidMount (node_modules/@blueprintjs/labs/dist/components/popover/popover2.js:157:14)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4553:24)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5729:9)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1610:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1649:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5833:9)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6800:42)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6750:7)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6661:7)
      at scheduleWorkImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6515:11)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6472:12)
      at scheduleTopLevelUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6976:5)
      at Object.updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7014:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7637:18)
      at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:26:44)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:146:28)
          at Promise (<anonymous>)
          at <anonymous>
```

#### Expected behavior

Not throw an exception :)

### PR DESCRIPTION
**Pull request by tobilen**
#### Checklist
- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)

#### Changes proposed in this pull request:

Make sure targetElement exists before trying to call `closest` on it

### CODE REVIEW

File: packages/labs/src/components/popover/popover2.tsx [hunk 1]
```diff
@@ -383,7 +383,7 @@ export class Popover2 extends AbstractComponent<IPopover2Props, IPopover2State>
 
     private updateDarkParent() {
         if (!this.props.inline && this.state.isOpen) {
-            const hasDarkParent = this.targetElement.closest(`.${Classes.DARK}`) != null;
+            const hasDarkParent = this.targetElement && this.targetElement.closest(`.${Classes.DARK}`) != null;
```
Comment (cmslewis) [inline packages/labs/src/components/popover/popover2.tsx]: Codebase convention: explicit boolean expression please:

```tsx
this.targetElement != null && ...
```

**Comment by tobilen** [comment]
<h3>Explicit null check</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/tobilen/blueprint/19/artifacts/0//home/ubuntu/blueprint/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://circleci.com/api/v1/project/tobilen/blueprint/19/artifacts/0//home/ubuntu/blueprint/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://circleci.com/api/v1/project/tobilen/blueprint/19/artifacts/0//home/ubuntu/blueprint/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/labs/src/components/popover/popover2.tsx [hunk 2]
```diff
@@ -383,7 +383,7 @@ export class Popover2 extends AbstractComponent<IPopover2Props, IPopover2State>
 
     private updateDarkParent() {
         if (!this.props.inline && this.state.isOpen) {
-            const hasDarkParent = this.targetElement && this.targetElement.closest(`.${Classes.DARK}`) != null;
+            const hasDarkParent = this.targetElement !== null && this.targetElement.closest(`.${Classes.DARK}`) != null;
```
Comment (cmslewis) [inline packages/labs/src/components/popover/popover2.tsx]: Oh, you'll want to do double-equals (`!=`) so that both `undefined` and `null` satisfy the condition.

**Comment by tobilen** [comment]
<h3>Explicit null check, take two. action!</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/tobilen/blueprint/20/artifacts/0//home/ubuntu/blueprint/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://circleci.com/api/v1/project/tobilen/blueprint/20/artifacts/0//home/ubuntu/blueprint/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://circleci.com/api/v1/project/tobilen/blueprint/20/artifacts/0//home/ubuntu/blueprint/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/labs/src/components/popover/popover2.tsx [hunk 3]
```diff
@@ -383,7 +383,10 @@ export class Popover2 extends AbstractComponent<IPopover2Props, IPopover2State>
 
     private updateDarkParent() {
         if (!this.props.inline && this.state.isOpen) {
-            const hasDarkParent = this.targetElement.closest(`.${Classes.DARK}`) != null;
+            const hasDarkParent =
+                this.targetElement != null &&
+                typeof this.targetElement !== "undefined" &&
```
Comment (cmslewis) [inline packages/labs/src/components/popover/popover2.tsx]: Line 387 is sufficient without this additional typeof check.

**Comment by tobilen** [comment]
<h3>Explicit null check, take three</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/tobilen/blueprint/21/artifacts/0//home/ubuntu/blueprint/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://circleci.com/api/v1/project/tobilen/blueprint/21/artifacts/0//home/ubuntu/blueprint/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://circleci.com/api/v1/project/tobilen/blueprint/21/artifacts/0//home/ubuntu/blueprint/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>
