### PR TITLE
fix warnings in tests

### LINKED ISSUE #1908: [2.0] warnings produced in unit tests
```
  <Select>
    ✔ renders a Popover around children that contains InputGroup and items
ERROR: 'Warning: `NaN` is an invalid value for the `left` css style property.
    in span (created by Arrow)
    in Arrow (created by Blueprint.Popover2Arrow)
    in Blueprint.Popover2Arrow (created by Blueprint.Popover2)
    in div (created by Blueprint.Popover2)
    in div (created by Popper)
    in Popper (created by Blueprint.Popover2)
    in Transition (created by CSSTransition)
    in CSSTransition (created by Blueprint.Overlay)
    in div (created by TransitionGroup)
    in TransitionGroup (created by Blueprint.Overlay)
    in span (created by Blueprint.Overlay)
    in Blueprint.Overlay (created by Blueprint.Popover2)
    in span (created by Manager)
    in Manager (created by Blueprint.Popover2)
    in Blueprint.Popover2 (created by Blueprint.QueryList)
    in Blueprint.QueryList (created by Blueprint.Select)
    in Blueprint.Select (created by WrapperComponent)
    in WrapperComponent'
```

```
  Suggest
WARN: '[Blueprint] <Popover inline={true}> ignores tetherOptions, constraints, and useSmartPositioning.'
```

```
Table
    Reordering
      ✔ Shows preview guide and invokes callback when selected columns reordered
ERROR: 'Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the Table component.'
      ✔ Shows preview guide and invokes callback when selected rows reordered
```

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

see commits for individual strategies to address warnings.
a few warning messages remain, namely that `NaN ... left` one in PopoverArrow, which I suspect is coming from Popper due to Phantom being a weird environment.

also includes (what I think is the) fix for Popover flakes, from https://github.com/palantir/blueprint/pull/2028/commits/1089e6e0c42329926067157b164451e6e7ad92f1 in #2028

### CODE REVIEW

File: packages/table/test/tableTests.tsx [hunk 1]
```diff
@@ -1566,19 +1566,10 @@ describe("<Table>", () => {
...
-                    consoleWarn.reset();
-                });
-
-                after(() => {
-                    consoleWarn.restore();
-                });
+                let consoleWarn: sinon.SinonStub;
+                before(() => (consoleWarn = sinon.stub(console, "warn")));
+                afterEach(() => consoleWarn.resetHistory());
+                after(() => consoleWarn.restore());
```
Comment (adidahiya) [inline packages/table/test/tableTests.tsx]: not a fan of these syntax changes, it's entirely unnecessary and makes the code too dense / hard to modify

Comment (giladgray) [reply packages/table/test/tableTests.tsx]: meh, prettier is good at fixing it for you

Comment (adidahiya) [reply packages/table/test/tableTests.tsx]: what do you mean? what if I have to add multiple statements to each of these blocks? it's a lot more editing. there's no benefit to this code style
