### PR TITLE
Fix column auto resize

### LINKED ISSUE #783: Table column auto-sizing does not work as expected
### Bug report

- __Package version(s)__: 1.11.0
- __Browser and OS versions__: Chrome / OS X

#### Actual behavior

- the first column I resized is too wide
- the second column gets the right width (fits the column header text)

#### Expected behavior

- first column action should try to fit the longest text in the viewport

### PR DESCRIPTION
**Pull request by gscshoyru**
Fix bug I accidentally introduced in #685 ( https://github.com/palantir/blueprint/pull/685/files#diff-85bb3412e972df58b0e3115a878bf248L63 )

#### Changes proposed in this pull request:

Make class should be what it should be so it actually selects the cells in the table.

### CODE REVIEW

**Comment by giladgray** [comment]
@gscshoyru is it possible to unit test this?

**Comment by gscshoyru** [comment]
Yeah, unit tests are coming, just wanted to make sure things looked good to everyone as I did 'em

**Comment by gscshoyru** [comment]
...yeah I think I can probably do something to make a test for this.

**Comment by giladgray** [comment]
sorry bud 😨 you'll thank yourself for this later 🍰

File: packages/table/src/locator.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ export class Locator implements ILocator {
 
     public getWidestVisibleCellInColumn(columnIndex: number): number {
         const cellClasses = [
-            `.${Classes.columnIndexClass(columnIndex)}`,
+            `.${Classes.columnCellIndexClass(columnIndex)}`,
```
Comment (adidahiya) [inline packages/table/src/locator.ts]: oooh so subtle. yeah unit test would be great
