### PR TITLE
Fix #2095: Ensure elements are compared to proxied component type

### LINKED ISSUE #2095: [core] Using Hotkeys breaks with react-hot-loader
### Bug report

The line here causes projects that use `react-hot-loader` to fall over:

https://github.com/palantir/blueprint/blob/57e66a7f884f7ea49dd47caa92bf5c69a9e53e42/packages/core/src/components/hotkeys/hotkey.tsx#L85

i.e. this is always false whether or not the instance is actually an instance of `Hotkey`, because `react-hot-loader` proxies the component so it fails the equality check as described here:

https://github.com/gaearon/react-hot-loader/tree/next#checking-element-types
https://github.com/gaearon/react-hot-loader/tree/master#checking-element-types

Ultimately it means that hotkeys are never registered! 😱

There are a few solutions outlined on the pages above - which do you like best? 🙂 I can make a PR!

- __Package version(s)__: 2.0.0-beta.3

### PR DESCRIPTION
**Pull request by benhjames**
#### Changes proposed in this pull request:

Since components end up proxied when using `react-hot-loader`, comparing to `React.createElement(Component).type` rather than `Component` should be a better solution to check if a component is of the right type (e.g. a `Hotkey`) 🙂 

#### Reviewers should focus on:

Whether the components changed still behave as normal: Collapsible List, Radio Group, Hotkeys, Popover and Tabs.

### CODE REVIEW

**Comment by benhjames** [comment]
<h3>Empty commit to get CircleCI to build</h3>

Preview: <strong><a href='https://13-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://13-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://13-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by benhjames** [comment]
<h3>Fix missing negation</h3>

Preview: <strong><a href='https://19-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://19-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://19-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/core/src/components/hotkeys/hotkey.tsx [hunk 1]
```diff
@@ -83,7 +84,7 @@ export class Hotkey extends AbstractPureComponent<IHotkeyProps, {}> {
     };
 
     public static isInstance(element: any): element is React.ReactElement<IHotkeyProps> {
```
Comment (giladgray) [inline packages/core/src/components/hotkeys/hotkey.tsx]: borrow this type guard signature for your util function please.

and also remove this function since you replaced its usage (in Hotkeys below) with the new util function.

File: packages/core/src/common/utils.ts [hunk 2]
```diff
@@ -33,6 +35,10 @@ export function getDisplayName(ComponentClass: React.ComponentClass | INamed) {
     return (ComponentClass as React.ComponentClass).displayName || (ComponentClass as INamed).name || "Unknown";
 }
 
+export function isElementType(element: JSX.Element, ComponentClass: React.ComponentClass) {
```
Comment (giladgray) [inline packages/core/src/common/utils.ts]: would be awesome to do something like this:
```
isElementType<P = {}>(element: any, ComponentClass: React.ComponentClass<P>): element is React.ReactElement<P>
```

then you won't need to cast when calling this function (but you will need to check `!= null` and cast inside this fn)

File: packages/core/src/components/tabs/tabs.tsx [hunk 3]
```diff
@@ -316,5 +316,5 @@ function isEventKeyCode(e: React.KeyboardEvent<HTMLElement>, ...codes: number[])
 }
 
 function isTab(child: React.ReactChild): child is TabElement {
```
Comment (giladgray) [inline packages/core/src/components/tabs/tabs.tsx]: when finished, should be able to delete this function and use `Utils.isElementType(child, Tab)` directly.

**Comment by giladgray** [comment]
also @benhjames is it possible to increase your build parallelization so tests will run? https://circleci.com/gh/benhjames/blueprint/18

File: packages/core/src/common/utils.ts (hunk 2 above)
Comment (adidahiya) [inline packages/core/src/common/utils.ts]: nit: rename to `isElementOfType`

**Comment by benhjames** [comment]
<h3>Rename isElementType => isElementOfType, improve typings</h3>

Preview: <strong><a href='https://25-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://25-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://25-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by benhjames** [comment]
Great feedback - thanks! :+1:

Not sure there's anything I can do about test parallelisation - it's specified in config to be 7 and I don't really want to pay for extra containers...!

https://github.com/palantir/blueprint/blob/ad3306e2a1adebbfd44881e189ee8aad7e32f6a3/.circleci/config.yml#L79

**Comment by benhjames** [comment]
<h3>Linting fixes</h3>

Preview: <strong><a href='https://31-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://31-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://31-120608509-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by adidahiya** [comment]
Thanks @benhjames, we'll merge this and deal with any issues that arise on develop. I'll look into reducing parallelism to make these PRs easier.

**Comment by phpnode** [comment]
We ran into this issue after upgrading to 2.0.1, we were using HMR in v1.x.x without issues, so it does seem that there's something wrong with the workaround. It also seems a bit inefficient to create a react element just to check the type. We've solved this problem for now by turning off HMR in our application, but it would be interesting to see what the root cause is.

**Comment by giladgray** [comment]
@phpnode if you're having issues then please file a new one rather than commenting on closed PRs. I'm surprised to hear this, though, given that everyone else who used HMR experienced issues _before_ the fix.

**Comment by mmoutenot** [comment]
Issue still active in table. Will create new issue and MR

**Comment by ajones** [comment]
@mmoutenot can you provide a link to your MR. This issue is really causing us a headache.
Thanks!

**Comment by mmoutenot** [comment]
@ajones Ah yes, been travelling. My teammate and I will push today.
