### PR TITLE
[Table] Improve shift-select behavior

### LINKED ISSUE #823: Shift selection mode for table regions
This would mitigate #505 because you could make one selection, scroll over to the end of your range, and then make another selection in the <kbd>Shift</kbd> mode of interaction.

Part of #298, but I'd like to track it separately.

### LINKED ISSUE #1249: [Table] Weird multi-region-select behavior
### Bug report

- __Package version(s)__: Latest
- __Browser and OS versions__: Chrome, OSX

#### Steps to reproduce

1. Select some regions holding down command
1. Select a column or row header to select that as well, still holding down command

#### Actual behavior
The new region is added to the selection, but other regions... do strange things. See attached screenshot

#### Expected behavior

The new region is added to the selection, and nothing in any of the other regions changes 

jun-19-2017 15-19-33

### LINKED ISSUE #1285: [Table] Focus cell moves when shift selection
focus-expand

### LINKED ISSUE #1323: allowMultipleSelection={false} doesn't seem to stop shift+select multiple
### Bug report

- __Package version(s)__:     "@blueprintjs/table": "^1.18.0",
- __Browser and OS versions__: mac chrome

#### Steps to reproduce
<Table
   {...defaultTablePropsAndSomeTableData}
              allowMultipleSelection={false}
            >

#### Actual behavior

Hitting shift allows for the selection of multiple rows

#### Expected behavior

Shouldn't be able to select multiple rows with shift-click

Here is a gif of the behavior. You can see in the side panel that the allowMultipleSelection prop has been set to false:
timing

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

Improve shift-selection behavior.
- 🐛 __FIXED__ `Table` expand-selection behavior now expands from the focused cell. #823 #298 #1285 #1080
- 🐛 __FIXED__ `Table` <kbd>Shift+Click</kbd> no longer expands the selection when `allowMultipleSelection=false`. #1323
- 🐛 __FIXED__ `Table` disjoint-selection behavior (no longer results in janky updates). #1249
- __CHANGED__ `Table` `menuElement` now selects-all `onMouseDown`, not `onClick` (for consistency with `Header`s).

#### Reviewers should focus on:

- The `returnEndOnly` flag feels unclean, but...it gets the job done.
- I put the expand-region logic in `FocusedCellUtils` to make it slightly easier to unit-test.
- Do the interactions feel correct?

#### Screenshot

_SINGLE SELECTION:_

_DISJOINT SELECTIONS:_

### CODE REVIEW

**Comment by llorca** [comment]
Single selection GIF looks amazing! Disjoint selections seems a bit more funky but still reasonable, can't wait to check out the build preview

File: packages/table/src/common/internal/focusedCellUtils.ts [hunk 1]
```diff
@@ -26,13 +27,72 @@ export function getInitialFocusedCell(
         // use the current focused cell from state
         return focusedCellFromState;
     } else if (selectedRegions.length > 0) {
-        // focus the top-left cell of the first selection
+        // focus the top-left cell of the last selection
```
Comment (cmslewis) [inline packages/table/src/common/internal/focusedCellUtils.ts]: note this change. focusing the _last_ selection is more consistent with other focused-cell behavior.

File: packages/table/src/common/internal/focusedCellUtils.ts [hunk 2]
```diff
@@ -26,13 +27,72 @@ export function getInitialFocusedCell(
...
         // focus the top-left cell of the table
         return { col: 0, row: 0, focusSelectionIndex: 0 };
     }
 }
+
+/**
+ * Returns a new cell-coordinates object that includes a focusSelectionIndex property.
+ * The returned object will have the proper IFocusedCellCoordinates type.
+ */
+export function toFullCoordinates(
```
Comment (cmslewis) [inline packages/table/src/common/internal/focusedCellUtils.ts]: @gscshoyru here's the helper I mentioned

File: packages/table/src/common/internal/focusedCellUtils.ts [hunk 3]
```diff
@@ -26,13 +27,72 @@ export function getInitialFocusedCell(
...
+function getExpandedRegionIndices(
+    focusedCell: IFocusedCellCoordinates,
+    newRegion: IRegion,
+    focusedCellDimension: "row" | "col",
+    regionDimension: "rows" | "cols",
+) {
+    const srcIndex = focusedCell[focusedCellDimension];
+    const [dstIndex, dstIndexEnd] = newRegion[regionDimension];
+
+    if (dstIndex !== dstIndexEnd) {
```
Comment (cmslewis) [inline packages/table/src/common/internal/focusedCellUtils.ts]: expect `newRegion` to be a single cell

File: packages/table/src/headers/columnHeader.tsx [hunk 4]
```diff
@@ -48,24 +48,20 @@ export class ColumnHeader extends React.Component<IColumnHeaderProps, {}> {
         loading: false,
     };
 
-    public shouldComponentUpdate(nextProps: IColumnHeaderProps) {
```
Comment (cmslewis) [inline packages/table/src/headers/columnHeader.tsx]: This logic lives in `header.tsx` now.

File: packages/table/src/headers/columnHeader.tsx [hunk 5]
```diff
@@ -87,14 +82,15 @@ export class ColumnHeader extends React.Component<IColumnHeaderProps, {}> {
                 handleSizeChanged={this.handleSizeChanged}
                 headerCellIsReorderablePropName={"isColumnReorderable"}
                 headerCellIsSelectedPropName={"isColumnSelected"}
+                indexEnd={indexEnd}
+                indexStart={indexStart}
```
Comment (cmslewis) [inline packages/table/src/headers/columnHeader.tsx]: @themadcreator made this name change just for you 👌

File: packages/table/src/headers/columnHeader.tsx [hunk 6]
```diff
@@ -48,24 +48,20 @@ export class ColumnHeader extends React.Component<IColumnHeaderProps, {}> {
...
-            maxColumnWidth,
+            minColumnWidth: minSize,
+            maxColumnWidth: maxSize,
             defaultColumnWidth,
 
             // from IColumnIndices
-            columnIndexStart,
-            columnIndexEnd,
+            columnIndexStart: indexStart,
+            columnIndexEnd: indexEnd,
```
Comment (cmslewis) [inline packages/table/src/headers/columnHeader.tsx]: using this syntactic trick everywhere now

File: packages/table/src/headers/columnHeader.tsx [hunk 7]
```diff
@@ -198,10 +194,4 @@ private wrapCells = (cells: Array<React.ReactElement<any>>) => {
     private toRegion = (index1: number, index2?: number) => {
         return Regions.column(index1, index2);
     }
-
-    private isSelectedRegionRelevant = (selectedRegion: IRegion) => {
```
Comment (cmslewis) [inline packages/table/src/headers/columnHeader.tsx]: no longer needed

File: packages/table/src/headers/header.tsx [hunk 8]
```diff
@@ -432,33 +456,3 @@ export class Header extends React.Component<IInternalHeaderProps, IHeaderState>
...
- * shouldComponentUpdate code at their level. To avoid writing the same code in two places, we
- * expose this utility for each higher-level component to leverage in their own respective
- * shouldComponentUpdate functions.
- *
- * (See: https://github.com/palantir/blueprint/issues/1214)
- *
- * @param props - the current props
- * @param nextProps - the next props
- */
-export function shouldHeaderComponentUpdate<T extends IHeaderProps>(
```
Comment (cmslewis) [inline packages/table/src/headers/header.tsx]: no longer needed, since this logic lives entirely in the `<Header>` now!

File: packages/table/src/headers/rowHeader.tsx [hunk 9]
```diff
@@ -175,12 +171,6 @@ export class RowHeader extends React.Component<IRowHeaderProps, {}> {
         // the `this` value is messed up for Regions.row, so we have to have a wrapper function here
         return Regions.row(index1, index2);
     }
-
-    private isSelectedRegionRelevant = (selectedRegion: IRegion) => {
```
Comment (cmslewis) [inline packages/table/src/headers/rowHeader.tsx]: woo woo less duplicate code

File: packages/table/src/interactions/reorderable.tsx [hunk 10]
```diff
@@ -39,8 +39,9 @@ export interface IReorderableProps {
 
     /**
      * An array containing the table's selection Regions.
+     * @default []
      */
-    selectedRegions: IRegion[];
+    selectedRegions?: IRegion[];
```
Comment (cmslewis) [inline packages/table/src/interactions/reorderable.tsx]: makes unit tests easier. no reason not to default this to `[]`

File: packages/table/src/interactions/selectable.tsx [hunk 11]
```diff
@@ -9,10 +9,11 @@ import { Utils as BlueprintUtils } from "@blueprintjs/core";
 import * as PureRender from "pure-render-decorator";
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: refactored this whole file. see unit tests (in `selectableTests.tsx`) for a description of the behavior.

File: packages/table/src/interactions/selectable.tsx [hunk 12]
```diff
@@ -21,8 +22,14 @@ export interface ISelectableProps {
      * If `false`, only a single region of a single column/row/cell may be
      * selected at one time. Using `ctrl` or `meta` key will have no effect,
      * and a mouse drag will select the current column/row/cell only.
+     * @default false
      */
-    allowMultipleSelection: boolean;
+    allowMultipleSelection?: boolean;
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: Again, no reason we can't make this optional and default it to `false`

File: packages/table/src/interactions/selectable.tsx [hunk 13]
```diff
@@ -84,11 +92,17 @@ export interface IDragSelectableProps extends ISelectableProps {
      * coordinate data representing a drag. If no valid region can be found,
      * `null` may be returned.
      */
-    locateDrag: (event: MouseEvent, coords: ICoordinateData) => IRegion;
+    locateDrag: (event: MouseEvent, coords: ICoordinateData, returnEndOnly?: boolean) => IRegion;
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: Kind of a weird parameter, but seemed necessary:
- If `returnEndOnly=false`, then `locateDrag` returns the region that stretches the activation cell to the most recent target cell.
- If `returnEndOnly=true`, then `locateDrag` returns the most recent target cell by itself, so we can join it with the `focusedCell` using our own logic.

File: packages/table/src/interactions/selectable.tsx [hunk 14]
```diff
@@ -110,142 +124,92 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
     }
 
     private handleActivate = (event: MouseEvent) => {
+        const { locateClick, selectedRegions, selectedRegionTransform } = this.props;
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: moving to this approach for consistency with other table code (and for shorter line length in some cases)

File: packages/table/src/interactions/selectable.tsx [hunk 15]
```diff
@@ -110,142 +124,92 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
-            const fullFocusCellCoordinates: IFocusedCellCoordinates = {
-                col: focusCellCoordinates.col,
-                focusSelectionIndex: null,
-                row: focusCellCoordinates.row,
-            };
-            this.props.onFocus(fullFocusCellCoordinates);
+        const matchesExistingSelection = foundIndex !== -1;
 
+        if (matchesExistingSelection) {
+            this.handleUpdateExistingSelection(foundIndex, event);
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: this whole function is much easier to read now IMO. i basically just pulled the logic out into clearly, consistently named helpers

File: packages/table/src/interactions/selectable.tsx [hunk 16]
```diff
@@ -110,142 +124,92 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
+            locateDrag,
+            selectedRegions,
+            selectedRegionTransform,
+        } = this.props;
+
+        let region = allowMultipleSelection
+            ? locateDrag(event, coords, /* returnEndOnly? */ this.didExpandSelectionOnActivate)
+            : locateClick(event);
+
+        if (!Regions.isValid(region)) {
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: every weird logic path in these functions is now unit-tested. woo.

File: packages/table/src/interactions/selectable.tsx [hunk 17]
```diff
@@ -110,142 +124,92 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
 
-        if (!this.props.allowMultipleSelection) {
-            // have the focused cell follow the selected region
-            const mostRecentRegion = nextSelectedRegions[nextSelectedRegions.length - 1];
-            const focusCellCoordinates = Regions.getFocusCellCoordinatesFromRegion(mostRecentRegion);
-            const fullFocusCellCoordinates: IFocusedCellCoordinates = {
-                col: focusCellCoordinates.col,
-                focusSelectionIndex: nextSelectedRegions.length - 1,
-                row: focusCellCoordinates.row,
-            };
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: This pattern (line 193-197) is super common. This is what `FocusedCellUtils.toFullCoordinates` is for (used within the new `this. invokeOnFocusCallbackForRegion helper`.

File: packages/table/src/interactions/selectable.tsx [hunk 18]
```diff
@@ -110,142 +124,92 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
     }
 
-    private handleDragEnd = (event: MouseEvent, coords: ICoordinateData) => {
-        const nextSelectedRegions = this.getDragSelectedRegions(event, coords);
-        if (nextSelectedRegions == null) {
-            return;
-        }
-        this.maybeInvokeSelectionCallback(nextSelectedRegions);
-        BlueprintUtils.safeInvoke(this.props.onSelectionEnd, nextSelectedRegions);
+    private handleDragEnd = () => {
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: We were doing duplicate work on `dragEnd` and on `click` that was already done on `mousedown` and/or on `mousemove`.

File: packages/table/src/interactions/selectable.tsx [hunk 19]
```diff
@@ -110,142 +124,92 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
-            BlueprintUtils.safeInvoke(this.props.onSelectionEnd, []);
-            return false;
-        }
-
-        if (this.props.selectedRegionTransform != null) {
-            region = this.props.selectedRegionTransform(region, event);
-        }
+    private handleClick = () => {
+        this.finishInteraction();
+    }
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: note that both are simple now. thought about passing `this.finishInteraction` directly in [`this.getDraggableProps`](https://github.com/palantir/blueprint/pull/1524/files#diff-6f85c4f864b85874d8deec61bac44cb0R117), but it felt clearer to have separate `handleDragEnd` and `handleClick` functions.

File: packages/table/src/interactions/selectable.tsx [hunk 20]
```diff
@@ -110,142 +124,92 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
-            nextSelectedRegions = [region];
-        }
+    // Boolean checks
+    // ==============
 
-        this.maybeInvokeSelectionCallback(nextSelectedRegions);
-        BlueprintUtils.safeInvoke(this.props.onSelectionEnd, nextSelectedRegions);
-        this.finishInteraction();
-        return false;
+    private shouldExpandSelection = (event: MouseEvent) => {
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: Added these single-use helpers just to clarify the intent of these checks.

File: packages/table/src/interactions/selectable.tsx [hunk 21]
```diff
@@ -256,71 +220,101 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
+    private handleUpdateExistingSelection = (selectedRegionIndex: number, event: MouseEvent) => {
+        const { onSelection, selectedRegions } = this.props;
 
-        if (!Regions.isValid(region)) {
-            return undefined;
+        if (DragEvents.isAdditive(event)) {
+            // remove just the clicked region, leaving other selected regions in place
+            const nextSelectedRegions = selectedRegions.slice();
+            nextSelectedRegions.splice(selectedRegionIndex, 1);
+            onSelection(nextSelectedRegions);
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: whoops, should use `this.maybeInvokeSelectionCallback` here and elsewhere! will add more unit tests.

File: packages/table/src/interactions/selectable.tsx [hunk 22]
```diff
@@ -256,71 +220,101 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
+    private expandSelectedRegions(regions: IRegion[], region: IRegion, focusedCell?: IFocusedCellCoordinates) {
+        if (regions.length === 0) {
+            return [region];
+        } else if (focusedCell != null) {
+            const expandedRegion = FocusedCellUtils.expandFocusedRegion(focusedCell, region);
+            return Regions.update(regions, expandedRegion);
+        } else {
+            const expandedRegion = Regions.expandRegion(regions[regions.length - 1], region);
+            return Regions.update(regions, expandedRegion);
+        }
```
Comment (cmslewis) [inline packages/table/src/interactions/selectable.tsx]: Pulled all the expand-region logic out into more easily unit-testable helper functions.

File: packages/table/src/table.tsx [hunk 23]
```diff
@@ -843,7 +843,7 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
             <div
                 className={classes}
                 ref={refHandler}
-                onClick={this.selectAll}
+                onMouseDown={this.selectAll}
```
Comment (cmslewis) [inline packages/table/src/table.tsx]: changed for interaction consistency with other selection modes // CC @llorca

File: packages/table/src/table.tsx [hunk 24]
```diff
@@ -870,19 +870,18 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
 
         // move the focus cell to the top left
-        const newFocusedCellCoordinates = Regions.getFocusCellCoordinatesFromRegion(Regions.table());
-        const fullFocusCellCoordinates: IFocusedCellCoordinates = {
-            col: newFocusedCellCoordinates.col,
-            focusSelectionIndex: 0,
-            row: newFocusedCellCoordinates.row,
-        };
-        this.handleFocus(fullFocusCellCoordinates);
+        if (enableFocus) {
```
Comment (cmslewis) [inline packages/table/src/table.tsx]: whoops, don't need this check, because it's handled in `handleFocus`. will undo.

File: packages/table/src/table.tsx [hunk 25]
```diff
@@ -1086,9 +1088,6 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         const numFrozenColumns = this.getNumFrozenColumnsClamped();
         const numFrozenRows = this.getNumFrozenRowsClamped();
 
-        const { selectedRegions, viewportRect/*, verticalGuides, horizontalGuides*/ } = this.state;
-
-        // const style = grid.getRect().sizeStyle();
```
Comment (cmslewis) [inline packages/table/src/table.tsx]: deleted commented code

File: packages/table/src/tableBody.tsx [hunk 26]
```diff
@@ -89,6 +89,7 @@ export interface ITableBodyProps extends ISelectableProps, IRowIndices, IColumnI
  * `ITableBodyProps` since those are only used when a context menu is launched.
  */
 const UPDATE_PROPS_KEYS: Array<keyof ITableBodyProps> = [
+    "focusedCell",
```
Comment (cmslewis) [inline packages/table/src/tableBody.tsx]: oops, was missing before

File: packages/table/src/tableBody.tsx [hunk 27]
```diff
@@ -315,10 +318,12 @@ export class TableBody extends React.Component<ITableBodyProps, {}> {
         return Regions.cell(this.activationCell.row, this.activationCell.col);
     }
 
-    private locateDrag = (_event: MouseEvent, coords: ICoordinateData) => {
+    private locateDrag = (_event: MouseEvent, coords: ICoordinateData, returnEndOnly = false) => {
```
Comment (cmslewis) [inline packages/table/src/tableBody.tsx]: here's that weird param again

File: packages/table/test/common/internal/focusCellUtilsTests.ts [hunk 28]
```diff
@@ -1,87 +0,0 @@
-/**
```
Comment (cmslewis) [inline packages/table/test/common/internal/focusCellUtilsTests.ts]: renamed this file to `focusedCellUtilsTests.ts`, in keeping with my goal to use "focused cell" instead of "focus cell," everywhere (and also because the tested module is `FocusedCellUtils` anyway).

File: packages/table/test/common/internal/focusedCellUtilsTests.ts [hunk 29]
```diff
@@ -0,0 +1,222 @@
...
+            };
+            expect(focusedCell).to.deep.equal(expectedFocusedCell);
+        });
+
+        function getFocusedCell(row: number, col: number, focusSelectionIndex: number = 0): IFocusedCellCoordinates {
+            return { row, col, focusSelectionIndex };
+        }
+    });
+
+    describe("expandFocusedRegion", () => {
```
Comment (cmslewis) [inline packages/table/test/common/internal/focusedCellUtilsTests.ts]: added tests for the new helper

File: packages/table/test/common/internal/focusedCellUtilsTests.ts [hunk 30]
```diff
@@ -0,0 +1,222 @@
...
+        function checkEqual(result: IRegion, expected: IRegion) {
+            expect(result).to.deep.equal(expected);
+        }
+
+        function toCellCoords(row: number, col: number): IFocusedCellCoordinates {
+            return { row, col, focusSelectionIndex: 0 };
+        }
+    });
+
+    describe("toFullCoordinates", () => {
```
Comment (cmslewis) [inline packages/table/test/common/internal/focusedCellUtilsTests.ts]: and same for this helper

File: packages/table/test/harness.ts [hunk 31]
```diff
@@ -91,10 +108,24 @@ export class ElementHarness {
     }
 
     public mouse(eventType: MouseEventType = "click",
-                 offsetX = 0,
+                 offsetXOrOptions: number | IHarnessMouseOptions = 0, // TODO: Change all tests to the object API
```
Comment (cmslewis) [inline packages/table/test/harness.ts]: I prefer passing an object over passing a bunch of unnamed params.

File: packages/table/test/tableTests.tsx [hunk 32]
```diff
@@ -268,7 +268,7 @@ describe("<Table>", () => {
 
         function selectFullTable(table: ReactWrapper<any, {}>) {
             const menu = table.find(`.${Classes.TABLE_QUADRANT_MAIN} .${Classes.TABLE_MENU}`);
-            menu.simulate("click");
+            menu.simulate("mousedown").simulate("mouseup");
```
Comment (cmslewis) [inline packages/table/test/tableTests.tsx]: had to change this to fix tests after making the `onClick` => `onMouseDown` change for the top-left menu element

File: packages/table/test/selectableTests.tsx [hunk 33]
```diff
@@ -186,6 +730,31 @@ describe("DragSelectable", () => {
         expect(onFocus.args[0][0]).to.deep.equal({col: 2, row: 0, focusSelectionIndex: 0});
     });
 
+    it("does not expand the selection on shift+click if allowMultipleSelection=false", () => {
```
Comment (cmslewis) [inline packages/table/test/selectableTests.tsx]: ah, will delete all these commented tests

File: packages/table/test/selectableTests.tsx [hunk 34]
```diff
@@ -7,12 +7,27 @@
```
Comment (cmslewis) [inline packages/table/test/selectableTests.tsx]: totally rewrote the `DragSelectable` tests

**Comment by cmslewis** [comment]
@llorca @gscshoyru @tgreenwatts the preview is up

**Comment by tgreenwatts** [comment]
Note: Excel if you select the full table, the focus cell stays in the same spot, whereas ours moves to upper left corner

**Comment by cmslewis** [comment]
@tgreenwatts thanks for your thorough eye. ;)

File: packages/table/src/common/internal/focusedCellUtils.ts (hunk 1 above)
Comment (gscshoyru) [reply packages/table/src/common/internal/focusedCellUtils.ts]: Huh, ok. Either way is fine as long as we're consistent.

File: packages/table/src/common/internal/focusedCellUtils.ts [hunk 35]
```diff
@@ -26,13 +27,72 @@ export function getInitialFocusedCell(
...
+}
+
+function getExpandedRegionIndices(
+    focusedCell: IFocusedCellCoordinates,
+    newRegion: IRegion,
+    focusedCellDimension: "row" | "col",
+    regionDimension: "rows" | "cols",
+) {
+    const srcIndex = focusedCell[focusedCellDimension];
+    const [dstIndex, dstIndexEnd] = newRegion[regionDimension];
```
Comment (gscshoyru) [inline packages/table/src/common/internal/focusedCellUtils.ts]: Can you spell these out? dst is... destination?

File: packages/table/src/common/internal/focusedCellUtils.ts [hunk 36]
```diff
@@ -26,13 +27,72 @@ export function getInitialFocusedCell(
...
+
+    if (dstIndex !== dstIndexEnd) {
+        if (regionDimension === "rows") {
+            throw new Error(Errors.TABLE_EXPAND_FOCUSED_REGION_MULTI_ROW_REGION);
+        } else if (regionDimension === "cols") {
+            throw new Error(Errors.TABLE_EXPAND_FOCUSED_REGION_MULTI_COLUMN_REGION);
+        }
+    }
+
+    return srcIndex <= dstIndex
```
Comment (gscshoyru) [inline packages/table/src/common/internal/focusedCellUtils.ts]: Oh, yeah, 'cause you have src. Ok. I guess dst is probably fine? Still slight preference for spelling both of them out, though.

**Comment by cmslewis** [comment]
@tgreenwatts fixed

File: packages/table/src/headers/columnHeader.tsx (hunk 6 above)
Comment (gscshoyru) [reply packages/table/src/headers/columnHeader.tsx]: I love destructuring. So much.

File: packages/table/src/common/internal/focusedCellUtils.ts (hunk 36 above)
Comment (cmslewis) [reply packages/table/src/common/internal/focusedCellUtils.ts]: Opted for the equal-length variable names for the aesthetic of it, but I'll spell them out.

**Comment by cmslewis** [comment]
Did another pass on my own. Going to merge.
