### PR TITLE
Don't clear TagInput inputValue state if controlled

### LINKED ISSUE #3134: Multi select mistakenly clears selection when no tag is added
#### Environment

- Blueprint 3.8.0
- MacOS. Chrome 69

#### Steps to reproduce

1. Open MultiSelect docs
2. Enter gibberish so that nothing matches

image

3. Press enter

#### Actual behavior

Gibberish is no longer shown but the gibberish filter still applies.

image

#### Expected behavior

Nothing happens when pressing enter, and the gibberish is still shown.

image

#### Possible solution

A few, though I'm not sure which is most in line with the rest of the Blueprint API:

1. Don't automatically clear the `inputValue` in `TagInput.addTags` if `inputValue` is controlled
2. Add a prop to `TagInput` that controls whether the value is auto cleared
3. In `MultiSelect`, pass an `onAdd` function to the `TagInput` component that always returns false, because we don't want it to auto clear the input.

### PR DESCRIPTION
**Pull request by ericjeney**
#### Changes proposed in this pull request:

This change modifies `TagInput` to not clear the value displayed in the `input` field when adding tags if the consumer passes in their own `inputValue` prop. Previously, adding tags would clear this field, which resulted in confusing behavior in `MultiSelect`, as described in the issue. This seems philosophically correct: If the consumer specifies an explicit value for `inputValue`, it should never be overridden in `TagInput`'s state.

### CODE REVIEW

File: packages/core/src/components/tag-input/tagInput.tsx [hunk 1]
```diff
@@ -184,14 +184,13 @@ export class TagInput extends AbstractPureComponent<ITagInputProps, ITagInputSta
         addOnBlur: false,
         addOnPaste: true,
         inputProps: {},
-        inputValue: "",
```
Comment (giladgray) [inline packages/core/src/components/tag-input/tagInput.tsx]: i prefer one fully type-safe `defaultProps` over two not-strictly-typesafe boolean coercions `this.props.inputValue || ""`

File: packages/core/src/components/tag-input/tagInput.tsx [hunk 2]
```diff
@@ -261,15 +260,16 @@ export class TagInput extends AbstractPureComponent<ITagInputProps, ITagInputSta
     }
 
     private addTags = (value: string) => {
-        const { onAdd, onChange, values } = this.props;
+        const { inputValue, onAdd, onChange, values } = this.props;
         const newValues = this.getValues(value);
-        let shouldClearInput = Utils.safeInvoke(onAdd, newValues);
+        let shouldClearInput = inputValue === undefined;
+        shouldClearInput = Utils.safeInvoke(onAdd, newValues) !== false && shouldClearInput;
```
Comment (giladgray) [inline packages/core/src/components/tag-input/tagInput.tsx]: collapse these two to one line?
`let shouldClearInput = Utils.safeInvoke(onAdd, newValues) !== false && inputValue === undefined;`

File: packages/core/src/components/tag-input/tagInput.tsx (hunk 1 above)
Comment (ericjeney) [reply packages/core/src/components/tag-input/tagInput.tsx]: If I switch this back, I won't be able to explicitly check in `addTags` if `inputValue` is controlled, and will instead have to check if `inputValue === ""`. I think that works in this case, but is less explicit. Would you still prefer me to set the `inputValue` default here?

Comment (giladgray) [reply packages/core/src/components/tag-input/tagInput.tsx]: oh hmm that's a thing. in other components, i've checked `=== X.defaultProps.Y` to great success.

File: packages/core/src/components/tag-input/tagInput.tsx [hunk 3]
```diff
@@ -262,8 +263,8 @@ export class TagInput extends AbstractPureComponent<ITagInputProps, ITagInputSta
     private addTags = (value: string) => {
         const { inputValue, onAdd, onChange, values } = this.props;
         const newValues = this.getValues(value);
-        let shouldClearInput = inputValue === undefined;
-        shouldClearInput = Utils.safeInvoke(onAdd, newValues) !== false && shouldClearInput;
+        let shouldClearInput =
+            Utils.safeInvoke(onAdd, newValues) !== false && inputValue === TagInput.defaultProps.inputValue;
```
Comment (giladgray) [inline packages/core/src/components/tag-input/tagInput.tsx]: ok on second thought, this doesn't work for strings:
```js
{} === {}
> false

[] === []
> false

"" === ""
> true // uh oh - controlled empty value looks like uncontrolled
```

i think we do have to remove the `defaultProps` entry and compare against undefined like you had before

File: packages/core/test/tag-input/tagInputTests.tsx [hunk 4]
```diff
@@ -356,6 +362,13 @@ describe("<TagInput>", () => {
             pressEnterInInput(wrapper, NEW_VALUE);
             assert.strictEqual(wrapper.state().inputValue, "");
         });
+
+        it("does not clear the input if the input is controlled", () => {
+            const onChange = sinon.stub();
+            const wrapper = shallow(<TagInput onChange={onChange} values={VALUES} inputValue={NEW_VALUE} />);
```
Comment (giladgray) [inline packages/core/test/tag-input/tagInputTests.tsx]: i'll bet if you did `inputValue=""` (controlled empty value) this test would fail.

Comment (ericjeney) [reply packages/core/test/tag-input/tagInputTests.tsx]: I don't think it would fail in this particular case, but I in general agree that we should be more explicit in checking if this prop is controlled.
