### PR TITLE
[core] fix(NumericInput): disabled prop prevents button interactions

### LINKED ISSUE #4213: NumericInput fill prop doesn't work
discovered while testing https://github.com/palantir/blueprint/pull/4211

#### Environment

- __Package version(s)__: develop & 3.29.0
- __Operating System__: macOS
- __Browser name and version__: Firefox

#### Steps to reproduce

1. Enable fill option in NumericInput docs

#### Actual behavior

image

#### Expected behavior

control group should be full width

### PR DESCRIPTION
**Pull request by ejose19**
#### Fixes #4213

Also fixes a bug where disabled element allowed interacting with the buttonHandlers (due to now using AnchorButton)

#### Checklist

- [X] Includes tests
- [X] Update documentation

#### Changes proposed in this pull request:

- Add missing class to sass to handle control-group fill
- Don't execute handleButtonClick if component is disabled

### CODE REVIEW

File: packages/core/src/components/forms/numericInput.tsx [hunk 1]
```diff
@@ -406,10 +406,12 @@ export class NumericInput extends AbstractPureComponent2<HTMLInputProps & INumer
             // keydown is fired repeatedly when held so it's implicitly continuous
             onKeyDown: evt => {
                 if (Keys.isKeyboardClick(evt.keyCode)) {
+                    if (this.props.disabled) return;
```
Comment (adidahiya) [inline packages/core/src/components/forms/numericInput.tsx]: I am surprised we don't have a lint rule for this... I swear we used to... please use `{ }` braces for all if statements.

Comment (adidahiya) [reply packages/core/src/components/forms/numericInput.tsx]: also I think this check should go outside the `if (Keys.isKeyboardClick)` statement... or just be merged into the same conditional

File: packages/core/test/controls/numericInputTests.tsx [hunk 2]
```diff
@@ -1015,6 +1016,34 @@ describe("<NumericInput>", () => {
...
+            const decrementButton = component.find(AnchorButton).last();
+            decrementButton.simulate("mousedown");
+            decrementButton.simulate("mousedown", { altKey: true });
+            decrementButton.simulate("keyDown", SPACE_KEYSTROKE);
+            decrementButton.simulate("keyDown", { ...SPACE_KEYSTROKE, altKey: true });
+
+            expect(handleButtonClickSpy.notCalled).to.be.true;
+        });
+
+        it("must set fill class on controlGroup element when fill is enabled", () => {
```
Comment (adidahiya) [inline packages/core/test/controls/numericInputTests.tsx]: we don't need this test, it's tautological and doesn't add much value

File: packages/core/src/components/forms/_control-group.scss [hunk 3]
```diff
@@ -229,6 +229,9 @@ Styleguide control-group
 
   Styleguide control-group-fill
   */
+  &.#{$ns}-fill {
```
Comment (adidahiya) [inline packages/core/src/components/forms/_control-group.scss]: while looking into this bug I found some strange code which I don't think should exist. we have special logic in the control group example to make the "fill" option work on the page... this logic is outside the Blueprint API so it's misleading for developers testing the component. please remove these lines in this PR: https://github.com/palantir/blueprint/blob/842b2bb43f43ad11b71cdec86fff410d1a14474c/packages/docs-app/src/examples/core-examples/controlGroupExample.tsx#L46-L49

**Review by adidahiya — CHANGES_REQUESTED** [review]
thanks for the contribution. in the future I would appreciate separate PRs for unrelated issues/features.

**Comment by ejose19** [comment]
@adidahiya Sure, adjusted files. Will take your notes in consideration for next PRs

**Review by adidahiya — APPROVED** [review]

**Comment by ejose19** [comment]
@adidahiya Is there any estimate where all the NumericInput changes will be released on npm?

**Comment by adidahiya** [comment]
@ejose19 this was released. you can see which releases a commit is included in here:

image

**Comment by ejose19** [comment]
@adidahiya If it's not much trouble, can you tell me where do I see exactly that? I checked all "tabs" on current page but I can't find that.

**Comment by ejose19** [comment]
@adidahiya Thanks, didn't know about that feature.
