### PR TITLE
[Table] Deselect cells on cmd+click only

### LINKED ISSUE #1073: Remove table selection toggle behavior
#### Steps to reproduce

1. http://blueprintjs.com/docs/#table-js.sorting
1. Click on a cell
1. Click on the same cell again

#### Actual behavior

Toggles selection. (See #1266 as well for a variant of this undesired behavior.)

#### Expected behavior

Preserves selection.

The standards for selection is `click`, deselection `cmd+click`, range selection `shift+click`, multi selection `cmd+click`, I'm surely missing more. The default behavior of `Table` should respect those standards

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

A morning surprise for @llorca.

- 🔄 __CHANGED__ `Table` no longer toggles selection on click; now, you must `cmd` + click to deselect cells, columns, or rows.
- 🐛 __FIXED__ `Table` `ctrl` + click now works on Windows again.

#### Reviewers should focus on:

- There was an edge case for rows due to the fact that selected rows become reorderable, meaning the `DragReorderable` component would swallow all clicks (even `cmd` + clicks meant for deselecting). The fix required a refactor of the `disabled?` prop to optionally be a function that accepts the current `MouseEvent`, so it can check if the `metaKey` is pressed.
- This isn't an issue for columns, because the reorder handle is the only trigger for reordering; the rest of the column header cell is managed by the `DragSelectable` layer.
- This isn't an issue for body cells either, because reordering isn't even a thing there.
- You can still start new drag-selections from an already-selected cell. 🎉

### CODE REVIEW

File: packages/table/src/headers/header.tsx [hunk 1]
```diff
@@ -435,7 +440,30 @@ export class Header extends React.Component<IInternalHeaderProps, IHeaderState>
         this.setState({ hasSelectionEnded: true });
     };
 
-    private isEntireCellTargetReorderable = (isSelected: boolean) => {
+    private isDragSelectableDisabled = (event: MouseEvent) => {
+        if (event.metaKey) {
+            // if the meta key is pressed, we want to forcefully ignore reordering
+            // interactions and prioritize drag-selection interactions (e.g. to make
+            // it possible to deselect a row).
```
Comment (themadcreator) [inline packages/table/src/headers/header.tsx]: i don't think `meta` is the ideal key here for all platforms. `meta` means `cmd` on mac and `windows-key` on windows. typically i use what the hotkeys code calls `mod` which is `cmd` on mac and `ctrl` on windows. i think the `windows-key` accesses OS resources like the start menu so it's not usually used in a key combo.

File: packages/table/src/tableBody.tsx [hunk 2]
```diff
@@ -85,6 +85,7 @@ export class TableBody extends React.Component<ITableBodyProps, {}> {
                 onFocus={this.props.onFocus}
                 onSelection={this.props.onSelection}
                 onSelectionEnd={this.handleSelectionEnd}
+                requireMetaKeyToDeselect={true}
```
Comment (themadcreator) [inline packages/table/src/tableBody.tsx]: non-configurable? why even have a prop?

Comment (cmslewis) [reply packages/table/src/tableBody.tsx]: Because I added it at the beginning of this work. And then realized by the end of it that I didn't need it to be configurable. Will remove.

File: packages/table/src/headers/header.tsx [hunk 3]
```diff
@@ -224,23 +224,19 @@ const SHALLOW_COMPARE_PROP_KEYS_BLACKLIST: Array<keyof IInternalHeaderProps> = [
 const RESET_CELL_KEYS_BLACKLIST: Array<keyof IInternalHeaderProps> = ["indexEnd", "indexStart"];
 
 export class Header extends React.Component<IInternalHeaderProps, IHeaderState> {
-    public state: IHeaderState = {
-        hasSelectionEnded: false,
-    };
+    public state: IHeaderState;
```
Comment (giladgray) [inline packages/table/src/headers/header.tsx]: remove this if defining in constructor.

File: packages/table/src/headers/header.tsx [hunk 4]
```diff
@@ -224,23 +224,19 @@ const SHALLOW_COMPARE_PROP_KEYS_BLACKLIST: Array<keyof IInternalHeaderProps> = [
...
-    public componentDidMount() {
-        if (this.props.selectedRegions != null && this.props.selectedRegions.length > 0) {
-            // we already have a selection defined, so we'll want to enable reordering interactions
-            // right away if other criteria are satisfied too.
-            this.setState({ hasSelectionEnded: true });
-        }
+        // a selection is already defined, so enable reordering interactions
+        // right away if other criteria are satisfied too.
+        this.state = {
+            hasSelectionEnded: props.selectedRegions != null && props.selectedRegions.length > 0,
```
Comment (giladgray) [inline packages/table/src/headers/header.tsx]: does this logic need to appear in `componentWillReceiveProps ` too?

File: packages/table/src/headers/header.tsx (hunk 1 above)
Comment (giladgray) [reply packages/table/src/headers/header.tsx]: maybe holding _any_ modifier key should disable the drag?

File: packages/table/src/interactions/selectable.tsx [hunk 5]
```diff
@@ -93,13 +93,20 @@ export interface IDragSelectableProps extends ISelectableProps {
      * `null` may be returned.
      */
     locateDrag: (event: MouseEvent, coords: ICoordinateData, returnEndOnly?: boolean) => IRegion;
+
+    /**
+     * Whether the meta key should be pressed to enable deselection on click.
+     * @default false
+     */
+    requireMetaKeyToDeselect?: boolean;
```
[the remark this answers is not in the document]
Comment (giladgray) [reply packages/table/src/interactions/selectable.tsx]: yes please

File: packages/table/src/headers/header.tsx (hunk 1 above)
Comment (themadcreator) [reply packages/table/src/headers/header.tsx]: seems like this would likely conflict with other key combos

File: packages/table/src/headers/header.tsx (hunk 4 above)
Comment (cmslewis) [reply packages/table/src/headers/header.tsx]: Yep, already does.

File: packages/table/src/headers/header.tsx (hunk 1 above)
Comment (cmslewis) [reply packages/table/src/headers/header.tsx]: Fixed by using `DragEvents.isAdditive(event)`

**Comment by cmslewis** [comment]
@themadcreator @giladgray @adidahiya @gscshoyru 

The situation:

- On non-MAC, `CTRL + Click` _should_ add disjoint selections.
- On Mac, `CMD + Click` _should_ add disjoint selections.
- On Mac, `CTRL + Click` triggers the context menu and _shouldn't_ add disjoint selections.
 
I tried using `Hotkeys` in the `DragSelectable` component so that I could leverage its platform detection capabilities, but given that a click is involved, I would have to add some awkward flag-toggling callbacks like:
```tsx
<Hotkey
    label="???"
    combo="mod"
    onKeyDown={() => (this.isModKeyPressed = true)}
    onKeyUp={() => (this.isModKeyPressed = false)}
/>
```

This leaves some problems:
- There's a click involved, so using a `Hotkey` feels forced.
- The `Hotkey` `label` is meaningless.
- I still need to know the platform somehow: if I'm on a Mac, `CTRL + click` requires special handling, so I need some way to write `if (isLeftClick && event.ctrlKey && isMac())`.

So I need some kind of platform detection. We're already doing this via the `isMac` helper in `hotkeyParser.ts` in __core__, but I don't particularly want to export that function for __table__ to reuse, because that would also enable any other Blueprint consumer to use it (and it ain't the most rigorous function in the world).

For now, I've copied the `isMac` code into __table__, written an `isModKeyPressed` helper too, and written/copied tests for each. Everything now works as expected on both Mac and Windows.

__^ Thoughts on this approach?__ I'd rather not copy code between packages, but nothing else seemed workable.

File: packages/table/test/common/internal/platformUtilsTests.ts [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+        });
+    });
+
+    describe("isModKeyPressed", () => {
+        describe("on non-Mac platform", () => {
+            const PLATFORM = "Win32";
+
+            it("returns true if CTRL key pressed", () => {
+                const fakeEvent: any = { metaKey: false, ctrlKey: true };
+                expect(PlatformUtils.isModKeyPressed(fakeEvent, PLATFORM)).to.be.true;
```
Comment (cmslewis) [inline packages/table/test/common/internal/platformUtilsTests.ts]: You can't do `const isMac = sinon.stub(PlatformUtils, "isMac")` and expect the tests to pass, because under the hood, `isModKeyPressed` invokes `isMac` as its own free-floating function, not as a child of some `PlatformUtils` construct.

Thus, a `platformOverride` parameter.

Comment (adidahiya) [reply packages/table/test/common/internal/platformUtilsTests.ts]: that seems wrong... you should be able to stub the function at the module where it's exported (but not at some other module which re-exports the symbol). did you try stubbing it with a specific implementation (specify its return value)?

Comment (cmslewis) [reply packages/table/test/common/internal/platformUtilsTests.ts]: I'd love to be wrong, but it wouldn't work with my normal strategies. I tried stubbing the return value within the `describe`, but that actually stubs the `isMac` function before the `describe("isMac")` block runs, which causes all those tests to fail. When I did the stubbing in a `beforeEach`, it didn't work. Maybe I was just tired and missing something yesterday - I'll try some other stuff right now.

Comment (cmslewis) [reply packages/table/test/common/internal/platformUtilsTests.ts]: Yeah, this test fails when run on a Mac; `isModKeyPressed` still invokes the real `isMac` function in its same file:

```tsx
import * as PlatformUtils from "../../../src/common/internal/platformUtils";

it("returns true if CTRL key pressed", () => {
    const isMac = sinon.stub(PlatformUtils, "isMac").returns(false);
    const fakeEvent: any = { metaKey: false, ctrlKey: true };
    expect(PlatformUtils.isModKeyPressed(fakeEvent)).to.be.true;
    isMac.restore();
});
```

File: packages/table/src/headers/header.tsx [hunk 7]
```diff
@@ -224,35 +225,20 @@ const SHALLOW_COMPARE_PROP_KEYS_BLACKLIST: Array<keyof IInternalHeaderProps> = [
...
         this.batcher.cancelOutstandingCallback();
     }
 
     public componentWillReceiveProps(nextProps?: IInternalHeaderProps) {
-        if (nextProps.selectedRegions != null && nextProps.selectedRegions.length > 0) {
-            this.setState({ hasSelectionEnded: true });
-        } else {
-            this.setState({ hasSelectionEnded: false });
-        }
+        this.setState({ hasSelectionEnded: this.isSelectedRegionsControlledAndNonEmpty(nextProps) });
```
Comment (giladgray) [inline packages/table/src/headers/header.tsx]: ⚠️ this will always update the state when props change; was that your intention behind this change? or does it need to be gated with an `if` clause?

Comment (cmslewis) [reply packages/table/src/headers/header.tsx]: Yep, that's intended. For row headers, `hasSelectionEnded` needs to be `true` before reordering is allowed. When you pass in `selectedRegions` in a controlled fashion, we want the flag to be true from the get-go so that reordering is immediately enabled.

File: packages/table/test/common/internal/platformUtilsTests.ts (hunk 6 above)
Comment (cmslewis) [reply packages/table/test/common/internal/platformUtilsTests.ts]: How would I test the logic in the real `isMac` without a `platformOverride` param? I'd like to just stub `navigator.platform`, but you can't because it's not a function.

File: packages/table/src/headers/header.tsx (hunk 7 above)
Comment (cmslewis) [reply packages/table/src/headers/header.tsx]: Changed to `hasValidSelection`.

File: packages/table/src/headers/header.tsx [hunk 8]
```diff
@@ -406,7 +400,11 @@ export class Header extends React.Component<IInternalHeaderProps, IHeaderState>
         return this.props.fullRegionCardinality === RegionCardinality.FULL_COLUMNS;
     }
 
-    private wrapInDragReorderable(index: number, children: JSX.Element, disabled?: boolean) {
+    private wrapInDragReorderable(
+        index: number,
+        children: JSX.Element,
+        disabled: boolean | ((event: MouseEvent) => boolean) = false,
```
[the remark this answers is not in the document]
Comment (cmslewis) [reply packages/table/src/headers/header.tsx]: Actually this function is used twice: in one case, it falls back to the default `false` value, in the other, shown in this diff, the invoking function passes `this.isDragReorderableDisabled` directly.

For clarity, I'll remove the default in the first case and passed in the `false` value explicitly.

File: packages/table/src/interactions/selectable.tsx [hunk 9]
```diff
@@ -216,44 +225,48 @@ export class DragSelectable extends React.Component<IDragSelectableProps, {}> {
...
 
     private shouldIgnoreMouseDown(event: MouseEvent) {
-        const { ignoredSelectors = [] } = this.props;
+        const { disabled, ignoredSelectors = [] } = this.props;
         const element = event.target as HTMLElement;
 
         const isLeftClick = Utils.isLeftClick(event);
-        const isContextMenuTrigger = isLeftClick && event.ctrlKey;
+        const isContextMenuTrigger = isLeftClick && event.ctrlKey && PlatformUtils.isMac();
+        const isDisabled = CoreUtils.isFunction(disabled) ? CoreUtils.safeInvoke(disabled, event) : disabled;
```
[the remark this answers is not in the document]
Comment (cmslewis) [reply packages/table/src/interactions/selectable.tsx]: Added `CoreUtils.safeInvokeOrValue`. 👍

File: packages/table/src/common/internal/platformUtils.ts [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+    const platformActual = typeof navigator !== "undefined" ? navigator.platform : undefined;
+    const platform = platformOverride != null ? platformOverride : platformActual;
+    return platform == null ? false : /Mac|iPod|iPhone|iPad/.test(platform);
+}
+
+/**
+ * Returns `true` if (1) the platform is Mac and the keypress includes the `cmd`
+ * key, or (2) the platform is non-Mac and the keypress includes the `ctrl` key.
+ */
+export const isModKeyPressed = (event: KeyboardEvent, platformOverride?: string) => {
```
Comment (gscshoyru) [inline packages/table/src/common/internal/platformUtils.ts]: ...there's no way to do this via feature discovery, huh? Drat.

File: packages/table/src/headers/header.tsx [hunk 11]
```diff
@@ -427,15 +427,38 @@ export class Header extends React.Component<IInternalHeaderProps, IHeaderState>
...
 
     private handleDragSelectableSelectionEnd = () => {
         this.activationIndex = null; // not strictly required, but good practice
-        this.setState({ hasSelectionEnded: true });
+        this.setState({ hasValidSelection: true });
+    };
+
+    private isDragSelectableDisabled = (event: MouseEvent) => {
+        if (DragEvents.isAdditive(event)) {
+            // if the meta/crtl key was pressed, we want to forcefully ignore
```
Comment (gscshoyru) [inline packages/table/src/headers/header.tsx]: Nitpick: ctrl, not crtl :P
