### PR TITLE
MenuItem supports HTML props, remove submenu prop

### LINKED ISSUE #605: Normal HTML props not working on MenuItem
### Bug report

- __Package version(s)__: v1.7.0

#### Steps to reproduce

`<MenuItem onMouseEnter={...} />` doesn't work as expected

#### Current workaround
`<div class="pt-menu-item" onMouseEnter={...} />` manually

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- MenuItem supports all HTML props
  - ⚠️ add `labelElement` because `label` doesn't support JSX (just like `Switch` etc)
- 🔥  remove `submenu` prop: only one way to submenu
- improve MenuItem props docs
- pull MenuItem tests to separate file

### CODE REVIEW

File: packages/core/src/components/menu/menuItem.tsx [hunk 1]
```diff
@@ -22,10 +22,32 @@ export interface IMenuItemProps extends IActionProps, ILinkProps {
     /** Item text, required for usability. */
     text: string;
 
+    /**
+     * Children of this component will be rendered in a __submenu__ that appears when hovering or
+     * clicking on this menu item. You can instead pass an array of props objects to the `submenu` prop
```
[the remark this answers is not in the document]
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: oops

File: packages/core/src/components/menu/menuItem.tsx [hunk 2]
```diff
@@ -148,3 +193,13 @@ const SUBMENU_POPOVER_MODIFIERS: Popper.Modifiers = {
     offset: { offset: -5 },
     preventOverflow: { boundariesElement: "viewport", padding: 20 },
 };
+
+// props to ignore when disabled
+const DISABLED_PROPS: React.AnchorHTMLAttributes<HTMLAnchorElement> = {
```
[the remark this answers is not in the document]
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: what does this mean? where can i move this constant? it's defined outside the class so it'll actually be static, and used once in `render()`.

[the remark this answers is not in the document]
Comment (adidahiya) [reply packages/core/src/components/menu/menuItem.tsx]: I meant above the class

[the remark this answers is not in the document]
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: what i thought we were in the habit of putting statics at the bottom?

[the remark this answers is not in the document]
Comment (adidahiya) [reply packages/core/src/components/menu/menuItem.tsx]: feels weird for `const`, more acceptable for `function` since those get hoisted

[the remark this answers is not in the document]
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: hoisted? both feel precisely the same level of weird to me.

[the remark this answers is not in the document]
Comment (adidahiya) [reply packages/core/src/components/menu/menuItem.tsx]: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

File: packages/core/src/components/menu/menuItem.tsx [hunk 3]
```diff
@@ -22,10 +22,32 @@ export interface IMenuItemProps extends IActionProps, ILinkProps {
     /** Item text, required for usability. */
     text: string;
 
+    /**
+     * Children of this component will be rendered in a __submenu__ that appears when hovering or
+     * clicking on this menu item. You can instead pass an array of props objects to the `submenu` prop.
```
Comment (adidahiya) [inline packages/core/src/components/menu/menuItem.tsx]: I still don't understand this second sentence. Instead of what?

Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: `submenu` array instead of `children` elements. how can i clarify?

Comment (adidahiya) [reply packages/core/src/components/menu/menuItem.tsx]: Do you mean to say that a user can render a submenu with __either__ children or the `submenu` prop? (the "instead" wording works counter to this, it suggests that only one option works)

Why do we want to support that?

Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: yes that's what I mean to say. this has been supported forever.

remember when I asked about making `MenuItem` children into the content (`text`) of the item and relegating submenu to props only?

Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: 🔥  proposal: `submenu?: React.ReactNode; submenuProps?: IMenuItemProps[]`

Comment (adidahiya) [reply packages/core/src/components/menu/menuItem.tsx]: I'd rather not break the API here and only support one usage pattern for submenus

File: packages/core/src/components/menu/menuItem.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: `const` gets hoisted too: functions _and_ variables.

and it's used inside a function (not synchronously), so guaranteed to be defined.

File: packages/core/src/components/menu/menuItem.tsx (hunk 3 above)
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: > one usage pattern

but we already support two patterns, and have for a _very_ long time

> not break the API

removing one usage pattern would be an API break...

what should I do here?

File: packages/core/src/components/menu/menuItem.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: a cursory search _suggests_ no one is using the `submenu` prop, but hard to verify.

File: packages/core/src/components/menu/menuItem.tsx (hunk 3 above)
Comment (giladgray) [reply packages/core/src/components/menu/menuItem.tsx]: a cursory search _suggests_ no one is using the `submenu` prop, but hard to verify.

Comment (adidahiya) [reply packages/core/src/components/menu/menuItem.tsx]: ohh ok I thought this was adding new support. in that case I'd suggest removing the `submenu` prop while we can in 2.0

File: packages/core/test/menu/menuTests.tsx [hunk 4]
```diff
@@ -5,149 +5,10 @@
...
-        assert.lengthOf(submenu.props.children, 3);
-    });
-
-    it("submenu props appear as MenuItems in submenu", () => {
-        const items: IMenuItemProps[] = [
-            { icon: "align-left", text: "Align Left" },
-            { icon: "align-center", text: "Align Center" },
-            { icon: "align-right", text: "Align Right" },
-        ];
-        const wrapper = shallow(<MenuItem icon="align-left" text="Alignment" submenu={items} />);
```
Comment (giladgray) [inline packages/core/test/menu/menuTests.tsx]: deleted this test

File: packages/core/test/menu/menuTests.tsx [hunk 5]
```diff
@@ -5,149 +5,10 @@
...
-        const warnSpy = stub(console, "warn");
-        const wrapper = shallow(
-            <MenuItem icon="style" text="Style" submenu={[{ text: "foo" }]}>
-                <MenuItem text="one" />
-                <MenuItem text="two" />
-            </MenuItem>,
-        );
-        const submenu = findSubmenu(wrapper);
-        assert.lengthOf(submenu.props.children, 2);
-        assert.isTrue(warnSpy.alwaysCalledWith(MENU_WARN_CHILDREN_SUBMENU_MUTEX));
```
Comment (giladgray) [inline packages/core/test/menu/menuTests.tsx]: deleted this test
