### PR TITLE
[core] fix(Section): Section header should only render if title is provided

### LINKED ISSUE #6324: `Section` shows header even if `title` isn't provided
According to the docs, the header shouldn't be rendered if the `title` isn't provided.

#### Steps to reproduce

Create a `Section`, don't pass a `title` prop

#### Actual behavior

An empty header is rendered

#### Expected behavior

The header shouldn't be rendered

#### Possible solution

https://github.com/palantir/blueprint/pull/6321

### PR DESCRIPTION
**Pull request by pgoldberg**
#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Hide the header if there's no passed in `title` prop

#### Reviewers should focus on:

Maybe we should have a separate prop for this? It seems a bit strange that we'd just ignore `subtitle` and `rightElement` if there's no `title`...

#### Screenshot

image

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>remove now-unnecessary title null checks</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/16ea40e0-ca99-4c2b-bba4-d544aab648c4/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/16ea40e0-ca99-4c2b-bba4-d544aab648c4/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/16ea40e0-ca99-4c2b-bba4-d544aab648c4/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/16ea40e0-ca99-4c2b-bba4-d544aab648c4/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>prettier</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/d5098040-9f3e-443d-86ba-c8f3e78c3a82/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/d5098040-9f3e-443d-86ba-c8f3e78c3a82/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/d5098040-9f3e-443d-86ba-c8f3e78c3a82/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/d5098040-9f3e-443d-86ba-c8f3e78c3a82/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/components/section/section.tsx [hunk 1]
```diff
@@ -74,6 +74,7 @@ export interface SectionProps extends Props, Omit<HTMLDivProps, "title">, React.
 
     /**
      * Element to render on the right side of the section header.
+     * Note that the header will only be rendered if `title` is provided.
```
Comment (gluxon) [inline packages/core/src/components/section/section.tsx:77]: Nice catch copying this comment over from the other props that are no-ops if `title` is not provided.

**Review by gluxon — APPROVED** [review]
Thanks!
