### PR TITLE
Pass locale to moment for formatting. Fixes #1428

### LINKED ISSUE #1428: [DateInput] Locale not passed to moment for i18n format strings like `L`
### Bug report

- __Package version(s)__: @blueprintjs/datetime 1.19.0
- __Browser and OS versions__: All

#### Steps to reproduce

1. Pass a format string to `DateInput` like `L` and a locale with a different date format.

#### Actual behavior

`L` still outputs the expected `en-US` format.

#### Expected behavior

The output should be based on the provided `locale` prop.

### PR DESCRIPTION
**Pull request by nomcopter**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)

### CODE REVIEW

File: packages/datetime/src/dateInput.tsx [hunk 1]
```diff
@@ -316,7 +320,14 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
...
 
     private handleInputFocus = (e: React.FocusEvent<HTMLInputElement>) => {
-        const valueString = isMomentNull(this.state.value) ? "" : this.state.value.format(this.props.format);
+        let valueString: string;
+        if (isMomentNull(this.state.value)) {
+          valueString = "";
+        } else if (this.props.locale) {
+          valueString = this.props.locale ? this.state.value.locale(this.props.locale).format(this.props.format);
+        } else {
+          valueString = this.state.value.format(this.props.format);
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: 4 space indentation

Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: also lots of repetition here. maybe add a helper function that does the `if (locale) else` logic?

File: packages/datetime/src/dateInput.tsx [hunk 2]
```diff
@@ -355,7 +366,7 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
 
     private handleInputBlur = (e: React.FocusEvent<HTMLInputElement>) => {
         const valueString = this.state.valueString;
-        const value = moment(valueString, this.props.format);
+        const value = moment(valueString, this.props.format, this.props.locale);
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: i feel like a `createMoment(valueString)` wrapper would be useful, in case we ever want to change it again in the future. this change appears 3 times in this PR.

File: packages/datetime/src/dateInput.tsx (hunk 1 above)
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]:
```
if (isMomentNull(this.state.value)) {
    valueString = "";
} else {
    valueString = this.formatMoment(this.state.value);
}
```

**Comment by nomcopter** [comment]
Ready for rereview @giladgray

File: packages/datetime/src/dateInput.tsx [hunk 3]
```diff
@@ -247,13 +247,21 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
         }
     }
 
+    private localizedFormat = (value: moment.Moment) => {
+        if (this.props.locale) {
+            return value.locale(this.props.locale).format(this.props.format);
+        } else {
+            return value.format(this.props.format);
+        }
+    }
```
Comment (nomcopter) [inline packages/datetime/src/dateInput.tsx]: /shrug I like the destructuring, dislike the ternary.
