### PR TITLE
Simplify EditableText callback logic

### LINKED ISSUE #573: EditableText onConfirm is not called when pressing ENTER on unchanged value
### Bug report

- __Package version(s)__: 1.7.0
- __Browser and OS versions__: chrome, osx

### Steps to reproduce

for an `EditableText` where `isEditing={true}`
1) Ensure element has focus
2) Press enter

Actual: the element loses focus and neither the confirm nor cancel is called the second time
Expected: 
1) the element does not lose focus at all 
or perhaps
2) the element loses focus and the cancel callback is called

In case this seems esoteric (which it does, here is the use case):

I have an `EditableText` where `""` is a forbidden value. To achieve this, I have the following code

```ts
    public render() {
        return (
            <EditableText
                isEditing={this.state.isEditing}
                value={this.state.value}
                onCancel={this.handleCancel}
                onChange={this.handleChange}
                onConfirm={this.handleConfirm}
                onEdit={this.handleStartEdit}
            />
        );
    }

    private handleStartEdit = () => {
        this.setState({ ...this.state, isEditing: true });
    }

    private handleChange = (name: string) => {
        this.setState({ ...this.state, isError: false, value: name });
    }

    private handleCancel = () => {
        this.setState({ ...this.state, isError: false, value: this.props.title, isEditing: false });
    }

    private handleConfirm = (name: string) => {
        const trimmedName = name.trim();

        if (trimmedName.length === 0) {
            this.setState({ ...this.state, isError: true });
            return;
        }

        this.setState({ ...this.state, isEditing: false });
        this.props.doSomething(trimmedName);
    }
```

If I remove all text, press enter, nothing happens (the confirm successfully blocks). However If I press enter *again* the element loses focus, and neither the confirm nor cancel callback is called. This seems like a bug to me as one of the two should definitely be called (either cancel if the element should be losing focus, or confirm if it should not).
I think this is tied up with pressing enter when the `EditableText` does not think there are changes.

### PR DESCRIPTION
**Pull request by leebyp**
#### Fixes #573 

Reverting changes made in #499.

### CODE REVIEW

File: packages/core/src/components/editable-text/editableText.tsx [hunk 1]
```diff
@@ -212,27 +212,19 @@ export class EditableText extends AbstractComponent<IEditableTextProps, IEditabl
...
-        } else {
-            this.setState({ isEditing: false, value: lastValue });
-            // invoke onCancel after onChange so consumers' onCancel can override their onChange
-            safeInvoke(this.props.onChange, lastValue);
-            safeInvoke(this.props.onCancel, lastValue);
-        }
+        const { lastValue } = this.state;
+        this.setState({ isEditing: false, value: lastValue });
+        // invoke onCancel after onChange so consumers' onCancel can override their onChange
+        safeInvoke(this.props.onChange, lastValue);
```
Comment (cmslewis) [inline packages/core/src/components/editable-text/editableText.tsx]: Does it make more sense to at least not trigger the `this.props.onChange` callback unless `if (lastValue === value)`?

File: packages/core/src/components/editable-text/editableText.tsx [hunk 2]
```diff
@@ -212,27 +212,19 @@ export class EditableText extends AbstractComponent<IEditableTextProps, IEditabl
...
-            if (lastValue === value) {
-                this.setState({ isEditing: false });
-            } else {
-                this.setState({ isEditing: false, lastValue: value });
-                safeInvoke(this.props.onChange, value);
-                safeInvoke(this.props.onConfirm, value) ;
-            }
+            const { value } = this.state;
+            this.setState({ isEditing: false, lastValue: value });
+            safeInvoke(this.props.onChange, value);
```
Comment (cmslewis) [inline packages/core/src/components/editable-text/editableText.tsx]: Same.

File: packages/core/src/components/editable-text/editableText.tsx (hunk 1 above)
Comment (giladgray) [inline packages/core/src/components/editable-text/editableText.tsx]: i was thinking the same thing. here, we definitely want to call both because the value _does_ change: it is reset to the `lastValue`.

File: packages/core/src/components/editable-text/editableText.tsx (hunk 2 above)
Comment (giladgray) [inline packages/core/src/components/editable-text/editableText.tsx]: however, here the only thing that changes is the editing state, so i could see adding a check for whether value changed.

Comment (giladgray) [inline packages/core/src/components/editable-text/editableText.tsx]: but perhaps for consistency's sake, it's easiest to do nothing.

**Comment by leebyp** [comment]
on further discussion, it looks like the points made [here](https://github.com/palantir/blueprint/issues/573#issuecomment-276546538) give the most consistent API.

**Comment by giladgray** [comment]
🎉  this is amazing! so simple, so effortless.
