### PR TITLE
[Table] Move focused cell when columns/rows are reordered

### LINKED ISSUE #1258: [Table] Focus cell does not move after reordering
### Bug report

- __Package version(s)__: v1.20.0
- __Browser and OS versions__: Chrome 59 on Mac OS X Sierra

#### Steps to reproduce

1. Enable focus cell and row reordering.
2. Click a row to select it.
3. Reorder it elsewhere.

#### Actual behavior

Focus cell does not move with the selection after reordering is complete.

reorder-focus-bug
 

#### Expected behavior

Focus cell should move with the newly reordered selection.

### PR DESCRIPTION
**Pull request by gscshoyru**
#### Changes proposed in this pull request:

Add the focus cell logic to the selection logic for the drag handles.

### CODE REVIEW

**Comment by cmslewis** [comment]
Behavior feels good. 👍 Looking at the code now.

File: packages/table/src/interactions/reorderable.tsx [hunk 1]
```diff
@@ -130,6 +137,13 @@ export class DragReorderable extends React.Component<IDragReorderable, {}> {
         } else {
             // select the new region to avoid complex and unintuitive UX w/r/t the existing selection
             this.props.onSelection([region]);
+            const focusCellCoordinates = Regions.getFocusCellCoordinatesFromRegion(region);
```
Comment (cmslewis) [inline packages/table/src/interactions/reorderable.tsx]: We're inconsistent about `*focusedCell*` vs `*focusCell*`. I've opted to move to the former in my work; you okay with that? If so, let's change this to `focusedCellCoordinates`.

File: packages/table/src/interactions/reorderable.tsx [hunk 2]
```diff
@@ -130,6 +137,13 @@ export class DragReorderable extends React.Component<IDragReorderable, {}> {
...
+            const fullFocusCellCoordinates: IFocusedCellCoordinates = {
+                col: focusCellCoordinates.col,
```
Comment (cmslewis) [inline packages/table/src/interactions/reorderable.tsx]: FYI I made a nifty helper for this repetitive pattern in another upcoming PR:

```tsx

/**
 * Returns a new cell-coordinates object that includes a focusSelectionIndex property.
 * The returned object will have the proper IFocusedCellCoordinates type.
 */
export function toFullCoordinates(
    cellCoords: ICellCoordinates,
    focusSelectionIndex: number = 0,
): IFocusedCellCoordinates {
    return { ...cellCoords, focusSelectionIndex };
}
```

File: packages/table/src/interactions/reorderable.tsx [hunk 3]
```diff
@@ -130,6 +137,13 @@ export class DragReorderable extends React.Component<IDragReorderable, {}> {
         } else {
             // select the new region to avoid complex and unintuitive UX w/r/t the existing selection
             this.props.onSelection([region]);
+            const focusCellCoordinates = Regions.getFocusCellCoordinatesFromRegion(region);
+            const fullFocusCellCoordinates: IFocusedCellCoordinates = {
```
Comment (cmslewis) [inline packages/table/src/interactions/reorderable.tsx]: `fullFocusedCellCoordinates`

File: packages/table/src/interactions/reorderable.tsx [hunk 4]
```diff
@@ -158,6 +172,13 @@ export class DragReorderable extends React.Component<IDragReorderable, {}> {
         // the newly reordered region becomes the only selection
         const newRegion = this.props.toRegion(reorderedIndex, reorderedIndex + length - 1);
         this.props.onSelection(Regions.update([], newRegion));
+        const focusCellCoordinates = Regions.getFocusCellCoordinatesFromRegion(newRegion);
```
Comment (cmslewis) [inline packages/table/src/interactions/reorderable.tsx]: Same

File: packages/table/src/interactions/reorderable.tsx [hunk 5]
```diff
@@ -158,6 +172,13 @@ export class DragReorderable extends React.Component<IDragReorderable, {}> {
...
+        const fullFocusCellCoordinates: IFocusedCellCoordinates = {
+            col: focusCellCoordinates.col,
```
Comment (cmslewis) [inline packages/table/src/interactions/reorderable.tsx]: Same

File: packages/table/src/interactions/reorderable.tsx [hunk 6]
```diff
@@ -38,6 +39,12 @@ export interface IReorderableProps {
     onSelection: (regions: IRegion[]) => void;
 
     /**
+     * When the user reorders something, this callback is called with the new
+     * focus cell for the newly selected set of regions.
```
Comment (giladgray) [inline packages/table/src/interactions/reorderable.tsx]: these docs don't match what I expect from a prop called `onFocus`: i expect a handler for a `focus` event, but you're talking about reordering. can you come up with a more intuitive name?

File: packages/table/src/interactions/reorderable.tsx [hunk 7]
```diff
@@ -130,6 +137,13 @@ export class DragReorderable extends React.Component<IDragReorderable, {}> {
         } else {
             // select the new region to avoid complex and unintuitive UX w/r/t the existing selection
             this.props.onSelection([region]);
+            const focusCellCoordinates = Regions.getFocusCellCoordinatesFromRegion(region);
+            const fullFocusCellCoordinates: IFocusedCellCoordinates = {
+                col: focusCellCoordinates.col,
+                focusSelectionIndex: 1,
+                row: focusCellCoordinates.row,
+            };
+            this.props.onFocus(fullFocusCellCoordinates);
```
Comment (giladgray) [inline packages/table/src/interactions/reorderable.tsx]: i would write this entire block as simply

```js
// argument to function will be typed as IFocusedCellCoordinates, so you don't have to
this.props.onFocus({ ...focusedCellCoordinates, focusSelectionIndex: 1 })
```

File: packages/table/src/interactions/reorderable.tsx [hunk 8]
```diff
@@ -158,6 +172,13 @@ export class DragReorderable extends React.Component<IDragReorderable, {}> {
         // the newly reordered region becomes the only selection
         const newRegion = this.props.toRegion(reorderedIndex, reorderedIndex + length - 1);
         this.props.onSelection(Regions.update([], newRegion));
+        const focusCellCoordinates = Regions.getFocusCellCoordinatesFromRegion(newRegion);
+        const fullFocusCellCoordinates: IFocusedCellCoordinates = {
+            col: focusCellCoordinates.col,
+            focusSelectionIndex: 1,
+            row: focusCellCoordinates.row,
+        };
+        this.props.onFocus(fullFocusCellCoordinates);
```
Comment (giladgray) [inline packages/table/src/interactions/reorderable.tsx]: same as above with the pithy one-liner

File: packages/table/src/interactions/reorderable.tsx (hunk 6 above)
Comment (gscshoyru) [reply packages/table/src/interactions/reorderable.tsx]: ...I'm just cribbing from "onSelection" above -- and that's what the "set my selection" and "set my focus" callbacks are called everywhere. They just filter up to the toplevel onFocus and onSelection behavior. Not sure what the issue is here?

File: packages/table/src/interactions/reorderable.tsx (hunk 7 above)
Comment (gscshoyru) [reply packages/table/src/interactions/reorderable.tsx]: Apparently Chris has an incoming helper instead, see above -- going to use that. Good point though, your way here is more succinct.

Comment (giladgray) [reply packages/table/src/interactions/reorderable.tsx]: his helper does precisely what i wrote above. i honestly don't see a need to wait for the helper when the spread is so simple.

Comment (cmslewis) [reply packages/table/src/interactions/reorderable.tsx]: Yeah @gscshoyru feel free to just do this one-liner for now

**Comment by cmslewis** [comment]
Chatted offline w/ @gscshoyru. I'll take this over. 👍

File: packages/table/src/interactions/reorderable.tsx (hunk 6 above)
Comment (cmslewis) [reply packages/table/src/interactions/reorderable.tsx]: @giladgray this is a good point, but it's something we'd have to address more globally, since `onFocus` appears everywhere in `Table` right now. I vote to leave as is in this PR and revisit separately. Tracking in https://github.com/palantir/blueprint/issues/1562.

File: packages/table/src/interactions/reorderable.tsx (hunk 1 above)
Comment (cmslewis) [reply packages/table/src/interactions/reorderable.tsx]: Done

File: packages/table/src/interactions/reorderable.tsx (hunk 2 above)
Comment (cmslewis) [reply packages/table/src/interactions/reorderable.tsx]: No action needed

File: packages/table/src/interactions/reorderable.tsx (hunk 7 above)
Comment (cmslewis) [reply packages/table/src/interactions/reorderable.tsx]: Also, @gscshoyru did we mean to change `focusSelectionIndex` to `1` instead of `0`? There's only one region in the new `selectedRegions` array, so it seems like `0` is correct. LMK if that's wrong.

File: packages/table/src/interactions/reorderable.tsx (hunk 4 above)
Comment (cmslewis) [reply packages/table/src/interactions/reorderable.tsx]: Done

File: packages/table/src/interactions/reorderable.tsx (hunk 8 above)
Comment (cmslewis) [reply packages/table/src/interactions/reorderable.tsx]: Done
