### PR TITLE
[RadioGroup] Add inline prop for radio button group

### LINKED ISSUE #1399: [RadioGroup] add option to create inline radios
Enhancement: I suggest adding an option to create an inline RadioGroup, instead of vertically stacked as they are now. I tried to pass "pt-inline" as a class, but that doesn't work. For now I can roll my own, but this would be nice!

### PR DESCRIPTION
**Pull request by cathyxz**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)
- [x] Update documentation

#### Changes proposed in this pull request:

Add `inline` as a prop to RadioGroup to enable inline radio buttons. 

#### Screenshot

screen shot 2017-08-20 at 9 15 25 pm

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/blueprint/1475)

### CODE REVIEW

File: packages/core/src/components/forms/radioGroup.tsx [hunk 1]
```diff
@@ -89,11 +94,12 @@ export class RadioGroup extends AbstractComponent<IRadioGroupProps, {}> {
     }
 
     private getRadioProps(optionProps: IOptionProps) {
-        const { name } = this.props;
+        const { name, inline } = this.props;
         const { value, disabled } = optionProps;
         return {
             checked: value === this.props.selectedValue,
             disabled: disabled || this.props.disabled,
+            inline: inline == null ? false : inline,
```
Comment (giladgray) [inline packages/core/src/components/forms/radioGroup.tsx]: no need for a ternary when dealing with booleans. should be safe to just pass `inline` directly, or you could assign default prop value.

File: packages/core/src/components/forms/radioGroup.tsx [hunk 2]
```diff
@@ -20,6 +20,11 @@ export interface IRadioGroupProps extends IProps {
      */
     disabled?: boolean;
 
+    /**
+     * True if radio buttons are to be displayed inline horizontally.
```
Comment (giladgray) [inline packages/core/src/components/forms/radioGroup.tsx]: please match language for other boolean props, like the one above which begins "Whether..." (like you did in the file above)

File: packages/core/src/components/forms/controls.tsx [hunk 3]
```diff
@@ -72,6 +75,7 @@ export class Control<P extends IControlProps> extends React.Component<P, {}> {
             typeClassName,
             { [Classes.DISABLED]: this.props.disabled },
             this.props.className,
+            { [Classes.INLINE]: this.props.inline },
```
Comment (giladgray) [inline packages/core/src/components/forms/controls.tsx]: merge this into the object on line 76, so it has two entries.

**Comment by cathyxz** [comment]
@giladgray thanks for the prompt review! Addressed comments. I was going to amend my commit, but I think squash and merge means you can just "squash" it in the Github UI?

**Comment by giladgray** [comment]
@cathyxz yes please do not amend commits that have already been pushed--that destroys any semblance of history as you cannot see my comments on commits that no longer exist. we use squash&merge to keep a clean `master`
