### PR TITLE
[Overlay] Support nested overlays

### LINKED ISSUE #2030: [Overlay] Nested overlays close all overlays when inner content is clicked
### Bug report

- __Package version(s)__: v1.x and v2.x
- __Browser and OS versions__: Irrelevant
#### Steps to reproduce

1. Create nested overlays/popovers
2. Click the content of a nested popover.

Screencast of the issue on the docs [here](https://cl.ly/373Q0w192H1b).

#### Actual behavior

All the popovers close.

#### Expected behavior

All popovers remain open.

I have fixed this locally by patching `Overlay`. My solution works by propagating depth via context. Every overlay reads the current depth and then sets the new depth to +1. I then override [handleDocumentClick](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/overlay/overlay.tsx#L348-L356) and if a nested overlay was clicked, only close the descendants.

The source code for this patch is [here](https://gist.github.com/tyscorp/2bc90d8c3c90cbd701a63aaffb87c45f). I currrently use the DOM to store data but I think another solution would be possible.

I'd be interested in making a PR with a better solution if wanted.

### PR DESCRIPTION
**Pull request by tyscorp**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)
- [x] Include tests

#### Changes proposed in this pull request:

Uses `Overlay.openStack` to test if a document click is in a descendant overlay. Children overlays _should_ always be after the parent's index, so I think this should work for most cases.

This PR does not handle the case of having a non-`Overlay` `Blueprint.Portal` or `ReactDOM.createPortal`.

### CODE REVIEW

**Comment by tyscorp** [comment]
<h3>[Overlay] Support nested overlays. Fixes #2030</h3>

Preview: <strong><a href='https://13-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://13-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://13-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by adidahiya** [comment]
looks like you need more containers 😅 

image

**Comment by adidahiya** [comment]
Are builds like this not allowed in free CircleCI accounts? That's unfortunate... we'll have to refactor the test workflow steps

File: packages/core/src/components/overlay/overlay.tsx [hunk 1]
```diff
@@ -348,7 +349,19 @@ export class Overlay extends React.PureComponent<IOverlayProps, IOverlayState> {
...
+
+        const isClickInDescendantOverlay = openStack
+            .slice(stackIndex)
+            .map(findDOMNode)
+            .filter(elem => elem && elem.contains)
+            .some(elem => elem.contains(eventTarget));
+
+        const isClickInOverlay =
+            (this.containerElement != null && this.containerElement.contains(eventTarget)) ||
+            isClickInDescendantOverlay;
```
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: don't `||` here cuz it makes the variable name incorrect (includes a check for clicks _not_ in overlay). `||` in the `if`.

File: packages/core/src/components/overlay/overlay.tsx [hunk 2]
```diff
@@ -348,7 +349,19 @@ export class Overlay extends React.PureComponent<IOverlayProps, IOverlayState> {
...
-        const isClickInOverlay = this.containerElement != null && this.containerElement.contains(eventTarget);
+
+        const { openStack } = Overlay;
+        const stackIndex = openStack.indexOf(this);
+
+        const isClickInDescendantOverlay = openStack
+            .slice(stackIndex)
+            .map(findDOMNode)
+            .filter(elem => elem && elem.contains)
+            .some(elem => elem.contains(eventTarget));
```
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: 👌  sweet array manipulation

File: packages/core/src/components/overlay/overlay.tsx [hunk 3]
```diff
@@ -348,7 +349,19 @@ export class Overlay extends React.PureComponent<IOverlayProps, IOverlayState> {
     private handleDocumentClick = (e: MouseEvent) => {
         const { isOpen, onClose } = this.props;
         const eventTarget = e.target as HTMLElement;
-        const isClickInOverlay = this.containerElement != null && this.containerElement.contains(eventTarget);
+
+        const { openStack } = Overlay;
+        const stackIndex = openStack.indexOf(this);
+
+        const isClickInDescendantOverlay = openStack
+            .slice(stackIndex)
```
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: i'm struggling to wrap my head around why this works... new ("descendant") Overlays are pushed to the end of the stack so we can slice off everything _before_ this one?

**Comment by giladgray** [comment]
@tyscorp got a moment to update this PR? if not, please close it and i'll pick up this feature.

**Comment by tyscorp** [comment]
Thanks for the reminder. I updated with the requested changes. I'm not sure how to write a unit test for this.

**Comment by tyscorp** [comment]
<h3>[Overlay] Support nested overlays. Fixes #2030</h3>

Preview: <strong><a href='https://19-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://19-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://19-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by giladgray** [comment]
@tyscorp thanks! in the future, please do not amend/force-push commits--it destroys the links to outdated changes (try clicking on filename in one of my outdated comments above): https://github.com/palantir/blueprint/pull/2033/files/c263f3d136f5884357d65597524f386610bc1095#diff-567c0c7f15281ce63ededd202d7220f5

**Comment by giladgray** [comment]
@tyscorp I'm going to need a test before I can accept this sort of change. make a test that asserts that a simple repro, ahem, doesn't reproduce after this change. 

take the code that led you to this bug, simplify it to just use `Overlay`s and some dummy content, exercise the events, and assert that the outer overlays don't close.

**Comment by tyscorp** [comment]
<h3>Added test</h3>

Preview: <strong><a href='https://28-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://28-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://28-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by tyscorp** [comment]
<h3>Fixed lint</h3>

Preview: <strong><a href='https://34-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://34-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://34-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/core/src/components/overlay/overlay.tsx [hunk 4]
```diff
@@ -348,8 +349,18 @@ export class Overlay extends React.PureComponent<IOverlayProps, IOverlayState> {
     private handleDocumentClick = (e: MouseEvent) => {
         const { isOpen, onClose } = this.props;
         const eventTarget = e.target as HTMLElement;
+
+        const { openStack } = Overlay;
+        const stackIndex = openStack.indexOf(this);
+
+        const isClickInDescendantOverlay = openStack
+            .slice(stackIndex)
+            .map(findDOMNode)
```
Comment (adidahiya) [inline packages/core/src/components/overlay/overlay.tsx]: If we change the visibility of `Overlay#containerElement` to `public`, then we can avoid this `findDOMNode` call. I would prefer that approach.

File: packages/core/src/components/overlay/overlay.tsx [hunk 5]
```diff
@@ -348,8 +349,18 @@ export class Overlay extends React.PureComponent<IOverlayProps, IOverlayState> {
...
+            .some(elem => elem && elem.contains && elem.contains(eventTarget));
+
         const isClickInOverlay = this.containerElement != null && this.containerElement.contains(eventTarget);
-        if (isOpen && this.props.canOutsideClickClose && !isClickInOverlay) {
+
+        if (isOpen && this.props.canOutsideClickClose && !isClickInOverlay && !isClickInDescendantOverlay) {
```
Comment (adidahiya) [inline packages/core/src/components/overlay/overlay.tsx]: Since `isClickInDescendantOverlay` includes _this_ overlay instance (`openStack.slice(stackIndex)` will include this Overlay), I think we can remove `isClickInOverlay` altogether.

File: packages/core/src/components/overlay/overlay.tsx (hunk 3 above)
Comment (adidahiya) [reply packages/core/src/components/overlay/overlay.tsx]: yes

**Comment by tyscorp** [comment]
<h3>code style tweaks</h3>

Preview: <strong><a href='https://40-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://40-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://40-118695582-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by adidahiya** [comment]
thanks @tyscorp!
