### PR TITLE
[Table] Better editable names

### LINKED ISSUE #1262: [Table] Resolve differences between <EditableCell> and <EditableName>
### Bug report

- __Package version(s)__: v1.20.0

### Changes proposed

There are some differences between `EditableCell`  and `EditableName` that we should resolve:
- Should emit the `columnIndex` as a second parameter in `onCancel`, `onChange`, and `onConfirm` callbacks
- Should fully control the value so that updating `props.name` actually renders the new name. (See: #1257, #1234)

### PR DESCRIPTION
**Pull request by gscshoyru**
#### Changes proposed in this pull request:

Clone the header name so it gets the index as props when created, so it can use it to pass it in the callbacks. Also improve the header so that it actually is controlled mode, more or less.

### CODE REVIEW

File: packages/table/src/headers/columnHeaderCell.tsx [hunk 1]
```diff
@@ -154,7 +154,9 @@ export class ColumnHeaderCell extends AbstractComponent<IColumnHeaderCellProps,
 
         const nameComponent = (
             <LoadableContent loading={loading} variableLength={true}>
-                {renderName == null ? defaultName : renderName(name, index)}
+                {renderName == null
```
Comment (cmslewis) [inline packages/table/src/headers/columnHeaderCell.tsx]: Isn't multiline JSX forbidden by our TSLint config? Regardless, I'd prefer to kick this out into a variable above to keep the JSX lean.

File: packages/table/src/headers/editableName.tsx [hunk 2]
```diff
@@ -35,24 +35,80 @@ export interface IEditableNameProps extends IIntentProps, IProps {
...
+        this.setState({ dirtyName: value });
+        this.invokeCallback(this.props.onChange, value);
+    };
+
+    private handleConfirm = (value: string) => {
+        this.setState({ isEditing: false, savedName: value, dirtyName: undefined });
+        this.invokeCallback(this.props.onConfirm, value);
+    };
+
+    private invokeCallback(callback: (value: string, columnIndex?: number) => void, value: string) {
```
Comment (cmslewis) [inline packages/table/src/headers/editableName.tsx]: How about `maybeInvokeCallback`, since these aren't required?

File: packages/table/src/headers/editableName.tsx [hunk 3]
```diff
@@ -35,24 +35,80 @@ export interface IEditableNameProps extends IIntentProps, IProps {
...
             />
         );
     }
+
+    private handleEdit = () => {
+        this.setState({ isEditing: true, dirtyName: this.state.savedName });
+    };
+
+    private handleCancel = (value: string) => {
+        // don't strictly need to clear the dirtyName, but it's better hygiene
```
Comment (cmslewis) [inline packages/table/src/headers/editableName.tsx]: This comment looks familiar. 😛
