### PR TITLE
[core] fix(Collapse): closing animation in Firefox

### LINKED ISSUE #4114: Collapse doesn't animate closing on Firefox
#### Environment

- __Package version(s)__: Whatever is used on [documentation page](https://blueprintjs.com/docs/#core/components/collapse)
- __Browser and OS versions__: Firefox 76.0, Windows 10

Can be reproduced on official documentation website: https://blueprintjs.com/docs/#core/components/collapse

#### Steps to reproduce

1. Open [Collapse documentation](https://blueprintjs.com/docs/#core/components/collapse) in Firefox
2. Click "Show build logs"
3. Click "Hide build logs"

#### Actual behavior

Build logs disappear immediately

#### Expected behavior

Build logs show collapse animation

### PR DESCRIPTION
**Pull request by Arbalester**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Changed height for transition. Set 'heightWhenOpen' as content height for the closing process.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @Arbalester! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
[PR preview docs-app build](https://33179-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#core/components/collapse)

File: packages/core/src/components/collapse/collapse.tsx [hunk 1]
```diff
@@ -223,10 +223,12 @@ export class Collapse extends AbstractPureComponent2<ICollapseProps, ICollapseSt
             });
             this.setTimeout(() => this.onDelayedStateChange(), transitionDuration);
         } else if (animationState === AnimationStates.CLOSING_START) {
+            const { clientHeight } = this.contents;
             this.setTimeout(() =>
                 this.setState({
                     animationState: AnimationStates.CLOSING,
                     height: "0px",
+                    heightWhenOpen: clientHeight,
```
Comment (adidahiya) [inline packages/core/src/components/collapse/collapse.tsx:231]: hmm I'm not sure why this state field is not already set at this time by L222, but this change seems to fix the bug so I'll approve it and look into any potential tweaks later.

**Review by adidahiya — APPROVED** [review]
are you able to sign the CLA @Arbalester?

File: packages/core/src/components/collapse/collapse.tsx (hunk 1 above)
Comment (Arbalester) [reply packages/core/src/components/collapse/collapse.tsx:231]: I'll sign the cla in 1-2 days, because my company wants me to sign the corporate version. I'll send it asap

**Comment by Arbalester** [comment]
> Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @Arbalester! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

Hi, I've sent on your email signed corporate cla.
