### PR TITLE
Pass along column props to cell renderer

### LINKED ISSUE #690: Table `Column` component doesn't respect className prop
### Bug report

- __Package version(s)__: Blueprint table 1.6.0
- __Browser and OS versions__: Chrome 56 OSX 10.11.6

#### Steps to reproduce

1. Make a blueprint table with`Column` components that have a `className` prop set.

#### Actual behavior

Column headers don't get the class specified added in the rendered HTML.

#### Expected behavior

Column headers have the class specified added in the rendered HTML.

(Pretty sure this is a regression, this previously worked for us.)

### PR DESCRIPTION
**Pull request by gscshoyru**
#### Changes proposed in this pull request:
Fix behavior so that className (and everything else) from the parent column, as it worked before.

### CODE REVIEW

File: packages/table/src/table.tsx [hunk 1]
```diff
@@ -610,7 +610,7 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
             ? cellLoading
             : this.hasLoadingOption(columnProps.loadingOptions, ColumnLoadingOption.CELLS);
 
-        return React.cloneElement(cell, { loading } as ICellProps);
+        return React.cloneElement(cell, { ...columnProps, loading } as ICellProps);
```
Comment (michael-yx-wu) [inline packages/table/src/table.tsx]: this compiles fine, but will this result in unknown prop warnings? https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by giladgray** [comment]
@gscshoyru possible to write a unit test for this?

**Comment by michael-yx-wu** [comment]
https://xkcd.com/703/
