### PR TITLE
[popover2] fix(Popover2): get correct click target in shadow DOM

### LINKED ISSUE #5908: Clicking Popover button reopens it when in Shadow DOM
#### Environment

- __Package version(s)__:  4.10.1
- __Operating System__: Win 11
- __Browser name and version__: Chrome

#### Sandbox example
https://codesandbox.io/s/vibrant-solomon-7xvetc

#### Steps to reproduce

1. Put Popover inside Shadow DOM
1. Click on Popover button (it is opened)
1. Click on Popover button once again

#### Actual behavior

Popover closed and immediately opened

#### Expected behavior

Popover should be closed

#### Possible solution

In Popover2.tsx in function "handleOverlayClose" we should check not for "e.target", instead we should find the actual target from "composedPath", the same way it was done in "overlay.tsx" in function "handleDocumentClick"

### PR DESCRIPTION
**Pull request by kutensky**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Get the actual click target. The same way it was done in "overlay.tsx" in function "handleDocumentClick"

### CODE REVIEW

File: packages/popover2/src/popover2.tsx [hunk 1]
```diff
@@ -685,7 +685,7 @@ export class Popover2<T extends DefaultPopover2TargetHTMLProps> extends Abstract
             return;
         }
 
-        const eventTarget = e.target as HTMLElement;
+        const eventTarget = (e.composed ? e.composedPath()[0] : e.target) as HTMLElement;
```
Comment (adidahiya) [inline packages/popover2/src/popover2.tsx]: this approach seems reasonable, but I think you'll need to access `e.nativeEvent.composedPath` ([docs](https://beta.reactjs.org/reference/react-dom/components/common#react-event-object))

**Review by adidahiya — CHANGES_REQUESTED** [review]

File: packages/popover2/src/popover2.tsx (hunk 1 above)
Comment (kutensky) [reply packages/popover2/src/popover2.tsx]: It makes sense according to e is "React.SyntheticEvent". But actually the caller of this function passes native event instead of React.SyntheticEvent.
I guess in that case I can check that "e" has "nativeEvent" and use it, otherwise use "e"

Comment (kutensky) [reply packages/popover2/src/popover2.tsx]: So I updated the code

**Review by adidahiya — APPROVED** [review]

**Comment by adidahiya** [comment]
thanks @kutensky

**Comment by kutensky** [comment]
> thanks @kutensky

Thank you for such a quick response. That fix will help to close a bug in our application
