### PR TITLE
[Table] Have EditableCell fully control value in child EditableText

### LINKED ISSUE #1234: [Table] EditableCell + setState = value doesn't change
### Bug report

- __Package version(s)__: whatever is on the docs at the time of filing (Core v1.20.0, Table v1.17.0)
- __Browser and OS versions__: Chrome 58.0.3029.110, OS X 10.12.5

#### Steps to reproduce

1. Go to the "Editable content" docs: http://blueprintjs.com/docs/#table-js.editable-content and open React dev tools
2. Find the `TableEditableExample` component and select it such that it's assigned to `$r` in the console
3. run `$r.setState({ sparseCellData: Object.assign({}, $r.state.sparseCellData, { '1-1': 'foo' }) })` in the console

#### Actual behavior

1. Nothing changes.

#### Expected behavior

1. The value of the cell currently set to "editable" should change to "foo". Note that the dev tools reflect the correct state and the implementation of the example isn't doing anything particularly weird (https://github.com/palantir/blueprint/blob/master/packages/table/examples/tableEditableExample.tsx).

This is a stripped-down version of the issue I originally saw, but note that in my actual code, I use the `intent` field for validation as well, which is calculated at render time (as opposed to cached in state like the example), and changing the value using `setState` _does_ cause the intent to change in the DOM, but not the text content (as here).

In my use-case, the table is editable and part of a controlled component, so every time you change something it makes the callback -> props roundtrip, which means I hit this issue all of the time. :(

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

Have `EditableCell` fully control the value that it passes to its child `EditableText` component. (At preset, it's simply passing down the value as a `defaultValue`, so only the initial render is "controlled," as it were.) 

#### Reviewers should focus on:

This approach fixes the issue as far as I can tell. Does everything feel right? @seansfkelley, would especially appreciate a pass from you.

### CODE REVIEW

File: packages/table/src/cell/editableCell.tsx [hunk 1]
```diff
@@ -49,30 +49,42 @@ export interface IEditableCellProps extends ICellProps {
...
 
     public shouldComponentUpdate(nextProps: IEditableCellProps, nextState: IEditableCellState) {
         return !Utils.shallowCompareKeys(this.props, nextProps, { exclude: ["style"] })
             || !Utils.shallowCompareKeys(this.state, nextState)
             || !Utils.deepCompareKeys(this.props, nextProps, ["style"]);
     }
 
+    public componentWillReceiveProps(nextProps: IEditableCellProps) {
+        const { value } = nextProps;
+        this.setState({ savedValue: value, dirtyValue: value });
```
Comment (cmslewis) [inline packages/table/src/cell/editableCell.tsx]: If I'm actively editing the value and the props change, is it best to replace the "dirty" value I'm editing, pulling the rug out from under me, or is it best to update only the saved value, giving no visual indication to the user yet that the saved value as changed?

File: packages/table/src/cell/editableCell.tsx [hunk 2]
```diff
@@ -49,30 +49,42 @@ export interface IEditableCellProps extends ICellProps {
...
+    isEditing?: boolean;
+    savedValue?: string;
+    dirtyValue?: string;
 }
 
 export class EditableCell extends React.Component<IEditableCellProps, IEditableCellState> {
-    public state = {
-        isEditing: false,
-    };
+    public state: IEditableCellState;
```
Comment (giladgray) [inline packages/table/src/cell/editableCell.tsx]: no need to declare member, only need to do this if you're also defining it. but since you're defining in constructor, please remove this.

File: packages/table/src/cell/editableCell.tsx (hunk 1 above)
Comment (giladgray) [inline packages/table/src/cell/editableCell.tsx]: ugh, i don't even know. props == truth, right? so i'd replace dirty value.

Comment (seansfkelley) [inline packages/table/src/cell/editableCell.tsx]: Both seem gross, but I agree that replacing the direct value is better. You could also kick the user out of edit mode...?

Comment (cmslewis) [inline packages/table/src/cell/editableCell.tsx]: This would assume people wouldn't update the parent component's `value` on `change` right, only on confirm? If we forcefully left edit mode on every keystroke, we may drive folks to drink.
