### PR TITLE
Fix change activeItem when query changes on props for QueryList

### LINKED ISSUE #3179: QueryList activeItem does not change when query and items change on props
#### Environment

- __Package version(s)__: @blueprintjs/select:3.3.0
- __Browser and OS versions__: 

#### Steps to reproduce

1. have a QueryList and set the props for "query" and "items"
2. select an activeItem
3. change "query" and "items" props
4. use Enter key

#### Actual behavior

an item from the old items props will be chosen with the new query

#### Expected behavior

the new list of items will be used with the query

#### Possible solution

Issue is that `setQuery` is called here: https://github.com/rhysbrettbowen/blueprint/blob/develop/packages/select/src/components/query-list/queryList.tsx#L139

and the `setQuery` method looks at the current props - not the next props.

### PR DESCRIPTION
**Pull request by rhysbrettbowen**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)
- [x] Include tests
- [ ] Update documentation

#### Changes proposed in this pull request:

pass through next props to `setQuery` during `componentWillRecieveProps` in `QueryList`

### CODE REVIEW

File: packages/select/src/components/query-list/queryList.tsx [hunk 1]
```diff
@@ -136,7 +136,7 @@ export class QueryList<T> extends React.Component<IQueryListProps<T>, IQueryList
             this.setState({ activeItem: nextProps.activeItem });
         }
         if (nextProps.query != null) {
-            this.setQuery(nextProps.query);
+            this.setQuery(nextProps.query, nextProps.resetOnQuery, nextProps);
```
Comment (giladgray) [inline packages/select/src/components/query-list/queryList.tsx]: might this work better if it happened in `DidUpdate` instead? seems much better to invoke callbacks in a `Did` than in a `Will`.

Comment (giladgray) [reply packages/select/src/components/query-list/queryList.tsx]: mm tho there is some state manipulation inside `setQuery` so it does make sense here.

Comment (rhysbrettbowen) [reply packages/select/src/components/query-list/queryList.tsx]: I'll leave it in componentWillRecieveProps for now as it's meant to be a simple bug fix. Moving things around in the lifecycle is probably a bigger job since things are getting deprecated for react V17

File: packages/select/test/queryListTests.tsx [hunk 2]
```diff
@@ -3,16 +3,15 @@
  *
  * Licensed under the terms of the LICENSE file distributed with this project.
  */
-
 import { assert } from "chai";
 import { mount, ReactWrapper, shallow } from "enzyme";
 import * as React from "react";
 import * as sinon from "sinon";
 
+import { IFilm, renderFilm, TOP_100_FILMS } from "@blueprintjs/docs-app";
```
Comment (giladgray) [inline packages/select/test/queryListTests.tsx]: oh dude revert this change! it should be the relative path below. this is failing the tests on CircleCI too. 

how did this get introduced?
