### PR TITLE
Fix daterangepicker initial value month

### LINKED ISSUE #429: DateRangePicker default value not highlighting properly.
### Bug report

- __Package version(s)__: @blueprintjs/datetime 1.4.1
- __Browser and OS versions__: Version 57.0.2962.0 (Official Build) canary (64-bit), Mac Os Sierra 10.12 (16A323)

#### Steps to reproduce

```jsx
import React from 'react';

import { DateRangePicker } from "@blueprintjs/datetime";

const TestDateRange = React.createClass({
  getInitialState() {
    return {
      selectedDateRange: [new Date("2016-12-04"),new Date()]
    }
  },
  componentWillMount() {
   
  },
  handleDateChange (value) {
    this.setState({ selectedDateRange: value})
  },
  render() {
    return (
      <div>
        <DateRangePicker
        allowSingleDayRange={true}
        value={this.state.selectedDateRange}
        onChange={this.handleDateChange}/>
      </div>
    );
  }
});

export default TestDateRange;
```

#### Actual behavior
daterange picker

Nov 4th is being highlighted.
Am i doing something wrong with initial state?

#### Expected behavior

Dec 4th should be highlighted

### PR DESCRIPTION
**Pull request by leebyp**
#### Changes proposed in this pull request:

make a copy of the `value[0]` so that it doesn't get mutated in line 140.

#### Reviewers should focus on:

`props.initialMonth` can also be mutated from the first part of the if block, but I don't think that matters.

### CODE REVIEW

**Comment by themadcreator** [comment]
Why not use https://github.com/palantir/blueprint/blob/master/packages/datetime/src/common/dateUtils.ts#L44 ?

**Comment by leebyp** [comment]
ah sweet, missed it - updated

File: packages/datetime/test/dateRangePickerTests.tsx [hunk 1]
```diff
@@ -110,6 +110,15 @@ describe("<DateRangePicker>", () => {
             assert.equal(dateRangePicker.state.displayMonth, NOVEMBER);
         });
 
+        it("is value - 1 if set and initialMonth not set and value month === maxDate month", () => {
```
Comment (giladgray) [inline packages/datetime/test/dateRangePickerTests.tsx]: hrmm this description is more confusing than helpful. reword please to describe the issue being tested, not the code itself.

Comment (leebyp) [inline packages/datetime/test/dateRangePickerTests.tsx]: I thought the same thing about the wording in some of these tests. The problem is that the issue is tied to a specific setup when using the API, which in effect leads to describing the code.
