### PR TITLE
fix(DayRangePicker3): Fixed being able to get out of bounds in non contiguous mode

### LINKED ISSUE #7267: DateRangeInput3 get corrupted sometimes
#### Environment

-   **Package version(s)**:
@blueprintjs/core: 5.16.4
@blueprintjs/datetime2: 2.3.21
-   **Operating System**:
Windows 10 Home Edition
-   **Browser name and version**:
Google Chrome 133.0.6943.127

#### Code Sandbox

https://codesandbox.io/p/devbox/damp-butterfly-ls23lv?file=%2Fsrc%2FDateRangeInputBug.tsx%3A8%2C6-8%2C21&workspaceId=ws_PXP8Hez1WaKoj9r6rKHn5t

#### Steps to reproduce

1. Open date range input and switch year to 2024(previous year) on the left part of the component
Image
2. Switch month to the current month(February at this moment) on the left part of the component
Image
3. Switch year to 2025(current year) on the left part of the component

#### Actual behavior

Corrupted state of the component: months on both parts of the component got switched to January(previous month), all dates are disabled, month names on both sides are overlaped with arrow controls.

Image

#### Expected behavior

No blocked dates since there are valid ranges for selection in February(as well as in January).
No overlap.

#### Possible solution

None.

### PR DESCRIPTION
**Pull request by jscheiny**
#### Changes proposed in this pull request:

Fixed an issue that would allow users to get out of bounds by moving to an invalid month in a different year and then changing to that year. For example, if the max date is March 2024, you can switch to May 2023 and then change the year to 2024 and result in a broken state. This works in both directions for min and max dates.

Some minimal repros include:

```tsx
<DateRangeInput3
    contiguousCalendarMonths={false}
    minDate={new Date(2024, 3, 1)}
/>
```

```tsx
<DateRangeInput3
    contiguousCalendarMonths={false}
    maxDate={new Date()}
/>
```

### CODE REVIEW

File: packages/datetime2/src/components/date-range-picker3/nonContiguousDayRangePicker.tsx [hunk 1]
```diff
@@ -255,6 +249,25 @@ function useNonContiguousCalendarViews(
     };
 }
 
+function getBoundedViews(
+    leftView: MonthAndYear,
+    rightView: MonthAndYear,
+    minDate: Date | undefined,
+    maxDate: Date | undefined,
+): [left: MonthAndYear, right: MonthAndYear] {
+    let minView = MonthAndYear.fromDate(minDate ?? null);
```
Comment (ggdouglas) [inline packages/datetime2/src/components/date-range-picker3/nonContiguousDayRangePicker.tsx]: **lint:** These variables, `minView` and `maxView` can be `const`.

**Review by ggdouglas — APPROVED** [review]
