### PR TITLE
[core] fix(Popover): work around react-popper bug, fix React 18 compat

### LINKED ISSUE #6203: [v5] Popover doesn't close when clicked outside in React 18 StrictMode
tl;dr: Popovers with `interactionKind="click"` in v5 don't close when rendered within React 18 StrictMode and the user clicks outside the popover. This includes anything depending on Popover, like Select.

This is an upstream bug in `react-popper`. Already filed a PR, but I'm also filing it here because I don't want anyone else to have to debug this. Only an uncommon use case of `react-popper` (`Reference` with `innerRef`) is affected but that breaks BlueprintJS's usage.

https://github.com/floating-ui/react-popper/pull/459

`v4` and `popover2` are unaffected because they use `findDOMNode` instead of `innerRef`.

#### Environment

- __Package version(s)__: `@blueprintjs/core@5.0.0-alpha.6`
- __Operating System__: Windows 10
- __Browser name and version__: Firefox 113

#### Code Sandbox

https://codesandbox.io/p/sandbox/tender-brown-wryqy4

#### Steps to reproduce

1. Click on popover target button
2. Click outside popover

#### Actual behavior

The popover inside StrictMode doesn't close when you click outside the popover

#### Expected behavior

...it does?

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [x] Update (code) documentation

#### Changes proposed in this pull request:

fix(`Popover`): adjust target ref behavior to work around react-popper `innerRef` bug, fixing React 18 strict mode compatibility

#### Reviewers should focus on:

No regressions in Popover, table draggable interactions, ResizeSensor

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>[core] fix(Popover): work around react-popper bug, React 18 compat</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/326c87f2-4bda-4e43-a51a-dab25380ed97/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/326c87f2-4bda-4e43-a51a-dab25380ed97/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/326c87f2-4bda-4e43-a51a-dab25380ed97/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/326c87f2-4bda-4e43-a51a-dab25380ed97/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/components/resize-sensor/resizeSensor.tsx [hunk 1]
```diff
@@ -79,12 +85,6 @@ export class ResizeSensor extends AbstractPureComponent<ResizeSensorProps> {
 
     public render(): React.ReactNode {
         const onlyChild = React.Children.only(this.props.children);
-
-        // if we're provided a ref to the child already, we don't need to attach one ourselves
-        if (this.props.targetRef !== undefined) {
-            return onlyChild;
-        }
```
Comment (adidahiya) [inline packages/core/src/components/resize-sensor/resizeSensor.tsx]: it turns out that this change to accept both `RefObject` and `RefCallback` broke all Popovers with children that are not DOM elements, such as `<Suggest>` which renders an `<InputGroup>` child. here's what happens:

1. ResizeSensor gets a ref callback as its `targetRef`
2. ResizeSensor is not able to peek into this ref callback (like it could with `.current` on ref _objects_) to get the DOM element, so it must create its own ref
3. ResizeSensor's own ref can only attach to its direct child, which may not be a native DOM element
4. ResizeSensor returns this non-DOM element value to `Popover#targetRef` at runtime, thereby setting `Popover#targetElement` to an invalid type (e.g. `InputGroup` inside a `Suggest`, instead of `HTMLInputElement`)
5. the page crashes because:
  i. `Popover` code which expects `this.targetElement` to be a DOM node fails (e.g. `element.closest()`)
  ii. popper.js fails because it doesn't have access to a valid DOM node

thus, `targetRef` can _only_ accept a `RefObject` type, which _must_ be provided if the child is a non-native DOM element node

**Comment by adidahiya** [comment]
<h3>Fix tests, add comments</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/9fcf6efd-40e8-4b97-a0e8-9c7b04f9cbd2/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/9fcf6efd-40e8-4b97-a0e8-9c7b04f9cbd2/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/9fcf6efd-40e8-4b97-a0e8-9c7b04f9cbd2/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/9fcf6efd-40e8-4b97-a0e8-9c7b04f9cbd2/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>fix tests, only create ResizeObserver on mount</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/1a199993-a119-416e-ae10-0258c361bfb0/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/1a199993-a119-416e-ae10-0258c361bfb0/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/1a199993-a119-416e-ae10-0258c361bfb0/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/1a199993-a119-416e-ae10-0258c361bfb0/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/components/resize-sensor/resizeSensor.tsx [hunk 2]
```diff
@@ -89,6 +90,7 @@ export class ResizeSensor extends AbstractPureComponent<ResizeSensorProps> {
     }
 
     public componentDidMount() {
+        this.observer = new ResizeObserver(entries => this.props.onResize?.(entries));
```
Comment (adidahiya) [inline packages/core/src/components/resize-sensor/resizeSensor.tsx:93]: this caused a runtime error in some test environments like jsdom where `ResizeObserver` is undefined. apparently components still get mounted in jsdom, whoops. I will fix the regression ASAP
