### PR TITLE
[NumericInput] Add support for large styling

### LINKED ISSUE #907: NumericInput doesn't pass down className props (or accept ".pt-large" modifier)
### Bug report

- __Package version(s)__: 1.13.0

#### Steps to reproduce

1. Render NumericInput component with className prop
2. `<NumericInput className="pt-large"/>`

#### Actual behavior

1. Rendered class name is placed on div surrounding `div.pt-control-group`

#### Expected behavior

2. Class name props are placed on `div.pt-control-group` element so that modifiers such as ".pt-large" work

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Update documentation (added "Large" toggle in basic example)

#### Changes proposed in this pull request:

- `NumericInput` now supports the `pt-large` modifier
- Removed unnecessary styles in `pt-numeric-input` to rely more heavily on defaults defined elsewhere (e.g. now relying on default button widths/paddings for both regular and large buttons).

#### Reviewers should focus on:

- I verified that this looks good in the following cases:
    - Light theme
    - Dark theme
    - Light theme w/ intent
    - Dark theme w/ intent

#### Screenshot

Ignore the shoddy colors; they're an artifact of Gifox.

_Light theme_
image
image

_Dark theme_
image
image

### CODE REVIEW

**Comment by cmslewis** [comment]
@rnadrag FYI

File: packages/core/src/components/forms/numericInput.tsx [hunk 1]
```diff
@@ -201,9 +201,12 @@ export class NumericInput extends AbstractComponent<HTMLInputProps & INumericInp
             "stepSize",
         ], true);
 
+        const isLarge = className != null && className.indexOf(Classes.LARGE) >= 0;
```
Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: Hmm, well we already support the `pt-fill` class on `NumericInput`, so it would seem intuitive to me to support other modifiers like `pt-large` in the same way (i.e. by passing the CSS class explicitly).

Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: but we also have `<Button active>` and #992

**Comment by cmslewis** [comment]
@adidahiya that's a problem on `master`. It's just an issue with the wrapping documentation CSS—maybe a result of the change to Documentalist? Anyway, I'll open a separate PR to fix the full-width functionality in the example.

File: packages/core/src/components/forms/numericInput.tsx (hunk 1 above)
Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: Ah, I like that.

File: packages/core/src/components/forms/numericInput.tsx [hunk 2]
```diff
@@ -47,6 +47,13 @@ export interface INumericInputProps extends IIntentProps, IProps {
     disabled?: boolean;
 
     /**
+     * If set to `true`, the input will display with larger styling.
+     * This is equivalent to setting `pt-large` via className.
```
Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: but it sets `.pt-large` class on multiple elements, so they're not exactly equivalent. worth noting the difference here?

File: packages/core/src/components/forms/numericInput.tsx [hunk 3]
```diff
@@ -236,8 +246,11 @@ export class NumericInput extends AbstractComponent<HTMLInputProps & INumericInp
             const decrementButton = this.renderButton(
                 NumericInput.DECREMENT_KEY, NumericInput.DECREMENT_ICON_NAME, this.handleDecrementButtonClick);
 
+            const buttonGroupClasses = classNames(Classes.BUTTON_GROUP, Classes.VERTICAL, Classes.FIXED, {
+                [Classes.LARGE]: large,
```
Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: actually i don't think this does anything. there are no styles for `.pt-button-group.pt-large`.

the selector is `.pt-button.pt-large, .pt-large .pt-button`.

Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: `pt-button-group` does support the `pt-large` modifier. Here's the code from http://blueprintjs.com/docs/#core/components/button-group.css-api:

```
<div class="pt-button-group pt-large">
  <a class="pt-button pt-icon-database" tabindex="0" role="button">Queries</a>
  <a class="pt-button pt-icon-function" tabindex="0" role="button">Functions</a>
  <a class="pt-button" tabindex="0" role="button">
    Options <span class="pt-icon-standard pt-icon-caret-down pt-align-right"></span>
  </a>
</div>
```

Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: 👎 
but not actually! what's providing the style there is `.pt-large .pt-button` (button inside any large container). the descendant selector was my clever trick to not have to reimplement large buttons on any possible container.

File: packages/core/src/components/forms/numericInput.tsx (hunk 1 above)
Comment (adidahiya) [inline packages/core/src/components/forms/numericInput.tsx]: I don't think this is so brittle... `active` and `loading` make a little more sense as props since you might change them over the lifecycle of the component... but the same is not true for `pt-large` or `pt-fill`. CSS classes work fine

File: packages/core/src/components/forms/numericInput.tsx (hunk 3 above)
Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: I see. Something else to note is that `pt-input-group` gets large styling for free, but only when `pt-large` is applied directly to it. Seems like the choices are:

**Option 1**
```
.pt-numeric-input.pt-large
   .pt-input-group // need to copy a bunch of large input group styles here (maybe via a mixin)
   .pt-button-group .pt-button // need to scope within .pt-button-group b/c the input group may contain buttons too
```

or

**Option 2**
```
.pt-numeric-input.pt-large
   .pt-input-group.pt-large // get large input-group styles for free (from _input-group.scss)
   .pt-button-group .pt-button // get large button styles for free (from _button.scss) due to pt-large ancestor
```

or

**Option 3** *(currently implemented)*
```
.pt-numeric-input
   .pt-input-group.pt-large // get large input-group styles for free
   .pt-button-group.pt-large .pt-button // get large button styles for free
```

Which feels best?

**Comment by cmslewis** [comment]
@giladgray ready for re-review

**Comment by giladgray** [comment]
@cmslewis merge conflicts but looks good

File: packages/core/src/components/forms/numericInput.tsx [hunk 4]
```diff
@@ -204,6 +214,7 @@ export class NumericInput extends AbstractComponent<HTMLInputProps & INumericInp
         const inputGroup = (
             <InputGroup
                 {...inputGroupHtmlProps}
+                className={classNames({ [Classes.LARGE]: large })}
```
Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: add `inputGroupHtmlProps.className`

File: packages/core/src/components/forms/numericInput.tsx [hunk 5]
```diff
@@ -47,6 +47,14 @@ export interface INumericInputProps extends IIntentProps, IProps {
     disabled?: boolean;
 
     /**
+     * If set to `true`, the input will display with larger styling.
+     * This is equivalent to setting `pt-large` via className on the
+     * parent `pt-control-group` and on the child `pt-input-group`.
```
Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: add `.` before class names

File: packages/core/src/components/forms/numericInput.tsx (hunk 4 above)
Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: Good catch.

File: packages/core/src/components/forms/numericInput.tsx (hunk 5 above)
Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: I was copying the format of [`AbstractButton`](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/button/abstractButton.tsx#L33). We should change both if I added a preceding `.` here. Should I go ahead and do that, or leave as is?

**Comment by cmslewis** [comment]
@giladgray ready for re-review.
