### PR TITLE
[Table] Add more checks to componentWillReceiveProps

### LINKED ISSUE #533: Automatically scroll to visible rows when `numRows` is reduced or expanded
### Bug report

**v1.6.0**

If you are scrolled to the bottom of a large table, then the `numRows` prop is reduced, the scroll position is **not** updated so it looks like there are no rows in the table.

Users can scroll up themselves to see the rows, but a better solution would be to adjust the scroll position automatically when the number of rows is reduced. Care should be taken to deal with tables that don't have enough rows to fill a full screen (or available the table area).

#### Steps to reproduce

1. Create table with many `10000` rows
1. Scroll to bottom
1. Update `numRows` prop to `100` or  `5`

#### Actual behavior

You are greeted with a large empty gray space

#### Expected behavior

Scrolls you to some visible rows

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

Added a few checks to `componentWillReceiveProps` to leave the table in a good state post-update: 
- If `enableFocus` toggles from `true` to `false`, clear the focused cell.
- If `selectionModes` changes, clear selected regions having cardinalities that are no longer selectable.
- If the number of rows or columns decreases, auto-scroll to the last row/column to keep it visible.
- If the number of row widths or column heights decrease, auto-scroll to the last row/column to keep it visible.

#### Reviewers should focus on:

- I can add more checks later.

### CODE REVIEW

File: packages/table/src/table.tsx [hunk 1]
```diff
@@ -615,6 +622,32 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         }
     }
 
+    private syncScrollPosition(_prevProps: ITableProps, prevState: ITableState) {
```
Comment (cmslewis) [inline packages/table/src/table.tsx]: This didn't really need to be a separate function since it's only used in one place, but I prefer boxing related functionality into a helper to reduce cognitive load when reading the parent function.

Comment (gscshoyru) [inline packages/table/src/table.tsx]: Why are you passing prevProps if you don't need it though, then? Consistency, of a sort?

File: packages/table/src/table.tsx [hunk 2]
```diff
@@ -615,6 +622,32 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
+        const prevNumCols = prevState.columnWidths.length;
+        const prevNumRows = prevState.rowHeights.length;
+
+        const { numCols, numRows } = this.grid;
+        const { viewportRect } = this.state;
+
+        const maxRowIndex = numRows - 1;
+        const maxColIndex = numCols - 1;
+
+        if (numRows < prevNumRows) {
```
Comment (gscshoyru) [inline packages/table/src/table.tsx]: This only scrolls if there are fewer rows/columns as before, but not if the rows/columns decide to shrink. Do we need to also do code for if they decide to shrink? Is that a separate commit?

File: packages/table/src/table.tsx (hunk 1 above)
Comment (giladgray) [inline packages/table/src/table.tsx]: please remove unused prop

File: packages/table/src/table.tsx (hunk 2 above)
Comment (cmslewis) [inline packages/table/src/table.tsx]: Good thought. Let's do in a separate PR though.

Comment (cmslewis) [inline packages/table/src/table.tsx]: Actually, will do here!

**Comment by cmslewis** [comment]
@giladgray @gscshoyru ready for re-review

File: packages/table/test/tableTests.tsx [hunk 3]
```diff
@@ -783,4 +857,19 @@ describe("<Table>", () => {
     function renderCell() {
         return <Cell>gg</Cell>;
     }
+
+    function updateLocatorBodyElement(table: ReactWrapper<any, {}>,
+                                      left: number,
+                                      top: number,
+                                      width: number,
+                                      height: number) {
```
Comment (giladgray) [inline packages/table/test/tableTests.tsx]: hmm i'd be inclined to name these args for the HTML properties they represent. 
left => scrollLeft, height => clientHeight, etc.

File: packages/table/test/tableTests.tsx [hunk 4]
```diff
@@ -677,6 +663,94 @@ describe("<Table>", () => {
...
+        function renderColumns(numCols: number) {
+            return Array(numCols).fill(undefined).map(renderColumn);
+        }
+
+        function renderColumn(_unused: any, i: number) {
+            return <Column key={i} renderCell={renderCell}/>;
+        }
+
+        function scrollTable(table: ReactWrapper<any, {}>, scrollLeft: number, scrollTop: number) {
+            // make the viewport large enough to fit a single cell in view
```
Comment (giladgray) [inline packages/table/test/tableTests.tsx]: "small enough to fit only one cell" ?

**Comment by cmslewis** [comment]
@giladgray @gscshoyru added a few more tests. take a look when you get a moment.

File: packages/table/src/table.tsx [hunk 5]
```diff
@@ -615,6 +622,31 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         }
     }
 
+    private maybeScrollTableIntoView() {
+        const { viewportRect } = this.state;
+
+        const maxRowIndex = this.grid.numRows - 1;
+        const maxColIndex = this.grid.numCols - 1;
```
Comment (giladgray) [inline packages/table/src/table.tsx]: i'd just inline these in the consts below, where they are each used exactly once.

File: packages/table/src/table.tsx [hunk 6]
```diff
@@ -615,6 +622,31 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
+
+        if (tableBottom < viewportRect.top + viewportRect.height) {
+            // scroll the last row into view
+            nextScrollTop = Math.max(0, tableBottom - viewportRect.height);
+        }
+
+        if (tableRight < viewportRect.left + viewportRect.width) {
+            // scroll the last column into view
+            nextScrollLeft = Math.max(0, tableRight - viewportRect.width);
+        }
```
Comment (giladgray) [inline packages/table/src/table.tsx]: these could be done as ternaries, rather than `let`s:

```js
const nextScrollLeft = (tableRight < viewportRect.left + viewportRect.width)
    ? Math.max(0, tableRight - viewportRect.width)
    : viewportRect.left;
```
