### PR TITLE
[MultiSelect] Uncontrolled selectedItems no longer throws error

### LINKED ISSUE #1785: Not defining selectedItems on MultiSelect throws typeError
### Bug report

- __Package version(s)__: blueprintjs/labs@0.12.0,
- __Browser and OS versions__: Chrome 61.0.3163.100, Mac OS X 10.12.6

#### Steps to reproduce

1. Create a Multi Select without a selectedItems prop defined
1. Try to render it

#### Actual behavior

Type Error: cannot find property 'map' on undefined

The line throwing the error is here: https://github.com/palantir/blueprint/blob/master/packages/labs/src/components/select/multiSelect.tsx#L147

it looks like there is no check to see if selectedItems is undefined on the multi-select, so it barfs if you don't pass it down.  The prop is listed as optional though.

#### Expected behavior

The prop should either be changed to required or there should be a null check

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist
- [x] Include tests

#### Changes proposed in this pull request:
- `MultiSelect` no longer throws an error when `selectedItems` is not controlled.

### CODE REVIEW

File: packages/labs/src/components/select/multiSelect.tsx [hunk 1]
```diff
@@ -111,7 +111,7 @@ export class MultiSelect<T> extends React.Component<IMultiSelectProps<T>, IMulti
     }
 
     private renderQueryList = (listProps: IQueryListRendererProps<T>) => {
-        const { tagInputProps = {}, popoverProps = {} } = this.props;
+        const { tagInputProps = {}, popoverProps = {}, selectedItems } = this.props;
```
Comment (llorca) [inline packages/labs/src/components/select/multiSelect.tsx]: shouldn't `selectedItems = []` here be enough of a fix that you wouldn't need what you added below?

Comment (cmslewis) [reply packages/labs/src/components/select/multiSelect.tsx]: That wouldn't be applied if `selectedItems === null`, but I guess `tagInputProps` and `popoverProps` also aren't hardened to that case. Will change.

File: packages/labs/test/multiSelectTests.tsx [hunk 2]
```diff
@@ -64,6 +64,10 @@ describe("<MultiSelect>", () => {
         assert.strictEqual(handlers.onItemSelect.args[0][0], TOP_100_FILMS[4]);
     });
 
+    it("selectedItems can be missing without throwing an error", () => {
```
Comment (giladgray) [inline packages/labs/test/multiSelectTests.tsx]: `selectedItems is optional`
