### PR TITLE
Fix Overlay2 storing stale onClose callback

### LINKED ISSUE #6748: Overlay has old onClosed callback stored
#### Environment

- __Package version(s)__: 5.10.1
- __Operating System__: Win10
- __Browser name and version__: Chrome 122

#### Code Sandbox

Link to a minimal repro [this code sandbox](https://codesandbox.io/p/devbox/shy-grass-h6nfpx?file=%2Fsrc%2FDialogExample.tsx%3A12%2C5&workspaceId=cc5bb818-707f-498c-b164-c25f45182460&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu1vddf70007356jsfgx0vmf%2522%252C%2522sizes%2522%253A%255B54.236034370382015%252C45.763965629617985%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu1vddf70002356jh8c17mzz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu1vddf70004356jurky3uei%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu1vddf70006356jhb0ogcd3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu1vddf70002356jh8c17mzz%2522%253A%257B%2522id%2522%253A%2522clu1vddf70002356jh8c17mzz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu1z1eq40002356j4270e1sj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDialogExample.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu1z1eq40002356j4270e1sj%2522%257D%252C%2522clu1vddf70006356jhb0ogcd3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu1vddf70005356j7241asjn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu1vddf70006356jhb0ogcd3%2522%252C%2522activeTabId%2522%253A%2522clu1vddf70005356j7241asjn%2522%257D%252C%2522clu1vddf70004356jurky3uei%2522%253A%257B%2522id%2522%253A%2522clu1vddf70004356jurky3uei%2522%252C%2522activeTabId%2522%253A%2522clu1vddf70003356jz3di4peu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu1vddf70003356jz3di4peu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clu1zbpmy00f1356jcbmu5vxw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu1zbpqk01kedjik3fo5ceqw%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D):

#### Steps to reproduce

1. Click "Open Dialog". Drawer will be opened.
2. Click on "Inner Button" button.
3. Click outside of the drawer.

#### Actual behavior

When drawer is closed by outside click, it should call the latest callback passed to "onClose".

#### Expected behavior

Drawer call the first callback that was attached to it when it was opened.

#### Possible solution

This problem isn't only Drawer specific. It reproduces for every component that use Overlay.

I found next problems in overlay2.tsx
**Problem 1:**
line 202:
`
React.useEffect(() => {
        document.removeEventListener("mousedown", handleDocumentMousedown);
    }, [handleDocumentMousedown]);
`
This function intends to remove old callback when the callback was updated. But in fact it tries to remove new callback that wasn't set yet. 
So to fix this, we should keep the old function somewhere and remove it from event callbacks rather than removing the new callback.

**Problem 2:**
Event listener to mousedown on the document is set in "overlayWillOpen" function (line 274):
`document.addEventListener("mousedown", handleDocumentMousedown);`

"overlayWillOpen" function get called only when the drawer is just opened (line 317).
I could understand how this was working in overlay.tsx (previous version of overlay), but it did work before.
We need to reapply eventListener callback each time callback is updated

### PR DESCRIPTION
**Pull request by evansjohnson**
#### Checklist

- [x] Includes tests
- [-] Update documentation

#### Changes proposed in this pull request:
There are 3 changes in this PR, will split to separate PRs on request but figured they are closely related:
1. Fix cleaning up event listeners - previously we'd always be trying to remove the current version of the event listener that will have never been set yet.
2. Ensure we re-attach latest version of event listeners if for example `onClose` updates. We handle `onClose` updating for esc key and backdrop click because the latest callback versions are always passed to the element those are attached to, but did not do a similar update to the document listeners. A test case has been added for this behavior.
3. Ensure we don't call a stale version of the `overlayWillClose` callback on component unmount: [`evanj/overlay-fix?expand=1`#diff-50ceef9007](https://github.com/palantir/blueprint/compare/evanj/overlay-fix?expand=1#diff-50ceef90072c82bdf126a28d4f90f718d8a384f60d4ac90e7b1a9d2c4f4e57d4R342)

#### Reviewers should focus on:
- Any possible breaking changes
- Any possible mistakes when translating logic from `overlayWillOpen` callback directly into `useEffect` hooks

#### Screenshot
n/a

### CODE REVIEW

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 1]
```diff
@@ -325,14 +306,41 @@ export const Overlay2 = React.forwardRef<OverlayInstance, Overlay2Props>((props,
         }
     }, [isOpen, overlayWillOpen, overlayWillClose, prevIsOpen]);
 
-    // run once on unmount
+    // Important: clean up old document-level event listeners if their memoized values change (this is rare, but
```
Comment (evansjohnson) [inline packages/core/src/components/overlay2/overlay2.tsx:297]: I'm not sure if this order matters - I moved these below the `useEffect` that calls `overlayWillOpen` because these event listeners were attached towards the end of that method and I believe `useEffect` hooks are called in order. But now I'm seeing these were also attached before `setRef(lastActiveElementBeforeOpened, getActiveElement(getRef(containerElement)));` and now will be after.

I don't expect that to be an issue, but also don't see any issues if these get attached before the other code in `overlayWillOpen` runs.

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 2]
```diff
@@ -325,14 +306,41 @@ export const Overlay2 = React.forwardRef<OverlayInstance, Overlay2Props>((props,
...
     React.useEffect(() => {
+        if (!isOpen || !(canOutsideClickClose && !hasBackdrop)) {
+            return;
+        }
+
+        document.addEventListener("mousedown", handleDocumentMousedown);
+
         return () => {
-            // we need to run cleanup code to remove some event handlers from the overlay element
-            overlayWillClose();
```
Comment (evansjohnson) [inline packages/core/src/components/overlay2/overlay2.tsx:332]: I wasn't able to find a test case that can assert this because we only call `onClose` from user actions, but I believe this is a function that has a stale closure around old versions of the document event listeners that may have already been removed.

Now we rely on the `useEffect` that adds the event listeners to clean up themselves - but continue calling this for the other overlay cleanup code. I [didn't see any warnings](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener) about calling `removeEventListener` twice/for an already removed handler, and also didn't see any issues with this from my testing, but please flag if this seems bad.

**Review by evansjohnson — COMMENTED** [review]
it may be easier to first review this diff: https://github.com/palantir/blueprint/pull/6874/files/f49bee2d29a5a01eecfe831de5cf5121f1e4cb1a and then see the last commit that just moves the hooks up top lower

File: packages/core/test/overlay2/overlay2Tests.tsx [hunk 3]
```diff
@@ -201,15 +206,18 @@ describe("<Overlay2>", () => {
...
                 </OverlayWrapper>,
             );
 
+            // ensure onClose can be updated
+            const onClose2 = spy();
+            overlay.setProps({ onClose: onClose2 });
             dispatchMouseEvent(document.documentElement, "mousedown");
-            assert.isTrue(onClose.calledOnce);
+            assert.isTrue(onClose.notCalled);
+            assert.isTrue(onClose2.calledOnce);
```
Comment (evansjohnson) [inline packages/core/test/overlay2/overlay2Tests.tsx:220]: this test case was previously failing - the other methods of closing handled updating `onClose` properly

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 4]
```diff
@@ -325,14 +296,41 @@ export const Overlay2 = React.forwardRef<OverlayInstance, Overlay2Props>((props,
...
+            document.removeEventListener("focus", handleDocumentFocus, /* useCapture */ true);
         };
+    }, [handleDocumentFocus, enforceFocus, isOpen]);
 
-        // eslint-disable-next-line react-hooks/exhaustive-deps
+    React.useEffect(() => {
+        // run cleanup code once on unmount, ensuring we call the most recent overlayWillClose callback
+        // by storing in a ref and keeping up to date
+        return () => {
+            mostRecetOverlayWillClose.current();
```
Comment (evansjohnson) [inline packages/core/src/components/overlay2/overlay2.tsx]: similar to https://github.com/palantir/blueprint/pull/6753#pullrequestreview-2012662200 this diff brings this closer to the original behavior, as `overlayWillClose` was previously a class method and so could never be a stale reference

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 5]
```diff
@@ -195,17 +195,6 @@ export const Overlay2 = React.forwardRef<OverlayInstance, Overlay2Props>((props,
...
-    // may happen, for example, if a user forgets to use `React.useCallback` in the `props.onClose` value).
-    // Otherwise, we will lose the reference to those values and create a memory leak since we won't be able
-    // to successfully detach them inside overlayWillClose.
-    React.useEffect(() => {
-        document.removeEventListener("mousedown", handleDocumentMousedown);
-    }, [handleDocumentMousedown]);
-    React.useEffect(() => {
-        document.removeEventListener("focus", handleDocumentFocus, /* useCapture */ true);
-    }, [handleDocumentFocus]);
-
```
Comment (evansjohnson) [inline packages/core/src/components/overlay2/overlay2.tsx:208]: linking diff that added: https://github.com/palantir/blueprint/pull/6681/files#diff-50ceef90072c82bdf126a28d4f90f718d8a384f60d4ac90e7b1a9d2c4f4e57d4R227-R232

I think this had the right idea but I don't think it does what the comment suggests

File: packages/core/src/components/overlay2/overlay2.tsx (hunk 2 above)
Comment (invliD) [reply packages/core/src/components/overlay2/overlay2.tsx:332]: > I believe this is a function that has a stale closure around old versions of the document event listeners that may have already been removed.

Agree, overlayWillClose was not a dependency of this effect but itself had dependencies.

> I didn't see any warnings about calling `removeEventListener` twice

Quoting the page you linked:

> Calling `removeEventListener()` with arguments that do not identify any currently registered event listener on the `EventTarget` has no effect.

This should be fine.

File: packages/core/src/components/overlay2/overlay2.tsx (hunk 5 above)
Comment (invliD) [reply packages/core/src/components/overlay2/overlay2.tsx:208]: > I don't think it does what the comment suggests

Do you mean because it's doing this directly in the effect vs. in a cleanup function returned from the effect? Or did you find something else?

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 6]
```diff
@@ -307,6 +276,8 @@ export const Overlay2 = React.forwardRef<OverlayInstance, Overlay2Props>((props,
             }
         }
     }, [closeOverlay, getLastOpened, handleDocumentFocus, handleDocumentMousedown, id]);
+    const mostRecetOverlayWillClose = React.useRef(overlayWillClose);
```
Comment (invliD) [inline packages/core/src/components/overlay2/overlay2.tsx]: typo
```suggestion
    const mostRecentOverlayWillClose = React.useRef(overlayWillClose);
```

**Review by invliD — DISMISSED** [review]

File: packages/core/src/components/overlay2/overlay2.tsx (hunk 5 above)
Comment (evansjohnson) [reply packages/core/src/components/overlay2/overlay2.tsx:208]: yea, since it's directly in the effect it's reference the version of the handler that was just defined and never had a chance to be attached (or worse was just intentionally attached, but I didn't find a case of this happening)

File: packages/core/src/components/overlay2/overlay2.tsx (hunk 6 above)
Comment (evansjohnson) [reply packages/core/src/components/overlay2/overlay2.tsx]: ah thanks! I decided "mostRecent" was weird anyways and went with `overlayWillCloseRef` and also co-located it with the `useEffect` so it's a bit more clear why we have this ref

**Review by invliD — APPROVED** [review]
