### PR TITLE
[core] feat: Overlay2 component

### LINKED ISSUE #3979: Removing findDOMNode
**Update**:
I think my analysis about how this can be solved is wrong. See my [comment](https://github.com/palantir/blueprint/issues/3979#issuecomment-705573953).

---

As part of the move to strict and concurrent mode support, I'd like to tackle removing usages of `findDOMNode`. I analyzed the scope of changes needed in the first-party components and possible implications on third-party consumers.

### Refs (preferred)
Refs are probably the standard way to get access to an HTML node. Instead of explicitly wiring refs through the consuming component, they can often be set through `cloneElement`.
**Downsides:**
- Can reference JSX elements instead of DOM nodes

**Workarounds:**
- Add a warning in the documentation and print a runtime warning
- Some components already only allow a single DOM node as a child (e.g. `ResizeSensor`)
  - Can clone the element and attach a ref that way

### Wrapper element
**Downsides:**
- Can cause problems with DOM nesting and layout
- Possible performance overhead

**Workarounds:**
- `display: contents;` (doesn't work all most usages)
- Provide `tagName`, etc. properties

### ResizeSensor
ResizeSensor uses `findDOMNode` to attach a ResizeObserver to the child node. It requires a single DOM node child and can use `cloneElement` to attach a ref. I don't know about the performance implications of `cloneElement` (resize sensor explicitly mentions this in the source comments), but `ContextMenuTarget` also uses `cloneElement`. My understanding is that `cloneElement` is pretty cheap. I don't even think it's slower than `findDOMNode`, so I'd say `cloneElement` and attaching a ref is the way to go here.

### ContextMenuTarget
The element returned by `findDOMNode` is used to check if dark mode is enabled or not, by calling a helper method. `ContextMenuTarget` already requires a DOM node and uses `cloneElement` to attach the event-listener so that we can attach a ref in the same call.

### Overlay
If I understand this correctly `TransitionGroup` creates a container by instantiating the component passed to it. As `Overlay` requests a `div`, this `div` is the element we want a reference to. I currently don't know how to get a ref to this `div`. Afaik `TransitionGroup` doesn't expose a reference. This needs some further investigation.

## Conclusion
Without considering `Overlay`, I'd say this is doable without breaking changes. I would split this into three separate tasks.

1. Using `cloneElement` in `ContextMenuTarget` to attach a ref is a non-breaking change. 
2. Using `cloneElement` in `ResizeSensor` to attach a ref is a non-breaking change.
3. `Overlay` needs some further investigation.

There have been previous issues that mentioned `findDOMNode`. For reference:
- #3361 
- #3797

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

- Create new __Overlay2__ component which has the following improvements compared to __Overlay__:
  - it is a function component (see #6289)
  - it utilizes `<CSSTransition nodeRef>` correctly to avoid any code path which uses `ReactDOM.findDOMNode()` (this was not done properly in https://github.com/palantir/blueprint/pull/4623)
- Deprecate __Overlay__
- Add __Overlay2__ example with [`<StrictMode>`](https://react.dev/reference/react/StrictMode) enabled
- Add unit test suite for __Overlay2__ (mostly ported from `overlayTests.tsx`, with some modifications to adjust for the new constraints on `children` - see [migration guide](https://github.com/palantir/blueprint/wiki/Overlay2-migration))
- Migrate straightforward overlay-based components to use Overlay2
	- Dialog
	- Drawer
	- Omnibar
- Migrate complex overlay-based components to use Overlay2
	- OverlayToaster
	- Popover
- Create __Toast2__ component (forwards DOM `ref` to rendered DOM node), deprecate __Toast__
- Add documentation for __Overlay2__, update __OverlayToaster__ documentation

TODO (likely in a future PR):

- [ ] use [react-focus-lock](https://github.com/theKashey/react-focus-lock) to replace a bunch of bespoke focus management code https://github.com/palantir/blueprint/issues/6676
- [x] refactor module-level global `overlayStack` state into a new context/provider pattern #6674
- [x] try [`useImperativeHandle()`](https://react.dev/reference/react/useImperativeHandle) hook to set the `OverlayInstance` ref https://github.com/palantir/blueprint/pull/6675

#### Reviewers should focus on:

No regressions in overlay-based components

#### Screenshot

Overlay2 in docs-app:

Screen Recording 2024-01-23 at 10 36 48 AM

OverlayToaster using Overlay2 and Toast2 in docs-app:

Screen Recording 2024-01-23 at 10 38 05 AM

Toast2 in demo-app:

image

Child ref docs:

<details>

image
image

</details>

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>fix compilation, add docs, strict mode compat</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/b155eaa2-bec1-4aaa-a9f1-ebe93b4b7964/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/b155eaa2-bec1-4aaa-a9f1-ebe93b4b7964/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/b155eaa2-bec1-4aaa-a9f1-ebe93b4b7964/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/b155eaa2-bec1-4aaa-a9f1-ebe93b4b7964/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>fix Overlay2 iso test</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/b5d22d8d-a35c-4d66-bad9-d7e9b18dde0f/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/b5d22d8d-a35c-4d66-bad9-d7e9b18dde0f/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/b5d22d8d-a35c-4d66-bad9-d7e9b18dde0f/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/b5d22d8d-a35c-4d66-bad9-d7e9b18dde0f/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>migrate overlay components to use Overlay2</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/0f2d2d55-3536-4ff4-a1d7-0c45e306b711/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/0f2d2d55-3536-4ff4-a1d7-0c45e306b711/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/0f2d2d55-3536-4ff4-a1d7-0c45e306b711/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/0f2d2d55-3536-4ff4-a1d7-0c45e306b711/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/hooks/useRequestAnimationFrame.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+ * limitations under the License.
+ */
+
+import * as React from "react";
+
+/**
+ * Runs the given callback on the next animation frame. If the frame occurs after the current component has unmounted,
+ * the callback is not invoked.
+ */
+export const useRequestAnimationFrame = (callback: FrameRequestCallback) => {
```
Comment (adidahiya) [inline packages/core/src/hooks/useRequestAnimationFrame.ts]: need to remove this, it's unused

**Comment by adidahiya** [comment]
<h3>fix (almost) all tests</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/aabb4c58-113d-4838-a7a0-f770795783f0/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/aabb4c58-113d-4838-a7a0-f770795783f0/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/aabb4c58-113d-4838-a7a0-f770795783f0/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/aabb4c58-113d-4838-a7a0-f770795783f0/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>Merge remote-tracking branch 'origin/develop' into ad/overlay2</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/c580f9a6-9b41-4ac3-90a1-040f091a1681/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/c580f9a6-9b41-4ac3-90a1-040f091a1681/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/c580f9a6-9b41-4ac3-90a1-040f091a1681/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/c580f9a6-9b41-4ac3-90a1-040f091a1681/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/common/utils/jsUtils.ts [hunk 2]
```diff
@@ -79,3 +79,10 @@ export function uniqueId(namespace: string) {
     uniqueCountForNamespace.set(namespace, curCount + 1);
     return `${namespace}-${curCount}`;
 }
+
+/**
+ * @returns `true` if the value is an empty string after trimming whitespace
+ */
+export function isEmptyString(val: any) {
```
Comment (adidahiya) [inline packages/core/src/common/utils/jsUtils.ts:86]: this should either get used in `reactUtils.ts` (which was the original intent) or be removed

**Comment by adidahiya** [comment]
<h3>update Overlay2 docs</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/afb0c641-be88-42d6-a15b-58331c7debf8/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/afb0c641-be88-42d6-a15b-58331c7debf8/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/afb0c641-be88-42d6-a15b-58331c7debf8/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/afb0c641-be88-42d6-a15b-58331c7debf8/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/components/dialog/dialog.tsx [hunk 3]
```diff
@@ -118,21 +128,31 @@ export class Dialog extends AbstractPureComponent<DialogProps> {
...
-                <div className={Classes.DIALOG_CONTAINER} ref={this.props.containerRef}>
+            <Overlay2
+                {...overlayProps}
+                className={Classes.OVERLAY_SCROLL_CONTAINER}
+                childRef={this.childRef}
+                hasBackdrop={true}
+            >
+                <div
+                    className={Classes.DIALOG_CONTAINER}
+                    ref={containerRef === undefined ? this.childRef : mergeRefs(containerRef, this.childRef)}
```
Comment (adidahiya) [inline packages/core/src/components/dialog/dialog.tsx:142]: we should double-check if `props.containerRef` still works here (is there a unit test?)

File: packages/core/src/components/overlay/overlay.md [hunk 4]
```diff
@@ -1,23 +1,36 @@
...
+<div class="@ns-callout @ns-intent-danger @ns-icon-error @ns-callout-has-body-content">
+    <h5 class="@ns-heading">
+
+Deprecated: use [**Overlay2**](#core/components/overlay2)
+
+</h5>
+
+This component is **deprecated since @blueprintjs/core v5.9.0** in favor of the new
+**Overlay2** component which is compatible with React 18 strict mode. You should migrate to the
+new API which will become the standard in Blueprint v6.
```
Comment (adidahiya) [inline packages/core/src/components/overlay/overlay.md]: as with other places in the docs, we should avoid stating explicit version numbers in these deprecation notices and say instead "a future major version"

File: packages/core/src/components/overlay2/overlay2.md [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+    <h5 class="@ns-heading">DOM ref required</h5>
+
+Overlay2's implementation (via `react-css-transition`) relies on a React ref being attached to a DOM
+element, so the children of this component _must be a native DOM element_ or utilize
+[`React.forwardRef()`](https://reactjs.org/docs/forwarding-refs.html) to forward any
+injected ref to the underlying DOM element.
+
+</div>
+
+TODO(@adidahiya)
```
Comment (adidahiya) [inline packages/core/src/components/overlay2/overlay2.md]: need to remove this TODO

**Review by adidahiya — COMMENTED** [review]
need to deprecate `<Toast>` and update OverlayToaster docs to mention `<Toast2>`

**Comment by adidahiya** [comment]
<h3>fix docs TODO, improve errors</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/bd37e093-4d51-4427-ae1e-ac2edb353b81/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/bd37e093-4d51-4427-ae1e-ac2edb353b81/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/bd37e093-4d51-4427-ae1e-ac2edb353b81/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/bd37e093-4d51-4427-ae1e-ac2edb353b81/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>fix lint</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/f364461c-202e-4f4f-b52e-652900121fa6/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/f364461c-202e-4f4f-b52e-652900121fa6/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/f364461c-202e-4f4f-b52e-652900121fa6/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/f364461c-202e-4f4f-b52e-652900121fa6/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 6]
```diff
@@ -0,0 +1,710 @@
...
+import type { OverlayProps } from "../overlay/overlayProps";
+import { getKeyboardFocusableElements } from "../overlay/overlayUtils";
+import { Portal } from "../portal/portal";
+
+// HACKHACK: ugly global state manipulation should move to a proper React context
+const openStack: OverlayInstance[] = [];
+const getLastOpened = () => openStack[openStack.length - 1];
+
+/**
+ * HACKHACK: ugly global state manipulation should move to a proper React context
```
Comment (adidahiya) [inline packages/core/src/components/overlay2/overlay2.tsx:49]: consider fixing this in this PR and biting the bullet with the necessary `<OverlayProvider>` break

edit: this PR is already quite large, I could add the context/provider in a follow-up before cutting the next release

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 7]
```diff
@@ -0,0 +1,710 @@
...
+                enforceFocus,
+                hasBackdrop,
+                usePortal,
+            },
+        }),
+        [autoFocus, bringFocusInsideOverlay, enforceFocus, handleDocumentFocus, hasBackdrop, id, usePortal],
+    );
+
+    React.useEffect(() => {
+        setRef(ref, instance);
```
Comment (adidahiya) [inline packages/core/src/components/overlay2/overlay2.tsx:219]: consider [`useImperativeHandle`](https://react.dev/reference/react/useImperativeHandle) to do this instead
