### PR TITLE
Fix possibly mis-measured text width in DatePicker

### LINKED ISSUE #316: Utils.measureTextWidth should add span to relevant container not body - measurements are off
My root has font-size of 100px.

My div holding the `<Blueprint.DatePicker>` has `font-size: 16px`.

DatePicker tries to measure the width of the month labels by adding <span>'s to the body - as a result the measurements are wrong.  I'd suggest the <span>'s get appended to the component container and NOT document.body.

This would stop differing font-sizes from screwing things up.

### PR DESCRIPTION
**Pull request by cmslewis**
#### Changes proposed in this pull request:

- Add an optional third `containerElement` parameter to `Utils.measureTextWidth` (defaults to `document.body`)
- Leverage this in `DatePicker` to ensure we're measuring text as sized within that component 

#### Reviewers should focus on:

- FYI: I added `*Element` suffixes to each of the elements for clarity and consistency. The type handles that, but this makes things easier to read quickly at a glance.
- FYI: Verified that this works by changing body text size to `100px` and observing that the `<DatePicker>` dropdown arrows still appeared in the expected place.

### CODE REVIEW

File: packages/datetime/src/datePickerCaption.tsx [hunk 1]
```diff
@@ -101,16 +105,19 @@ export class DatePickerCaption extends React.Component<IDatePickerCaptionProps,
         this.positionArrows();
     }
 
-    private monthArrowRefHandler = (r: HTMLElement) => this.monthArrow = r;
-    private yearArrowRefHandler = (r: HTMLElement) => this.yearArrow = r;
+    private containerRefHandler = (r: HTMLElement) => this.containerElement = r;
+    private monthArrowRefHandler = (r: HTMLElement) => this.monthArrowElement = r;
+    private yearArrowRefHandler = (r: HTMLElement) => this.yearArrowElement = r;
```
Comment (adidahiya) [inline packages/datetime/src/datePickerCaption.tsx]: unrelated: I would like to move to the following pattern for ref handlers:

```ts
private refHandlers = {
    container: (r: HTMLElement) => this.containerElement = r,
    monthArrow: ...,
    yearArrow: ...,
};
```

Comment (giladgray) [inline packages/datetime/src/datePickerCaption.tsx]: i'm accumulating a list of major refactors to datetime code, for the new year... will add this!

**Comment by paulpooch** [comment]
This looks great. Thank you.  I also like the refHandler pattern you're using.  I was doing the gross

`<div ref={ (el) => (this.fooRef = el) } />` style.

PS You guys above Hill Country?

**Comment by giladgray** [comment]
@paulpooch yes the `refHandlers` property is great! our TSLint config disallows [lambdas in JSX](https://github.com/palantir/tslint-react#rules) cuz functions interfere with React's diffing, so we had to look for other answers.

what's this Hill Country?

**Comment by paulpooch** [comment]
Hill Country was in reference to one of your NYC offices.
