### PR TITLE
[site-docs] fix theme switcher inheritance

### LINKED ISSUE #163: Popover does not inherit theme change till second click
### Bug Report

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: Windows 10, Firefox 49.0.2

#### Describe the issue:

1.  Go to http://blueprintjs.com/docs/#components.popover
2.  Make sure inherit theme is selected
3.  Change theme using the icon in navbar
4.  Click button 'Popover target'
5. Dismiss and click it again

#### Actual behavior:

Does not inherit the theme change till second click

#### Expected behavior:

Should inherit the team change on first click

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- the actual fix for the issue was ensuring that we call `this.setState()` _after_ updating local storage with new theme state so that the examples are seeing the latest state when they re-render.
- refactor BaseExample `getTheme` callback prop to string `themeName`, for simplicity.

#### Focus on

- Popover and Tooltip examples should respond to theme switching every time.

Here's a cool thing:
toasts-dark-inheritance

### CODE REVIEW

File: packages/core/src/components/popover/popover.tsx [hunk 1]
```diff
@@ -381,10 +381,13 @@ export class Popover extends AbstractComponent<IPopoverProps, IPopoverState> {
         if (props.isModal && props.interactionKind !== PopoverInteractionKind.CLICK) {
             throw new Error(Errors.POPOVER_MODAL_INTERACTION);
         }
-        try {
-            React.Children.only(props.children);
-        } catch (e) {
-            throw new Error(Errors.POPOVER_ONE_CHILD);
+        if (typeof props.children === "object") {
```
Comment (cmslewis) [inline packages/core/src/components/popover/popover.tsx]: what's the reasoning for the change here? just ensuring we support non-JSX children in `Popover` without freaking out?

Comment (giladgray) [inline packages/core/src/components/popover/popover.tsx]: i'm not sure what changed but i was getting errors for tooltips with string targets (a very common use case, I imagine). `React.Children.only` asserts that it must have a single _React element_ child, which does not include strings.

this checks first that children is not a basic type before testing the assertion.
