### PR TITLE
[node-build-scripts] fix(generate-css-variables): LibSass compat

### LINKED ISSUE #5244: variables.scss is incompatible with node-sass
#### Environment

- __Package version(s)__: core v4.1.1

#### Bug

@blueprintjs/core v4.1.1 contains a `lib/scss/variables.scss` file which uses `@use "sass:math"` and `math.div(...)`. This language feature is only available in Dart Sass v1.33+, and not available in LibSass / node-sass ([see docs](https://sass-lang.com/documentation/modules/math#div)). This means that node-sass compatibility is broken in the latest release.

#### Solution

Update `generate-css-variables` script, use `get-sass-vars` functionality (we are already doing this to generate Less variables) to simplify the variable values and compute the math which `math.div()` is currently doing.

### PR DESCRIPTION
**Pull request by pgoldberg**
#### Fixes #5244

Uses `get-sass-vars` for scss variable generation as well as less generation

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

### CODE REVIEW

File: packages/node-build-scripts/generate-css-variables.js [hunk 1]
```diff
@@ -33,94 +33,139 @@ function main() {
...
         .replace(/(@import|\/\/).*\n+/g, "")
         .replace(/@use "sass:math";\n/g, "")
         .replace(/border-shadow\((.+)\)/g, "0 0 0 1px rgba($black, $1)")
         .replace(/\n{3,}/g, "\n\n");
     if (!retainDefault) {
-        variablesScss = variablesScss.replace(/\ \!default/g, "");
+        cleanedInput = cleanedInput.replace(/\ \!default/g, "");
     }
-    variablesScss = [COPYRIGHT_HEADER, USE_MATH_RULE, variablesScss].join("\n");
+    cleanedInput = [USE_MATH_RULE, cleanedInput].join("\n");
```
Comment (adidahiya) [inline packages/node-build-scripts/generate-css-variables.js:64]: no need for the USE_MATH_RULE now, we can remove that constant completely

**Review by adidahiya — DISMISSED** [review]

File: packages/node-build-scripts/generate-css-variables.js (hunk 1 above)
Comment (pgoldberg) [reply packages/node-build-scripts/generate-css-variables.js:64]: It is actually needed here so it can properly run through `getSassVars` (which compiles with `sass`, so without it, it wouldn't know how to resolve `math.div`s). When it goes through `generateScssVariables` there's no outputted `@use "sass:math"`

Comment (adidahiya) [reply packages/node-build-scripts/generate-css-variables.js:64]: oh wait, I guess we need this to compute the values... sorry, disregard

**Review by adidahiya — APPROVED** [review]
lgtm, I verified the variables.scss and variables.less output locally
