### PR TITLE
[core] fix(Overlay2): use mutable stack ref, fix document event listeners

### LINKED ISSUE #6679: Cannot select items inside overlay
#### Environment

- __Package version(s)__: @blueprintjs/core unreleased as of https://github.com/palantir/blueprint/pull/6674
- __Operating System__: macOS
- __Browser name and version__: Firefox

#### Steps to reproduce

1. open [docs preview build](https://output.circle-artifacts.com/output/job/8a91ccec-dcb7-4f58-a8ba-cdbed4156d64/artifacts/0/packages/docs-app/dist/index.html) from #6674 (where this regression was introduced)
1. attempt to select an option in a `<Select>` dropdown

#### Actual behavior

no selection happens

Screen Recording 2024-01-26 at 10 46 43 AM

#### Expected behavior

selection works, like it does in latest release (v5.8.x) and after the Overlay2 PR (https://github.com/palantir/blueprint/pull/6656):

Screen Recording 2024-01-26 at 10 47 56 AM

#### Possible solution

some bug in the `useOverlaysStack()` "click in this overlay or descendants" implementation

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

- fix(`Overlay2`): improve overlay stack state management to fix document mousedown event handler

#### Reviewers should focus on:

Fixes the linked bug

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>WIP fix useOverlayStack</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/2d3d2cf5-7e7d-4beb-9780-f037d13102f3/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/2d3d2cf5-7e7d-4beb-9780-f037d13102f3/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/2d3d2cf5-7e7d-4beb-9780-f037d13102f3/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/2d3d2cf5-7e7d-4beb-9780-f037d13102f3/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>use mutable stack</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/3c91095b-6e90-4eed-9f34-53ce8dfc848e/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/3c91095b-6e90-4eed-9f34-53ce8dfc848e/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/3c91095b-6e90-4eed-9f34-53ce8dfc848e/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/3c91095b-6e90-4eed-9f34-53ce8dfc848e/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/table-dev-app/src/index.tsx [hunk 1]
```diff
@@ -24,10 +24,10 @@ import { Nav } from "./nav";
 
 ReactDOM.render(<Nav selected="index" />, document.getElementById("nav"));
 ReactDOM.render(
-    <HotkeysProvider>
-        <OverlaysProvider>
+    <OverlaysProvider>
+        <HotkeysProvider>
```
Comment (adidahiya) [inline packages/table-dev-app/src/index.tsx:28]: need to add docs about the ordering of these providers. will do that in a separate PR which adds `<BlueprintProvider>`

**Comment by adidahiya** [comment]
<h3>fix lint: break import cycle</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/71087a20-0ef7-4d24-9a6c-be5c80fa068d/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/71087a20-0ef7-4d24-9a6c-be5c80fa068d/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/71087a20-0ef7-4d24-9a6c-be5c80fa068d/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/71087a20-0ef7-4d24-9a6c-be5c80fa068d/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/components/overlay2/overlay2.tsx [hunk 2]
```diff
@@ -55,6 +55,9 @@ export interface OverlayInstance {
     /** Document "focus" event handler which needs to be attached & detached appropriately. */
     handleDocumentFocus: (e: FocusEvent) => void;
 
+    /** Document "mousedown" event handler which needs to be attached & detached appropriately. */
```
Comment (adidahiya) [inline packages/core/src/components/overlay2/overlay2.tsx:58]: now that there's an appropriate global context manager to handle this kind of logic, we should consider refactoring this behavior to have a single handler for the whole overlay stack instead of separate handlers for each overlay which need to be attached/detached. that would likely be safer and less prone to memory leaks.
