### PR TITLE
[DateRangeInput] Pass locale to moment for formatting, part 2

### LINKED ISSUE #1428: [DateInput] Locale not passed to moment for i18n format strings like `L`
### Bug report

- __Package version(s)__: @blueprintjs/datetime 1.19.0
- __Browser and OS versions__: All

#### Steps to reproduce

1. Pass a format string to `DateInput` like `L` and a locale with a different date format.

#### Actual behavior

`L` still outputs the expected `en-US` format.

#### Expected behavior

The output should be based on the provided `locale` prop.

### PR DESCRIPTION
**Pull request by AlexLandau**
#### Fixes #1428 for date range inputs

This PR is closely related to #1429. We didn't notice that the date range input was a separate component from the date input. This applies the same two fixes (applying the locale at parsing time and at formatting time) to the date range input.

#### Screenshot

screen shot 2017-08-21 at 7 47 09 pm

(Note: To get the screenshot of the change, I had to add "L" to the list of formats and set the locale of the DateRangeInput. Neither of these changes are currently in the PR.)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @AlexLandau! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by AlexLandau** [comment]
Note: This PR is closely related to #1429. We didn't notice that the date range input was a separate component from the date input. This applies the same two fixes (applying the locale at parsing time and at formatting time) to the date range input.

File: packages/datetime/src/dateRangeInput.tsx [hunk 1]
```diff
@@ -790,13 +790,18 @@ export class DateRangeInput extends AbstractComponent<IDateRangeInputProps, IDat
...
-    private getFormattedDateString = (momentDate: moment.Moment, format?: string) => {
+    private getFormattedDateString = (momentDate: moment.Moment, formatOverride?: string) => {
         if (isMomentNull(momentDate)) {
             return "";
         } else if (!momentDate.isValid()) {
             return this.props.invalidDateMessage;
         } else {
-            return momentDate.format((format != null) ? format : this.props.format);
+            const format = (formatOverride != null) ? formatOverride : this.props.format;
+            if (this.props.locale) {
```
Comment (cmslewis) [inline packages/datetime/src/dateRangeInput.tsx]: I noticed this same code also appeared in #1429. Let's pull this out into a utility function in `dateUtils.ts`:

Maybe:

```tsx
/**
 * Returns a date string in the provided format localized to the provided locale.
 */
export function toLocalizedDateString(momentDate: moment.Moment, format: string, locale: string) {
    const adjustedMomentDate = (locale != null) ? momentDate.locale(locale) : momentDate;
    return adjustedMomentDate.format(format);
}
```

File: packages/datetime/test/dateRangeInputTests.tsx [hunk 2]
```diff
@@ -2303,6 +2305,11 @@ describe("<DateRangeInput>", () => {
             startInput.simulate("blur");
             assertInputTextsEqual(root, START_STR, "");
         });
+
+        it("Formats locale specific format strings properly", () => {
```
Comment (cmslewis) [inline packages/datetime/test/dateRangeInputTests.tsx]: ubernit: should hyphenate `locale-specific` 🤓

File: packages/datetime/test/dateRangeInputTests.tsx [hunk 3]
```diff
@@ -2303,6 +2305,11 @@ describe("<DateRangeInput>", () => {
...
+            const { root } = wrap(<DateRangeInput locale="de" format="L" value={DATE_RANGE_2}/>);
```
Comment (cmslewis) [inline packages/datetime/test/dateRangeInputTests.tsx]: add space before `/>`

**Comment by AlexLandau** [comment]
@cmslewis I've addressed your comments. (I did tweak the locale type in your suggested function to "string | undefined", since it will make things easier if you ever decide to move to strict null checks and will give extra context in the meantime.)
