### PR TITLE
[core] fix(HotkeyParser): use e.code to get physical keys

### LINKED ISSUE #6257: [v5] Hotkeys using `alt` no longer work as expected
#### Environment

- __Package version(s)__: 5.0.0-beta.2
- __Operating System__: OSX
- __Browser name and version__: Chrome 114.0.5735.133

#### Code Sandbox

https://stackblitz.com/edit/vitejs-vite-vsbugp?file=src%2FCoreExample.tsx

#### Steps to reproduce

1. Make a hotkey like this:

```
      {
        label: "test",
        global: true,
        combo: "alt+a",
        onKeyDown: () => {
          alert("here");
        }
      }
```

2. Attempt to trigger it with `alt+a`

#### Actual behavior

Nothing happens.

#### Expected behavior

Alert appears.

#### Possible solution

This line swapped the key combo parsing to use `event.key` instead of `event.which`: https://github.com/palantir/blueprint/pull/6106/files#diff-fec59d61737971c807d9d0b765c8d0c3ba1d1f1880cdd4b3a652ab0789d016dbR169

The `key` in the case of `alt+a` is `å`, and I suspect is also variable depending on keyboard settings. Probably shouldn't depend on `key` for parsing key combos?

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Refactor HotkeyParser functions to use `event.code` instead of `event.key` in most cases. This property is more reliable than `event.key` since the latter is prone to changing based on keyboard layout and modifier keys. This change restores the behavior of the hotkey parser (which is responsible for taking a user-requested key combo and generating the appropriate event handler) to that of Blueprint v4.x (it regressed in v5.0 via https://github.com/palantir/blueprint/pull/6106).

I also updated the docs to move the "Key combo" and "hotkeys tester" sections to the non-deprecated `useHotkeys` documentation (previously this was only available on the "Hotkeys (legacy)" docs page).

#### Reviewers should focus on:

No regressions in `useHotkeys()`

#### Screenshot

before this change:

after this change:

in [Blueprint v4.x legacy docs](https://blueprintjs.com/docs/versions/4/#core/components/hotkeys.key-combos):

### CODE REVIEW

File: packages/core/src/components/hotkeys/hotkeyParser.ts [hunk 1]
```diff
@@ -61,18 +61,9 @@ export const CONFIG_ALIASES: KeyMap = {
     space: " ",
 };
 
+/** Key mapping used in getKeyCombo() implementation for physical keys which are not alphabet characters or digits. */
 export const SHIFT_KEYS: KeyMap = {
     "~": "`",
-    "!": "1",
```
Comment (adidahiya) [inline packages/core/src/components/hotkeys/hotkeyParser.ts:66]: We no longer need the 0-9 digit keys in this mapping because we now handle events with `{ code: "DigitX" }` in a more straightforward way. In a future PR, we can remove this `KeyMap` entirely by switching to `event.code` for more keys, but for now I decided to be conservative and make fewer behavioral changes in this PR.

Edit: I added a code comment to reflect this

File: packages/core/src/components/hotkeys/hotkeyParser.ts [hunk 2]
```diff
@@ -130,7 +121,10 @@ export const parseKeyCombo = (combo: string): KeyCombo => {
 };
 
 /**
- * Converts a keyboard event into a valid combo prop string
+ * Interprets a keyboard event as a valid KeyCoboTag `combo` prop string value.
```
Comment (adidahiya) [inline packages/core/src/components/hotkeys/hotkeyParser.ts]: nit: typo

```suggestion
 * Interprets a keyboard event as a valid KeyComboTag `combo` prop string value.
```

**Comment by adidahiya** [comment]
<h3>[core] fix(HotkeyParser): use e.code to get physical keys</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/4195bedc-ced5-48c9-bf29-72c9afedbc39/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/4195bedc-ced5-48c9-bf29-72c9afedbc39/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/4195bedc-ced5-48c9-bf29-72c9afedbc39/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/4195bedc-ced5-48c9-bf29-72c9afedbc39/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>Fix self-review and lint</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/eceb21a6-ffb6-470c-95de-9f7869863296/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/eceb21a6-ffb6-470c-95de-9f7869863296/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/eceb21a6-ffb6-470c-95de-9f7869863296/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/eceb21a6-ffb6-470c-95de-9f7869863296/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
I think there's one more regression compared to v4.x which is worth fixing related to the "space" key.

Currently with this PR:



On [v4.x legacy docs](https://blueprintjs.com/docs/versions/4/#core/components/hotkeys.key-combos):

**Comment by adidahiya** [comment]
<h3>use e.code for space key</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/df6b32c7-ee18-498c-b0c6-ae0d57681e54/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/df6b32c7-ee18-498c-b0c6-ae0d57681e54/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/df6b32c7-ee18-498c-b0c6-ae0d57681e54/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/df6b32c7-ee18-498c-b0c6-ae0d57681e54/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>
