### PR TITLE
fix bug related to ticket #6703 placeholder not updating due to wrong…

### LINKED ISSUE #6703: Controlled DateInput3 does not display new values if popover is closed without selecting a date
#### Environment

- __Package version(s)__:
  "@blueprintjs/core": "^5.9.1",
  "@blueprintjs/datetime": "^5.3.1",
  "@blueprintjs/datetime2": "^2.3.1",
- __Operating System__: Windows 11
- __Browser name and version__: Firefox 122.0

#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/p/devbox/eloquent-swanson-h79ky6?file=%2Fsrc%2FDatetimeExample.tsx

#### Steps to reproduce

1. Click within the input to open the popover
1. Click outside the popover to close it, without selecting a date
1. Click `Now` to set the date

#### Actual behavior

The displayed date in the DateInput still shows the placeholder text, and does not change to the new value.

This only occurs if the popover was opened without a date already set, and closed without selecting a date within the popover.

#### Expected behavior

The displayed text in the DateInput should change to 'now'.

### PR DESCRIPTION
**Pull request by sc-mitton**
… focus state

#### Fixes #6703

Fix a bug where the value isn't updating from controlled input.

Screenshot 2024-12-10 at 6 22 24 PM

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @sc-mitton! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/datetime2/src/components/date-input3/dateInput3.tsx [hunk 1]
```diff
@@ -373,6 +373,7 @@ export const DateInput3: React.FC<DateInput3Props> = React.memo(function _DateIn
     const handleInputBlur = React.useCallback(
         (e: React.FocusEvent<HTMLInputElement>) => {
             if (inputValue == null || valueAsDate == null) {
+                setIsInputFocused(false);
```
Comment (ggdouglas) [inline packages/datetime2/src/components/date-input3/dateInput3.tsx:377]: This seems to fix the bug where a controlled prop passed to DateInput3 is set to a particular value, but it still seems to miss when the value is cleared, e.g.
Screenshot 2025-01-07 at 12 14 49
Can we also handle that related case here?

I think it should be a matter of affecting one of the useEffects above to handle the case where `valueFromProps` gets set to to a nullish value. Something like:
```ts
React.useEffect(() => {
    if (isControlled || valueFromProps == null) {
        setValue(valueFromProps);
    }
}, [isControlled, valueFromProps]);
```

Comment (sc-mitton) [reply packages/datetime2/src/components/date-input3/dateInput3.tsx:377]: `const isControlled = valueFromProps !== undefined;`

The isControlled variable is already defined as valueFromProps !== undefined. So isControlled || valueFromProps == null would be redundant no? If valueFromProps == null is true, then isControlled is already true.

Comment (sc-mitton) [reply packages/datetime2/src/components/date-input3/dateInput3.tsx:377]: I'm also not having this issue you mentioned in my local dev. In the hook you mentioned the value should be cleared.

Comment (ggdouglas) [reply packages/datetime2/src/components/date-input3/dateInput3.tsx:377]: Apologies! I didn't have access to the original repro from the issue. It's possible that I have some other confounding variable in my local example that is causing this.

**Review by ggdouglas — APPROVED** [review]
Thanks for the fix 🙂
