### PR TITLE
[hotkeys] Fix sorting for global hotkey groups with labels

### LINKED ISSUE #2439: Hotkey popup sorting
### Bug report

- __Package version(s)__: 2.2.0
- __Browser and OS versions__: Mac Chrome Version 65.0.3325.181 (Official Build) (64-bit)

#### Steps to reproduce

1. Add hotkeys
2. Press `?` to open the hotkey popup

#### Actual behavior

Hotkeys are not grouped together and are out of order

#### Expected behavior

Hotkeys should be grouped together and remain in the order they are defined.

screen shot 2018-04-30 at 4 19 13 pm

### PR DESCRIPTION
**Pull request by jeroenvisser101**
Hotkey groups with labels that are have the global={true} prop should
now also be alphabetically sorted.

Fixes #2439 

#### Changes proposed in this pull request:
The change will prioritize global hotkeys, but still sort them with other global hotkey groups. If a hotkey group is both global but also has a group name, it will still sort it alphabetically.

#### Reviewers should focus on:
Sorting and order of global hotkey groups with a group name set.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @jeroenvisser101! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/core/src/components/hotkeys/hotkeys.tsx [hunk 1]
```diff
@@ -44,15 +44,12 @@ export class Hotkeys extends AbstractPureComponent<IHotkeysProps, {}> {
             (child: React.ReactElement<IHotkeyProps>) => child.props,
         );
 
-        // sort by group label alphabetically, globals first
+        // sort by group label alphabetically, prioritize globals
         hotkeys.sort((a, b) => {
-            if (a.global) {
-                return b.global ? 0 : -1;
+            if ((a.global && b.global) || (!a.global && !b.global)) {
```
Comment (giladgray) [inline packages/core/src/components/hotkeys/hotkeys.tsx]: how about `if (a.global === b.global)`?

Comment (jeroenvisser101) [reply packages/core/src/components/hotkeys/hotkeys.tsx]: Ah! That's a good one

Comment (giladgray) [reply packages/core/src/components/hotkeys/hotkeys.tsx]: cool, waiting for a push from you.

**Comment by jeroenvisser101** [comment]
@giladgray I added tests, and they do test the sorting, but they only test the appearance order of the labels. I think that should do it, but please let me know if there are better ways of doing that.

**Comment by jeroenvisser101** [comment]
Thanks!
