### PR TITLE
Make HotkeysDialog not inline

### LINKED ISSUE #359: Hotkey dialog does not close
### Bug report

image
Chrome, Mac

#### Steps to reproduce

1.  Open hotkey dialog via `?`
2. Attempt to close dialog by clicking away
Expected: Closes
Actual: Does not close
3. Attempt to close via ESC - does not work

You can close via ESC if you haven't click elsewhere.

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

- Make `HotkeysDialog` **not** inline
- Add a unit test to verify that the `HotkeysDialog` doesn't render inline 

_BEFORE:_

before

_AFTER:_

after

#### Reviewers should focus on:

I've verified that the dialog closes when you click the background and/or when you press <kbd>Esc</kbd>.

### CODE REVIEW

**Comment by adidahiya** [comment]
devtested that this fixes #359 on Chrome and FF 👍

File: packages/core/test/hotkeys/hotkeysTests.tsx [hunk 1]
```diff
@@ -124,6 +124,7 @@ describe("Hotkeys", () => {
             // wait for the dialog to animate in
             setTimeout(() => {
                 expect(document.querySelector(".pt-hotkey-column")).to.exist;
+                expect(document.querySelector(".pt-overlay-open").classList.contains("pt-overlay-inline")).to.be.false;
```
Comment (adidahiya) [inline packages/core/test/hotkeys/hotkeysTests.tsx]: I'm ok with merging this for the PR, but this is a tautological test that doesn't really help to prevent bugs (it matches exactly what you wrote in the component markup / props)

Comment (cmslewis) [inline packages/core/test/hotkeys/hotkeysTests.tsx]: Yeah makes sense. Just figured a shoddy palisade would be better than no defense at all.
