### PR TITLE
[Popover] Improved focus event handling

### LINKED ISSUE #2373: Tooltip pops up repeatedly on changing tab
### Bug report

- __Package version(s)__: 2.1.1
- __Browser and OS versions__: Chrome 65, Windows 10

#### Steps to reproduce

1. Wrap a button in a tooltip and place this inside an input group.
1. Pass focus to the button.
1. Change the tab out and back in.

Eg: The "Enter the password" example in the [docs](http://blueprintjs.com/docs/v2/#core/components/forms/input-group).

#### Actual behavior

Tooltips pops up every time the tab is switched to.

#### Expected behavior

Tooltip shouldn't display on its own.

### PR DESCRIPTION
**Pull request by reiv**
#### Changes proposed in this pull request:

This PR makes two changes to the way `Popover` handles focus events.

1. Use [`FocusEvent.relatedTarget`](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent)¹ instead of wrapping `document.activeElement` in a timeout to accomplish the same.
2. Check if the target gained focus when it was already previously focused but the *page itself* lost focus (e.g. due to tabbing out) -- in this case the popover won't open again.

___________

<sup>[1] MDN says this is "experimental technology", but it seems to be available in all browsers save for IE < 9.</sup>

### CODE REVIEW

**Comment by reiv** [comment]
<h3>Ignore focus gained from outside page</h3>

Preview: <strong><a href='https://491-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://491-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://491-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

File: packages/core/src/components/popover/popover.tsx [hunk 1]
```diff
@@ -499,23 +503,26 @@ export class Popover extends AbstractPureComponent<IPopoverProps, IPopoverState>
...
+                // ignore this focus event -- the target was already focused but the page itself
+                // lost focus (e.g. due to switching tabs).
+                return;
+            }
             this.handleMouseEnter(e);
         }
     };
 
-    private handleTargetBlur = (e?: React.FormEvent<HTMLElement>) => {
+    private handleTargetBlur = (e?: React.FocusEvent<HTMLElement>) => {
```
Comment (giladgray) [inline packages/core/src/components/popover/popover.tsx]: can we make this arg required? to ensure that it exists before you reference it

File: packages/core/src/components/popover/popover.tsx [hunk 2]
```diff
@@ -499,23 +503,26 @@ export class Popover extends AbstractPureComponent<IPopoverProps, IPopoverState>
         }
     };
 
-    private handleTargetFocus = (e?: React.FormEvent<HTMLElement>) => {
+    private handleTargetFocus = (e?: React.FocusEvent<HTMLElement>) => {
```
Comment (giladgray) [inline packages/core/src/components/popover/popover.tsx]: required?

File: packages/core/src/components/popover/popover.tsx (hunk 1 above)
Comment (reiv) [reply packages/core/src/components/popover/popover.tsx]: Sure thing. No idea why it was optional to begin with. API change in React?

**Comment by reiv** [comment]
<h3>Make event arg non-optional</h3>

Preview: <strong><a href='https://497-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://497-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://497-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by giladgray** [comment]
@reiv what's the best way to verify this feature in the docs preview? perhaps you could add a switch for `openOnTargetFocus` in the example after `canEscapeKeyClose` in the Interactions column? 
image

**Comment by giladgray** [comment]
@reiv ah yes of course, thanks. in this PR, the tooltip no longer re-opens when switching back to the page, but i think ideally the tooltip wouldn't close when you leave the page (`relatedTarget == null`). is that possible to implement?

**Comment by reiv** [comment]
@giladgray That sounds reasonable. I'll check it out when I get the time.

**Comment by giladgray** [comment]
thanks @reiv, you are a champion! 🏆

**Comment by reiv** [comment]
@giladgray Ok so the behavior in #2373 is actually a bit more nuanced than that, and your suggestion alone wouldn't change it. To break it down step by step:

1. Let's say I'm hovering the popover target with the mouse, causing the popover to appear.
2. I then *click* the target, causing it to acquire focus (if it is focusable, either due to being an interactive element or via the `openOnTargetFocus` prop).
3. Now I move the mouse away, which is what initially causes the popover to close. (Note that the target still has focus at this point).
4. Then I navigate away from the page by tabbing out, clearing focus on that page.
5. Finally, I return to the page, causing focus to return to the target and re-opening the popover. It feels weird because I already mentally registered "dismissing" the popover by moving the mouse away from it. 

In order to reconcile this with your suggestion, the popover would need to stay open *as long as the popover target has focus*, even if the hover interaction dictates that it should close. I'm not sure what this means for `canEscapeKeyClose`, though. I think maybe the current state of the PR has the least surprising user experience, compared to all the focus-related edge cases we would otherwise have to consider.

**Comment by giladgray** [comment]
@reiv thank you for investigating! what you describe makes good sense about opened vs focused. perhaps we could add some "opened & focused & lost focus to other page" logic but that's starting to feel crufty, so let's call it here. 

the behavior in this PR is certainly an improvement so let's ship it!
