### PR TITLE
[DateTimePicker] Fix where changing TimePicker clears date

### LINKED ISSUE #1402: [DateTimePicker] Clears selected day when arrow keys used in TimePicker
### Bug report

- datetime 1.19.0 
- Chrome 60, macOS 

#### Steps to reproduce

1. Select a day and time in a `DateTimePicker` in the docs
1. Click inside a `TimePicker` input and use the arrows to change the time

#### Actual behavior

The selected day unselects itself

#### Expected behavior

The selected day stays selected

#### Demo

Just noticed this bug and wanted to report it! It isn't affect me personally, so it's not urgent at all from my end.

### PR DESCRIPTION
**Pull request by cathyxz**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)
- [x] Add unit tests

#### Changes proposed in this pull request:
In dateTimePicker component, we should only reset the state based on props if the props have actually changed. Otherwise, we will needless clear or reset DateTimePicker state based on props that have not changed. 

#### Screenshot
bugfix

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/blueprint/1474)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @cathyxz! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
Thanks @cathyxz! Would you be able to add a unit test that asserts the bug is fixed? Like, changing time props should not reset date.

File: packages/datetime/src/dateTimePicker.tsx [hunk 1]
```diff
@@ -96,14 +96,16 @@ export class DateTimePicker extends AbstractComponent<IDateTimePickerProps, IDat
...
     public componentWillReceiveProps(nextProps: IDatePickerProps) {
-        if (nextProps.value != null) {
-            this.setState({
-                dateValue: nextProps.value,
-                timeValue: nextProps.value,
-            });
-        } else {
-            // clear only the date to remove the selected-date style in the calendar
-            this.setState({ dateValue: null });
+        if (this.props.value !== nextProps.value) {
```
Comment (cmslewis) [inline packages/datetime/src/dateTimePicker.tsx]: nit: would prefer this structure to avoid nesting everything so much:

```tsx
if (this.props.value === nextProps.value) {
    return;
} else if (nextProps.value != null) {
    // ....
} else {
    // ...
}
```

Comment (cathyxz) [inline packages/datetime/src/dateTimePicker.tsx]: I actually like it better too...

**Comment by giladgray** [comment]
@cathyxz case in point for why you should not force-push: try to click the filename for chris' comment above and you'll see a sad github page. https://github.com/palantir/blueprint/pull/1474/files/4f0d54473b9647c02915d9270b66403fb06f8256

**Comment by giladgray** [comment]
also @cathyxz can we get that unit test?

**Comment by cathyxz** [comment]
I added the unit test, but I'm not too sure now about this being the correct fix.

Since @cmslewis wrote logic to ensure that passing a `null` or `undefined` value clears the selected date, I'm not actually sure whether we should fix the `DateTimePicker` or the usage of it in our `DateTimePickerExample`. `DateTimePickerExample` is kind of weird in the sense that it does not pass a `value` prop, thus `value` here defaults to undefined. Usually if you are controlling the `DateTimePicker`, I imagine you would want to control the value. For example, an equally effective fix for the original problem would be to pass in `state.date` from the `DateTimePickerExample` as `value`. This would entail something more along the lines of a docs clarification. Basically to require that if you pass in an `onChange`, then you also have to manage the `value`?

File: packages/datetime/test/dateTimePickerTests.tsx [hunk 2]
```diff
@@ -101,6 +100,14 @@ describe("<DateTimePicker>", () => {
                 assert.isFalse(getSelectedDay().exists());
             });
         }
+
+        it("Passing the same value prop twice does not clear the selected date", () => {
+            const { root, getSelectedDay } = wrap(<DateTimePicker />);
+            assert.isTrue(getSelectedDay().exists());
+            root.setProps({ value: undefined });
```
Comment (giladgray) [inline packages/datetime/test/dateTimePickerTests.tsx]: would be much clearer to use an actual `value` and pass it on line 105 too. 
`<DateTimePicker value={VALUE} />`

**Comment by giladgray** [comment]
😄 if you're worried about incorrect behavior, write more unit tests! 🏫

File: packages/datetime/test/dateTimePickerTests.tsx (hunk 2 above)
Comment (cathyxz) [inline packages/datetime/test/dateTimePickerTests.tsx]: But that does not test the same thing. I think it is more appropriate to change the name of this test to reflect what it's really testing (which I did). So the DateTimePicker only selects its own date and time if the `value` prop is undefined. What we are trying to fix here is given that a user implements `onChange` but does NOT pass in a `value`, we want to avoid the `onChange` handler, which will pass in new props, to interfere with / clear out the date/time state managed by the `DateTimePicker`. 

For example, this test should fail: 

```        it("Passing the same value prop twice does not change a user-selected date", () => {
            const value = new Date(2012, 2, 5, 6, 5, 40);
            const { root, getDay } = wrap(<DateTimePicker value={value} />);
            assert.strictEqual(root.state("dateValue"), value);
            
            getDay(15).simulate("click");

            const modifiedDate = new Date(2012, 2, 15, 6, 5, 40);
            assert.strictEqual(root.state("dateValue"), modifiedDate); // this will fail because DateTimePicker no longer manages state since value is defined
            
            root.setProps({ value: value });
            assert.strictEqual(root.state("dateValue"), modifiedDate);
        });
```

File: packages/datetime/test/dateTimePickerTests.tsx [hunk 3]
```diff
@@ -8,7 +8,6 @@
 import { assert } from "chai";
 import { mount } from "enzyme";
 import * as React from "react";
-
```
Comment (cmslewis) [inline packages/datetime/test/dateTimePickerTests.tsx]: Let's keep this newline in place to differentiate external dependencies from internal dependencies.

File: packages/datetime/test/dateTimePickerTests.tsx [hunk 4]
```diff
@@ -101,6 +100,15 @@ describe("<DateTimePicker>", () => {
...
         }
+
+        it("Passing an undefined value prop twice does not clear the selected date", () => {
+            const { root, getSelectedDay } = wrap(<DateTimePicker />);
+            assert.isTrue(getSelectedDay().exists());
+            root.setProps({ value: undefined });
+            assert.isNotNull(root.state("dateValue"));
+            assert.isTrue(getSelectedDay().exists());
+        });
+
```
Comment (cmslewis) [inline packages/datetime/test/dateTimePickerTests.tsx]: Delete this trailing newline

File: packages/datetime/test/dateTimePickerTests.tsx [hunk 5]
```diff
@@ -116,4 +124,5 @@ describe("<DateTimePicker>", () => {
             root,
         };
     }
+
```
Comment (cmslewis) [inline packages/datetime/test/dateTimePickerTests.tsx]: Delete this trailing newline

**Comment by cathyxz** [comment]
@cmslewis I think we're gtg here, but obviously welcome any more feedback and comments.

File: packages/datetime/test/dateTimePickerTests.tsx (hunk 4 above)
Comment (giladgray) [reply packages/datetime/test/dateTimePickerTests.tsx]: 👍  newline is legit now that there's a second test

**Comment by cmslewis** [comment]
I'll try to add this to the release.
