### PR TITLE
[Table] Validation improvements

### LINKED ISSUE #1371: [Table] Table silently ignores `rowHeights` prop if it has the wrong length
```
    /**
     * Takes in one full array of values and one sparse array of the same
     * length and type. Returns a copy of the `defaults` array, where each
     * value is replaced with the corresponding non-null value at the same
     * index in `sparseOverrides`.
     *
     * @param defaults - the full array of default values
     * @param sparseOverrides - the sparse array of override values
     */
    assignSparseValues: function (defaults, sparseOverrides) {
        if (sparseOverrides == null || defaults.length !== sparseOverrides.length) {
            return defaults;
        }
        defaults = defaults.slice();
        for (var i = 0; i < defaults.length; i++) {
            var override = sparseOverrides[i];
            if (override != null) {
                defaults[i] = override;
            }
        }
        return defaults;
    },
```

It should throw an error, otherwise it can be confusing to debug why it isn't working.

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

- 🐛  __FIXED__ `Table` now validates props on mount _and_ on update.
- 🔄 __CHANGED__ `Table` now validates props as follows (assuming each prop involved is defined):
    - Errors:
        - `numRows < 0`
        - `numFrozenRows < 0`
        - `numFrozenColumns < 0`
        - `numRows !== rowHeights.length`
        - `numColumns !== columnWidths.length`
        - `non-<Column> child` (*)
    - Warnings:
        - `numFrozenRows > numRows` (changed the message to mention that we'll clamp for you)
        - `numFrozenColumns > numColumns` (same)

#### Reviewers should focus on:

- How does the error-message language look?
- (*) Is this the right choice? Per my code comment, we're currently just printing a warning, but the Table would eventually throw a convoluted error from deep inside when processing non-`<Column>` children, so I figure we might as well just throw a clear error at the outset.

#### Screenshot

```
Validation
  on mount
    errors
      ✔ throws an error if numRows < 0
      ✔ throws an error if numFrozenRows < 0
      ✔ throws an error if numFrozenColumns < 0
      ✔ throws an error if rowHeights.length !== numRows
      ✔ throws an error if columnWidths.length !== number of <Column>s
      ✔ throws an error if a non-<Column> child is provided
    warnings
      ✔ should print a warning when numFrozenRows > numRows
      ✔ should print a warning when numFrozenColumns > num <Column>s
  on update
    errors
      ✔ on numRows update, throws an error if numRows < 0
      ✔ on numFrozenRows update, throws an error if numFrozenRows < 0
      ✔ on numFrozenColumns update, throws an error if numFrozenColumns < 0
      ✔ on numRows update, throws an error if rowHeights.length !== numRows
      ✔ on rowHeights update, throws an error if rowHeights.length !== numRows
      ✔ on children update, throws an error if columnWidths.length !== number of <Column>s
      ✔ on columnWidths update, throws an error if columnWidths.length !== number of <Column>s
      ✔ on children update, throws an error if a non-<Column> child is provided
    warnings
      ✔ on numFrozenRows update, should print a warning when numFrozenRows > numRows
      ✔ on numRows update, should print a warning when numFrozenRows > numRows
      ✔ on numFrozenColumns update, should print a warning when numFrozenColumns > num <Column>s
      ✔ on children update, should print a warning when numFrozenColumns > num <Column>s
      ✔ should print a warning when numFrozenColumns > num <Column>s
```

### CODE REVIEW

File: packages/table/src/table.tsx [hunk 1]
```diff
@@ -524,6 +524,8 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
     }
 
     public componentWillReceiveProps(nextProps: ITableProps) {
+        super.componentWillReceiveProps(nextProps);
```
Comment (cmslewis) [inline packages/table/src/table.tsx]: #whoops

File: packages/table/src/table.tsx [hunk 2]
```diff
@@ -685,29 +687,49 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
         React.Children.forEach(children, (child: React.ReactElement<any>) => {
             // save as a variable so that union type narrowing works
             const childType = child.type;
 
-            if (typeof childType === "string") {
-                console.warn(Errors.TABLE_NON_COLUMN_CHILDREN_WARNING);
+            // the second part of this conditional will never be true, but it
+            // informs the TS compiler that we won't be invoking
+            // childType.prototype on a "string" element.
+            if (typeof child === "string" || typeof childType === "string") {
```
Comment (cmslewis) [inline packages/table/src/table.tsx]: Janky, but it was throwing an error before I added the `typeof child === "string"` check. Turns out `typeof childType === undefined` for strings, so the check wasn't working as expected before.

File: packages/table/src/table.tsx [hunk 3]
```diff
@@ -685,29 +687,49 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
+                throw new Error(Errors.TABLE_NON_COLUMN_CHILDREN_WARNING);
             } else {
                 const isColumn = childType.prototype === Column.prototype || Column.prototype.isPrototypeOf(childType);
                 if (!isColumn) {
-                    console.warn(Errors.TABLE_NON_COLUMN_CHILDREN_WARNING);
+                    throw new Error(Errors.TABLE_NON_COLUMN_CHILDREN_WARNING);
```
Comment (cmslewis) [inline packages/table/src/table.tsx]: Is there ever a case where we'd want to let people wrap child `<Column>`s with a thing? If not, would prefer this to be an `Error`.

File: packages/table/src/table.tsx (hunk 1 above)
Comment (gscshoyru) [reply packages/table/src/table.tsx]: Womp

File: packages/table/src/table.tsx (hunk 2 above)
Comment (gscshoyru) [reply packages/table/src/table.tsx]: ...so it's a... typeguard? That's... weird. I am confused as to how this could possibly be working. But... ok?

File: packages/table/src/table.tsx (hunk 3 above)
Comment (gscshoyru) [reply packages/table/src/table.tsx]: I think you're probably right, @adidahiya might know if the other ever comes up? Not sure.

File: packages/table/src/table.tsx (hunk 2 above)
Comment (cmslewis) [reply packages/table/src/table.tsx]: `typeof childType === "string"` is the typeguard, yeah. But it never returns `true`. @giladgray, do you know a way out of this comical quagmire?

**Comment by cmslewis** [comment]
Adding @adidahiya for CR because you've used the `Table` in the wild.

File: packages/table/src/table.tsx (hunk 3 above)
Comment (adidahiya) [reply packages/table/src/table.tsx]: do we really need to validate the react children? what does this buy us? what's the harm in being lenient? please keep https://github.com/palantir/blueprint/issues/1108 in mind; enforcing constraints on React children in typescript usually gets in the way more often than it helps.

Comment (cmslewis) [reply packages/table/src/table.tsx]: `table.tsx` accesses `props.children` expecting it to be an array of `<Column>s` (e.g. in `Table.getColumnProps`). If that accessing fails, the error message is somewhat convoluted; throwing a clear error from `validateProps` would be more helpful.

Only reservation is that maybe there are cases when people would want to compose a basic `<Column>` into something else they'd want to provide as a direct child of `Table`? In that case, a duck-typing approach would seem preferable (i.e. as long as the child in question supports the `Column` API, we don't care).

I've never heard of anyone doing the above customization, so I'm including the error check as a result of my first point. ^ Thoughts?

Comment (adidahiya) [reply packages/table/src/table.tsx]: for now I'm fine with enforcing `Column` to be a direct child of `Table` -- as you said we haven't seen the wrapping component use case come up. makes sense to have a better error message and halt execution since the table won't render correctly. let's get to #1108 soon for 2.0.

Comment (cmslewis) [reply packages/table/src/table.tsx]: 👍
