### PR TITLE
[table] Remove min width from editable components

### LINKED ISSUE #281: EditableCell/EditableName not truncating properly
### Bug report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__: Chrome 54.0.2840.98 (64-bit) and OS X El Capitan 10.11.6

#### Steps to reproduce

1. Render an `EditableCell`/`EditableName` with lengthy content (resizing column is not necessary).

#### Actual behavior

screen shot 2016-11-30 at 5 10 04 pm

#### Expected behavior

screen shot 2016-11-30 at 5 13 49 pm

### PR DESCRIPTION
**Pull request by themadcreator**
#### Changes proposed in this pull request:

`<EditableText>` has a default min-width of 80px,
which overflows the table cell.

Settings the minWidth prop to null will fix this.

### CODE REVIEW

File: packages/table/src/cell/editableCell.tsx [hunk 1]
```diff
@@ -57,6 +57,7 @@ export class EditableCell extends React.Component<IEditableCellProps, {}> {
                         className={"bp-table-editable-name"}
                         defaultValue={value}
                         intent={intent}
+                        minWidth={null}
```
Comment (adidahiya) [inline packages/table/src/cell/editableCell.tsx]: shouldn't we limit it to _something_, like 5px maybe? also, minor: it always feels weird to pass `null` as a prop.

Comment (themadcreator) [inline packages/table/src/cell/editableCell.tsx]: The min/max is set by the table's minColumnWidth/maxColumnWidth and is handled elsewhere. We don't want them to compete. I don't know how to unset a default other than passing null
