### PR TITLE
[core] refactor(Popover): improve popover captureDismiss mechanism

### LINKED ISSUE #2820: Classes.POPOVER_DISMISS is not working with <Link /> (react-router-dom) in Popover
#### Environment
```
    "@blueprintjs/core": "^3.0.1",
    "@blueprintjs/datetime": "^3.0.0",
    "@blueprintjs/select": "^3.0.0",
```
#### Question

When I use Popover i would like to hide the box when I click the link. But it only works when I click the button without the text.
```js
<Popover
			position={Position.BOTTOM}
		>
			<Button className={Classes.MINIMAL} icon="menu">
				MENU
			</Button>
			<SlideBar />
		</Popover>

const LinkItemView = ({ icon, text, path, match, location, history }: ILinkPropsIn) => {
	return (
		<MenuItem icon={icon} className={Classes.POPOVER_DISMISS}
			text={
				<Link
					className={classnames('o-menu__link', Classes.POPOVER_DISMISS, { 'o-menu__link--selected': isRouteEqualPathname(location, path) })}
					to={path}
				>
				{text}
				</Link>
			}
		/>
	)
}
const LinkItem = compose<ILinkPropsIn, ILinkPropsOut>(withRouter)(LinkItemView)
const SlideBar = () => (
	<Menu className={'o-menu--vertical'}>
		<div>
			<MenuDivider title="NAVIGATION" />
			<LinkItem icon="lock" text="Setting" path="/setting"  />
			<LinkItem icon="lock" text="Dashboard" path="/"  />
		</div>
		<div>
			<MenuDivider title="Test" />
			<LinkItem icon="lock" text="Test Tab" path="/test" />
		</div>

	</Menu>
)
```

### PR DESCRIPTION
**Pull request by ejose19**
#### Checklist

- [X] Update documentation

#### Changes proposed in this pull request:

- Add a new popover class that will be used to determine when a popover is using ```captureDismiss```
- Add a new popover private property to hold the popover ref
- Remove dependency of ```preventDefault```/```defaultPrevented``` and instead use a more self contained approach to determine whether the popover should close in the presence of ```captureDismiss```

### CODE REVIEW

File: packages/core/src/components/popover/popover.tsx [hunk 1]
```diff
@@ -313,13 +314,19 @@ export class Popover extends AbstractPureComponent2<IPopoverProps, IPopoverState
                 [Classes.DARK]: this.props.inheritDarkTheme && this.state.hasDarkParent,
                 [Classes.MINIMAL]: this.props.minimal,
             },
+            this.props.captureDismiss ? Classes.POPOVER_CAPTURING_DISMISS : "",
```
Comment (adidahiya) [inline packages/core/src/components/popover/popover.tsx]:
```suggestion
                [Classes.MINIMAL]: this.props.minimal,
                [Classes.POPOVER_CAPTURING_DISMISS]: this.props.captureDismiss,
            },
```

File: packages/core/src/components/popover/popover.tsx [hunk 2]
```diff
@@ -103,6 +103,7 @@ export interface IPopoverState {
 @polyfill
 export class Popover extends AbstractPureComponent2<IPopoverProps, IPopoverState> {
     public static displayName = `${DISPLAYNAME_PREFIX}.Popover`;
+    private popoverRef = React.createRef<HTMLDivElement>();
```
Comment (adidahiya) [inline packages/core/src/components/popover/popover.tsx]: you'll need to add backwards compatibility for React 15 :)

**Review by adidahiya — CHANGES_REQUESTED** [review]
overall looks like a reasonable approach

**Comment by ejose19** [comment]
@adidahiya Thanks for the review, I run tests locally and completely forgot about react 15. Is there an script for running tests with that configuration?

File: packages/core/src/components/popover/popover.tsx [hunk 3]
```diff
@@ -495,15 +502,15 @@ export class Popover extends AbstractPureComponent2<IPopoverProps, IPopoverState
...
         const eventTarget = e.target as HTMLElement;
+        const eventPopover = eventTarget.closest(`.${Classes.POPOVER}`);
+        const isEventFromSelf = eventPopover === this.popoverRef.current;
+        const isEventPopoverCapturing = eventPopover.classList.contains(Classes.POPOVER_CAPTURING_DISMISS);
         // an OVERRIDE inside a DISMISS does not dismiss, and a DISMISS inside an OVERRIDE will dismiss.
         const dismissElement = eventTarget.closest(`.${Classes.POPOVER_DISMISS}, .${Classes.POPOVER_DISMISS_OVERRIDE}`);
         const shouldDismiss = dismissElement != null && dismissElement.classList.contains(Classes.POPOVER_DISMISS);
         const isDisabled = eventTarget.closest(`:disabled, .${Classes.DISABLED}`) != null;
-        if (shouldDismiss && !isDisabled && !e.isDefaultPrevented()) {
+        if (shouldDismiss && !isDisabled && (!isEventPopoverCapturing || isEventFromSelf)) {
```
Comment (thasner) [inline packages/core/src/components/popover/popover.tsx:512]: is `isDisabled` still relevant here? Not sure if the check was to avoid `preventDefault` on an event that should not have been touched, or if we genuinely didn't want to close the popover if its target is disabled

**Comment by adidahiya** [comment]
@ejose19 yes, it is possible to run those tests by [setting an environment variable in your shell: `REACT=15`](https://github.com/palantir/blueprint/blob/af91a1a93a4f9ec45b6b396f7e60f866477fa6a6/.circleci/config.yml#L158) before running `yarn test` and related test scripts.

File: packages/core/src/components/popover/popover.tsx (hunk 3 above)
Comment (ejose19) [reply packages/core/src/components/popover/popover.tsx:512]: I'm pretty sure it's redundant, since a disabled element can't emit a click event. However I don't know if any blueprint component only uses disabled class but doesn't respect that rule (I checked anchor button and they do respect not triggering onClick) if there's no element which applies disabled class and allow clicking I can remove that too.

**Comment by adidahiya** [comment]
[docs preview build](https://34975-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#core/components/popover.closing-on-click)

**Review by adidahiya — APPROVED** [review]
thanks @ejose19
