### PR TITLE
[Tabs2] Fix Tabs2 indicator not moving when tabs are removed or added

### LINKED ISSUE #1491: Tabs2 indicator does not move when tabs are removed
### Bug report

- __Package version(s)__:  @blueprintjs/core v1.25.1
- __Browser and OS versions__:  Firefox 55 and Chrome 60 on Ubuntu 17.04

#### Steps to reproduce

1. Create a Tabs2 component with several tabs
1. Select a tab
1. Make one of the previous tabs disappear

#### Actual behavior

The selection box or underline showing the selected tab doesn't move (both vertical and horizontal tabs)
bug

#### Expected behavior

The selection box or underline showing the selected tab should move following the selected tab

Check the following example code:

    import React, {Component} from "react";
    import "@blueprintjs/core/dist/blueprint.css";
    import {Tabs2, Tab2, Button} from "@blueprintjs/core";

    export class Tabs2Example extends Component {

        constructor(props) {
            super(props);
            this.state = {
                id: null,
                tabs: [{"name": "Tab 1", "id": "a", "visible": true}, 
                    {"name": "Tab 2", "id": "b", "visible": true}, 
                    {"name": "Tab 3", "id": "c", "visible": true}]
            }
        }

        visibleTab = index => {
            let newTabs = this.state.tabs;
            newTabs[index].visible = !newTabs[index].visible;
            this.setState({tabs: newTabs});
        };

        render() {
            return (
                <div>
                    {this.state.tabs.map((tab, index) => <Button key={index} style={{marginBottom: "20px"}} active={!this.state.tabs[index].visible} onClick={() => this.visibleTab(index)}>{"Tab " + (index + 1)}</Button>)}
                    <Tabs2 selectedTabId={this.state.id} vertical onChange={event => this.setState({id: event}, console.log(event))} >
                        {this.state.tabs.filter(i => i.visible).map((tab, index) =>
                            <Tab2 id={tab.id} key={index}
                                  title={tab.name} panel={null}/>)}
                    </Tabs2>
                </div>
            )
        }
    }

### PR DESCRIPTION
**Pull request by franciscofabian**
#### Changes proposed in this pull request:

Check if the selected tab id is the same as the previous state and if so, check if the index of the selected tab has changed or not. If both things are true, then move the selection indicator

#### Reviewers should focus on:

Is this the most efficient and simple way of implementing that change?

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @franciscofabian! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 1]
```diff
@@ -153,6 +153,12 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
     public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId !== undefined) {
+            var selectedTabIdIndex = this.props.children.map(child => child.props.id).indexOf(this.state.selectedTabId);
```
Comment (llorca) [inline packages/core/src/components/tabs2/tabs2.tsx]: `var` -> `const`

`gulp` isn't happy with this `map`:
```
packages/core/src/components/tabs2/tabs2.tsx(157,58): error TS2339: Property 'map' does not exist on type 'ReactNode'.
  Property 'map' does not exist on type 'string'.
```

**Comment by franciscofabian** [comment]
@llorca Thanks for the review! I think that that mapping issue should be solved now

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 2]
```diff
@@ -153,6 +153,12 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
     public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId !== undefined && prevState.selectedTabId !== null) {
+            const selectedTabIdIndex = this.props.children[1].map(child => child.props.id).indexOf(this.state.selectedTabId);
+            const prevSelectedTabIdIndex = _prevProps.children[1].map(child => child.props.id).indexOf(prevState.selectedTabId);
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: wow this is some frightening array indexing and i don't trust it one bit. shouldn't you be using `children` entirely, not the first child?
 
but actually, can you use `this.getTabChildren()` instead, like i do elsewhere in the component? you can add a param to that method to customize which `children` array it uses.

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 3]
```diff
@@ -153,6 +153,12 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
     public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId !== undefined && prevState.selectedTabId !== null) {
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: `prevState.selectedTabId != null` (double-not-equals) handles both of these values.

File: packages/core/src/components/tabs2/tabs2.tsx (hunk 1 above)
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: use `React.Children.map`, but actually see my comments below.

File: packages/core/src/components/tabs2/tabs2.tsx (hunk 3 above)
Comment (franciscofabian) [inline packages/core/src/components/tabs2/tabs2.tsx]: yes, completely agree

File: packages/core/src/components/tabs2/tabs2.tsx (hunk 2 above)
Comment (franciscofabian) [inline packages/core/src/components/tabs2/tabs2.tsx]: yeah, I don't like that ugly indexing either. I have changed `this.props.children[1]` but I'm not sure how to change `_prevProps.children[1]`

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 4]
```diff
@@ -153,6 +153,13 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
     public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId != null) {
+            const tabs = this.getTabChildren();
+            const selectedTabIdIndex = tabs.map(child => child.props.id).indexOf(this.state.selectedTabId);
+            const prevSelectedTabIdIndex = _prevProps.children[1].map(child => child.props.id).indexOf(prevState.selectedTabId);
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: ❌  use `React.Children` for interacting with `children` arrays: https://facebook.github.io/react/docs/react-api.html#react.children

but _actually_, please do what I said previously so you can say `this.getTabChildren(prevProps.children)` instead. that's the most correct way to write this.

and add unit tests for this!!

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 5]
```diff
@@ -153,6 +153,13 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
     public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: remove _ prefix cuz this argument is now used.

Comment (franciscofabian) [inline packages/core/src/components/tabs2/tabs2.tsx]: done

File: packages/core/src/components/tabs2/tabs2.tsx (hunk 4 above)
Comment (franciscofabian) [inline packages/core/src/components/tabs2/tabs2.tsx]: thanks for the info, I have changed add.

I will add later an unit test.

Comment (franciscofabian) [inline packages/core/src/components/tabs2/tabs2.tsx]: actually `this.getTabChildren(prevProps.children)` doesn't work, it gives the current children, not the previous ones

Comment (franciscofabian) [inline packages/core/src/components/tabs2/tabs2.tsx]: fixed now

**Comment by franciscofabian** [comment]
can somebody review the latest changes? I'm not sure how to make a test for this

**Comment by franciscofabian** [comment]
I have found situations where the previous fix would not work, e.g. changing the title of the tab without changing its id or adding/removing tabs that make the selected tab to change in size (see below, the tab indicator should resize in that case):
bug2

**Comment by giladgray** [comment]
@franciscofabian there is a compile error in your code, see CircleCI output.

```
packages/core/src/components/tabs2/tabs2.tsx(158,75): error TS2339: Property 'children' does not exist on type 'ITabs2Props'.
```

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 6]
```diff
@@ -179,9 +185,9 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
         return undefined;
     }
 
-    /** Filters this.props.children to only `<Tab>`s */
-    private getTabChildren() {
-        return React.Children.toArray(this.props.children).filter(isTab) as TabElement[];
+    /** Filters component children to only `<Tab>`s */
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: drop the word "component"

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 7]
```diff
@@ -150,9 +150,15 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
...
     }
 
-    public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
+    public componentDidUpdate(prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId != null) {
+            const selectedTabChildren = this.getTabChildren();
+            const prevSelectedTabChildren = this.getTabChildren(prevProps.children);
+            if (selectedTabChildren !== prevSelectedTabChildren) {
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: ❌ this will _never_ be false because the two objects are always by definition different array instances.

better to check that the lengths are the same, but as you've pointed out there are still plenty of holes with that logic... not really sure the best approach here at the moment.

Comment (franciscofabian) [inline packages/core/src/components/tabs2/tabs2.tsx]: This is not an easy issue to solve, but I came with a different way that might work. I compare the title, id, length and position of the tabs in the current and previous state, if they are not identical then move the indicator. Let me know what do you think about that fix.

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 8]
```diff
@@ -150,9 +150,15 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
         }
     }
 
-    public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
+    public componentDidUpdate(prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId != null) {
+            const prevChildren = JSON.stringify(prevProps.children.map(thisArg => JSON.stringify(thisArg.props, ["title", "id"])));
+            const children = JSON.stringify(React.Children.map(this.props.children, thisArg => JSON.stringify(thisArg.props, ["title", "id"])));
```
Comment (giladgray) [inline packages/core/src/components/tabs2/tabs2.tsx]: hmmmm this is clever but i'm not comfortable relying on this sort of logic in __core__: i've seen issues where certain JSX elements are actually _not_ stringifiable (as in, `JSON.stringify` throws an error).

what we really want is a `shallowCompare`, but we unfortunately don't have such a utility in __core__ yet (we do in __table__).

Comment (franciscofabian) [reply packages/core/src/components/tabs2/tabs2.tsx]: ok, and are there any plans to add `shallowCompare` into **core**?

**Comment by cmslewis** [comment]
@giladgray status here?

File: packages/core/src/components/tabs2/tabs2.tsx (hunk 8 above)
Comment (llorca) [reply packages/core/src/components/tabs2/tabs2.tsx]: @cmslewis if trivial enough, would you be able to add a `shallowCompare` util you're using in `table` into `core`? Looks like we need it to move forward with this PR

Comment (cmslewis) [reply packages/core/src/components/tabs2/tabs2.tsx]: @franciscofabian @llorca just moved the utils in question into **core** in https://github.com/palantir/blueprint/pull/1604. @franciscofabian, does this unblock you for this PR?

Comment (franciscofabian) [reply packages/core/src/components/tabs2/tabs2.tsx]: @cmslewis yes, it does! I will update this PR to use the new utils

**Comment by franciscofabian** [comment]
I’m not sure how to fix the error “Property 'children' does not exist on type 'ITabs2Props'.”, can somebody help me with that one?

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 9]
```diff
@@ -39,6 +39,12 @@ export interface ITabs2Props extends IProps {
     defaultSelectedTabId?: TabId;
 
     /**
+     * The children of a `Tabs2` component, which are React elements
+     * that use `ITab2Props`.
+     */
+    children?: React.ReactElement<ITab2Props> | Array<React.ReactElement<ITab2Props>>;
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs2.tsx]: Remove this prop.

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 10]
```diff
@@ -163,9 +169,19 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
         }
     }
 
-    public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
+    public componentDidUpdate(prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId != null) {
+            if (
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs2.tsx]: For legibility, how about:

```tsx
} else if (prevState.selectedTabId != null) {
    const didChildrenChange = !Utils.arraysEqual(
        this.getTabChildren(prevProps),
        this.getTabChildren(),
        Utils.shallowCompareKeys,
    );
    if (didChildrenChange) {
        this.moveSelectionIndicator();
    }
}
```

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 11]
```diff
@@ -192,9 +208,9 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
         return undefined;
     }
 
-    /** Filters this.props.children to only `<Tab>`s */
-    private getTabChildren() {
-        return React.Children.toArray(this.props.children).filter(isTab) as TabElement[];
+    /** Filters children to only `<Tab>`s */
+    private getTabChildren(children = this.props.children) {
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs2.tsx]: This will fix your typings issues (we use this pattern elsewhere in the codebase):
```tsx
private getTabChildren(props: ITabs2Props & { children?: React.ReactNode } = this.props) {
    return React.Children.toArray(props.children).filter(isTab) as TabElement[];
}
```

**Comment by franciscofabian** [comment]
Thanks for your comments. I have fixed those issues but I get a CI error that I don’t understand

**Comment by cmslewis** [comment]
@franciscofabian Weird. I'll take a look after lunch.

File: packages/core/src/components/tabs2/tabs2.tsx [hunk 12]
```diff
@@ -163,9 +163,18 @@ export class Tabs2 extends AbstractComponent<ITabs2Props, ITabs2State> {
         }
     }
 
-    public componentDidUpdate(_prevProps: ITabs2Props, prevState: ITabs2State) {
+    public componentDidUpdate(prevProps: ITabs2Props, prevState: ITabs2State) {
         if (this.state.selectedTabId !== prevState.selectedTabId) {
             this.moveSelectionIndicator();
+        } else if (prevState.selectedTabId != null) {
+            const didChildrenChange = !Utils.arraysEqual(
```
Comment (cmslewis) [inline packages/core/src/components/tabs2/tabs2.tsx]: Here's your fix to your build woes:

```tsx
// comparing React nodes is difficult to do with simple logic, so
// shallowly compare their props as a workaround.
const didChildrenChange = !Utils.arraysEqual(
    this.getTabChildrenProps(prevProps),
    this.getTabChildrenProps(),
    Utils.shallowCompareKeys,
);
if (didChildrenChange) {
    this.moveSelectionIndicator();
}

// ...


private getTabChildrenProps(props: ITabs2Props & { children?: React.ReactNode } = this.props) {
    return this.getTabChildren(props).map(child => child.props);
}
```

There was a property called `_store` on each child that was being reset to a new object instance in each render cycle, causing `didChildrenChange` to always be `true`. This led to an infinite loop of `setState`s, hence your `Maximum call stack size exceeded` errors.

**Comment by franciscofabian** [comment]
<h3>fix mistakenly deleted function</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/44/artifacts/0//home/ubuntu/blueprint/packages/site-docs/dist/index.html' target='_blank'>documentation</a></strong>
Coverage: <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/44/artifacts/0//home/ubuntu/blueprint/packages/core//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>core</a> | <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/44/artifacts/0//home/ubuntu/blueprintpackages/datetime//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>datetime</a>

**Comment by franciscofabian** [comment]
@cmslewis everything it solved now, thank you for looking into that issue

**Comment by franciscofabian** [comment]
<h3>Merge pull request #3 from palantir/master</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/45/artifacts/0//home/ubuntu/blueprint/packages/site-docs/dist/index.html' target='_blank'>documentation</a> | <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/45/artifacts/0//home/ubuntu/blueprint/packages/site-landing/dist/index.html' target='_blank'>landing</a> | <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/45/artifacts/0//home/ubuntu/blueprint/packages/table/preview/index.html' target='_blank'>table</a></strong>
Coverage: <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/45/artifacts/0//home/ubuntu/blueprint/packages/core//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>core</a> | <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/45/artifacts/0//home/ubuntu/blueprintpackages/datetime//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>datetime</a>

**Comment by cmslewis** [comment]
@franciscofabian - Never mind, let's just get this in. I'll write the test after this merges.

**Comment by cmslewis** [comment]
Thanks for your work, @franciscofabian!

**Comment by llorca** [comment]
woo, thanks for pushing this through @cmslewis @franciscofabian. Great stuff!
