### PR TITLE
Um/fix collapse animation

### LINKED ISSUE #2706: Collapse doesn't animate on first open
ezgif com-optimize

#### Environment

- __Package version(s)__: v3.0.1
- __Browser and OS versions__: Chrome 67 / Safari 11.1.2 / Firefox 61, MacOS 10.13.6

#### Steps to reproduce

1. go to this docs page: http://blueprintjs.com/docs/#core/components/collapse
1. Click "Show build logs" demo button

#### Actual behavior

First open of the collapse object isn't animated and simply appears (also the button jumps left).
NB subsequent open and closes are animated.

#### Expected behavior

All open and close animations are animated.

#### Possible solution

Maybe use React-Spring?

### PR DESCRIPTION
**Pull request by odusseys**
#### Changes proposed in this pull request:

Adds an `OPEN_START` state to Collapse in order to properly compute content height and animate smoothly.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @odusseys! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/core/src/components/collapse/collapse.tsx [hunk 1]
```diff
@@ -65,7 +66,13 @@ export enum AnimationStates {
  * OPEN
  * When in this state, the collapse height is set to auto, and the body Y is set to 0 (so the element can be seen
  * as normal).
+ * 
+ * OPEN START
```
Comment (giladgray) [inline packages/core/src/components/collapse/collapse.tsx]: `OPEN_START`

**Comment by giladgray** [comment]
@odusseys i have opened #2914 to reformat the docs. thanks for this fix!!
