### PR TITLE
[DateInput] add inputProps just like DRI

### LINKED ISSUE #387: Unable to pass props to input in DateInput
### Bug report

Unable to pass props to the input element inside of a DateInput. e.g. can't use the HTML5 validation attributes. Related to: #361 

- __Package version(s)__: @blueprintjs/datetime 1.4.0
- __Browser and OS versions__: All.

#### Steps to reproduce

```jsx
<DateInput required={true} />
```

#### Actual behavior

```html
<input type="text" class="pt-input">
```

#### Expected behavior

```html
<input type="text" class="pt-input" required>
```

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- add `DateInput` `inputProps` exactly like we did for `DateRangeInput` in #945 
- turns out this wasn't the least bit breaking, nor did it require any deprecations!

### CODE REVIEW

File: packages/datetime/src/dateInput.tsx [hunk 1]
```diff
@@ -337,9 +352,18 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
...
     private setInputRef = (el: HTMLElement) => {
         this.inputRef = el;
+        const { inputProps = {} } = this.props;
+        Utils.safeInvoke(inputProps.inputRef, el);
+    }
+
+    /** safe wrapper around invoking input props event handler (prop defaults to undefined) */
+    private safeInvokeInputProp(name: keyof HTMLInputProps, e: React.SyntheticEvent<HTMLElement>) {
+        const { inputProps = {} } = this.props;
+        Utils.safeInvoke(inputProps[name], e);
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: thoughts on this pattern? it's a way to avoid defining `defaultProps.inputProps = {}` to prevent accidental mutation like in #980. but maybe it's just too much overhead and we should set the default prop and keep an eye out for potential mutation?

File: packages/datetime/src/dateInput.tsx [hunk 2]
```diff
@@ -337,9 +352,18 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
...
     }
 
     private setInputRef = (el: HTMLElement) => {
         this.inputRef = el;
+        const { inputProps = {} } = this.props;
+        Utils.safeInvoke(inputProps.inputRef, el);
+    }
+
+    /** safe wrapper around invoking input props event handler (prop defaults to undefined) */
+    private safeInvokeInputProp(name: keyof HTMLInputProps, e: React.SyntheticEvent<HTMLElement>) {
```
Comment (cmslewis) [inline packages/datetime/src/dateInput.tsx]: > `keyof HTMLInputProps`

Nice. Worth making an even more restrictive whitelist? `HTMLInputProps` is kinda huge.

File: packages/datetime/src/dateInput.tsx (hunk 1 above)
Comment (cmslewis) [inline packages/datetime/src/dateInput.tsx]: This new approach seems good to me.

File: packages/datetime/src/dateInput.tsx [hunk 3]
```diff
@@ -68,6 +70,13 @@ export interface IDateInputProps extends IDatePickerBaseProps, IProps {
     format?: string;
 
     /**
+     * Props to pass to the input group.
+     * `disabled` and `value` will be ignored in favor of the top-level props on this component.
+     * Note that `ref` will also be ignored; use `inputRef` instead.
```
Comment (cmslewis) [inline packages/datetime/src/dateInput.tsx]: Is this ref note also true of how `DateRangeInput` uses `{start,end}InputProps`? We should add a note there if so, maybe even in this PR.

Also, worth mentioning that `type` is ignored?

File: packages/datetime/src/dateInput.tsx (hunk 2 above)
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: hmm it's true this is only meant for the `on*` event handlers, but it's a quick private method and `safeInvoke` will protect us so i'm not sure the extra effort is worth it.

Comment (cmslewis) [inline packages/datetime/src/dateInput.tsx]: Cool. Happy with it as is then.
