### PR TITLE
[Table] Show focus cell appropriately when enableFocus becomes true

### LINKED ISSUE #1443: [Table] When enableFocus becomes true, show the focus cell right away
### Bug report

- __Package version(s)__: v1.24.0

#### Steps to reproduce

1. Set `enableFocus` to true on a `Table`.

#### Actual behavior

No focus cell shown until you make a selection, then it persists as expected.

#### Expected behavior

Show a focus cell right away.

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

- __Fixed__ Changing `Table` `enableFocus` prop to `true` now shows a focused cell right away.

#### Reviewers should focus on:

- All the tests look at the component state, rather than what is rendered. Seemed easier to check the exact coordinates of the focused cell that way.

### CODE REVIEW

File: packages/table/src/table.tsx [hunk 1]
```diff
@@ -461,9 +461,27 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
+            } else if (this.state.selectedRegions.length > 0) {
+                // focus the top-left cell of the first selection
+                newFocusedCellCoordinates = {
+                    ...Regions.getFocusCellCoordinatesFromRegion(this.state.selectedRegions[0]),
+                    focusSelectionIndex: 0,
+                };
+            } else {
+                // focus the top-left cell of the table
+                newFocusedCellCoordinates = { col: 0, row: 0, focusSelectionIndex: 0 };
+            }
```
[the remark this answers is not in the document]
Comment (cmslewis) [reply packages/table/src/table.tsx]: Sounds like it's time to introduce `focusUtils.ts` (per https://github.com/palantir/blueprint/pull/1496/files#r135396325). 😎

File: packages/table/test/common/internal/index.ts [hunk 2]
```diff
@@ -0,0 +1,3 @@
+
```
Comment (giladgray) [inline packages/table/test/common/internal/index.ts]: needs file header

Comment (cmslewis) [reply packages/table/test/common/internal/index.ts]: Done
