### PR TITLE
[Overlay] New Overlay CSS plays nice with centered, scrollable dialogs

### LINKED ISSUE #552: Dialogs are not vertically centered
Dialogs are off center. It is particularly obvious when the dialog is larger
image

### Bug report

- __Package version(s)__: 1.6.0
- __Browser and OS versions__: Chrome

### LINKED ISSUE #1240: Overlay background is in front of overlay content by default
### Bug report

- __Package version(s)__: 
- __Browser and OS versions__: Win 10, Chrome 59
#### Steps to reproduce

1. [Open overlay example ](http://blueprintjs.com/docs/#core/components/overlay)
2. Observe how zIndex is only set because of style [OVERLAY_EXAMPLE_CLASS](https://github.com/palantir/blueprint/blob/94e5bd35c6b99bc3f1f0e3009e9c4056cb8c0e24/packages/core/examples/overlayExample.tsx#L55) with dev tools
3. Remove className and see how grey background is now in front of content

#### Actual behavior

Background of overlay is in front of overlay content.

#### Expected behavior

Content should be in front automatically. Maybe set appropriate zIndex by default or invert order of content and background elements?

### LINKED ISSUE #1313: [Dialog] scrolling UX is bad because dialog is not scrolling when hovered overlay
Hi, i'm making usability testing and already see a lot feedback about bad UX with dialogs because when user is trying to scroll dialog scrolling does work only when mouse cursors is over the dialog contents if mouse is over the overlay scroll scrolls background page but not dialog, which is primary active content at that moment.

At least there should be a property if you really want to let user scroll background page when dialog is active.

### Bug report

- __Package version(s)__: 1.21.0
- __Browser and OS versions__: Version 59.0.3071.115 (Build officiel) (64 bits)

#### Steps to reproduce

1. create random site with some html/text
2. use dialog component `Dialog`
3. scroll while hovered over dialog and when hovered overlay

#### Actual behavior

scroll is working not like users expect it to work. Bad ux.

#### Expected behavior

Dialog is scrolling always no matter where the mouse is, while dialog is primary active content.

image

### PR DESCRIPTION
**Pull request by llorca**
#### Checklist

- [x] Include tests
- [x] Update documentation

#### Reviewers should focus on:

- New overlay CSS
- Updated dialog CSS

#### What happened

`Dialog` component now renders a `.pt-dialog-container` wrapper as its root element which centers the `.pt-dialog` in a viewport-covering flex container. This provides super reliable centering behavior (#552) and much improved scrolling support (though some issues are still present like #1008).

### CODE REVIEW

**Comment by cmslewis** [comment]
Take a look at the `Overlay` example: the background color is flickering and ending up darker after a moment:

**Comment by llorca** [comment]
@cmslewis Hmm, what browser? I can't repro on Chrome nor Firefox

**Comment by llorca** [comment]
Just added `user-select: none` to the backdrop. It fixes this bug in Firefox where mousing down on the backdrop selects the text below:
screen recording firefox

File: packages/core/src/components/context-menu/contextMenu.tsx [hunk 1]
```diff
@@ -65,16 +65,15 @@ class ContextMenu extends AbstractComponent<{}, IContextMenuState> {
...
+        safeInvoke(this.state.onClose);
+        this.setState({ isOpen: false, onClose: undefined });
     }
 
     private cancelContextMenu = (e: React.SyntheticEvent<HTMLDivElement>) => e.preventDefault();
 
     private handleBackdropContextMenu = (e: React.MouseEvent<HTMLDivElement>) => {
-        // HACKHACK: React function to remove from the event pool (not sure why it's not in typings #66)
-        (e as any).persist();
+        // HACKHACK: React function to remove from the event pool
```
Comment (giladgray) [inline packages/core/src/components/context-menu/contextMenu.tsx]: actually this is not a HACKHACK, it's expected usage if you want to use an event in a callback. can you remove the HACKHACK keyword but leave the rest of comment?

File: packages/core/src/components/dialog/_dialog.scss [hunk 2]
```diff
@@ -37,32 +37,37 @@ Styleguide pt-dialog
...
+.pt-dialog {
+  display: flex;
   flex-direction: column;
-  position: absolute;
-  top: 10%;
-  right: 50%;
-  z-index: $pt-z-index-overlay;
-  // add bottom margin for overflow scrolling scenarios
-  margin-bottom: $pt-grid-size * 2;
+  margin: ($pt-grid-size * 3) 0;
```
Comment (giladgray) [inline packages/core/src/components/dialog/_dialog.scss]: `$dialog-margin` please

File: packages/core/src/components/dialog/dialog.tsx [hunk 3]
```diff
@@ -66,12 +66,14 @@ export class Dialog extends AbstractComponent<IDialogProps, {}> {
...
             <Overlay
                 {...this.props}
-                className={classNames({ [Classes.OVERLAY_SCROLL_CONTAINER]: !this.props.inline })}
+                className={Classes.OVERLAY_SCROLL_CONTAINER}
                 hasBackdrop={true}
             >
-                <div className={classNames(Classes.DIALOG, this.props.className)} style={this.props.style}>
-                    {this.maybeRenderHeader()}
-                    {this.props.children}
+                <div className="pt-dialog-container">
```
Comment (giladgray) [inline packages/core/src/components/dialog/dialog.tsx]: `Classes.DIALOG_CONTAINER`

File: packages/core/src/components/overlay/overlay.md [hunk 4]
```diff
@@ -56,4 +56,4 @@ and we'll take care of the rest.
 <Overlay className="pt-overlay-scroll-container" ... />
 ```
 
-The `Dialog` component does this automatically internally, except when it is used `inline`.
+The `Dialog` component applies this CSS class automatically internally.
```
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.md]: remove word "internally"

File: packages/core/src/components/overlay/overlay.tsx [hunk 5]
```diff
@@ -193,7 +193,14 @@ export class Overlay extends React.Component<IOverlayProps, IOverlayState> {
...
 
         if (inline) {
-            return <span {...elementProps} ref={this.refHandlers.container}>{transitionGroup}</span>;
+            return (
+                <span
+                    {...elementProps}
+                    ref={this.refHandlers.container}
+                >
+                    {transitionGroup}
+                </span>
```
Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: should be safe to undo this formatting, nothing actually changed here.

File: packages/core/src/components/popover/_popover.scss [hunk 6]
```diff
@@ -120,6 +120,10 @@ $popover-width: $pt-grid-size * 35 !default;
   .pt-transition-container {
     @include popover-inline-position();
   }
+
+  .pt-overlay-inline {
```
Comment (giladgray) [inline packages/core/src/components/popover/_popover.scss]: can you add a comment why this is necessary? so we don't come wondering later. might require re-deriving why we had to add this.

File: packages/core/src/components/overlay/overlay.tsx (hunk 5 above)
Comment (llorca) [inline packages/core/src/components/overlay/overlay.tsx]: Much easier to parse next to the corresponding `else` block right after, don't you think?

Comment (giladgray) [inline packages/core/src/components/overlay/overlay.tsx]: can't see that other block in the default diff here but you're right

**Comment by adidahiya** [comment]
Am I supposed to be able to scroll the background when a dialog is open like this?

**Comment by llorca** [comment]
@adidahiya I suppose you opened the dialog and then hovered the primary button to view the tooltip? In that case, yes it's expected. Separate bug, there's a fix in review now: https://github.com/palantir/blueprint/pull/1369

**Comment by giladgray** [comment]
@adidahiya @llorca: just merged master with fix for background scrolling. hopefully that'll work as expected now.

@adidahiya please continue reviewing for potential workspace breaks!

**Comment by giladgray** [comment]
@adidahiya tested with multiple different versions of blueprint CSS and fixed a few loose ends. the new styles now include a small patch to reset `position` on new Dialogs that use the `.pt-dialog-container` element. i also reverted changes we made to padding/margin on Dialog inner elements cuz those def don't play nice with old versions. looking good now!

**Comment by llorca** [comment]
https://github.com/palantir/blueprint/pull/1373/commits/4e5e9c91fd5155319514f923f9c298b02d29f561 🏆 🥇

File: packages/core/src/components/dialog/dialog.tsx [hunk 7]
```diff
@@ -122,6 +126,13 @@ export class Dialog extends AbstractComponent<IDialogProps, {}> {
             </div>
         );
     }
+
+    private handleContainerClick = (evt: React.MouseEvent<HTMLDivElement>) => {
+        // quick re-implementation of canOutsideClickClose because .pt-dialog-container covers the backdrop
+        if (this.props.canOutsideClickClose && evt.currentTarget.closest(`.${Classes.DIALOG}`) == null) {
```
Comment (adidahiya) [inline packages/core/src/components/dialog/dialog.tsx]: I think the second part of the boolean condition here will always be true because `currentTarget` is `.pt-dialog-container`... I think you want `evt.target` instead

Comment (giladgray) [inline packages/core/src/components/dialog/dialog.tsx]: currentTarget should be container. i'm testing that the click did not come from within the `.pt-dialog`, meaning it came from the `.pt-dialog-container` itself.

**Comment by giladgray** [comment]
it's always been mousedown for "outside click." there was an old bug with click where you could move the mouse around while holding it down and do weird things.

**Comment by llorca** [comment]
@adidahiya the real backdrop in `Overlay` uses `onMouseDown` so we're just replicating https://github.com/palantir/blueprint/blob/master/packages/core/src/components/overlay/overlay.tsx#L239

File: packages/core/src/components/dialog/_dialog.scss [hunk 8]
```diff
@@ -35,34 +38,48 @@ Styleguide pt-dialog
...
+  align-items: center;
+  justify-content: center;
+  width: 100%;
+  min-height: 100%;
+  user-select: none;
+
+  // LEGACY: override old (<= 1.24.0) dialog styles when inside a container to respect flex layout
+  .pt-dialog {
+    // stylelint-disable-next-line declaration-no-important
+    position: static !important;
```
Comment (kmwhelan93) [inline packages/core/src/components/dialog/_dialog.scss]: Hey can this be reasonably removed? This is some pretty wicked styling to overcome if you don't want your dialog to be in the center of the screen.

Comment (giladgray) [reply packages/core/src/components/dialog/_dialog.scss]: @kmwhelan93 please file a new issue to discuss this. nearly lost this comment to the sands of time. also note that we're working on 3.0 on `develop`, while this PR is way back in the 1.x days.

Comment (giladgray) [reply packages/core/src/components/dialog/_dialog.scss]: @kmwhelan93 or even better, hit me with a PR and a passing build! ✅
