### PR TITLE
Fix portal/popover position and scrolling issues

### LINKED ISSUE #231: Opening any popover scrolls to bottom of page in Firefox
### Bug Report

- __Package version(s)__: 1.0.1 (blueprintjs.com)
- __Browser and OS versions__: FF 46 & 50, macOS 10.12

#### Describe the issue:

Clicking on any popover scrolls to the bottom of its overlay, which is now the bottom of the page (related: https://github.com/palantir/blueprint/pull/186#issuecomment-261658643).

### LINKED ISSUE #240: Popover doesn't behave correctly when it has an autofocus'd input inside it
### Bug Report

- __Package version(s)__: v1.1.0
- __Browser and OS versions__: OS X 10.11, Chrome 54

#### Describe the issue:

Weird things happen in the docs when you open a popover containing an `input` with `autofocus=true`. 

popover-bug

#### Actual behavior:

Page jumps down several hundred pixels, and the popover doesn't open.

#### Expected behavior:

Something like this, but with the input field autofocused after the popover opens:

expected

### PR DESCRIPTION
**Pull request by cmslewis**
#### Changes proposed in this pull request:

- Change `.pt-portal` to `position:absolute` to take it out of document flow.
_This prevents browsers from autoscrolling to the bottom of the document (where portals are appended) when programmatically .focus()'ing within a portal child element._
- Stick `.pt-portal` to the top, left, and right of the `body`.
_This ensures that content still calculates offsets from the top of the document and that content won't be horizontally scrunched._
- Move `tabindex` from the `.pt-overlay` wrapper down to the overlay's immediate **children**.
_Despite the CSS changes above, programmatically `.focus()`'ing on the overlay can still cause autoscrolling to the bottom of the page in some cases. Moving the `tabindex` to the overlay content ensures that the browser will scroll to the content itself if need be, not to some hidden parent element._ 
- Upgrade Tether from v1.2.0 to v1.4.0 to pick up [this crucial PR](https://github.com/HubSpot/tether/pull/204).
_This helps us solve an issue wherein Tether was removing portal content nodes and reinserting them as immediate children of the `body` if any ancestor was not `position: static`. This in turn severed React's handles on the original DOM nodes._

#### Reviewers should focus on:

- **Before merging this, we'll need to wait on [this DefinitelyTyped PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13142) to merge;** that'll give us the type declaration for Tether's new `bodyElement` option. 
- We should open an issue on Tether after this, explaining why we needed such a horrible workaround with the `fakeHtmlElement`. 
- Testing on different browsers (I checked on Safari, Firefox, and Chrome on Mac OS X).

### CODE REVIEW

File: packages/core/src/common/tetherUtils.ts [hunk 1]
```diff
@@ -14,6 +14,19 @@ const DEFAULT_CONSTRAINTS = {
...
+// per https://github.com/HubSpot/tether/pull/204,
+// Tether now exposes a `bodyElement` option that,
+// when present, gets the tethered element injected
+// into *it* instead of into the document body. but
+// both approaches still cause React to freak out,
+// because it loses its handle on the DOM element.
+// thus, we pass a fake HTML bodyElement to Tether,
+// with a no-op `appendChild` function (the only
+// function the library uses from bodyElement.)
+const fauxHtmlElement = ({
```
Comment (adidahiya) [inline packages/core/src/common/tetherUtils.ts]: Please avoid using "faux" in the terminology and instead opt for a more straightforward name, `fakeBodyElement`. It's harder to follow for non-native English speakers. -1 for this

File: packages/core/src/common/tetherUtils.ts [hunk 2]
```diff
@@ -14,6 +14,19 @@ const DEFAULT_CONSTRAINTS = {
     to: "scrollParent",
 };
 
+// per https://github.com/HubSpot/tether/pull/204,
```
Comment (adidahiya) [inline packages/core/src/common/tetherUtils.ts]: minor: I think the line breaks are a little too aggressive here -- you could comfortably take up more horizontal space

File: packages/core/src/components/portal/_portal.scss [hunk 3]
```diff
@@ -36,3 +36,18 @@ The children of a `Portal` component are appended to the `<body>` element.
 
 Styleguide components.portal.js
 */
+
+.pt-portal {
+  // take the portal out of the document flow to prevent
+  // browsers from autoscrolling to the bottom of the document
+  // (where portals are appended) when programmatically
+  // .focus()'ing within a portal child element. also, don't
```
Comment (adidahiya) [inline packages/core/src/components/portal/_portal.scss]: minor: don't need to say ".focus()", just use plain English, e.g. "focussing"

File: packages/core/src/common/tetherUtils.ts (hunk 2 above)
Comment (giladgray) [inline packages/core/src/common/tetherUtils.ts]: so true! at least 80 characters, could go as many as 100.

Comment (giladgray) [inline packages/core/src/common/tetherUtils.ts]: longer lines will make these comments look less wordy too 👒

**Comment by adidahiya** [comment]
If the DefinitelyTyped PR doesn't merge in the next couple days, I think you should go ahead with this PR for this week's release (but I think they're pretty quick and I already reviewed it, so you should be 👌 )

File: packages/core/src/common/tetherUtils.ts (hunk 1 above)
Comment (cmslewis) [inline packages/core/src/common/tetherUtils.ts]: Done

File: packages/core/src/components/portal/_portal.scss (hunk 3 above)
Comment (cmslewis) [inline packages/core/src/components/portal/_portal.scss]: Done

File: packages/core/src/common/tetherUtils.ts (hunk 2 above)
Comment (cmslewis) [inline packages/core/src/common/tetherUtils.ts]: Done

**Comment by cmslewis** [comment]
@adidahiya the DefinitelyTyped PR hasn't merged yet. How do we move ahead with this PR properly in the meantime?

**Comment by adidahiya** [comment]
@cmslewis you should be able to [merge namespaces](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and add the field you need

**Comment by giladgray** [comment]
@adidahiya in which file? declaration merging can only be done in `.d.ts` files and we track a single one (they're all from `@types`). time to add a `shim.d.ts` for like one release?

**Comment by bbenezech** [comment]
Chrome `55.0.2883.87` (64-bit) (Mac) looks affected as well.
I do think I had no problem with `54` yesterday, but can't be 100% sure. Is it just me?

**Comment by cmslewis** [comment]
bump @giladgray

**Comment by adidahiya** [comment]
@giladgray yes, you can add a `custom-typings.d.ts` for one release.

**Comment by cmslewis** [comment]
Verified on Chrome (v55) + Firefox + Safari on OS X and IE + Chrome on Windows.
