### PR TITLE
[Numeric Input] Add "selectAllOnFocus" and "selectAllOnIncrement" props

### LINKED ISSUE #703: [Numeric Input] Fix two failing cursor-placement unit tests in Firefox
### Bug report

- __Package version(s)__: v1.8.0
- __Browser and OS versions__: Firefox 51.0.1 on OS X 10.11.6

#### Steps to reproduce

1. Run `karma-unit-core` from terminal.
2. Go to `localhost:9876/debug.html` in Firefox.
3. Observe test results for `<NumericInput>`

#### Actual behavior

image

#### Expected behavior

All tests pass in all browsers.

_(Note: all tests currently pass in Safari and Chrome and Phantom)_

### LINKED ISSUE #704: [Numeric Input] Fix focus-hoarding on IE11
### Bug report

- __Package version(s)__: v1.8.0
- __Browser and OS versions__: IE11

#### Steps to reproduce

1. Type something in a numeric input in the docs.
1. Try to focus on something else (via click or <kbd>Tab</kbd>)

#### Actual behavior

You can't.

#### Expected behavior

You can.

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests
- [x] Update documentation
    - New props are automatically added to `NumericInput`'s props tables
    - Added toggles in the basic example for "Select all on focus" and "Select all on increment"

#### Changes proposed in this pull request:

- _New feature:_ Add `selectAllOnFocus` prop.
- _New feature:_ Add `selectAllOnIncrement` prop.
- _Bugfix:_ Fix an unrelated unit-test lint error that wasn't causing builds to fail.
- _Bugfix:_ Fix #703 (failing `karma-unit-core` test in FF)
- _Bugfix:_ Fix #704 (focus hoarding on IE11)

#### Reviewers should focus on:

- [x] As for `EditableText`, the unit tests I added for `selectAllOnFocus` don't work in Phantom. Thus, the tests are included but disabled. Is there a way to get them working? If not, should I keep them or delete them?
- [x] I'm going to try to address #704 in this PR too. (EDIT: Fixed!)

### CODE REVIEW

File: packages/core/src/components/forms/numericInput.tsx [hunk 1]
```diff
@@ -107,6 +119,8 @@ export class NumericInput extends AbstractComponent<HTMLInputProps & INumericInp
         buttonPosition: Position.RIGHT,
         majorStepSize: 10,
         minorStepSize: 0.1,
+        selectAllOnFocus: false,
+        selectAllOnIncrement: false,
```
Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: why default these features off? they use to be enabled all the time.

Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: Just following `EditableText`'s example, but I do prefer having them on. Will switch.

Comment (cmslewis) [inline packages/core/src/components/forms/numericInput.tsx]: Actually, both `EditableText` and `TimePicker` expose a `selectAllOnFocus` prop, and both default the prop to `false`. I'd prefer to stay consistent with their APIs by defaulting `NumericInput`'s `selectAllOnFocus` to `false` too. Thoughts?

Comment (llorca) [inline packages/core/src/components/forms/numericInput.tsx]: +1 on consistency, therefore I think it should be `false`. If necessary, follow up with a PR that changes this default behavior to `true` across the board

Comment (giladgray) [inline packages/core/src/components/forms/numericInput.tsx]: works for me
