### PR TITLE
[Table] Remove invalid selection regions when getting new props

### LINKED ISSUE #881: Invalid table selections are not cleared on data updates
### Bug report

- __Package version(s)__: table 1.10
- __Browser and OS versions__: irrelevant

#### Steps to reproduce

1. supply 2 columns to a `<Table selectionMode={SelectionModes.ALL}>` (uncontrolled selection)
1. select a cell in the 2nd column
1. update `<Table>` children to only have one column

#### Expected behavior

my invalid selection is cleared

### PR DESCRIPTION
**Pull request by gscshoyru**
#### Changes proposed in this pull request:

When receiving new props, if regions are in uncontrolled mode, check all regions to make sure they still fit. Remove the ones that don't. 

#### Reviewers should focus on:

I'm doing this in uncontrolled mode only. Should I do it in controlled mode too?

### CODE REVIEW

**Comment by adidahiya** [comment]
> Should I do it in controlled mode too?

nah, the best you can do is log a `console.warn`, and that could be a separate PR

File: packages/table/src/table.tsx [hunk 1]
```diff
@@ -356,7 +356,20 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         newRowHeights = Utils.arrayOfLength(newRowHeights, numRows, defaultRowHeight);
         newRowHeights = Utils.assignSparseValues(newRowHeights, rowHeights);
 
-        const newSelectedRegions = (selectedRegions == null) ? this.state.selectedRegions : selectedRegions;
+        const numCols = newColumnWidths.length;
+
+        let newSelectedRegions = selectedRegions;
+        if (selectedRegions == null) {
```
Comment (adidahiya) [inline packages/table/src/table.tsx]: leave a comment explaining that this is forking logic based on controlled vs. uncontrolled

File: packages/table/src/table.tsx [hunk 2]
```diff
@@ -356,7 +356,20 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
+            newSelectedRegions = this.state.selectedRegions.filter((region) => {
```
Comment (adidahiya) [inline packages/table/src/table.tsx]: leave a comment explaining why we're filtering at all

**Comment by giladgray** [comment]
util function seems legit. Table has others that operate on regions, no?

File: packages/table/src/regions.ts [hunk 3]
```diff
@@ -467,6 +467,16 @@ export class Regions {
         return true;
     }
 
+    public static isRegionValidForTable(region: IRegion, numRows: number, numCols: number) {
+        if (region.rows != null && (region.rows[0] >= numRows || region.rows[1] >= numRows)) {
```
Comment (cmslewis) [inline packages/table/src/regions.ts]: Do we need to verify that the values are not `< 0` too, or can that not happen / is that excessive?

Comment (gscshoyru) [inline packages/table/src/regions.ts]: It seemed a prudent check to make, given that we're checking that it's in-bounds. You're right that it's probably not necessary, though -- you can have negative regions. I can remove it if you think it's a bad thing to have/is confusing.

Comment (giladgray) [inline packages/table/src/regions.ts]: i'm confused... there's nothing to remove. @cmslewis was asking if we should _also_ verify `< 0`, not just `>= numRows` as you have here.

File: packages/table/src/table.tsx (hunk 1 above)
Comment (adidahiya) [inline packages/table/src/table.tsx]: hm so I was suggesting in another comment that we should also filter the regions in controlled mode and print a console warning

File: packages/table/src/regions.ts (hunk 3 above)
Comment (gscshoyru) [inline packages/table/src/regions.ts]: Guh. 

Somehow I parsed your thing as asking why I was checking if it was < 0 and that caused me to believe that is what I had done. As opposed to doing the opposite. It's a little disturbing my memory is so malleable. 

We don't need it because you can't have negative regions, but I can add it if it's necessary.

File: packages/table/src/table.tsx (hunk 1 above)
Comment (giladgray) [inline packages/table/src/table.tsx]: 🤔  not sure how best to handle this...

Comment (adidahiya) [inline packages/table/src/table.tsx]: something like this

```ts
let regionsToFilter = selectedRegions == null ? this.state.selectedRegions : selectedRegions;
const newSelectedRegions = regionsToFilter.filter((region) => Regions.isRegionValidForTable(region, numRows, numCols));
if (newSelectedRegions.length !== regionsToFilter.length && selectedRegions != null) {
    console.warn(...);
}
```

File: packages/table/src/regions.ts (hunk 3 above)
Comment (giladgray) [inline packages/table/src/regions.ts]: if you can't have them then no need to check.

File: packages/table/src/table.tsx (hunk 1 above)
Comment (giladgray) [inline packages/table/src/table.tsx]: `&& process.env.NODE_ENV !== "production"`?

Comment (adidahiya) [inline packages/table/src/table.tsx]: yeah that too. we should have a `warn` utility function that does that check for us though

Comment (gscshoyru) [inline packages/table/src/table.tsx]: Should I be adding this now? Or it a later commit? A bit unclear at present, sorry.

Comment (adidahiya) [inline packages/table/src/table.tsx]: either in this PR or a follow up. easy change either way
