### PR TITLE
[Fix] Allow focus on items wrapped in disabled tooltips

### LINKED ISSUE #7046: Popover with disabled={true} or empty content prevents focus from reaching wrapped MenuItem
See https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/popover/popover.tsx#L371-L373

#### Environment

- __Package version(s)__: BP-core 5.13.0
- __Operating System__: Mac Sonoma 14.7
- __Browser name and version__: Island Version 1.50.25 Chromium: 129.0.6668.59

#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/p/devbox/peaceful-shadow-yqcnf7

#### Steps to reproduce
- Attempt to tab to button with disabled tooltip, or tooltip with empty content
- Button does not receive focus due to disabled popover

#### Actual behavior
- Disabled popover prevents target from being focused

#### Expected behavior
- Just because a tooltip on a menu item is disabled (either through the prop, or through setting no content), does not mean the menu item itself is disabled and should not receive focus

#### Possible solution
unsure, at first I thought tabIndex was being clobbered but it does look like we take care to not clobber a defined tab index here: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/popover/popover.tsx#L426

I suspect this problem is not specific to MenuItem even though it is appearing there

### PR DESCRIPTION
**Pull request by mm-wang**
#### Checklist

-   [x] Includes tests
-   [ ] Update documentation

#### Changes proposed in this pull request:

The issue that came up was that `targetTabIndex` was `undefined` if the popover is disabled. There seems to have been work to not set `tabIndex` here (https://github.com/palantir/blueprint/pull/6851) as well when content is empty. However, this didn't allow for `menuItem` to set its `tabIndex`.

The fix is to have a fallback for `MenuItem` to set `tabIndex` even if the `htmlProps` come through with a `tabIndex` of `undefined`, since it was being overwritten by `...removeNonHTMLProps`.

#### Reviewers should focus on:

- https://github.com/palantir/blueprint/pull/6851 might now be an issue, need to check.
- Are the a11y responsibilities satisfied with this?

#### Screenshot

demo-app-popover-tab-index

### CODE REVIEW

File: packages/core/src/components/menu/menuItem.tsx [hunk 1]
```diff
@@ -248,15 +248,17 @@ export const MenuItem: React.FC<MenuItemProps> = forwardRef<HTMLLIElement, MenuI
             </span>
         );
 
+    const htmlPropsOnly = removeNonHTMLProps(htmlProps);
```
Comment (mm-wang) [inline packages/core/src/components/menu/menuItem.tsx:251]: Suggestion by @andyboscor, thank you!

**Comment by mm-wang** [comment]
Came back to this with a test:
```
            <Tooltip disabled={true}>
                <MenuItem text="Disabled tooltip, menu item is target" />
            </Tooltip>
            <Tooltip content={""}>
                <MenuItem text="Empty content in tooltip, menu item is target" />
            </Tooltip>
```
tooltip test

Had debated adding another check explicitly to `clonedTarget` in `popover` https://github.com/palantir/blueprint/blob/3ba0fb757acb5c2c2ca94aeaed69678c1c4c5b34/packages/core/src/components/popover/popover.tsx#L345-L351
where we would update `tabIndex` to:
```
tabIndex: childTarget.props.tabIndex ?? (targetTabIndex !== undefined ? targetTabIndex : null)
```
But not sure if it's necessary yet, so leaving this as is.

**Review by ggdouglas — APPROVED** [review]
Tested out some additional scenarios here, but generally the fix here LGTM. Nice work! 👍
