### PR TITLE
[Table] Newly focused cell after keyboard navigation is now transformed

### LINKED ISSUE #2871: Undesired interplay between selectedRegionTransform and focused cells in Table component
#### Environment

- __Package version(s)__: `@blueprintjs/core@3.0.1`, `@blueprintjs/table@3.0.0`
- __Browser and OS versions__: macOS 10.13.5, Firefox 61.0.2

#### Steps to reproduce

1. Create a `<Table>` component that uses `selectedRegionTransform` to enforce full-row selections (see an example function below)
1. Set `enableFocusedCell` to `true` on the component props
1. Click on a cell in the table to select the entire row (works correctly)
1. Press an arrow key to navigate to a neighboring cell

Function to enforce full-row selection:

```ts
const enforceWholeRowSelection = (region: IRegion) => {
    delete region.cols;
    return region;
};
```

#### Actual behavior

When a navigation arrow is pressed, the selection and the focused cell is moved in the appropriate direction, but the selection of the entire row is not enforced (only the newly focused cell is selected, not the row containing it).

#### Expected behavior

The `selectedRegionTransform` function should be called for the newly selected region (containing the focused cell only) and the entire row should be selected; however, the focus should be kept on the exact cell where the user navigated to (and not moved to the top-left cell of the newly selected region, which would be the first cell of the row).

#### Possible solution

In the `handleFocusMove()` private function of the `Table` component, when the value of the `newSelectedRegions` variable is constructed from the newly focused cell, pass it through the `selectedRegionTransform` if it is defined by the user.

### PR DESCRIPTION
**Pull request by ntamas**
#### Changes proposed in this pull request:

This pull request implements a change to the `Table` component that passes the newly focused cell through the `selectedRegionTransform` function of the table if it is present. This is to ensure that invariants enforced in the `selectedRegionTransform` function (e.g., "only whole rows should be selected") are not violated after the user navigates to another cell with the keyboard.

#### Reviewers should focus on:

Please check my changes made to the `handleFocusMove()` method of the `Table` component. I have updated the table dev app as well to make this change easier to test.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @ntamas! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/table/src/table.tsx [hunk 1]
```diff
@@ -1826,6 +1826,11 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
 
         // change selection to match new focus cell location
         const newSelectionRegions = [Regions.cell(newFocusedCell.row, newFocusedCell.col)];
+        const { selectedRegionTransform } = this.props;
+        if (selectedRegionTransform != null) {
+            // tslint:disable-next-line no-unnecessary-callback-wrapper
```
Comment (giladgray) [inline packages/table/src/table.tsx]: do we have to disable this? if so, leave another //comment explaining why.

File: packages/table/src/table.tsx [hunk 2]
```diff
@@ -1826,6 +1826,11 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
...
+            newSelectionRegions.forEach(region => selectedRegionTransform(region, undefined));
```
Comment (giladgray) [inline packages/table/src/table.tsx]: why the explicit `undefined`? i'm not familiar with this code.

Comment (ntamas) [reply packages/table/src/table.tsx]: `selectedRegionTransform()` is a function that takes a region and a mouse event that triggered the selection. In this case, there is no mouse event so the best I could do is to pass `undefined` as the second argument. (I did not want to mess around with the typing of `selectedRegionTransform` as that would be an API breakage). Actually, I was surprised to see that TypeScript accepts `undefined` for an argument that is typed as a `MouseEvent`.

Also, strangely enough, TypeScript complains if I omit the second argument ("Expected 2-3 arguments, got 1"), so that's why we need an explicit `undefined` here.

File: packages/table/src/table.tsx (hunk 1 above)
Comment (ntamas) [reply packages/table/src/table.tsx]: You are correct -- there is no need to disable this. Shall I add another commit to this PR to remove this line and will you squash it if it gets merged eventually?

**Comment by ntamas** [comment]
I have added the auth token after I have realized that CircleCI failed the checks and I have re-ran the pipeline on CircleCI. Is there anything else I need to do?

File: packages/table/src/table.tsx (hunk 1 above)
Comment (giladgray) [reply packages/table/src/table.tsx]: yes add commits. do not force push on PRs.

File: packages/table/src/table.tsx (hunk 2 above)
Comment (giladgray) [reply packages/table/src/table.tsx]: yeah this is not valid. it only accepts `undefined` because we have not enabled 
`strictNullChecks` compiler options.

File: packages/table/src/table.tsx [hunk 3]
```diff
@@ -1827,10 +1827,11 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         // change selection to match new focus cell location
         const newSelectionRegions = [Regions.cell(newFocusedCell.row, newFocusedCell.col)];
         const { selectedRegionTransform } = this.props;
-        if (selectedRegionTransform != null) {
-            newSelectionRegions.forEach(region => selectedRegionTransform(region, undefined));
-        }
-        this.handleSelection(newSelectionRegions);
+        const transformedSelectionRegions =
+            selectedRegionTransform != null
+                ? newSelectionRegions.map(region => selectedRegionTransform(region, undefined))
```
Comment (giladgray) [inline packages/table/src/table.tsx]: this `undefined` breaks the type contract. blocker for this feature.

Comment (ntamas) [reply packages/table/src/table.tsx]: Might be overkill but would it be acceptable to create a fake `MouseEvent` that simulates a click on the middle of the cell that the focus is being moved to?

Comment (giladgray) [reply packages/table/src/table.tsx]: this code is inside an event handler so we do have an event, it's just not a MouseEvent. best solution may be to change type to `MouseEvent | FocusEvent`

Comment (ntamas) [reply packages/table/src/table.tsx]: We have a `KeyboardEvent` there, not a `FocusEvent`, but I see your point. That would be a major version bump, though - so this has to wait until Blueprint 4, right?

Comment (giladgray) [reply packages/table/src/table.tsx]: oh right my bad it is a keyboard event. 

honestly this table library will never have a v4. we're working on a complete rewrite internally that will replace this implementation completely. it's going to be so much better but also quite different.

Comment (giladgray) [reply packages/table/src/table.tsx]: i'm willing to merge this change and declare it a bug fix, not an API break. makes sense for keyboard events to go through this flow just like mouse events. typescript users will see compile errors if they're relying on `MouseEvent` properties so at least it won't be silent.

Comment (ntamas) [reply packages/table/src/table.tsx]: Changed the typing of `ISelectedRegionTransform` in 6a35c0a0 - this version now also forwards the `KeyboardEvent` to the region transform function.

File: packages/table/src/table.tsx [hunk 4]
```diff
@@ -1829,7 +1829,7 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
         const { selectedRegionTransform } = this.props;
         const transformedSelectionRegions =
             selectedRegionTransform != null
-                ? newSelectionRegions.map(region => selectedRegionTransform(region, undefined))
+                ? newSelectionRegions.map(region => selectedRegionTransform(region, e))
```
Comment (giladgray) [inline packages/table/src/table.tsx]: do we have `ICoordinateData` for the third argument? perhaps `newFocusedCell`? (i'm not looking at the code actively)

Comment (ntamas) [reply packages/table/src/table.tsx]: `ICoordinateData` is defined in `src/interactions/draggable.tsx` and it seems to hold data that is relevant only for dragging gestures. The only time when this argument is used at the moment is in `handleDragMove()` in `src/interactions/selectable.tsx`. I would say that it is not relevant here.

Comment (giladgray) [reply packages/table/src/table.tsx]: nice thank you
