### PR TITLE
[OverflowList] fix browser zoom behavior

### LINKED ISSUE #2873: [OverflowList] All items are collapsed outside of 100% zoom
#### Environment

- __Browser and OS versions__: macOS 10.13 + Chrome 68.0.3440.106

#### Steps to reproduce

1. Navigate to `OverflowList` example
1. Increase the containers size so you can see more than one breadcrumb
1. Change your browser's zoom level to a non-100% value

#### Actual behavior

All items collapse into the overflow

#### Expected behavior

The number of visible items doesn't change

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- adjust the threshold to be slightly more permissive.

### CODE REVIEW

File: packages/core/src/components/overflow-list/overflowList.tsx [hunk 1]
```diff
@@ -170,8 +170,8 @@ export class OverflowList<T> extends React.PureComponent<IOverflowListProps<T>,
                 overflow: [],
                 visible: this.props.items,
             });
-        } else if (this.spacer.getBoundingClientRect().width < 1) {
-            // spacer has flex-shrink and width 1px so if it's any smaller then we know to shrink
+        } else if (this.spacer.getBoundingClientRect().width < 0.98) {
```
Comment (invliD) [inline packages/core/src/components/overflow-list/overflowList.tsx]: should we be even more permissive here, maybe 0.5?

Comment (giladgray) [reply packages/core/src/components/overflow-list/overflowList.tsx]: that feels extreme? 0.9 may be sufficient
