### PR TITLE
fixes: helperText no longer accepting React nodes

### LINKED ISSUE #2279: label helperText no longer accepting React nodes
### Bug report

- __Package version(s)__: 2.0.0-rc.3
- __Browser and OS versions__: Chrome, macOS

#### Steps to reproduce

1. Use a React node as helperText on a Label

```js
<Label
  text="Username"
  helperText={
      <span style={{ display: 'block', fontSize: '80%' }}>
          blah
       </span>
  }
>
  ...
</Label>
```

#### Actual behavior

This now displays as : `Username [object Object]`

#### Expected behavior

The helperText displays React node.

I suggest changing to:

```js
{helperText && <span className={classNames(Classes.TEXT_MUTED)}>{" "}{helperText}</span>}
```

### PR DESCRIPTION
**Pull request by will-stone**
#### Changes proposed in this pull request:

The current implementation of helperText on Label only allows for text, this fixes the regression and allows for React nodes again.

#### Reviewers should focus on:

Adding React nodes as helperText

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @will-stone! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/core/src/components/forms/label.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ export class Label extends React.PureComponent<ILabelProps, {}> {
         return (
             <label {...htmlProps} className={rootClasses}>
                 {text}
-                {helperText && <span className={classNames(Classes.TEXT_MUTED)}>{" " + helperText}</span>}
+                {helperText && <span className={classNames(Classes.TEXT_MUTED)}>{" "}{helperText}</span>}
```
Comment (giladgray) [inline packages/core/src/components/forms/label.tsx]: while we're at it, can you remove the `classNames()` call? not necessary for one class.

Comment (giladgray) [reply packages/core/src/components/forms/label.tsx]: @will-stone i went ahead and made this change here. thanks!

File: packages/core/src/components/forms/label.tsx [hunk 2]
```diff
@@ -42,7 +42,7 @@ export class Label extends React.PureComponent<ILabelProps, {}> {
         return (
             <label {...htmlProps} className={rootClasses}>
                 {text}
-                {helperText && <span className={classNames(Classes.TEXT_MUTED)}>{" " + helperText}</span>}
+                {helperText && <span className={Classes.TEXT_MUTED}>{" "}{helperText}</span>}
```
Comment (reiv) [inline packages/core/src/components/forms/label.tsx]: tslint/prettier is complaining about this line:

Replace `{"·"}` with `·`
