### PR TITLE
[Spinner] add additional child element to isolate spinner from parent

### LINKED ISSUE #2880: Spinner makes big circles
#### Environment

- __Package version(s)__: 

    "@blueprintjs/core": "3.4.0",
    "react": "16.4.2",
    "react-dom": "16.4.2",
    "react-scripts": "1.1.5",
    "react-transition-group": "2.4.0"

- __Browser and OS versions__: 

Linux (Ubuntu 14.04) with Chrome and Firefox

#### Steps to reproduce

I was migrating from 2.3.1 to 3.4.0 and found the following problem:
https://codesandbox.io/s/zl83zv89ox

#### Actual behavior

Instead of spinning in place, the spinner moves in a big circle.

#### Expected behavior

Should behave as a normal spinner.

#### Possible solution

No idea.

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- add `spinner-animation` element to isolate spinner from parent display styles
- this is basically what we had [back in 1.x](https://blueprintjs.com/docs/versions/1/#core/components/progress/spinner.css-api) with `.pt-spinner > .pt-spinner-svg-container > svg`

### CODE REVIEW

File: packages/core/src/components/spinner/spinner.tsx [hunk 1]
```diff
@@ -81,16 +81,18 @@ export class Spinner extends AbstractPureComponent<ISpinnerProps, {}> {
...
-                    <path className={Classes.SPINNER_TRACK} d={SPINNER_TRACK} />
-                    <path
-                        className={Classes.SPINNER_HEAD}
-                        d={SPINNER_TRACK}
-                        pathLength={PATH_LENGTH}
-                        strokeDasharray={`${PATH_LENGTH} ${PATH_LENGTH}`}
-                        strokeDashoffset={strokeOffset}
-                    />
-                </svg>
+                <span className={Classes.SPINNER_ANIMATION}>
```
Comment (themadcreator) [inline packages/core/src/components/spinner/spinner.tsx]: you have previously lamented the lack of comments in this part of the code, which caused many commits and reversions. So, add a whole bunch of comments here as to why we need so many wrappers.

Comment (giladgray) [reply packages/core/src/components/spinner/spinner.tsx]: https://github.com/palantir/blueprint/pull/2890/files#diff-85bf4db926db7eec3120880625d59adbR42

Comment (giladgray) [reply packages/core/src/components/spinner/spinner.tsx]: comments in styles

Comment (giladgray) [reply packages/core/src/components/spinner/spinner.tsx]: and now here too 👍
