### PR TITLE
[v5] [table] fix: stop using findDOMNode in Draggable interactions

### LINKED ISSUE #3979: Removing findDOMNode
**Update**:
I think my analysis about how this can be solved is wrong. See my [comment](https://github.com/palantir/blueprint/issues/3979#issuecomment-705573953).

---

As part of the move to strict and concurrent mode support, I'd like to tackle removing usages of `findDOMNode`. I analyzed the scope of changes needed in the first-party components and possible implications on third-party consumers.

### Refs (preferred)
Refs are probably the standard way to get access to an HTML node. Instead of explicitly wiring refs through the consuming component, they can often be set through `cloneElement`.
**Downsides:**
- Can reference JSX elements instead of DOM nodes

**Workarounds:**
- Add a warning in the documentation and print a runtime warning
- Some components already only allow a single DOM node as a child (e.g. `ResizeSensor`)
  - Can clone the element and attach a ref that way

### Wrapper element
**Downsides:**
- Can cause problems with DOM nesting and layout
- Possible performance overhead

**Workarounds:**
- `display: contents;` (doesn't work all most usages)
- Provide `tagName`, etc. properties

### ResizeSensor
ResizeSensor uses `findDOMNode` to attach a ResizeObserver to the child node. It requires a single DOM node child and can use `cloneElement` to attach a ref. I don't know about the performance implications of `cloneElement` (resize sensor explicitly mentions this in the source comments), but `ContextMenuTarget` also uses `cloneElement`. My understanding is that `cloneElement` is pretty cheap. I don't even think it's slower than `findDOMNode`, so I'd say `cloneElement` and attaching a ref is the way to go here.

### ContextMenuTarget
The element returned by `findDOMNode` is used to check if dark mode is enabled or not, by calling a helper method. `ContextMenuTarget` already requires a DOM node and uses `cloneElement` to attach the event-listener so that we can attach a ref in the same call.

### Overlay
If I understand this correctly `TransitionGroup` creates a container by instantiating the component passed to it. As `Overlay` requests a `div`, this `div` is the element we want a reference to. I currently don't know how to get a ref to this `div`. Afaik `TransitionGroup` doesn't expose a reference. This needs some further investigation.

## Conclusion
Without considering `Overlay`, I'd say this is doable without breaking changes. I would split this into three separate tasks.

1. Using `cloneElement` in `ContextMenuTarget` to attach a ref is a non-breaking change. 
2. Using `cloneElement` in `ResizeSensor` to attach a ref is a non-breaking change.
3. `Overlay` needs some further investigation.

There have been previous issues that mentioned `findDOMNode`. For reference:
- #3361 
- #3797

### PR DESCRIPTION
**Pull request by adidahiya**
#### Changes proposed in this pull request:

Migrate away from `ReactDOM.findDOMNode()` in the `<Draggable>` component by borrowing an implementation from `<ResizeSensor>` which clones its single React child and injects its own DOM ref. ~It's even simpler here than in ResizeSensor because we don't have to deal with a prop ref sent to `<Draggable>`.~

#### @blueprintjs/core changelog

- fix(`ResizeSensor`): account for `props.targetRef` if specified (previously, this component would not actually take DOM measurements properly if this prop was specified)
  - :warning: break: the type of the `targetRef` prop is now more specific, it only allows ref objects and no ref callbacks. Before this change, this prop's usage broke the component completely, so it's extremely unlikely that this break will impact any users negatively.
- feat(`EditableText`): new prop `elementRef` allows users to pass through a DOM ref (useful for taking measurements or implementing interactions like `<Draggable>` in @blueprintjs/table)

#### @blueprintjs/table changelog

- fix: stop using `ReactDOM.findDOMNode()` to implement drag & drop interactions, which unblocks support for React strict mode

#### Reviewers should focus on:

No regressions in dragging behavior in Table component demos

#### Screenshot

Note that there are some delays in re-rendering cells (until you scroll around a bit in some cases), but these are bugs present on develop too:

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>fix compile</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/e58a0712-948b-4e81-ac1f-2b8d7f24195d/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/e58a0712-948b-4e81-ac1f-2b8d7f24195d/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/e58a0712-948b-4e81-ac1f-2b8d7f24195d/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/e58a0712-948b-4e81-ac1f-2b8d7f24195d/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>plumb through targetRef</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/90eff6ae-2aec-4ad5-876e-ae945aab5cba/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/90eff6ae-2aec-4ad5-876e-ae945aab5cba/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/90eff6ae-2aec-4ad5-876e-ae945aab5cba/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/90eff6ae-2aec-4ad5-876e-ae945aab5cba/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/core/src/components/popover/popover.tsx [hunk 1]
```diff
@@ -330,8 +319,6 @@ export class Popover<
             targetTagName = "div";
         }
 
-        const ref = mergeRefs(popperChildRef, this.targetRef);
```
Comment (adidahiya) [inline packages/core/src/components/popover/popover.tsx:333]: no longer need to merge refs, since react-popper is already doing that under the hood: https://github.com/floating-ui/react-popper/blob/beac280d61082852c4efc302be902911ce2d424c/src/Reference.js#L17-L23

File: packages/core/src/components/resize-sensor/resizeSensor.tsx [hunk 2]
```diff
@@ -55,7 +55,7 @@ export interface ResizeSensorProps {
      * If you attach a `ref` to the child yourself when rendering it, you must pass the
      * same value here (otherwise, ResizeSensor won't be able to attach its own).
      */
-    targetRef?: React.Ref<any>;
+    targetRef?: React.RefObject<HTMLElement>;
```
Comment (adidahiya) [inline packages/core/src/components/resize-sensor/resizeSensor.tsx:58]: slight breaking change - see PR description for justification

**Comment by adidahiya** [comment]
<h3>Fix Popover <> ResizeSensor</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/f7cfb338-49f9-441b-9ccb-60743cdb79eb/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/f7cfb338-49f9-441b-9ccb-60743cdb79eb/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/f7cfb338-49f9-441b-9ccb-60743cdb79eb/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/f7cfb338-49f9-441b-9ccb-60743cdb79eb/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>Fix test typecheck</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/f20bc01e-7e37-4db0-bfd5-d2e1ea825cbe/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/f20bc01e-7e37-4db0-bfd5-d2e1ea825cbe/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/f20bc01e-7e37-4db0-bfd5-d2e1ea825cbe/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/f20bc01e-7e37-4db0-bfd5-d2e1ea825cbe/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>
