### PR TITLE
fix: downgrade fantasticon, fix windows build

### LINKED ISSUE #6019: yarn verify -   sass.Exception [Error]: Can't find stylesheet to import.
#### Environment

- __Package version(s)__: Latest
- __Operating System__: Windows 11
- __Browser name and version__: N/A

Running `yarn verify` errors on `@blueprintjs/icons:compile` with `sass.Exception [Error]: Can't find stylesheet to import`:

```
 √  @blueprintjs/test-commons:compile (7s)
    √  @blueprintjs/tslint-config:compile (7s)
    √  @blueprintjs/colors:compile (8s)

    ×  @blueprintjs/icons:compile
$ npm-run-all -s "generate-icon-src" -p "compile:*" -p "copy:*"
$ node scripts/generate-icon-fonts.mjs && node scripts/generate-icon-paths.mjs
(node:832) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
Generating font kit...
(node:832) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
No SVGs found in C:\Users\blake.vandercar\Code\blueprint\resources\icons\16px
No SVGs found in C:\Users\blake.vandercar\Code\blueprint\resources\icons\20px
(node:29512) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
Parsed 568 16px icons.
Writing index file for 16px icon kit paths...
Done.
Parsed 568 20px icons.
Writing index file for 20px icon kit paths...
Done.
(node:29512) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
$ tsc -p ./src
$ tsc -p ./src -t esnext --outDir lib/esnext
$ tsc -p ./src -m commonjs --outDir lib/cjs
$ sass-compile ./src
node:internal/process/esm_loader:100
           internalBinding('errors').triggerUncaughtException(
                                     ^

       sass.Exception [Error]: Can't find stylesheet to import.
         ╷
       6 │ @import "generated-icons/16px/blueprint-icons-16";
         │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         ╵
         src\blueprint-icons.scss 6:9  root stylesheet
           at Object.wrapException (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:1250:17)
           at C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:71174:25
           at _wrapJsFunctionForAsync_closure.$protected (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:3841:15)
           at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:28694:12)
           at _awaitOnObject_closure.call$1 (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:28682:32)
           at Object._rootRunUnary (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:4216:18)
           at StaticClosure.<anonymous> (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:100086:16)
           at _CustomZone.runUnary$2$2 (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:30091:39)
           at _Future__propagateToListeners_handleValueCallback.call$0 (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:29163:51)
           at Object._Future__propagateToListeners (C:\Users\blake.vandercar\Code\blueprint\node_modules\sass\sass.dart.js:4012:93)

       Node.js v19.8.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by bvandrc**
Fixes #6019 - downgrade fantasticon from 2.0.0 to ^1.2.3 in icons\package.json. Unfixed issue: https://github.com/tancredi/fantasticon/issues/470 .

Also includes a fix in [packages/docs-data/compile-docs-data.mjs](https://github.com/palantir/blueprint/pull/6020/files#diff-4f717f7533e4652bd8c385c37a78e2dd39b6962563500218c94bb2d3677c1de9) due to issue: https://github.com/palantir/documentalist/issues/98

### CODE REVIEW

File: packages/docs-data/compile-docs-data.mjs [hunk 1]
```diff
@@ -46,6 +46,10 @@ async function generateDocumentalistData() {
         // must mark our @Decorator APIs as reserved so we can use them in code samples
         reservedTags: ["import", "ContextMenuTarget", "HotkeysTarget", "param", "returns"],
     })
+        .use(".md", {
+            compile: files =>
+                process.platform === "win32" ? files.map(file => file.read().replace(/\r\n/g, "\n")) : files,
```
Comment (adidahiya) [inline packages/docs-data/compile-docs-data.mjs:53]: please leave a comment here:

```suggestion
                // HACKHACK: special case for Windows environment
                // see https://github.com/palantir/documentalist/issues/98
                process.platform === "win32" ? files.map(file => file.read().replace(/\r\n/g, "\n")) : files,
```

**Review by adidahiya — CHANGES_REQUESTED** [review]
please update `dependabot.yml` to ignore `fantasticon`, similar to how we're treating `svgo` upgrades. include a reference to the fantasticon issue, e.g. `# see https://github.com/tancredi/fantasticon/issues/470`

**Review by adidahiya — APPROVED** [review]
