### PR TITLE
[popover2] fix(Popover2): renderTarget typedef regression

### LINKED ISSUE #5889: New type for IPopover2SharedProps.renderTarget creates ambiguous type where properties are resolved as unknown
https://github.com/palantir/blueprint/commit/8d793f6c229cf372b11b0909573f69a35692e161#r97915117

> FYI, this is a breaking change as it creates an ambiguous type. For example, since onFocus is only defined in Popover2HoverTargetHandlers and not Popover2ClickTargetHandlers, TypeScript interprets the the type of onFoucs as unknown.
> 
> It causes CI to fail like this: https://github.com/pybricks/pybricks-code/actions/runs/3993794470/jobs/6850831641#step:5:6
> 
> Source code that triggered this is here: https://github.com/pybricks/pybricks-code/blob/939ded73fa18e26ae8aeedc88d95f1c9077eccce/src/toolbar/ActionButton.tsx#L103

#### Environment

- __Package version(s)__:"@blueprintjs/popover2": "^1.12.0",
- __Operating System__: any
- __Browser name and version__: any

#### Code Sandbox

Don't have time to do this at the moment, but see link above for CI failure.

#### Steps to reproduce

1. use Tooltip2 with renderTarget as recommended in the docs: https://blueprintjs.com/docs/#popover2-package/tooltip2
1. update @blueprintjs/popover2 to v1.12.0
1. Typescript type checking breaks and code no longer compiles

#### Possible solution

Types that inherit from IPopover2SharedProps should `Omit<..., 'renderTarget'>`  and supply the correct type.

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

- Use AND `&` type union instead of OR `|` to allow access to common props passed to `renderTarget`
- Add type param constraints to `Tooltip2` (this should fix the linked issue)

#### Reviewers should focus on:

No regressions, and the new unit test is appropriate

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>add default type params</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/c5e3066e-6379-42f9-8548-fc6b2a4383b4/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/c5e3066e-6379-42f9-8548-fc6b2a4383b4/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/c5e3066e-6379-42f9-8548-fc6b2a4383b4/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/c5e3066e-6379-42f9-8548-fc6b2a4383b4/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>clean up types</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/bb3398ba-3f61-43a8-905f-b8cf5b3b00c1/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/bb3398ba-3f61-43a8-905f-b8cf5b3b00c1/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/bb3398ba-3f61-43a8-905f-b8cf5b3b00c1/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/bb3398ba-3f61-43a8-905f-b8cf5b3b00c1/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/datetime2/src/components/date-input2/dateInput2.tsx [hunk 1]
```diff
@@ -568,13 +568,7 @@ export const DateInput2: React.FC<DateInput2Props> = React.memo(function _DateIn
 
     // We use the renderTarget API to flatten the rendered DOM and make it easier to implement features like the "fill" prop.
     const renderTarget = React.useCallback(
-        // N.B. pull out `defaultValue` so that it's not forwarded to the DOM.
```
Comment (adidahiya) [inline packages/datetime2/src/components/date-input2/dateInput2.tsx:571]: note that this is another benefit of the type changes in https://github.com/palantir/blueprint/pull/5802 -- we no longer have to deal with extraneous props which are not actually passed to the target renderer, but were presumed to exist in the previous type definitions 👍🏽
