### PR TITLE
[core] Add space in between Label 'text' and 'helperText'.

### LINKED ISSUE #2175: [label] missing space between text and helperText
### Bug report

- __Package version(s)__: 2.0.0-rc.2
- __Browser and OS versions__: Chrome 64, macOS Sierra 10.12.6

#### Steps to reproduce

```js
<Label
  text="Username"
  helperText="(blah blah)"
>
  <input autoFocus={true} className="pt-input" type="text" />
</Label>
```
#### Actual behavior

Label= "Username(blah blah)"

#### Expected behavior

Label= "Username (blah blah)"

### PR DESCRIPTION
**Pull request by danielbh**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/gh/danielbh/blueprint)
- [x] Include tests
- [x] Update documentation (not need, its a bugfix)

#### Changes proposed in this pull request:

Adds a space in between `text` and `helperText` for the Label component

#### Reviewers should focus on:

The updated `Label` component and new tests

#### Screenshot

`Before`

screen shot 2018-02-23 at 10 05 46 pm

`After`

screen shot 2018-02-23 at 11 15 07 pm

### CODE REVIEW

**Comment by danielbh** [comment]
Good morning. Having a bit if trouble getting Circle to run on my new branch.. Is this something you do on your end? Excited to start helping out.

**Comment by adidahiya** [comment]
Looks like your build workflow did run, but it was canceled. Can you try to retrigger it? https://circleci.com/gh/danielbh/workflows/blueprint/tree/dh%2Fadd-space-between-text-and-helperText

**Comment by danielbh** [comment]
<h3>Update labelTests.tsx</h3>

Preview: <strong><a href='https://70-122696040-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://70-122696040-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://70-122696040-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by adidahiya** [comment]
thanks!

File: packages/core/src/components/forms/label.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ export class Label extends React.PureComponent<ILabelProps, {}> {
         return (
             <label {...htmlProps} className={rootClasses}>
                 {text}
-                <span className={classNames(Classes.TEXT_MUTED)}>{helperText}</span>
+                <span className={classNames(Classes.TEXT_MUTED)}>{helperText ? " " + helperText : ""}</span>
```
Comment (will-stone) [inline packages/core/src/components/forms/label.tsx]: As the helper text is conditional, would it not be best to keep the span out of the DOM completely if helperText doesn't exist? e.g.
```
{helperText && <span className={classNames(Classes.TEXT_MUTED)}>{" " + helperText}</span>}
```

Comment (danielbh) [reply packages/core/src/components/forms/label.tsx]: Thanks for pointing this out Will. It seems cleaner to me. I’ll look if this affects the CSS. I can re-submit a PR tonight.

Comment (will-stone) [reply packages/core/src/components/forms/label.tsx]: Ah, the changes have broken the ability to add a React node as the helpertext e.g.
```js
<Label
  text="Username"
  helperText={
      <span style={{ display: 'block', fontSize: '80%' }}>
          blah
       </span>
  }
>
  ...
</Label>
```

This now displays as : `Username [object Object]`

I suggest changing to:

```js
{helperText && <span className={classNames(Classes.TEXT_MUTED)}>{" "}{helperText}</span>}
```
