### PR TITLE
Remove PureRender and default to detect truncation

### LINKED ISSUE #760: Detect truncation does not work on JSONFormat
### Bug report

- __Package version(s)__: BP Table 1.7.0
- __Browser and OS versions__: Chrome 56.0.2924.87, OS X 10.11

#### Steps to reproduce

1. Set `detectTruncation` to true and `showPopover` to `TruncatedPopoverMode.WHEN_TRUNCATED`

#### Actual behavior

The popover button never appears when the text is truncated.

mar-02-2017 17-21-35

#### Expected behavior

The popover button should appear when text is truncated.

### PR DESCRIPTION
**Pull request by michael-yx-wu**
#### Changes proposed in this pull request:

Remove `PureRender` and change the default props to detect truncation.

#### Reviewers should focus on:

I left JSONFormat alone when first implementing the detect truncation feature because I thought people might prefer to just always show the popover to view JSON and manually truncate. Are the default props changes okay?

#### Screenshot
JSONFormat now properly detects truncation 

screen shot 2017-03-02 at 5 26 43 pm

### CODE REVIEW

**Comment by michael-yx-wu** [comment]
@gscshoyru mentioned this might be a back compat break. should i revert the default props change?

**Comment by adidahiya** [comment]
no, I think this is fine -- it's an improvement of the default design

**Comment by gscshoyru** [comment]
Cool -- just wasn't sure how we handled that kind of backcompat. Sounds good to me :) 👍

**Comment by adidahiya** [comment]
why do you need to remove `@PureRender`?

**Comment by michael-yx-wu** [comment]
it doesn't seem to re-render when resizing columns otherwise. since we detect truncation after the component updates, we end up never detecting truncation

File: packages/table/src/cell/formats/jsonFormat.tsx [hunk 1]
```diff
@@ -30,26 +29,25 @@ export interface IJSONFormatProps extends ITruncatedFormatProps {
     stringify?: (obj: any) => string;
 }
 
-@PureRender
```
Comment (giladgray) [inline packages/table/src/cell/formats/jsonFormat.tsx]: why remove this? please justify.

Comment (michael-yx-wu) [inline packages/table/src/cell/formats/jsonFormat.tsx]: see my response to adi on the general comments thread

Comment (adidahiya) [inline packages/table/src/cell/formats/jsonFormat.tsx]: that doesn't sound right, this is a simple stateless component without any lifecycle hooks -- can you dig in to why it's not re-rendering, probably something further up the tree

Comment (adidahiya) [inline packages/table/src/cell/formats/jsonFormat.tsx]: ping here, please ack @michael-yx-wu / @giladgray

Comment (michael-yx-wu) [inline packages/table/src/cell/formats/jsonFormat.tsx]: My understanding is that because column resize doesn't directly result in props or state changes, a `@PureRender` `JSONFormat` component will never re-render on resize. Because `JSONFormat` renders a `TruncatedFormat` and the detect truncation code is triggered by `TruncatedFormat#componentDidUpdate`, the detect truncation code will also not run on resize.

Comment (adidahiya) [inline packages/table/src/cell/formats/jsonFormat.tsx]: > because column resize doesn't directly result in props or state changes

sounds like we should fix that instead. the current solution is a band-aid

Comment (michael-yx-wu) [inline packages/table/src/cell/formats/jsonFormat.tsx]: the obvious solution to me is listening for resize events. i remember this didn't work for some reason but i can look into it again.
