### PR TITLE
moment-timezone compatability for DateInput

### LINKED ISSUE #280: DateInput + Moment-Timezone incompatability
### BLUF

Using Moment-Timezone's [setDefault](http://momentjs.com/timezone/docs/#/using-timezones/default-timezone/) call, the DateInput UI becomes inconsistent.

### Bug report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__:  Mac OSX 10.11.6 / Chrome 54.0.2840.98 (64-bit)

#### Steps to reproduce

1. Use moment-timezone to set a default timezone, which affects all usage of the global 'moment'.
2. Create a `<DateInput>` element with a specific date
3. Configure specific problematic combinations of moment timezone and browser timezone.

#### Actual behavior

Depending on moment-timezone's configured timezone, and the browser's local timezone, the formatted date disagrees with the calendar date. For instance, if moment-timezone is set to `America/Los_Angeles` and the browser's timezone is set to Hawaii. The formatted date is correct, but the calendar will show a day behind. This has further repercussions when trying to get the time out of onChange as well.

#### Expected behavior

The DateInput correctly handles the timezone disagreement between moment and date.

#### Possible solution

I have built some quick functions that convert from moment->date that correct for the timezone discrepancy. They should be equivalent to a noop if a default timezone has not been set. The Date being passed into the render `<DatePicker>` and returned into `handleDateChange` can be adjusted with the methods below. It is important to make sure that the DateInput `value` prop is in the same timezone as the the date returned to the `onChange` prop.

```ts
/**
 * Translate a moment into a Date object, adjusting the moment timezone into the local one
 */
export function toDateFromMoment(date: moment.Moment) {
    return new Date(
        date.year(),
        date.month(),
        date.date(),
        date.hours(),
        date.minutes(),
        date.seconds(),
        date.milliseconds()
    );
}

/**
 * Translate a Date object into a moment, adjusting the local timezone into the moment one
 */
export function toMomentFromDate(date: Date) {
    return moment([
        date.getFullYear(),
        date.getMonth(),
        date.getDate(),
        date.getHours(),
        date.getMinutes(),
        date.getSeconds(),
        date.getMilliseconds(),
    ]);
}
```

### PR DESCRIPTION
**Pull request by mfedderly**
#### Changes proposed in this pull request:

- Properly handle moment-timezone's setDefault
- DateInput accepts dates in the local timezone
- DateInput onChange returns dates in the local timezone

#### Reviewers should focus on:

- DateInput.handleDateChange method 
- Making sure this works in multiple timezones
- Making sure this works with and without moment-timezone

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @mfedderly! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/datetime/src/dateInput.tsx [hunk 1]
```diff
@@ -320,4 +321,36 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
     private setInputRef = (el: HTMLElement) => {
         this.inputRef = el;
     }
+
+    /**
+     * Translate a moment into a Date object, adjusting the moment timezone into the local one.
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: where does the adjustment happen? i'm assuming it's _inside_ moment but it's not obvious _why_ this works.

File: packages/datetime/src/dateInput.tsx [hunk 2]
```diff
@@ -320,4 +321,36 @@ export class DateInput extends AbstractComponent<IDateInputProps, IDateInputStat
...
+     * This is a no-op unless moment-timezone's setDefault has been called.
+     */
+    private fromMomentToDate = (date: moment.Moment) => {
```
Comment (giladgray) [inline packages/datetime/src/dateInput.tsx]: a different name would be helpful to clarify that this is not a `Date`. `momentDate`?

File: packages/datetime/src/dateInput.tsx (hunk 1 above)
Comment (mfedderly) [inline packages/datetime/src/dateInput.tsx]: Date objects are always in the local timezone. Moment operates in the specified timezone after moment.tz.setDefault has been called (or the local timezone if none has been configured). Therefore directly copying the individual components of the dates corrects for the timezone discrepancy.

File: packages/datetime/src/dateInput.tsx (hunk 2 above)
Comment (mfedderly) [inline packages/datetime/src/dateInput.tsx]: Sounds good.

**Comment by giladgray** [comment]
thanks @mfedderly!
