### PR TITLE
Fix toast autofocus

### LINKED ISSUE #469: Auto focus for toast example not working
### Bug report

- __Package version(s)__: 1.5.0
- __Browser and OS versions__: macOS, Chrome 55

#### Steps to reproduce

1. http://blueprintjs.com/docs/#components.toaster
1. Switch "Auto focus" on
1. Trigger a toast
1. Press `tab` to focus the buttons inside the toast

#### Actual behavior

Buttons can't be focused after the toast appears

#### Expected behavior

Buttons inside the toast can be focused right after the toast appears

### PR DESCRIPTION
**Pull request by leebyp**
#### Checklist

- [x] Include tests

#### Changes proposed in this pull request:

- Add `tabIndex` to toast wrappers - necessary from the changes in #276, which is looking for an explicit `tabIndex`.
- Another solution is that we could set the `tabIndex` on the first toast if `autoFocus` is set to true, but I don't want to expose that in the Toast props...

### CODE REVIEW

File: packages/core/test/toast/toasterTests.ts [hunk 1]
```diff
@@ -121,4 +121,17 @@ describe("Toaster", () => {
             "mutation side effect!",
         );
     });
+
+    describe("with autoFocus set to true", () => {
```
Comment (giladgray) [inline packages/core/test/toast/toasterTests.ts]: no need to add a whole describe block here, just make it one more test in the block above.

also redundancy between `describe` and `it` here.

Comment (leebyp) [inline packages/core/test/toast/toasterTests.ts]: we need to set the toaster with `autoFocus: true`, I could turn it on for all the above too, but it's not the default so a new block makes sense

Comment (giladgray) [inline packages/core/test/toast/toasterTests.ts]: _oh_ because it's a prop on the `Toaster` instance. ok well then just fix the redundancy in `it` name. no need to repeat "autoFocus is set to true"
