### PR TITLE
Only add buffer widths in EditableText for IE and Edge

### LINKED ISSUE #482: Editable focused state is of different size than hover state
### Bug report

- __Package version(s)__: 1.5.0
- __Browser and OS versions__:  macOS, Chrome 55

#### Steps to reproduce

1. http://blueprintjs.com/docs/#components.editable
1. Hover editable header
1. Click editable header

#### Actual behavior

Hover has a nice border right around the text, while focus state adds extra 30px padding on the right.

screen recording google chrome

#### Expected behavior

Focused input is the same size as the hover border.

### PR DESCRIPTION
**Pull request by leebyp**
#### Checklist

- [x] Chrome v55.0 (no shift)
- [x] Firefox v51.0 (no shift)
- [x] IE 11.0 (shift 30px)
- [x] Edge 13.0 (shift 5px)

### CODE REVIEW

File: packages/core/src/compatibility/browser.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+const userAgent = navigator.userAgent;
+const browser = {
+    isEdge: !!userAgent.match(/Edge/),
+    isInternetExplorer: (!!userAgent.match(/Trident/) || !!userAgent.match(/rv:11/)),
+};
+
+export const Browser = {
+    isEdge: () => browser.isEdge,
+    isInternetExplorer: () => browser.isInternetExplorer,
```
Comment (giladgray) [inline packages/core/src/compatibility/browser.ts]: why are these functions that return constants? instead of constants themselves? 

(remember you can't modify constants, by definition)

File: packages/core/src/compatibility/index.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+/*
+ * Copyright 2017 Palantir Technologies, Inc. All rights reserved.
+ * Licensed under the BSD-3 License as modified (the “License”); you may obtain a copy
+ * of the license at https://github.com/palantir/blueprint/blob/master/LICENSE
+ * and https://github.com/palantir/blueprint/blob/master/PATENTS
+ */
+
+export * from "./browser";
```
Comment (giladgray) [inline packages/core/src/compatibility/index.ts]: this index isn't useful. why not move `browser.ts` to `utils/browser.ts` instead of adding a new directory?

File: packages/core/src/components/editable-text/editableText.tsx [hunk 3]
```diff
@@ -99,7 +100,8 @@ export interface IEditableTextState {
     value?: string;
 }
 
-const BUFFER_WIDTH = 30;
+const BUFFER_WIDTH_EDGE = 5;
+const BUFFER_WIDTH_IE = 30;
```
Comment (giladgray) [inline packages/core/src/components/editable-text/editableText.tsx]: really??? why do they need _different_ magic numbers? can't we just choose one value that works well enough for both?

File: packages/core/src/components/editable-text/editableText.tsx [hunk 4]
```diff
@@ -312,10 +314,12 @@ export class EditableText extends AbstractComponent<IEditableTextProps, IEditabl
             // Chrome's input caret height misaligns text so the line-height must be larger than font-size.
             // The computed scrollHeight must also account for a larger inherited line-height from the parent.
             scrollHeight = Math.max(scrollHeight, getFontSize(this.valueElement) + 1, getLineHeight(parentElement));
-            // IE11 needs a small buffer so text does not shift prior to resizing
+            // IE11 & Edge needs a small buffer so text does not shift prior to resizing
+            scrollWidth = Browser.isEdge() ? scrollWidth + BUFFER_WIDTH_EDGE : scrollWidth;
+            scrollWidth = Browser.isInternetExplorer() ? scrollWidth + BUFFER_WIDTH_IE : scrollWidth;
```
Comment (giladgray) [inline packages/core/src/components/editable-text/editableText.tsx]: double ternaries are really awkward. please expand to `if ... else if ... else` (since both lines have the same `else` case)

File: packages/core/src/components/editable-text/editableText.tsx (hunk 3 above)
Comment (leebyp) [inline packages/core/src/components/editable-text/editableText.tsx]: Yeah, they shift for different amounts. It'll "work" with both set to `30` as the buffer only needs to be a minimum, but looks better with the specific buffers.

File: packages/core/src/compatibility/index.ts (hunk 2 above)
Comment (leebyp) [inline packages/core/src/compatibility/index.ts]: What do you mean? There isn't a `utils` directory. I'm more following the structure we have for accessibility - I'd expect we'll get some os specific compatibility issues at some point too.

File: packages/core/src/compatibility/browser.ts [hunk 5]
```diff
@@ -0,0 +1,13 @@
+/*
+ * Copyright 2017 Palantir Technologies, Inc. All rights reserved.
+ * Licensed under the BSD-3 License as modified (the “License”); you may obtain a copy
+ * of the license at https://github.com/palantir/blueprint/blob/master/LICENSE
+ * and https://github.com/palantir/blueprint/blob/master/PATENTS
+ */
+
+const userAgent = navigator.userAgent;
+
+export const Browser = {
```
Comment (adidahiya) [inline packages/core/src/compatibility/browser.ts]: `export const foo = false` is not mutable, but the fields in an `export const` object _are_. I liked how @leebyp had it before.

Comment (leebyp) [inline packages/core/src/compatibility/browser.ts]: hm, did not even know that!
