### PR TITLE
[Table] Don't show regions that aren't in the table

### LINKED ISSUE #1077: Bad focus cell on loading table
When a table with a focus cell is loading, we have this empty sad focus cell 

image

### Bug report

- __Package version(s)__: 1.13.0
- __Browser and OS versions__: Mac chrome 
 Live in action: https://pl.ntr/eU

### PR DESCRIPTION
**Pull request by gscshoyru**
#### Changes proposed in this pull request:

Check whether or not a region is fully contained in the table before styling it; if it turns out it isn't, style it with `display: none`

### CODE REVIEW

File: packages/table/test/gridTests.ts [hunk 1]
```diff
@@ -158,6 +159,15 @@ describe("Grid", () => {
         });
     });
 
+    describe("style", () => {
+        it("returns display: none if region not inside grid", () => {
+            const grid = new Grid(test7s, test13s);
+            const region = Regions.cell(5, 5, 10, 10);
+            const regionStyle = grid.getRegionStyle(region);
+            expect(regionStyle.display).to.equal("none");
+        });
```
Comment (cmslewis) [inline packages/table/test/gridTests.ts]: Can we add a test—or at least an `expect`—for every relevant region cardinality (`CELLS`, `FULL_COLUMNS`, `FULL_ROWS`) to maximize confidence and test coverage?

File: packages/table/src/common/grid.ts [hunk 2]
```diff
@@ -308,6 +308,11 @@ export class Grid {
         const cardinality = Regions.getRegionCardinality(region);
         switch (cardinality) {
             case RegionCardinality.CELLS: {
+                // if the region is outside the bounds of the table, don't display it
+                if (this.isGhostIndex(region.rows[0], region.cols[0])
```
Comment (cmslewis) [inline packages/table/src/common/grid.ts]: nit: Since these array values are being accessed twice now, I'd consider pulling them out into their own named variables, e.g.:

```
const [rowStart, rowEnd] = region.rows;
const [colStart, colEnd] = region.cols;
```

**Comment by llorca** [comment]
Since regions outside of table bounds aren't acceptable, should we warn consumers in addition to hiding it?

**Comment by gscshoyru** [comment]
@llorca that's... complicated, since it'll still happen in situations where it's ok. We could possibly warn in the console -- but you'll get issues when loading tables and you have a focus cell, or if you're loading tables and you're doing selection in controlled mode because you saved it somewhere but the cells aren't in yet. But at the same time silently dropping it might make debugging hard. Do people have thoughts on sticking a console log here?

File: packages/table/src/common/grid.ts [hunk 3]
```diff
@@ -308,10 +308,18 @@ export class Grid {
...
-                const cellRect0 = this.getCellRect(region.rows[0], region.cols[0]);
-                const cellRect1 = this.getCellRect(region.rows[1], region.cols[1]);
-                const offsetLeft = region.cols[0] === 0 ? 0 : 1;
-                const offsetTop = region.rows[0] === 0 ? 0 : 1;
+                const [rowStart, rowEnd] = region.rows;
+                const [colStart, colEnd] = region.cols;
+
+                // if the region is outside the bounds of the table, don't display it
+                if (this.isGhostIndex(rowStart, colStart)
+                 || this.isGhostIndex(rowEnd, colEnd)) {
```
Comment (giladgray) [inline packages/table/src/common/grid.ts]: awkward indentation; always whole multiple of four spaces (half expect this to fail linter, but i guess it didn't).

```
if (A
    || B) {
}

Comment (giladgray) [inline packages/table/src/common/grid.ts]: + two more instances below

File: packages/table/src/common/grid.ts [hunk 4]
```diff
@@ -321,10 +329,17 @@ export class Grid {
             }
 
             case RegionCardinality.FULL_COLUMNS: {
-                const cellRect0 = this.getCellRect(0, region.cols[0]);
-                const cellRect1 = this.getCellRect(0, region.cols[1]);
+                const [colStart, colEnd] = region.cols;
+
+                // if the region is outside the bounds of the table, don't display it
+                if (this.isGhostIndex(0, colStart)
+                    || this.isGhostIndex(0, colEnd)) {
```
Comment (cmslewis) [inline packages/table/src/common/grid.ts]: Chatted with Gilad. Would probably just put these checks on one line to avoid the holy war over how to properly format this. 😛

**Comment by tgreenwatts** [comment]
:shipit: ??

**Comment by tgreenwatts** [comment]
Can I pleaseee merge now?! @gscshoyru @cmslewis

**Comment by gscshoyru** [comment]
Was waiting for someone else to look at it... but yeah it's probably ok. Go for it.
