### PR TITLE
[select] fix: ItemRendererProps type regression

### LINKED ISSUE #5943: ItemRendererProps has a new unexpected required "ref" property
#### Environment

- __Package version(s)__: @blueprintjs/select v4.9.0

#### Steps to reproduce

Define a custom item renderer which generates `ItemRendererProps` (either by explicitly referencing that type definition, or implicitly)

#### Actual behavior

Errors like this (redacted file name):

```
[error] TypeScript error packages/**/*.tsx:215:48 - error TS2345: Argument of type '{ index: number; handleClick: () => void; query: string; modifiers: { active: false; disabled: false; matchesPredicate: false; }; }' is not assignable to parameter of type 'ItemRendererProps'.
  Property 'ref' is missing in type '{ index: number; handleClick: () => void; query: string; modifiers: { active: false; disabled: false; matchesPredicate: false; }; }' but required in type 'ItemRendererProps'.
```

#### Expected behavior

New properties should not be required when bumping a minor version of the select package. This blocks Blueprint upgrades.

#### Possible solution

Make `ref` optional in `ItemRendererProps`.

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

- Make `ref` property optional in `ItemRendererProps`
- Improve type of `ref` and `handleClick` properties in `ItemRendererProps` by using generic type params
- Improve type of `onClick` and `onFocus` properties in `ActionProps` by adding generic type params
- Add tests to select package for #5943 regression

#### Reviewers should focus on:

Tests are accurate & sufficient

#### Screenshot

N/A

### CODE REVIEW

File: packages/select/src/common/itemRenderer.ts [hunk 1]
```diff
@@ -36,18 +36,28 @@ export type IItemRendererProps = ItemRendererProps;
...
+ * Make sure to forward the provided `ref` to the rendered element (usually via the `elementRef` prop on `MenuItem`/`MenuItem2`)
+ * to ensure that scrolling to active items works correctly.
+ *
+ * @template T type of the DOM element to attach a ref to, usually the component's root container (defaults to MenuItem's HTMLLIElement)
+ * @template U type of the DOM element to attach a click handler to, usually the component's root container (defaults to MenuItem's HTMLAnchorElement)
  */
-export interface ItemRendererProps {
-    /** A ref that receives the native HTML element rendered by this item. */
-    ref: Ref<any>;
+export interface ItemRendererProps<T extends HTMLElement = HTMLLIElement, U extends HTMLElement = HTMLAnchorElement> {
```
Comment (adidahiya) [inline packages/select/src/common/itemRenderer.ts:46]: we need two type params because MenuItems are weird and attach their ref to a different DOM element than the click handler. we should probably reconcile that at some point 🤷🏽

**Comment by adidahiya** [comment]
<h3>[select] fix: ItemRendererProps type regression</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/d90f0492-88b6-4f3e-9c66-f8f4426ab454/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/d90f0492-88b6-4f3e-9c66-f8f4426ab454/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/d90f0492-88b6-4f3e-9c66-f8f4426ab454/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/d90f0492-88b6-4f3e-9c66-f8f4426ab454/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>fix MenuItem references in tests</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/07596087-852f-40ce-8077-b49b6b709262/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/07596087-852f-40ce-8077-b49b6b709262/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/07596087-852f-40ce-8077-b49b6b709262/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/07596087-852f-40ce-8077-b49b6b709262/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

File: packages/select/src/common/itemRenderer.ts (hunk 1 above)
Comment (adidahiya) [reply packages/select/src/common/itemRenderer.ts:46]: actually, this turned out to be a bad approach. see https://github.com/palantir/blueprint/pull/5946
