### PR TITLE
Don't throw Errors for non-Column children of Table

### LINKED ISSUE #723: table does not work with react-hot-loader
### Bug report

- __Package version(s)__:  @blueprintjs/table@1.6.0
- __Browser and OS versions__:	54.0.2840.100

#### Steps to reproduce
running app with HMR  react-hot-loader@3.0.0-beta.6

#### Actual behavior

Crash because of check in table.js:265
``  var isColumn = cType.prototype === column_1.Column.prototype || column_1.Column.prototype.isPrototypeOf(cType);``
``                if (!isColumn) {``
``                   throw new Error(ERROR_MESSAGE); // Children of Table must be Columns``

the check fails, because react-hot-loader will proxy all React Components

Please could you remove this check (or make it optional) to support react-hot-loader? I seems to me anyway that this line is the only place where this kind of prototype check occurs in blueprintjs

Thanks

### PR DESCRIPTION
**Pull request by gscshoyru**
#### Changes proposed in this pull request:

Changed error to warning for validate props

### CODE REVIEW

File: packages/table/src/table.tsx [hunk 1]
```diff
@@ -440,11 +440,11 @@ export class Table extends AbstractComponent<ITableProps, ITableState> {
             const cType = child.type;
 
             if (typeof cType === "string") {
-                throw new Error(ERROR_MESSAGE);
+                console.warn(ERROR_MESSAGE);
             } else {
                 const isColumn = cType.prototype === Column.prototype || Column.prototype.isPrototypeOf(cType);
                 if (!isColumn) {
-                    throw new Error(ERROR_MESSAGE);
+                    console.warn(ERROR_MESSAGE);
```
Comment (giladgray) [inline packages/table/src/table.tsx]: why not `console.error`? these are errors after all (i think?).

Comment (adidahiya) [inline packages/table/src/table.tsx]: it's more of a warning; usually the code will still work. we might want to change the variable to `WARNING_MESSAGE`

Comment (giladgray) [inline packages/table/src/table.tsx]: that would make sense. you should `warn` a `WARNING`.
