### PR TITLE
countDecimalPlaces for number type

### LINKED ISSUE #3336: NumericInput fails when stepSize has more than 6 decimal places
#### Environment

- __Package version(s)__: @blueprintjs/core:3.12.0
- __Browser and OS versions__: Chrome 71 on Mac OS X 10.14.2(Mojave)

#### Steps to reproduce

Use NumericInput with a number in exponential notation:
`<NumericInput stepSize={1e-10} minorStepSize={null}/>`

usually when computing step size with exponent greater than 6:
`<NumericInput stepSize={Math.pow(10, -10)} minorStepSize={null}/>`

> js uses decimal notation when exponent is less or equal 6 and exponential notation for exponent greater than 6:
> 
> ```
> console.log(Math.pow(10, -2));
> // expected output: 0.01
> 
> console.log(Math.pow(10, -7));
> // expected output: 1e-7
> ```
> console.log(Number(0.0000000000001))
> // expected output: 1e-13
> console.log(Number("0.0000000000001"))
> // expected output: 1e-13

You can see it at `CoreExample.tsx` in the following code sandbox:

[Edit Blueprint Sandbox](https://codesandbox.io/s/wjw394v57)

#### Actual behavior

From code sanbox:
```
TypeError
Cannot read property 'length' of undefined
    at Object.countDecimalPlaces (https://nko3k41y60.codesandbox.io/node_modules/
blueprintjs/core/lib/cjs/common/utils.js:148:40
    at NumericInput.getStepMaxPrecision (https://nko3k41y60.codesandbox.io/node_modules/
blueprintjs/core/lib/cjs/components/forms/numericInput.js:378:35
    at new NumericInput (https://nko3k41y60.codesandbox.io/node_modules/
blueprintjs/core/lib/cjs/components/forms/numericInput.js:182:37
constructClassInstance
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:6789:20
updateClassComponent
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:8324:9
beginWork
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:8966:16
performUnitOfWork
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:11798:16
workLoop
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:11827:26
renderRoot
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:11858:9
performWorkOnRoot
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12422:24
performWork
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12343:9
performSyncWork
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12320:5
requestWork
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12220:7
scheduleWorkImpl
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12095:13
scheduleWork
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12055:12
scheduleRootUpdate
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12683:5
updateContainerAtExpirationTime
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12711:12
Object.updateContainer
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12730:14
ReactRoot.render
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:16030:15
eval
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:16449:14
Object.unbatchedUpdates
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12530:12
legacyRenderSubtreeIntoContainer
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:16445:17
Object.render
https://nko3k41y60.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:16513:12
evaluate
file:///src/index.tsx:23
  20 |     </div>
  21 | );
  22 | 
> 23 | render(<App />, document.getElementById("root"));
  24 | 
View compiled
▶ 10 stack frames were collapsed.
```

#### Expected behavior

Don't fail

#### Possible solution

https://github.com/palantir/blueprint/blob/2ad42204475e6a8a0cd05efad5e412f5756af736/packages/core/src/common/utils.ts#L187

```
/** Returns the number of decimal places in the given number. */
export function countDecimalPlaces(num: number) {
    if (!isFinite(num)) return 0;
    let e = 1, p = 0;
    while (Math.round(num * e) / e !== num) { e *= 10; p++; }
    return p;
}
```

### PR DESCRIPTION
**Pull request by teanocrata**
#### Checklist

- [x] Includes tests
- [x] Update documentation (same as current, the PR does not changes any behaviour nor interface)

#### Changes proposed in this pull request:

countDecimalPlaces returns decimal places for all number notations and do not covert the number to string (faster):

```
console.log(Utils.countDecimalPlaces(1e-10));
// expected output 10
console.log(Utils.countDecimalPlaces(NaN));
// expected output 0
```

#### Reviewers should focus on:

countDecimalPlaces from packages/core/src/common/utils.ts

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @teanocrata! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: packages/core/src/common/utils.ts [hunk 1]
```diff
@@ -185,10 +185,10 @@ export function clamp(val: number, min: number, max: number) {
 
 /** Returns the number of decimal places in the given number. */
 export function countDecimalPlaces(num: number) {
-    if (typeof num !== "number" || Math.floor(num) === num) {
-        return 0;
-    }
-    return num.toString().split(".")[1].length;
+    if (!isFinite(num)) return 0;
+    let e = 1, p = 0;
+    while (Math.round(num * e) / e !== num) { e *= 10; p++; }
```
Comment (giladgray) [inline packages/core/src/common/utils.ts]: this is very neat but I have some performance concerns. need to inspect how often this function is executed.

Comment (giladgray) [reply packages/core/src/common/utils.ts]: ah it's only used to update state so should be alright 👍
