### PR TITLE
fix(Tag): Add keyboard accessibility

### LINKED ISSUE #4782: Tag onClick does not fire with spacebar or enter press when focused
#### Code Sandbox
https://codesandbox.io/s/palantir-blueprint-forked-s0reo

#### Steps to reproduce
1. click tag, observe onClick handler works
2. use tab to navigate to tag, onClick does not fire with spacebar or enter

`Button` included to show expected behavior

#### Actual behavior
`onClick` of `Tag` does not fire with spacebar or enter press when focused

#### Expected behavior
spacebar/enter should trigger `onClick` of `Tag`

#### Possible solution
if `Tag` has `onClick` defined, render as a button but with the `Tag` styles

### PR DESCRIPTION
**Pull request by jscheiny**
#### Changes proposed in this pull request:

In this PR we pull out the common accessibility functionality from the button components to be shared with the tag component. This enables the tag component to be keyboard accessible when `interactive={true}`

### CODE REVIEW

File: packages/core/src/accessibility/useInteractiveAttributes.ts [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+
+interface InteractiveComponentProps extends InteractiveHTMLAttributes<HTMLElement> {
+    active?: boolean | undefined;
+}
+
+interface InteractiveAttributes<E extends HTMLElement> extends InteractiveHTMLAttributes<E> {
+    ref: React.Ref<E>;
+}
+
+export function useInteractiveAttributes<E extends HTMLElement>(
```
Comment (ggdouglas) [inline packages/core/src/accessibility/useInteractiveAttributes.ts:22]: **nit:** can we add tests for this hook with `@testing-library/react-hooks` in a follow-up PR?

File: packages/core/src/components/button/buttons.tsx [hunk 2]
```diff
@@ -73,69 +72,17 @@ AnchorButton.displayName = `${DISPLAYNAME_PREFIX}.AnchorButton`;
  */
 function useSharedButtonAttributes<E extends HTMLAnchorElement | HTMLButtonElement>(
     props: E extends HTMLAnchorElement ? AnchorButtonProps : ButtonProps,
-    ref: React.Ref<E>,
+    passedRef: React.Ref<E>,
```
Comment (ggdouglas) [inline packages/core/src/components/button/buttons.tsx]: Why are we renaming this?

File: packages/core/src/accessibility/useInteractiveAttributes.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+    const resolvedActive = interactive && (active || isActive);
+
+    return [
+        resolvedActive,
+        {
+            onBlur: handleBlur,
+            onClick: interactive ? onClick : undefined,
+            onFocus: interactive ? onFocus : undefined,
+            onKeyDown: handleKeyDown,
+            onKeyUp: handleKeyUp,
```
Comment (ggdouglas) [inline packages/core/src/accessibility/useInteractiveAttributes.ts:83]: Would this function the same if we were to conditionally render the inclusion of all the handlers based on the `interactive` flag? e.g.

```ts
const handlers = {
    onBlur: handleBlur,
    onClick,
    onFocus,
    onKeyDown: handleKeyDown,
    onKeyUp: handleKeyUp,
};

return [
    resolvedActive,
    {
        ...(interactive ? handlers : {}),
        ref: mergeRefs(elementRef, ref),
        tabIndex: interactive ? tabIndex : -1,
    },
];
```

File: packages/core/src/accessibility/useInteractiveAttributes.ts [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+    props: InteractiveComponentProps,
+    ref: React.Ref<E>,
+    defaultTabIndex?: number,
+): [active: boolean, interactiveProps: InteractiveAttributes<E>] {
+    const { active, onClick, onFocus, onKeyDown, onKeyUp, onBlur, tabIndex = defaultTabIndex } = props;
+    // the current key being pressed
+    const [currentKeyPressed, setCurrentKeyPressed] = React.useState<string | undefined>();
+    // whether the button is in "active" state
+    const [isActive, setIsActive] = React.useState(false);
+    // our local ref for the interactive element, merged with the consumer's own ref (if supplied) in this hook's return value
```
Comment (ggdouglas) [inline packages/core/src/accessibility/useInteractiveAttributes.ts]: **nit:** since `ref` is not an optional argument within this hook, can we change the wording of this comment?
```suggestion
    // our local ref for the interactive element, merged with the consumer's own ref in this hook's return value
```

File: packages/core/src/accessibility/useInteractiveAttributes.ts (hunk 1 above)
Comment (jscheiny) [reply packages/core/src/accessibility/useInteractiveAttributes.ts:22]: Yeah, sgtm

File: packages/core/src/components/button/buttons.tsx (hunk 2 above)
Comment (jscheiny) [reply packages/core/src/components/button/buttons.tsx]: Oops, left over from a previous iteration, no longer necessary.

File: packages/core/src/accessibility/useInteractiveAttributes.ts (hunk 3 above)
Comment (jscheiny) [reply packages/core/src/accessibility/useInteractiveAttributes.ts:83]: Very likely I think, but I wanted to quite safe to avoid any unintentional side effects so I wanted to match the button behavior as close as possible.

**Review by ggdouglas — APPROVED** [review]
