### PR TITLE
Fix Hotkeys for custom keyboard layouts

### LINKED ISSUE #6693: useHotkeys inaccurately infers characters, breaking alternate layouts, hurting accessibility and localisation
#### Environment

- __Package version(s)__: >=5.0.2
- __Operating System__: All
- __Browser name and version__: All

#### Code Sandbox

Link to a minimal repro: https://blueprintjs.com/docs/#core/hooks/use-hotkeys (the keyboard)

#### Steps to reproduce

1. Set your keyboard layout such that it doesn't match your physical keyboard layout
2. Try to use the piano with a key where both the physical key and the mapped character appear on the piano
3. The key based on the physical key value lights up, not based on the mapped character

#### Actual behavior

useHotkeys makes use of [code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) to infer which character a user has pressed, Mozilla's documentation states this is not correct usage: "Be aware, however, that you can't use the value reported by KeyboardEvent.code to determine the character generated by the keystroke".  

Currently users with keyboard layouts that don't match their physical keyboard are unable to use hotkeys effectively, as hotkeys will often end up colliding with browser shortcuts.  For example, if an application has a cmd+b hotkey a user of Left-handed DVORAK wouldn't be able to use cmd+w to quit the tab, and would instead end up triggered the cmd+b hotkey.

This has localisation impact (French user typing in AZERTY on a US keyboard) and accessibility impact (one handed user typing using a one handed DVORAK layout).

#### Expected behavior

[key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) should be used when the character generated instead of the specific key position is desired.  This way the users keyboard layout is respected, this is the approach shared by most software, websites, and operating systems, the main exceptions are some video games (but most support in application key remapping of some form)

#### Possible solution

The issues with useHotkeys raised in https://github.com/palantir/blueprint/issues/6257 would return if a simple switch back to key was done.  However, from my research, key combinations using option/alt are reasonably rare in web applications.  Additionally, alt key combinations risk conflicting with users wanting to use alt codes to type special characters, so maybe we should consider not supporting alt based combinations.

Some nuance is likely needed with handling modifier keys, thoughts here:
 - Use [getModifierState](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState) to handle a few common modifier keys
 - Find an appropriately licensed hotkey library to incorporate that deals with this issue already.
 - The experimental [getLayoutMap](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/getLayoutMap) could be used
 -  Hard part will likely be ensuring it isn't a breaking change for those with keyboard layouts that match their keyboards

### PR DESCRIPTION
**Pull request by ollie299792458**
#### Checklist

-   [x] Includes tests
-   [x] Update documentation

#### Changes proposed in this pull request:

Use key for all non-alt keyboard shortcuts, to respect non-default keyboard layouts.  Due to complexities around alt shortcuts, fall back to code for those.  For default keyboard layout users, no behaviour changes.  For shift, use code for numeric keys, which drops support for using '!` in place of  'shift+1', and clarify in the docs only 'shift + 1' is supported (as '!' isn't actually supported on develop).

For default keyboard layouts, changes are fully backward compatible.

#### Reviewers should focus on:

The piano widget in hotkeys in the docs. As well as the new example of modified keys below it.

#### Screenshot

No user facing changes.

### CODE REVIEW

File: packages/docs-app/src/examples/core-examples/hotkeysTargetExample.tsx [hunk 1]
```diff
@@ -60,6 +60,30 @@ export class HotkeysTargetExample extends PureComponent<ExampleProps, HotkeysTar
             label: "Focus the piano",
             onKeyDown: this.focusPiano,
         },
+        {
+            combo: "ctrl + B",
+            group: "Modifier Tests",
+            label: "Test Ctrl+B",
+            onKeyDown: () => console.log("Ctrl+B pressed"),
```
Comment (mm-wang) [inline packages/docs-app/src/examples/core-examples/hotkeysTargetExample.tsx]: **note**: I don't think this is sufficient for the documentation - there should be something in the UI denoting the keys pressed.

File: packages/core/test/hotkeys/hotkeysParserTests.ts [hunk 2]
```diff
@@ -137,6 +137,13 @@ describe("HotkeysParser", () => {
             tests.push(makeComboTest("alt + a", { altKey: true, code: "KeyA", key: "a" }));
             verifyCombos(tests);
         });
+
+        it("handles alt modifier with special characters (macOS)", () => {
```
Comment (mm-wang) [inline packages/core/test/hotkeys/hotkeysParserTests.ts:141]: **question**: Do you have additional tests in mind for having an alternate layout and checking keys?

**Review by mm-wang — COMMENTED** [review]
I think we may need a bit more documentation on the expected behavior here and what the exact change is, not just in code.

File: packages/docs-app/src/examples/core-examples/hotkeysTargetExample.tsx (hunk 1 above)
Comment (ollie299792458) [reply packages/docs-app/src/examples/core-examples/hotkeysTargetExample.tsx]: Removed it and add more docs + an example

File: packages/core/test/hotkeys/hotkeysParserTests.ts (hunk 2 above)
Comment (ollie299792458) [reply packages/core/test/hotkeys/hotkeysParserTests.ts:141]: Added some extra tests

File: packages/core/src/components/hotkeys/hotkeyParser.ts [hunk 3]
```diff
@@ -191,18 +191,37 @@ function maybeGetKeyFromEventCode(e: KeyboardEvent) {
...
+            key = codeKey;
+        } else if (e.altKey && isAltModifiedCharacter(e.key) && codeKey !== undefined) {
+            // Alt on macOS produces special characters (e.g., Alt+c → ç), use code for those cases
+            key = codeKey;
+        } else if (e.code?.startsWith(DIGIT_CODE_PREFIX) && codeKey !== undefined) {
+            // For digit keys, always use code to get the base digit (Shift+1 → "1", not "!")
+            key = codeKey;
+        } else {
+            // For letters and other keys, prefer event.key to respect keyboard layout
+            key = e.key?.toLowerCase() ?? codeKey;
```
Comment (mm-wang) [inline packages/core/src/components/hotkeys/hotkeyParser.ts:223]: **question**: What other e.key values would exist? If it is undefined, then wouldn't `codeKey` also be undefined?

File: packages/core/src/components/hotkeys/hotkeyParser.ts [hunk 4]
```diff
@@ -225,6 +244,19 @@ export const getKeyCombo = (e: KeyboardEvent): KeyCombo => {
...
+ * Checks if a character is likely the result of Alt modification on macOS.
+ * Alt produces characters like: ç, ñ, ø, ∫, etc. which are outside normal ASCII printable range.
+ */
+function isAltModifiedCharacter(key: string): boolean {
+    if (key == null || key.length !== 1) {
+        return false;
+    }
+    const code = key.charCodeAt(0);
+    // Check if it's outside the normal ASCII printable range (32-127), excluding space and delete (32 & 127)
+    return code > 126 || code < 33;
```
Comment (mm-wang) [inline packages/core/src/components/hotkeys/hotkeyParser.ts]: **question**: Did you mean `code > 127 || code < 32`. Or are you assuming space and delete would be used with alt? I'd suggest changing it to that if so. If this has been left out because the key has been addressed in `getKeyCombo` then I'd lean toward using `code > 127 || code < 32` in case this method is used elsewhere another time.

File: packages/core/src/components/hotkeys/hotkeyParser.ts [hunk 5]
```diff
@@ -191,18 +191,37 @@ function maybeGetKeyFromEventCode(e: KeyboardEvent) {
...
     let key: string | undefined;
     if (MODIFIER_KEYS.has(e.key)) {
         // Leave local variable `key` undefined
     } else {
-        key = maybeGetKeyFromEventCode(e) ?? e.key?.toLowerCase();
+        const codeKey = maybeGetKeyFromEventCode(e);
+
+        // Special cases where we must use code instead of key
+        if (e.code === "Space" || e.code === "Delete") {
+            // Space: event.key is " " but we need "space" to match parseKeyCombo
```
Comment (mm-wang) [inline packages/core/src/components/hotkeys/hotkeyParser.ts:212]: **suggestion**: I'd recommend that this be added into the docs as well, so that folks are aware of the change.

**Review by mm-wang — DISMISSED** [review]
LGTM, with a few clarifications on the alt key modifier and use of "space" vs " ". Thanks for going through this!

File: packages/core/src/components/hotkeys/hotkeyParser.ts (hunk 3 above)
Comment (ollie299792458) [reply packages/core/src/components/hotkeys/hotkeyParser.ts:223]: maybeGetKeyFromEventCode is always based on e.code.  But if it is a keyboard ASCII printable character, we want to use e.key as preference.

File: packages/core/src/components/hotkeys/hotkeyParser.ts (hunk 4 above)
Comment (ollie299792458) [reply packages/core/src/components/hotkeys/hotkeyParser.ts]: Yep, makes sense, didn't update when I changed approach, will update and smoketest

File: packages/core/src/components/hotkeys/hotkeyParser.ts (hunk 5 above)
Comment (ollie299792458) [reply packages/core/src/components/hotkeys/hotkeyParser.ts:212]: This is handled in maybeGetKeyFromEventCode, have added delete there.  The docs only reference the lower case option, so I think the docs are already up to date.

File: packages/core/src/components/hotkeys/hotkeyParser.ts (hunk 3 above)
Comment (mm-wang) [reply packages/core/src/components/hotkeys/hotkeyParser.ts:223]: I guess my question was whether `e.key?` is ever not defined, but it's not harmful to fall back to`e.code`, just wondering if it was redundant.

**Review by mm-wang — APPROVED** [review]
LGTM, thanks again!
