### PR TITLE
[DRP] Assign right and left together, keep them 1 month apart

### LINKED ISSUE #829: Shortcut not displayed if current month isn't already view
### Bug report

- __Package version(s)__: ^1.6.0
- __Browser and OS versions__: Any

#### Steps to reproduce

1. Go here: http://blueprintjs.com/docs/#components.datetime.daterangepicker
1. Click "Past 3 months", then "Past week"
1. See that no date range is visible in range selector.

#### Actual behavior

Upon selecting "Past week" shortcut, nothing is highlighted. But the value is accurate.

#### Expected behavior

Should jump to current month and show selected range.

### PR DESCRIPTION
**Pull request by omegdadi**
#### Changes proposed in this pull request:

1. During getStateChange, when setting a date range that spans months, left view and right view are kept only 1 month apart. Previous to this fix, the right view would get set to the end month of the range even though the start month and the following month are what gets displayed in the component. This then causes a no-op the following round trip through when selecting a single date range that lies within the previous range's end month.

#### Reviewers should focus on:

Behavior with other settings like `contiguousCalendarMonths`, but that is not taken into account throughout the existing code.

#### Screenshots

Selected "Past 3 months"
screen shot 2017-03-12 at 6 20 26 pm

Selected "Past week"
screen shot 2017-03-12 at 6 20 34 pm

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @omegdadi! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by omegdadi** [comment]
Got tests running locally now, please ignore until next update.

**Comment by omegdadi** [comment]
@giladgray This is now up-to-date with a test for the behavior. Thanks for reviewing.

File: packages/datetime/src/dateRangePicker.tsx [hunk 1]
```diff
@@ -691,9 +691,10 @@ function getStateChange(value: DateRange,
             } else {
                 if (!leftView.isSame(nextValueStartMonthAndYear)) {
                     leftView = nextValueStartMonthAndYear;
-                }
-                if (!rightView.isSame(nextValueEndMonthAndYear)) {
+                    rightView = nextValueStartMonthAndYear.getNextMonth();
+                } else if (!rightView.isSame(nextValueEndMonthAndYear)) {
                     rightView = nextValueEndMonthAndYear;
+                    leftView = rightView.getPreviousMonth();
```
Comment (leebyp) [inline packages/datetime/src/dateRangePicker.tsx]: I'd use the same pattern in line 694 and 697 in setting the "other" so it's obvious what's going on

**Comment by leebyp** [comment]
@omegdadi There's something funky going on with the month views when you click on same shortcut twice (the data is correct though). This is likely related to a `contiguousCalendarMonths` which you mentioned in the PR description, so might be a good simple start on that (and in the tests).

File: packages/datetime/src/dateRangePicker.tsx (hunk 1 above)
Comment (giladgray) [inline packages/datetime/src/dateRangePicker.tsx]: to be clear: `leftView = nextValueEndMonthAndYear.getPreviousMonth();`

**Comment by omegdadi** [comment]
@leebyp what do you think if the entire `getStateChange` handler shortcuts if the day/month/year for the dates haven't changed.

**Comment by omegdadi** [comment]
@leebyp Actually, looking closer, my changes wouldn't get reached in the case where the next value has the same start/end date as the current value. [Line 678](https://github.com/omegdadi/blueprint/blob/43063ff997463dac32718f5927cdb1101de81a30/packages/datetime/src/dateRangePicker.tsx#L678) looks like it would handle the same month use case. Can you provide an example of the funky behavior?

**Comment by leebyp** [comment]
@omegdadi i just ran your changes locally and got this:

untitled

**Comment by leebyp** [comment]
The checks for the same start / end date might be more confusing than it's worth because of our checks for `!= null`, but feel free to see how it comes out!

**Comment by omegdadi** [comment]
Got it working with `contiguousCalendarMonths = false`.

File: packages/datetime/src/dateRangePicker.tsx [hunk 2]
```diff
@@ -618,7 +618,8 @@ export class DateRangePicker
 
 function getStateChange(value: DateRange,
                         nextValue: DateRange,
-                        state: IDateRangePickerState): IDateRangePickerState {
+                        state: IDateRangePickerState,
+                        props: IDateRangePickerProps): IDateRangePickerState {
```
Comment (leebyp) [inline packages/datetime/src/dateRangePicker.tsx]: sweet! one final small nit: can you just pass in `contiguousCalendarMonths` directly rather than the whole prop?

**Comment by omegdadi** [comment]
Sure thing, it's updated.

**Comment by giladgray** [comment]
@omegdadi build failed linting. please fix errors. run `gulp tslint` locally (or, better, configure TSLint plugin for your editor).

**Comment by omegdadi** [comment]
Ugh...sorry about that. Last one hopefully.

**Comment by giladgray** [comment]
@omegdadi close but not quite. still have one line too long. did you run `gulp tslint` locally?

**Comment by omegdadi** [comment]
I did, but the output dumped out in terminal and pushed the error out of scroll history and I missed it.

**Comment by omegdadi** [comment]
Thanks for the feedback

**Comment by omegdadi** [comment]
@giladgray looks like it's passing this time

**Comment by leebyp** [comment]
@omegdadi and in it goes!!!

**Comment by omegdadi** [comment]
@leebyp hooray!
