### PR TITLE
[Core] Button should render text if text={0}

### LINKED ISSUE #2703: Passing 0 as text to <Button /> does not render any text
#### Environment

- __Package version(s)__: 3.0.1
- __Browser and OS versions__: Latest MacOS, latest Chrome

#### Steps to reproduce

1. `<Button text={0} />`

#### Actual behavior

Empty button rendered

#### Expected behavior

Button with 0 as text should be rendered

#### Possible solution

I suppose you're checking if the text prop is truthy, but 0 won't be truthy.

### PR DESCRIPTION
**Pull request by badams**
#### Changes proposed in this pull request:

Instead of checking if the text prop is truthy, check if it is defined and not an empty string.

#### Reviewers should focus on:

I've added an extra check `(text != null && text !== "")` to prevent a regression of the issue addressed in 540b88b.

This regression was not picked up by the unit test [here](https://github.com/palantir/blueprint/blob/develop/packages/core/test/buttons/buttonTests.tsx#L47 ) because the test in question is only checking if `children=""` rather than testing the `text` prop.

I think another assertion should be added:
```
assert.equal(button({text:""}, true).find("span").length, 0);
```

screen shot 2018-07-26 at 10 29 14 am

```
<Button icon="edit" />
<Button text="" icon="edit" />
```

### CODE REVIEW

File: packages/core/src/components/button/abstractButton.tsx [hunk 1]
```diff
@@ -149,7 +149,7 @@ export abstract class AbstractButton<H extends React.HTMLAttributes<any>> extend
         return [
             loading && <Spinner key="loading" className={Classes.BUTTON_SPINNER} size={Icon.SIZE_LARGE} />,
             <Icon key="leftIcon" icon={icon} />,
-            (text || children) && (
+            ((text != null && text !== "") || children) && (
```
Comment (giladgray) [inline packages/core/src/components/button/abstractButton.tsx]: can you also make it `children != null` for the same reason?
