### PR TITLE
fix(icons): generate static icons from resource SVGs (no font transforms)

### LINKED ISSUE #6329: Icon edges cut (by transforms?)
#### Environment

- __Package version(s)__: 
"@blueprintjs/core": "^5.2.0",
"@blueprintjs/datetime": "^5.0.8",
"@blueprintjs/icons": "^5.1.5",
- __Operating System__: MacOS Ventura
- __Browser name and version__: Chrome 116.0.5845.96 & Chromium M96

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4)): 

#### Steps to reproduce

1. Use the Error icon from @blueprint/icons. Probably any icon with a round form has the same problem. Code: `<Error />`

#### Actual behavior

The icon is rendered, but the left and bottom edges are cut off so it doesn't look completely round.

Screenshot 2023-08-22 at 12 54 53

#### Expected behavior

The icon is rendered and looks completely round.

Screenshot 2023-08-22 at 12 55 11

#### Possible solution

In Blueprint 4, the icon used to look like this when inspecting it:

`<svg data-icon="error" width="20" height="20" viewBox="0 0 20 20" role="img"><path d="M10 0C4.48 0 0 4.48 0 10s4.48 10 10 10 10-4.48 10-10S15.52 0 10 0zm1 16H9v-2h2v2zm0-3H9V4h2v9z" fill-rule="evenodd"></path></svg>`

In Blueprint 5, the icon looks like this:

`<svg data-icon="error" height="20" role="img" viewBox="0 0 20 20" width="20"><path d="M200 400C89.6 400 0 310.4 0 200C0 89.6 89.6 0 200 0S400 89.6 400 200C400 310.4 310.4 400 200 400zM220 80H180V120H220V80zM220 140H180V320H220V140z" fill-rule="evenodd" transform-origin="center" transform="scale(0.05, -0.05) translate(-200, -200)"></path></svg>`

I tried changing the scale from `scale(0.05, -0.05)` to `scale(0.04, -0.04)`, and that left enough space for the icon to become fully circular again.

I'm reporting the bug because of the above, and also because I was unable to find any way to fix it from my code. I tried changing paddings, the size of the icon etc. But I think it's a blueprint problem. We're seeing this in many icons across our application after updating to Blueprint 5.

I don't see the problem or the transforms in your icon documentation. Could those be using Blueprint 4, or using another way of showing the icons? We also moved to using the icon elements like `<Error />` from @blueprint/icons instead of using `<Icon icon="error" />` from @blueprint/core when we moved to Blueprint 5, because our tests started failing with the dynamic loading of icons. So that difference in usage is another possible factor.

### LINKED ISSUE #7558: Icons: Static vs Dynamic Icons Render Differently
## Description

Static icon components (e.g., `<Error />`, `<WarningSign />`) appear visually different from their dynamic counterparts (e.g., `<Icon icon="error" />`). Most notably, static icons get clipped/cut off around the edges, while dynamic icons render as expected.

Image

This is especially noticeable in components like Callout which use the static versions of icons as the default for intents.

Image

#### Static Icon Components (Current Implementation)

Static icon components use a complex coordinate system with scaling transforms:

```javascript
// Example from packages/icons/lib/esm/generated/components/error.js
const translation = `${(-1 * pixelGridSize) / 0.05 / 2}`;
return (
    <SVGIconContainer {...props}>
        <path
            d="M159.8 320.2C71.4 320.2 -0.2 248.6 -0.2 160.2S71.4 0.2 159.8 0.2..."
            transform={`scale(0.05, -0.05) translate(${translation}, ${translation})`}
        />
    </SVGIconContainer>
);
```

#### Dynamic Icon Components (Working as Expected)

Dynamic icons use path data that closely matches the original SVG coordinates:

```javascript
// Example from packages/icons/lib/esm/generated/16px/paths/error.js
export default ["M7.99-.01c-4.42 0-8 3.58-8 8s3.58 8 8 8 8-3.58 8-8-3.58-8-8-8zm1 13h-2v-2h2v2zm0-3h-2v-7h2v7z"];

// Compare to original SVG (resources/icons/16px/error.svg):
// d="M7.99-0.01c-4.42,0-8,3.58-8,8s3.58,8,8,8s8-3.58,8-8S12.41-0.01,7.99-0.01z
//    M8.99,12.99h-2v-2h2V12.99z M8.99,9.99h-2v-7h2V9.99z"

// Both rendered through SVGIconContainer in standard viewBox="0 0 16 16" without transforms
```

#### Code Sandbox

Image

https://codesandbox.io/p/sandbox/lqlph3

Image

https://codesandbox.io/p/sandbox/c5yz8w

### Reproduction

Compare these two approaches for rendering the same icon:

```tsx
// Static component (complex transforms)
import { Error } from "@blueprintjs/icons";
<Error size={16} />;

// Dynamic component (simple coordinates)
import { Icon } from "@blueprintjs/core";
<Icon icon="error" size={16} />;
```

The visual output should be identical, but the underlying rendering approaches are fundamentally different.

#### Environment

-   **Package version(s)**: 6.2.1
-   **Operating System**: macOS 15.6.1
-   **Browser name and version**: Chrome 139.0.7258.155

### PR DESCRIPTION
**Pull request by ggdouglas**
Fixes https://github.com/palantir/blueprint/issues/6329
Fixes https://github.com/palantir/blueprint/issues/7558

## Summary
- Generate static `@blueprintjs/icons` components from the same optimized paths as `generate-icon-paths.mjs` / `<Icon />`, instead of font glyph `d` + `scale/translate` transforms.
- Add `extractPathsFromResourceSvg.mjs` shared by path modules and icon component generation; fix path extraction to use `d="..."` capture (no stray quote in `d`).
- Write path kit exports with `JSON.stringify` per path for safe escaping.

Fixes visual mismatch / clipping issues discussed in [#7558](https://github.com/palantir/blueprint/issues/7558) / [#6329](https://github.com/palantir/blueprint/issues/6329); aligns with resource cleanup in [#7826](https://github.com/palantir/blueprint/pull/7826).

### Before

> Left and bottom edges of static icons are clipped

before

### After

> Clipping is fixed

after

### CODE REVIEW

File: packages/icons/scripts/extractPathsFromResourceSvg.mjs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+    const filepath = join(iconResourcesDir, `${iconSize}px`, `${iconName}.svg`);
+    const svg = readFileSync(filepath, "utf-8");
+    const optimizedSvg = await svgOptimizer.optimize(svg, { path: filepath });
+    /** @type string[] */
+    const paths = [];
+    // Match `d` attributes on `<path` elements specifically
+    const re = /<path[^>]*\sd="([^"]+)"/g;
+    let m;
+    while ((m = re.exec(optimizedSvg.data)) !== null) {
+        paths.push(m[1].replace(/[\n\t]/g, ""));
```
[the remark this answers is not in the document]
Comment (ggdouglas) [reply packages/icons/scripts/extractPathsFromResourceSvg.mjs]: Fair point. Updated regex to support both single and double quotes: 76df9aefaf68d31408a5c277bb25ba2470c21121

File: packages/icons/scripts/generate-icon-components.mjs [hunk 2]
```diff
@@ -51,50 +41,21 @@ const componentsIndexTemplate = Handlebars.compile(
...
         iconComponentTemplate({
             iconName,
-            icon16pxPath,
-            icon20pxPath,
-            pathScaleFactor: 1 / ICON_RASTER_SCALING_FACTOR,
+            paths16Json: JSON.stringify(paths16),
+            paths20Json: JSON.stringify(paths20),
         }),
     );
 }
```
[the remark this answers is not in the document]
Comment (ggdouglas) [reply packages/icons/scripts/generate-icon-components.mjs:71]: 955fa001e91b862693cb796aa73635c7ae7c2f81

File: packages/icons/scripts/iconComponent.tsx.hbs [hunk 3]
```diff
@@ -18,21 +18,22 @@ import type { SVGIconProps } from "../../svgIconProps";
 import { IconSize } from "../../iconTypes";
 import { SVGIconContainer } from "../../svgIconContainer";
 
+/** Path data for the 16px grid; matches {@link generate-icon-paths.mjs} / {@code <Icon />} from core. */
+const PATHS_16 = {{{paths16Json}}} as readonly string[];
+
+/** Path data for the 20px grid; matches {@link generate-icon-paths.mjs} / {@code <Icon />} from core. */
```
[the remark this answers is not in the document]
Comment (ggdouglas) [reply packages/icons/scripts/iconComponent.tsx.hbs]: 4b0d975e80752faac92de225641c6374218c14bd

File: packages/icons/scripts/iconComponent.tsx.hbs [hunk 4]
```diff
@@ -18,21 +18,22 @@ import type { SVGIconProps } from "../../svgIconProps";
...
     return (
         <SVGIconContainer iconName="{{iconName}}" ref={ref} {...props}>
-            <path
-                d={isLarge ? "{{icon20pxPath}}" : "{{icon16pxPath}}"}
-                fillRule="evenodd"
-                transform={`scale({{pathScaleFactor}}, -{{pathScaleFactor}}) translate(${translation}, ${translation})`}
-                style={style}
-            />
+            {paths.map((d, i) => (
+                <path key={i} d={d} fillRule="evenodd" />
```
[the remark this answers is not in the document]
Comment (ggdouglas) [reply packages/icons/scripts/iconComponent.tsx.hbs:33]: Keeping this as-is. Paths are static/deterministic, so index keys are stable here.

File: packages/icons/scripts/extractPathsFromResourceSvg.mjs [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+
+/**
+ * Extracts path `d` strings from an on-disk icon SVG. This matches the pipeline used for
+ * {@link generate-icon-paths.mjs} and the path modules consumed by `<Icon />` from core.
+ *
+ * @param {16 | 20} iconSize
+ * @param {string} iconName
+ * @returns {Promise<string[]>}
+ */
+export async function extractPathsFromResourceSvg(iconSize, iconName) {
```
Comment (mm-wang) [inline packages/icons/scripts/extractPathsFromResourceSvg.mjs:34]: **thought**: TODO comment on moving to a different file structure here? Just don't want to forget what we're moving toward.

File: packages/icons/scripts/extractPathsFromResourceSvg.mjs [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+    const filepath = join(iconResourcesDir, `${iconSize}px`, `${iconName}.svg`);
+    const svg = readFileSync(filepath, "utf-8");
+    const optimizedSvg = await svgOptimizer.optimize(svg, { path: filepath });
+    /** @type string[] */
+    const paths = [];
+    // Match `d` attributes on `<path` elements specifically, supporting single or double quotes.
+    const re = /<path[^>]*\sd=(["'])([\s\S]*?)\1/g;
```
Comment (mm-wang) [inline packages/icons/scripts/extractPathsFromResourceSvg.mjs]: **question**: Do you still need to match both single or double quotes after optimizing? I feel like this should be a step in the optimization. Similar question to the newlines/tabs.

I think it's fair to say this is a fallback to clean up the paths, but maybe note that as well in the naming.

File: packages/icons/scripts/generate-icon-components.mjs [hunk 7]
```diff
@@ -51,50 +41,29 @@ const componentsIndexTemplate = Handlebars.compile(
...
-for (const [iconName, icon16pxPath] of Object.entries(iconPaths[16])) {
-    const icon20pxPath = iconPaths[20][iconName];
-    if (icon20pxPath === undefined) {
-        console.error(`Could not find corresponding 20px icon path for ${iconName}, skipping!`);
-        continue;
+for (const { iconName } of iconsMetadata) {
+    let paths16;
+    let paths20;
+    try {
+        paths16 = await extractPathsFromResourceSvg(16, iconName);
```
Comment (mm-wang) [inline packages/icons/scripts/generate-icon-components.mjs]: **suggestion**: Can we use a promise all for 16/20 to parallelize?

I'm also a bit unsure about throwing the errors at this point - it will break on the first icon being unable to extract, but won't necessarily catch all issues with the icons. Might be nice to gather them and note the errors later.

**Review by mm-wang — COMMENTED** [review]
Small suggestions, main thing I would prefer is some level of parallelization of the icon paths extraction. Open to discussing the error failing.

File: packages/icons/scripts/extractPathsFromResourceSvg.mjs (hunk 6 above)
Comment (ggdouglas) [reply packages/icons/scripts/extractPathsFromResourceSvg.mjs]: Ah, good catch, agreed. I've narrowed extraction down to just the normalized `<path d="...">` output only since we have direct control over what paths we're extracting here. 135620e31cab23b753ad6ae6a683529d6a62fc63

File: packages/icons/scripts/extractPathsFromResourceSvg.mjs (hunk 5 above)
Comment (ggdouglas) [reply packages/icons/scripts/extractPathsFromResourceSvg.mjs:34]: > moving to a different file structure 

Not 100% sure what you mean. Are you referring to switching these to TypeScript? Or something else?

File: packages/icons/scripts/generate-icon-components.mjs (hunk 7 above)
Comment (ggdouglas) [reply packages/icons/scripts/generate-icon-components.mjs]: Good idea! I’m going to keep this fail-fast for now; generation should halt on the first broken icon. f40b9187ed820528b3a6cf6b240c47efa8dad3b8

File: packages/icons/scripts/extractPathsFromResourceSvg.mjs (hunk 5 above)
Comment (mm-wang) [reply packages/icons/scripts/extractPathsFromResourceSvg.mjs:34]: I meant to remove the 16px and 20px folders since we will have 1 folder after.

**Review by mm-wang — APPROVED** [review]

File: packages/icons/scripts/extractPathsFromResourceSvg.mjs (hunk 5 above)
Comment (ggdouglas) [reply packages/icons/scripts/extractPathsFromResourceSvg.mjs:34]: Happy to edit the comments to reflect the new realty whenever we get there, but for now I think I'm going to opt to leave these intact.
