### PR TITLE
always unmount Overlay in tests -- fixes flakes!

### LINKED ISSUE #1951: flaky overlay tests

### PR DESCRIPTION
**Pull request by giladgray**
#### Fixes #1951 for real real

Don't know of a way to assert that enzyme wrappers are unmounted before tests.

https://github.com/airbnb/enzyme/issues/911 captures the heart of this discussion: it's up to the consumer to ensure their tests clean up after themselves. enzyme does not automatically unmount, or provide a `cleanup()` method. There's actually a [**Note** to this effect](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md#full-rendering-api-mount) on the `.mount()` docs.

### CODE REVIEW

File: packages/core/test/overlay/overlayTests.tsx [hunk 1]
```diff
@@ -302,54 +312,51 @@ describe("<Overlay>", () => {
...
-            }, 1);
+                wrapper.update();
+                if (Utils.isFunction(selector)) {
+                    selector();
+                } else {
+                    assert.strictEqual(document.querySelector(selector), document.activeElement);
+                }
+                done();
+            }, 100);
+            // }, 1);
```
Comment (adidahiya) [inline packages/core/test/overlay/overlayTests.tsx]: remove commented code

**Comment by giladgray** [comment]
@adidahiya @cmslewis @themadcreator we could all learn a thing or two about enzyme testing from this situation. sometimes you actually have to clean up after yourself!
